import { Translations } from "../types";

const zhHant: Translations = {
  // onboarding
  inviteTeamMembersTo: "邀請團隊成員加入您的工作區",
  loggingIn: "正在登錄",
  defaultSpaceName: "一般",
  onboardingSpaceName: "歡迎 👋",
  loginCodeSendAgain: "再次發送您的登錄代碼",
  loginCodeResent: "您的登錄代碼已再次發送。",
  loginCodeError: "登錄驗證碼錯誤。",
  loginCodeErrorSending: "發送您的登錄驗證碼時出現問題。",
  loginCodeErrorExpired: "您的登錄驗證已過期，我們已發送另一個。",
  loginCodeErrorRateLimited: "您嘗試的次數過多，請稍後再試。",
  pickAWorkspaceName: "選擇一個工作區名稱",
  creatingWorkspace: "正在創建工作區",
  createaSpace: "創建一個空間",
  subdomainExists: "此工作區名稱已被佔用。請嘗試其他名稱。",
  emailLabel: "您的電子郵件地址",
  passwordLabel: "密碼",
  checkEmail: "檢查您的電子郵件",
  haveSent: "我們已發送一個",
  weSentALoginCode: "我們已將登錄代碼發送至：",
  ifEmailIsValidWeSentYouACode:
    "如果此電子郵件有效且可以更改，已發送一次性密碼。",
  genericEmailUpdateError: "更新您的電子郵件地址時出現問題。請重試。",
  sixDigit: "6位數登錄代碼",
  sixDigits: "6位數",
  confTo: "至",
  checkInbox: "請查看您的通知。",
  teamName: "您的團隊名稱是什麼？",
  workspaceNameLabel: "工作區名稱",
  workspaceNamePlaceHolder: "例如 Acme industries",
  spaceNameLabel: "空間名稱",
  spaceNamePlaceHolder: "例如 web-shop",
  min3Characters: "至少3個字符長。",
  continueWithProvider: "繼續使用%{provider}",
  welcomeToSuperThread: "歡迎來到Superthread",
  aWorkspaceIs: "工作區通常以您的組織或公司名稱命名。您可以稍後變更此名稱。",
  youCanChangeThis: "您可以稍後更改此名稱並創建任意多的空間。",
  LoginCode: "登錄代碼",
  enterLoginCode: "輸入登錄代碼",
  continueWithEmail: "繼續使用電子郵件",
  registerProvider: "註冊使用%{provider}",
  onboardingEmailPlaceholder: "you@example.com",
  // cards
  cardsLayoutList: "列表",
  cardsLayoutBoard: "看板",
  cardsLayoutTimeline: "時間線",
  cardsLayoutCalendar: "日曆（測試版）",
  // Group titles
  ["slash.group.media"]: "媒體",
  ["slash.group.basic"]: "基本",
  ["slash.group.inline"]: "內嵌",
  ["slash.group.embed"]: "嵌入",
  // Keywords
  ["slash.keyword.media"]: "附件,圖片,文件,上傳,媒體,附件",
  // Commands
  // slashCommands
  ["slash.display.attach"]: "附件",
  ["slash.search.attach"]: "附件",
  "slash.display.image": "圖片",
  "slash.display.video": "視頻",
  "slash.display.file": "文件",
  "slash.display.youtube": "嵌入 YouTube 視頻",
  "slash.display.checklist": "核對清單",
  "slash.display.table": "表格",
  "slash.display.h1": "H1",
  "slash.display.h2": "H2",
  "slash.display.h3": "H3",
  "slash.display.bulleted": "項目符號清單",
  "slash.display.numbered": "編號清單",
  "slash.display.blockquote": "引用",
  "slash.display.hr": "水平線",
  "slash.display.card": "卡片",
  "slash.display.mention": "提及",
  "slash.display.codeBlock": "程式碼區塊",
  "slash.display.board": "看板",
  "slash.display.callout": "提示",
  "slash.display.embedIframe": "嵌入 iframe",
  "slash.display.embedFigma": "嵌入 Figma",
  "slash.display.embedMiro": "嵌入 Miro 白板",
  "slash.display.embedLoom": "嵌入 Loom 影片",
  "slash.display.embedExcalidraw": "嵌入 Excalidraw",
  "slash.display.embedLucid": "嵌入 Lucid 圖表",
  "slash.search.image": "圖片",
  "slash.search.video": "視頻",
  "slash.search.file": "文件",
  "slash.search.youtube": "youtube 視頻",
  "slash.search.checklist": "核對清單",
  "slash.search.table": "表格",
  "slash.search.h1": "h1",
  "slash.search.h2": "h2",
  "slash.search.h3": "h3",
  "slash.search.bulleted": "項目符號清單",
  "slash.search.numbered": "編號清單",
  "slash.search.blockquote": "引用",
  "slash.search.hr": "水平線",
  "slash.search.card": "卡片",
  "slash.search.mention": "提及",
  "slash.search.codeBlock": "程式碼區塊",
  "slash.search.embed": "嵌入看板",
  "slash.search.embedIframe": "嵌入 iframe",
  "slash.search.embedFigma": "嵌入 figma iframe",
  "slash.search.embedMiro": "嵌入 miro iframe",
  "slash.search.embedLoom": "嵌入 loom iframe",
  "slash.search.embedExcalidraw": "嵌入 excalidraw iframe",
  "slash.search.embedLucid": "嵌入 lucid iframe",
  // menus
  "menu.add-column-before": "在前面添加列",
  "menu.add-column-after": "在後面添加列",
  "menu.add-row-before": "在前面添加行",
  "menu.add-row-after": "在後面添加行",
  "menu.merge-cells": "切換合併儲存格",
  "menu.toggle-header-row": "切換標題行",
  "menu.delete-column": "刪除列",
  "menu.delete-row": "刪除行",
  "menu.delete-table": "刪除表格",
  "menu.toggle-expand-to-page-size": "切換全寬",
  "menu.add-comment": "添加評論",
  "menu.heading": "標題 %{level}",
  "menu.bold": "粗體",
  "menu.italic": "斜體",
  "menu.strikethrough": "刪除線",
  "menu.underline": "底線",
  "menu.check-list": "核對清單",
  "menu.bullet-list": "項目符號清單",
  "menu.ordered-list": "編號清單",
  "menu.horizontal-rule": "水平線",
  "menu.link": "連結",
  "menu.quick-card": "快速卡片",
  "menu.blockquote": "區塊引用",
  "menu.codeblock": "程式碼區塊",
  "menu.code": "內嵌程式碼",
  "menu.undo": "復原",
  "menu.redo": "重做",
  "menu.table-cell-color": "儲存格顏色",
  "menu.clear-table-cell-color": "清除儲存格顏色",
  "menu.align-left": "靠左對齊",
  "menu.align-center": "置中對齊",
  "menu.align-right": "靠右對齊",
  "menu.align-justify": "左右對齊",
  "editor.clickToDownload": "點擊下載",
  "editor.loading": "載入中",
  "editor.characterLimitReachedTryFile":
    "已達字元限制。若內容較大，您可以附加檔案。",
  "editor.uploading": "上傳中",
  "editor.genericFileError": "您的檔案無法上傳。",
  // billing
  ["billing.unlimitedMembers"]: "無限團隊成員",
  ["billing.unlimitedSpaces"]: "無限空間",
  ["billing.unlimitedBoards"]: "無限看板",
  ["billing.unlimitedCardsAndPages"]: "無限卡片和頁面",
  ["billing.unlimitedViews"]: "無限的已儲存篩選器",
  ["billing.category.workspaceMembers"]: "工作區成員",
  ["billing.category.spaces"]: "空間",
  ["billing.category.boards"]: "看板",
  ["billing.category.cardsAndPages"]: "卡片和頁面",
  ["billing.category.views"]: "已儲存篩選器",
  ["billing.category.fileSize"]: "檔案大小",
  ["billing.category.privateSpaces"]: "私人空間",
  ["billing.category.userPermissions"]: "使用者權限",
  ["billing.category.guestAccounts"]: "訪客帳號",
  ["billing.noPrivateSpaces"]: "無私人空間",
  ["billing.everyoneIsAdmin"]: "所有人都是管理員",
  ["billing.noGuestAccounts"]: "無訪客帳號",
  ["billing.5mbFileSizeLimit"]: "5MB 檔案大小限制",
  ["billing.noFileSizeLimit"]: "無檔案大小限制",
  ["billing.unlimitedPrivateSpaces"]: "無限私人空間",
  ["billing.2Spaces"]: "2 個空間",
  ["billing.adminRolesAndPermissions"]: "管理員角色與權限",
  ["billing.unlimitedCards"]: "無限卡片",
  ["billing.sharePagesOnTheWeb"]: "在網路上分享頁面",
  ["billing.50Pages"]: "50 頁",
  ["billing.unlimitedPages"]: "無限頁面",
  ["billing.indexSharedPages"]: "在搜尋引擎中索引共享頁面",
  ["billing.privateSpaces"]: "私人空間",
  ["billing.viewOnlySpaces"]: "僅檢視空間",
  ["billing.timelineListAndBoardView"]: "時間軸、清單和看板視圖",
  ["billing.guestAccounts"]: "訪客帳號",
  ["billing.monthly"]: "每月",
  ["billing.yearly"]: "每年",
  ["billing.currentPlan"]: "目前的方案",
  ["billing.yourChosenPaymentMethodIs"]: "您選擇的付款方式是 %{method}",
  ["billing.thisIsThePaymentMethod"]:
    "這是我們將用於未來付款的付款方式。您可以隨時更改。",
  ["billing.billing"]: "帳單",
  ["billing.planAndBilling"]: "方案和帳單",
  ["billing.paymentMethod"]: "付款方式",
  ["billing.cardEndingIn"]: "%{cardType} 末四位數字為 %{last4}",
  ["billing.manageBillingDetails"]: "管理帳單詳情",
  ["billing.viewBillingDetails"]: "查看帳單詳情",
  ["billing.updatePaymentDetails"]: "更新付款詳情",
  ["billing.sendNewInvoicesTo"]: "將新發票發送至",
  ["billing.previousInvoices"]: "以前的發票",
  ["billing.plan"]: "方案",
  ["billing.manageWhichPlan"]: "管理工作區使用的方案",
  ["billing.standard"]: "隨心付費",
  ["billing.pro"]: "商業版",
  ["billing.standardSubtitle"]: "適合個人和小型團隊",
  ["billing.proSubtitle"]: "適合發展中的公司",
  ["billing.enterprise"]: "企業版",
  ["billing.changePlan"]: "更改方案",
  ["billing.free"]: "免費",
  ["billing.upgrade"]: "升級",
  ["billing.noPaymentMethod"]: "無付款方式",
  ["billing.thereIsNoPaymentMethod"]:
    "此工作區沒有關聯的付款方式。選擇付費方案後，付款方式將顯示在此處。",
  ["billing.selectAPaidPlan"]: "選擇付費方案",
  ["billing.upgradePlan"]: "付更多",
  ["billing.downgradePlan"]: "付更少",
  ["billing.downgradeToFree"]: "降級至免費",
  ["billing.viewYourPaymentMethodInStripe"]: "在 Stripe 中查看您的付款方式",
  ["billing.weBillTheWorkspacePayment"]:
    "當邀請被接受時，我們會向工作區的付款方式收費。",
  ["billing.checkThePlanPanel"]: "查看方案面板以獲取每個席位的成本估算。",
  ["billing.12"]: "$12",
  ["billing.10"]: "$10",
  ["billing.dollarPrice"]: "$%{price}",
  ["billing.numberSpaces"]: "%{number} 個空間",
  ["billing.numberBoards"]: "%{number} 個看板",
  ["billing.fileSizeLimit"]: "%{size}MB 文件大小限制",
  ["billing.sprints"]: "短衝",
  ["billing.projectsAndRoadmap"]: "專案",
  ["billing.ssoAndSaml"]: "SSO 和 SAML",
  ["billing.unlimitedFileUploads"]: "無限文件上傳",
  ["billing.cardAndPageTemplates"]: "卡片和頁面模板",
  ["billing.guestUsers"]: "訪客用戶",
  ["billing.meetingTranscription"]: "會議轉錄",
  ["billing.aiNoteTemplates"]: "AI 筆記模板",
  ["billing.askAiSearch"]: "詢問 AI 搜索",
  ["billing.perUserPerMonth"]: "每用戶每月",
  ["billing.perUserPerYear"]: "每用戶每年",
  ["billing.inAppLiveChatSupport"]: "應用內即時聊天支持",
  ["billing.aiTrainingOptOut"]: "選擇退出AI訓練",
  ["billing.timelineListAndCalendar"]: "時間軸、列表和日曆佈局",
  ["billing.billedYearly"]: "按年計費",
  ["billing.planStatus"]: "方案狀態",
  ["billing.yourCurrentPlanIsNotSetToRenew"]: "您的當前方案未設置為自動續訂",
  ["billing.canceledDescription"]:
    "在 %{date} 您的工作區將降級至 $t(billing.free) 方案。在此之前，您仍然可以邀請人員加入此工作區，但您將無法超過 %{memberCount} 位工作區成員",
  ["billing.turnRenewalBackOn"]: "重新開啟續訂",
  ["billing.youCanStillInvite"]: "您仍然可以邀請人員加入此工作區，但您不能超過",
  ["billing.workspaceFullError"]:
    "已達工作區成員上限。工作區管理員可以提高上限。",
  ["billing.genericJoinError"]: "無法加入工作區。",
  ["billing.startsOn"]: "開始於 %{date}",
  ["billing.switchToYearly"]: "切換至年度 (-20%)",
  ["billing.switchToMonthly"]: "切換至每月",
  ["billing.metadata"]: "%{plan} 的所有內容，加上...",
  ["billing.dedicatedAnalyst"]: "專屬策略分析師",
  ["billing.onsiteAdoption"]: "現場採用和部署",
  ["billing.customImplementation"]: "定制實施",
  ["billing.uptimeSLA"]: "%{percentage}% 正常運行時間 SLA",
  ["billing.byoc"]: "自帶雲端",
  ["billing.samlAndScim"]: "Single Sign-On (SSO) and SCIM provisioning",
  ["billing.auditLogs"]: "審計日誌",
  ["billing.customBilling"]: "自訂計費",
  ["billing.prioritySupport"]: "優先支援和諮詢",
  ["billing.unlimitedChildCards"]: "無限子卡",
  ["billing.publishPagesToTheWeb"]: "將頁面發布到網絡",
  ["billing.calendarLayout"]: "日曆佈局",
  ["billing.customViews"]: "自訂已儲存篩選器",
  ["billing.advancedSearch"]: "進階搜尋",
  ["billing.views"]: "已儲存篩選器",
  ["billing.timelineLayout"]: "時間線佈局",
  ["billing.guestsUsersAreFree"]: "在您目前的方案中，訪客用戶是免費的。",
  ["billing.newMembersAreBilledProRata"]:
    "新成員將按比例計算剩餘的年度計費週期。",
  ["billing.workspacePaymentMethodWillBeCharged"]:
    "工作區付款方式將在他們加入的月份結束時收費。",
  ["billing.learnModeAboutBilling"]: "了解更多關於計費的信息",
  ["billing.guestViewOnly"]: "訪客 – 僅查看",
  ["billing.daysLeftOnTrial_one"]: "試用還剩 %{count} 天",
  ["billing.daysLeftOnTrial_other"]: "試用還剩 %{count} 天",
  ["billing.keepPlan"]: "保留方案",
  ["billing.yourTrialEndsSoon"]: "您的試用即將結束",
  ["billing.thereAreDaysLeftOnYourTrial_one"]:
    "您的 %{planName} 方案試用還剩 %{count} 天。",
  ["billing.thereAreDaysLeftOnYourTrial_other"]:
    "您的 %{planName} 方案試用還剩 %{count} 天。",
  ["billing.afterTrialLong"]:
    "試用結束後，您將被降級至 %{planName} 方案。您可以在方案頁面查看您將失去的功能。",
  ["billing.afterTrialShort"]: "試用結束後，您將被降級至 %{planName} 方案。",
  ["billing.contactAdminOrOwner"]: "聯繫您的管理員或擁有者",
  ["billing.seeAvailablePlans"]: "查看可用方案",
  ["billing.yourTrialHasExpired"]: "您的試用已過期",
  ["billing.youHaveBeenDowngradedLong"]:
    "您已被降級至 %{planName} 方案。您可以在方案頁面查看您失去的功能。",
  ["billing.youHaveBeenDowngradedShort"]: "您已被降級至 %{planName} 方案。",
  ["billing.legacy"]: "舊版",
  ["billing.youAreOnLegacyPlan"]:
    "您使用的是舊版 %{planName} %{planPeriod} 方案",
  ["billing.legacyDescription"]:
    "此版本不再提供給新用戶。您可以繼續使用它，或%{contactUs}以探索我們目前方案的更新功能和定價。",

  // global
  ["global.text.create"]: "創建",
  ["option.label.cards"]: "卡片",
  ["option.label.pages"]: "頁面",
  ["option.label.boards"]: "看板",
  ["option.label.epics"]: "項目",
  ["option.label.spaces"]: "空間",
  ["option.label.showArchived"]: "顯示已封存",
  ["search.message.noResults"]: "未找到",
  ["global.text.discardDraft"]: "放棄草稿",
  switchAccount: "切換帳戶",
  all: "全部",
  search: "搜尋",
  searchPlaceholder: "搜尋或提問...",
  close: "關閉",
  send: "發送",
  resendInviteLink: "重新發送邀請連結",
  addComment: "新增評論",
  comment: "評論",
  replyToComment: "回覆評論...",
  writeComment: "撰寫評論...",
  draftComment: "草稿評論",
  finaliseCard: "完成卡片",
  comments: "評論",
  createBoard: "建立看板",
  createPage: "建立頁面",
  delete: "刪除",
  edit: "編輯",
  remove: "移除",
  done: "完成",
  cancel: "取消",
  cancelAndDiscard: "取消並放棄",
  enterBoardTitle: "看板標題",
  create: "建立",
  join: "加入",
  couldntJoinSpace: "無法加入空間，請稍後再試。",
  untitled: "未命名",
  containsNoContent: "不包含內容。",
  ama: "AMA",
  me: "我",
  assigned: "已分配",
  mentions: "提及",
  visited: "已訪問",
  saved: "已儲存",
  notifications: "通知",
  selectWhereWwhenWillNotified: "選擇您希望如何接收通知",
  recivePersonalNotification: "在 Slack 中接收個人通知",
  notifyMe: "通知我當",
  save: "儲存",
  saveChanges: "儲存變更",
  archived: "已封存",
  archive: "封存",
  watch: "關注",
  unwatch: "取消關注",
  cardArchived: "卡片已封存。",
  cardArchivedByCard: "卡片已封存。",
  cardArchivedByList: "卡片屬於已封存的列表。移至活動列表以恢復。",
  cardArchivedByBoard: "卡片屬於已封存的看板。移動到活動看板以恢復。",
  epicArchived: "專案已封存。",
  epicArchivedByEpic: "專案已封存。",
  epicArchivedByList: "專案屬於已封存的列表。移動到活動列表以恢復。",
  boardArchived: "看板已封存。",
  isArchived: "已封存",
  pageArchived: "頁面已封存。",
  cellMerge: "合併儲存格",
  new: "新增",
  view: "已儲存篩選器",
  project: "空間",
  spaces: "空間",
  teamId: "團隊 ID",
  deleteCommentPopupMessage: "您確定要刪除此評論嗎？",
  deleteMessage: "刪除評論",
  archiveResource: "封存 %{type}",
  restoreResource: "恢復 %{type}",
  deleteResource: "刪除 %{type}",
  deleteSuccess: "%{name} %{type} 已刪除",
  archiveSuccess: "%{name} %{type} 已封存",
  restoreSuccess: "%{name} %{type} 已恢復",
  deleteError: "無法刪除 %{name} %{type}",
  archiveError: "無法封存 %{name} %{type}",
  restoreError: "無法恢復 %{name} %{type}",
  addLink: "新增連結",
  couldntDeleteComment: "無法刪除評論，請再試一次",
  couldntLoadComments: "無法載入評論。",
  commentOnPage: "在頁面上評論",
  commentOn: "評論",
  emailPlaceholder: "例如 you@example.com",
  signOut: "登出",
  leave: "離開",
  browseAllSpaces: "瀏覽所有空間",
  preview: "預覽",
  goToCard: "前往卡片",
  zoomIn: "放大",
  zoomOut: "縮小",
  notFoundPageHeader: "發生了一個小故障...",
  notFoundPageContent:
    "我們不太確定出了什麼問題。您可以返回，或查看我們的幫助中心以獲得幫助。",
  addCard: "新增卡片",
  addProject: "新增專案",
  next: "下一步",
  addToCard: "新增到卡片",
  checklist: "清單",
  moveList: "移動列表",
  board: "看板",
  timeline: "時間軸",
  templates: "範本",
  cardTemplates: "卡片範本",
  pageTemplates: "頁面範本",
  saveCardContentYouRepeatedlyUse: "儲存您重複使用的內容，並在創建卡片時應用",
  savePageContentYouRepeatedlyUse: "儲存您重複使用的內容，並在創建頁面時應用",
  createCardTemplate: "創建卡片模板",
  editCardTemplate: "編輯卡片模板",
  searchTemplates: "搜尋模板",
  name: "名稱",
  noCardTemplates: "沒有卡片模板",
  noPageTemplates: "沒有頁面模板",
  calendar: "日曆",
  showAllCards: "顯示所有卡片",
  hideAllCards: "隱藏所有卡片",
  showWeekends: "顯示週末",
  youCanCreateATemplateAbove: "您可以在上方創建一個模板",
  youCanCreateABoardFrom: "您可以從應用程式側邊欄創建一個看板",
  createPageTemplate: "創建頁面模板",
  editPageTemplate: "編輯頁面模板",
  templateNameAndIcon: "模板名稱和圖標",
  thisIsHowPeopleFindTemplate: "這是人們稍後找到您的模板的方式",
  shortAndDescriptive: "簡短且具描述性",
  templateNameCannotBeEmpty: "模板名稱不能為空",
  templateSpace: "模板空間",
  whichSpacesWillThisTemplateBeAvailableIn: "此模板將在哪些空間中可用？",
  templateSpaceShouldHaveAtLeastOneSpaceSelected: "模板空間應至少選擇一個空間",
  noSpacesFound: "未找到空間。",
  allSpaces: "所有空間",
  peopleWillBeAbleToEditThisAfterTheyApplyTheTemplate:
    "人們在應用模板後可以編輯此內容",
  theseWillBeAddedToTheCardYouApplyTheTemplateTo:
    "這些將被添加到您應用模板的卡片中",
  taskDescription: "卡片描述",
  pageBody: "頁面內容",
  saveTemplate: "儲存模板",
  templateNotFound: "未找到模板",
  addAssignees: "添加受指派者",
  removeAssignees: "移除受指派者",
  changeAssignees: "更改受指派者",
  setTags: "設定標籤",
  selectAll: "全選",
  createInThisBoard: "在此看板中創建",
  setThisStatus: "設定此狀態",
  chooseABoard: "選擇一個看板",
  chooseABoardToUseThisField: "選擇一個看板以使用此欄位",
  ifYouLeaveThisPageAnyChangesWillBeLost:
    "如果您離開此頁面，您對此模板所做的任何更改將會丟失。",
  uploadFailedClickToRetry: "上傳失敗，點擊重試",
  areYouSureYouWantToDeleteTheTemplate:
    "您確定要刪除 ”%{templateName}” 模板嗎？",
  applyTemplate: "應用模板",
  noTemplates: "沒有模板。",
  manageTemplates: "管理模板",
  uploadFilesForTemplatesIsDisabled: "模板中禁用文件上傳",
  uploadFilesIsDisabled: "文件上傳已禁用",
  noTagsFoundSelectBoardToSeeTags:
    "未找到標籤。選擇一個看板以查看該空間中可用的標籤，或",
  createNewWorkspaceTagInSettings: "在設置中創建新的工作區標籤。",
  noTitle: "無標題",
  addChecklist: "新增清單",
  title: "標題",
  add: "新增",
  addItem: "新增項目",
  archiveList: "封存清單",
  actions: "操作",
  reply: "回覆...",
  replies: "回覆",
  description: "描述",
  cardDescriptionPlaceholder: "撰寫描述...",
  templateDescriptionPlaceholder: "輸入描述...",
  card: "卡片",
  space: "空間",
  page: "頁面",
  workspaceLabel: "輸入工作區名稱",
  workspacePlaceholder: "工作區名稱",
  roboto: "Roboto",
  sansserif: "無襯線",
  serif: "襯線",
  mono: "等寬",
  monospace: "等寬字體",
  download: "下載",
  move: "移動",
  background: "背景",
  share: "分享",
  upload: "上傳",
  paste_image_link: "貼上圖片連結",
  embed_image: "嵌入圖片",
  embedIframe: "嵌入 iframe",
  embedProductIframe: "嵌入 %{product}",
  drag_and_drop: "拖放",
  supported_files: "支援的檔案",
  maximum_size: "最大尺寸",
  createNewPage: "建立新頁面",
  createNewBoard: "建立新看板",
  newPage: "新頁面",
  addNewPage: "新增頁面",
  newBoard: "新看板",
  addNewBoard: "新增看板",
  oneColumn: "1 欄",
  twoColumns: "2 欄",
  previewStillUpdating: "預覽仍在更新中...",
  emptyPage: "空白頁面",
  searchSuperthread: "搜尋 Superthread",
  attachFrom: "附加自...",
  searchUnsplash: "搜尋 Unsplash",
  fullWidth: "全寬",
  largeText: "大文字",
  space___: "空間...",
  cannotExcludeAll: "不能全部排除",
  mustIncludeAtLeastOne: "必須至少包含一個",
  type: "類型",
  noResultsFound: "未找到結果",
  cardStatus: "卡片狀態",
  makeItPrivate: "設為私人",
  thisSpaceIsPrivate: "此空間為私人",
  privateSpaceDescription: "當空間設為私人時，只有受邀者才能加入。",
  boards: "看板",
  boardsCount_one: "%{count} 個看板",
  boardsCount_other: "%{count} 個看板",
  cardsCount_one: "%{count} 張卡片",
  cardsCount_other: "%{count} 張卡片",
  from: "來自",
  hiddenMember: "隱藏成員",
  hiddenMemberDesc: "此人與您沒有共享任何空間",
  linkTextLabel: "文字",
  linkUrlLabel: "連結",
  linkTextPlaceholder: "新增文字...",
  linkUrlPlaceholder: "新增連結...",
  linkOrEmbedCode: "新增連結或嵌入代碼...",
  editList: "編輯清單",
  copyList: "複製清單",
  sortBy: "排序依據",
  moveAllCards: "移動所有卡片",
  archiveAllCards: "封存所有卡片",
  enterResourceTitle: "輸入%{type}標題...",
  open: "打開",
  openCardInBoard: "在看板中打開卡片",
  editTitle: "編輯標題",
  editTags: "編輯標籤",
  editMembers: "編輯成員",
  copy: "複製",
  attachment: "附件",
  startDate: "開始日期",
  dueDate: "截止日期",
  cover: "封面",
  tags: "標籤",
  activity: "活動",
  created: "已創建",
  updated: "已更新",
  reload: "重新載入",
  timePeriod: "時間段",
  cardsAdded: "新增的卡片",
  cardsFinished: "完成的卡片",
  netChange: "淨變化",
  last7Days: "過去7天",
  last14Days: "過去14天",
  last30Days: "過去30天",
  cardsAddedBetween: "在...之間新增的獨特卡片",
  cardsAddedTo: "新增到的獨特卡片",
  between: "之間",
  deletedCards: "刪除的卡片會減少計數",
  moreCardsAddedThanFinished: "比完成的多%{number}張卡片被新增",
  sameNumberOfCardsAddedAndFinished: "新增和完成的卡片數量相同",
  moreCardsFinishedThanAdded: "比新增的多%{number}張卡片被完成",
  oneMoreCardAddedThanFinished: "比完成的多1張卡片被新增",
  oneMoreCardFinishedThanAdded: "比新增的多1張卡片被完成",
  convertToCard: "轉換為卡片",
  searchForTag: "搜尋標籤",
  createTag: "建立標籤",
  tagName: "標籤名稱",
  editTagName: "編輯標籤名稱",
  hideCheckedItems: "隱藏已勾選項目",
  showCheckedItems: "顯示已勾選項目",
  deleteChecklist: "刪除核對清單",
  attachments: "附件",
  versionHistory: "版本歷史",
  profile: "個人資料",
  settings: "設定",
  email: "電子郵件",
  firstNamePlaceholder: "輸入名字",
  lastNamePlaceholder: "輸入姓氏",
  displayNamePlaceholder: "輸入顯示名稱",
  profileBasicInfoSubtitle: "個人和聯絡資訊",
  uploadProfileImageRule:
    "圖片應為PNG、GIF或JPG格式，大小不超過3MB。這將作為您的頭像在應用中顯示。",
  workspaceLogo: "選擇工作區標誌。建議尺寸為256x256px",
  logoSaved: "標誌已儲存",
  logoRemoved: "標誌已移除",
  removeCover: "移除封面",
  uploadCoverImage: "上傳封面圖片",
  list: "清單",
  addChildCard: "新增子卡片",
  searchForCard: "搜尋現有卡片",
  newChildCard: "建立新的子卡片",
  cancelSearch: "取消搜尋",
  computer: "電腦",
  setDueDate: "設定截止日期",
  months: "一月,二月,三月,四月,五月,六月,七月,八月,九月,十月,十一月,十二月",
  monthsAbbreviation:
    "一月,二月,三月,四月,五月,六月,七月,八月,九月,十月,十一月,十二月",
  daysAbbreviation: "週一,週二,週三,週四,週五,週六,週日",
  daysAbbreviationLong: "週一,週二,週三,週四,週五,週六,週日",
  weekDays: "星期一,星期二,星期三,星期四,星期五,星期六,星期日",
  time: "時間",
  dueDateReminder: "截止日期提醒",
  weekBefore: "一週前",
  daysBefore: "幾天前",
  dayBefore: "一天前",
  hoursBefore: "幾小時前",
  hourBefore: "一小時前",
  onTime: "準時",
  none: "無",
  due: "到期",
  insertFile: "插入文件",
  addImage: "添加圖片",
  edited: "已編輯",
  insert: "插入",
  overdue: "逾期",
  continue: "繼續",
  createdBy: "創建者",
  press: "按",
  toClose: "關閉",
  cards: "卡片",
  on: "於",
  useArrowKeys: "使用方向鍵",
  toNavigate: "導航，選擇使用",
  sending: "發送邀請鏈接中..",
  inviteDoesntExist: "邀請鏈接不存在。",
  couldntResendLink: "無法重新發送邀請鏈接。",
  newInviteLinkSent: "我們已向您發送新的邀請鏈接，請檢查您的電子郵件。",
  inviteLinkAccepted: "邀請鏈接已被接受。",
  inviteNoLongerValid: "邀請鏈接已失效。請請求新的邀請鏈接。",
  inviteCodeIncorrect: "邀請鏈接不正確。點擊下方重新發送。",
  thereAreNoFreeSeatsForThisWorkspace: "此工作區沒有空閒席位",
  thisWorkspaceCantAcceptAnyMoreMembers:
    "此工作區無法接受更多成員。工作區管理員可以提高限制，或者現有成員可以離開工作區以騰出席位。",
  spaceAccess: "空間訪問",
  changeToPrivateSpace:
    "此空間的所有現有成員在轉為私人後仍將是成員。除非被邀請，否則無法加入新成員。",
  changeToOpenSpace: "工作區的所有成員都可以找到並加入此空間，並查看其內容。",
  changeToPrivate: "更改為私人",
  changeToOpen: "更改為公開",
  changeToPrivateSpaceTitle: "更改為私人空間？",
  changeToOpenSpaceTitle: "更改為公開空間？",
  ownersAdminsCreatorOfSpace:
    "只有工作區擁有者、管理員和空間創建者可以更改此設置",
  member: "成員",
  notMember: "不是成員",
  links: "鏈接",
  createNewView: "建立已儲存篩選器",
  newView: "新的已儲存篩選器",
  workspace: "工作區",
  views: "已儲存篩選器",
  roadmap: "專案",
  myViews: "我的已儲存篩選器",
  workspaceViews: "工作區的已儲存篩選器",
  private: "私人",
  lastUpdate: "最後更新",
  viewType: "已儲存篩選器類型",
  filters: "篩選器",
  filter___: "篩選...",
  filters___: "篩選器...",
  filterBy: "篩選依據",
  filter: "篩選",
  content: "內容",
  status: "狀態",
  subscriber: "訂閱者",
  creator: "創建者",
  tag: "標籤",
  subscribers: "訂閱者們",
  creators: "創建者們",
  shareWithWorkspace: "與工作區共享",
  discard: "丟棄",
  pageTitlePlaceholder: "無標題頁面",
  markAllAsRead: "標記全部為已讀",
  addTo: "已添加到",
  removeFrom: "已從中移除",
  movedTo: "%{name} 已移動",
  notificationCreated: "%{name} 已創建",
  notificationAdded: "%{name} 已添加",
  commented: "已評論",
  mentioned: "已提及",
  dropFilesLabel: "將文件拖放到此處",
  back: "返回",
  typeContent: "輸入內容",
  hasDueDate: "有截止日期",
  dueSoon: "即將到期",
  dueToday: "今天到期",
  epic: "項目",
  epics: "項目們",
  searchForEpic: "搜索項目",
  changedEpicFrom: "將項目從更改為",
  addedToEpicCard: "將此卡片添加到項目",
  removedFromEpicCard: "將此卡片從項目中移除",
  epicInherited: "項目從父卡片繼承",
  untitledView: "未命名的篩選器",
  cannotSaveUntitledView: "無法儲存未命名的篩選器。",
  viewSaved: "篩選器已儲存",
  pagePlaceholder: "寫點什麼...",
  newViewTitele: "新的篩選器標題",
  ["global.placeholder.pagePlaceholder"]: "寫點什麼...",
  ["global.placeholder.focusedStatePlaceholder"]:
    "@ 提及任何內容，/ 用於命令...",
  ["global.placeholder.focusedStatePlaceholderMobile"]: "@ 提及，/ 用於命令...",
  checkListItemPlaceholder: "@ 提及任何內容...",
  viewAll: "查看全部",
  filterByUnread: "按未讀過濾",
  pagePublished: "頁面已發布",
  restore: "恢復",
  cardPathArchivedBoard: "此卡片在已存檔的看板中",
  restoreMakeChange: "點擊這裡恢復",
  boardUpdated: "看板已更新",
  defaultBoardLayoutChangedTo: "默認佈局更改為 %{layoutStyle}",
  esc: "逃脫",
  assignee: "受讓人",
  assignees: "受讓人們",
  no_assignee: "無受讓人",
  findMembers: "尋找成員...",
  inviteExternalPeople: "邀請外部人員",
  notInThisSpace: "不在此空間",
  inThisSpace: "在此空間",
  notWorkspaceMember: "那個人還不是此工作區的成員",
  anchorLinkErrorMessage: "找不到該連結",
  childCard: "子卡",
  parentCards: "父卡",
  blocking: "阻擋中",
  blocked: "已阻擋",
  favourites: "收藏夾",
  dragOr: "拖曳或",
  somethingHere: "某物到這裡",
  linkCopiedToClipboard: "連結已複製到剪貼簿。",
  tomorrow: "明天",
  invitationsSent: "邀請已發送。",
  invitationsFailed: "邀請發送失敗。",
  retry: "重試",
  undo: "撤銷",
  boardMovedToSpace: "看板已移動到空間",
  pageMovedToSpace: "頁面已移動到空間",
  boardNotMoved: "看板移動已取消。",
  pageNotMoved: "頁面移動已取消。",
  newTag: "新標籤",
  tagExists: "標籤已存在",
  toggleSection: "切換區段",
  toggleContent: "空區段。點擊以在此處撰寫或複製內容。",
  removeChildCardFail: "移除子卡失敗",
  moveChildCardFail: "移動子卡失敗",
  addChildCardFail: "新增子卡失敗",
  cantRemoveMembers: "您無法從預設空間中移除成員",
  cantRemoveMembersFromSpace: "您無法從此空間中移除成員",
  cannotModifyMembers: "您沒有權限更改成員",
  inactiveMembersCannotBeAdded: "無法將非活躍成員新增到空間",
  duplicate: "重複",
  setParentCard: "設定父卡",
  duplicateCard: "複製卡片",
  duplicateBoard: "複製看板",
  duplicateBoardDescription:
    "此看板中的任何卡片將不會被複製。為複製的看板選擇一個空間和名稱。",
  duplicateTo: "複製到",
  duplicateDefaultTitle: "輸入新標題（默認為原始標題）",
  duplicates: "重複項",
  duplicateOf: "的重複項",
  markAsBlockedBy: "標記為被阻擋",
  markAsBlocking: "標記為阻擋中",
  markAsRelatedTo: "標記為相關",
  markAsDuplicateOf: "標記為的重複項",
  blocks: "阻擋",
  blockedBy: "被阻擋",
  related: "相關",
  relatedEpics: "相關專案",
  markedEpicAsBlocking: "將此專案標記為阻擋中",
  markedEpicAsBlockedBy: "將此專案標記為被阻擋",
  markedEpicAsRelated: "將此專案標記為相關",
  markedEpicAsDuplicate: "將此專案標記為重複",
  relatedCards: "相關卡片",
  markedCardAsBlocking: "將此卡片標記為阻擋中",
  markedCardAsBlockedBy: "將此卡片標記為被阻擋",
  markedCardAsRelated: "將此卡片標記為相關",
  markedCardAsDuplicate: "將此卡片標記為重複",
  removedCardRelationship: "移除關係",
  noListsInBoard: "看板中沒有列表",
  noBoardsInSpace: "空間中沒有看板",
  noBoardsInThisSpace: "此空間中沒有看板",
  emptyList: "空列表",
  cardDuplicated: "卡片已複製",
  boardDuplicated: "看板已複製",
  viewDuplicated: "已儲存篩選器已複製",
  viewDeleted: "已儲存篩選器已刪除",
  cardDuplicateFailed: "無法複製卡片",
  boardDuplicateFailed: "無法複製看板",
  viewDuplicateFailed: "無法複製已儲存篩選器",
  cantUndoneAction: "此操作無法撤銷。",
  eachSpaceCanContain: "每個空間可以包含任意多的看板",
  browseSpaces: "瀏覽空間",
  popupSpaceDescription: "在空間中組織工作。通常以團隊、專案或高階目標命名。",
  eachSpaceCanContainMultiple: "每個空間可以包含多個",
  pagesLowercase: "頁面",
  kanbanBoards: "看板",
  and: "和",
  removeFromParent: "從父項中移除",
  removeChildCard: "移除子卡片",
  changeCardParent: "更改卡片父項",
  changeParent: "更改父項",
  changeParentDescription:
    "此卡片的父項為「%{card_title}」。您要將父項更改為當前卡片嗎？",
  editChildCardDetails: "編輯子卡片詳情",
  copyLink: "複製連結",
  childCardTitleNotUpdated: "子卡片標題未更新。",
  addNewChildCard: "新增子卡片",
  enterCardTitleOrFind: "輸入卡片標題或查找現有卡片",
  createNewCard: "建立新卡片",
  unsplashImage: "Unsplash 圖片",
  shareToWeb: "分享至網路",
  publishesSubpagesButNoComments: "發布子頁面，但不包括評論",
  pageIsSharedToWeb: "頁面已分享至網路",
  shared: "已分享",
  openSharedPage: "打開已分享的頁面",
  pageIsSetToPrivate: "頁面設為私人",
  profileSettings: "個人資料設定",
  switchWorkspace: "切換工作區",
  archivedItems: "已封存項目",
  logOut: "登出",
  helpFeedback: "幫助與反饋",
  help: "幫助",
  joinSlack: "加入我們的 Slack 社群",
  askQuestions: "提問並幫助他人",
  contactUs: "聯絡我們",
  letUsKnow: "如果有問題或疑問，請告訴我們",
  assign: "指派",
  unassign: "取消指派",
  pageIsNoLongerShared: "頁面不再分享至網路",
  favourite: "收藏",
  unfavourite: "取消收藏",
  allowSearchEngines: "允許搜索引擎索引此頁面",
  searchEngineIndexing: "搜索引擎索引",
  searchIndexingEnabled: "搜索索引已啟用",
  searchIndexingDisabled: "搜索索引已停用",
  attachIconFrom: "從...附加圖標",
  addIcon: "新增圖標",
  addCoverImage: "新增封面圖片",
  pageDuplicated: "頁面已複製",
  pageDuplicateFailed: "複製頁面失敗",
  copyOf: "的副本",
  displayNameDescription: "這可以是您的名字或暱稱。它將顯示在應用程式中。",
  embedVideo: "嵌入 Youtube 視頻",
  removePullRequest: "移除拉取請求",
  viewOnGitHub: "在 GitHub 上查看",
  setUpGHIntegration: "設置 GitHub 整合",
  integrateSuperthread: "將 Superthread 整合到您喜愛的 git 客戶端。",
  githubIntegradionDescripiton:
    "將 Superthread 卡片連結到 GitHub 拉取請求。在分支名稱或拉取請求標題中包含 Superthread 卡片 ID（例如 C-123），以自動在卡片中顯示 PR 狀態。",
  connectGithub: "連接 GitHub",
  connectedAccounts: "已連接帳戶",
  integrationConnectedToSuperthread: "%{integrationName} 已連接到 Superthread",
  enabledBy: "啟用者",
  select: "選擇",
  integrations: "整合",
  importer: "導入工具",
  github: "GitHub",
  github_pull_request: "GitHub",
  gitlab: "GitLab",
  jira: "Jira",
  trello: "Trello",
  importFrom: "導入自",
  selectYour: "選擇您的",
  usersToSuperthreadUsers: "用戶到 Superthread 用戶",
  issues: "問題",
  teams: "團隊",
  setUpImport: "設置導入",
  importHistory: "導入歷史",
  importBoards: "導入看板",
  selectWhichBoards: "選擇哪些看板",
  runImport: "執行匯入",
  quickImport: "快速匯入",
  importBoardIntoExsistingSpace: "自訂匯入",
  start: "開始",
  started: "已開始",
  DontImport: "不要匯入",
  map: "映射",
  dontImportUsers: "不要匯入用戶",
  ImportUsers: "匯入用戶",
  importAs: "匯入為...",
  selectUser: "選擇用戶",
  inviteByEmail: "通過電子郵件邀請",
  users: "用戶",
  options: "選項",
  chooseAditionslOptions: "選擇其他選項",
  importAttachments: "匯入附件",
  includeCardCoverImages: "包含卡片封面圖片",
  importInProgress: "匯入進行中",
  importError: "匯入完成但有錯誤",
  importSuccess: "匯入完成",
  importUnstarted: "匯入未開始",
  timeStarted: "開始時間",
  completed: "已完成",
  showCompleted: "顯示已完成",
  details: "詳情",
  finish: "完成",
  validEmail: "請輸入有效的電子郵件地址。",
  emailAdresses: "電子郵件地址，用逗號分隔",
  person1Email: "person1@example.com, person2@example.com…",
  addToSpaces: "添加到空間",
  addSpaces: "添加空間",
  browseProjects: "瀏覽所有空間",
  createAndBrowseSpaces: "瀏覽和創建空間",
  nameIsRequired: "需要名稱",
  noProjectFound: "沒有更多空間可添加",
  memberExplanation: "成員可以瀏覽並加入工作區中的任何空間",
  adminExplanation: "管理員對工作區設置有更多訪問權限",
  guestExplanation: "訪客對工作區的訪問有限，只能看到他們被添加到的空間",
  connect: "連接",
  selectBoardImport: "選擇您想匯入的看板",
  selectUsersImport: "選擇您想匯入的用戶",
  notImportArchivedIssues: "我們不會匯入已封存的問題。",
  importTasksIntoSuperthread: "將您現有的任務匯入Superthread。",
  connectAccount: "連接您的帳戶",
  completedOn: "完成於",
  importedBy: "匯入者：",
  timeCreated: "創建時間：",
  createdDate: "創建日期",
  updatedDate: "更新日期",
  numberOfImportedBoards: "匯入的板數量:",
  numberOfImportedUsers: "匯入用戶數量:",
  importingIsFinished: "匯入完成",
  importing: "您的匯入已完成",
  selectService:
    "選擇我們應該從哪裡導入問題。我們會要求您的身份驗證詳細信息，以便我們可以訪問他們的API。在您在最後一步確認選擇之前，我們不會導入任何數據。",
  account: "帳戶",
  importers: "進口商",
  general: "一般",
  manageWorkspaceSettings: "管理一般工作區設定",
  dangerZone: "危險區域",
  notOwnerOrAdmin: "您不是此工作區的擁有者或管理員",
  archiveWorkspace: "存檔工作區",
  archiveWorkspaceDescription:
    "如果工作區被歸檔，所有成員將失去訪問權限。任何公開分享的內容仍將可用。",
  archiveWorkspaceDescriptionDetail:
    "所有成員將失去此工作區的訪問權限。如果您想撤銷此操作，請發送電子郵件至 contact@superthread.com。",
  deleteWorkspace: "刪除工作區",
  deleteWorkspaceDescription:
    "如果工作區及其數據被刪除，所有成員將失去訪問權限。此操作無法撤銷。",
  deleteWorkspaceDescriptionDetail:
    "所有成員將失去對此工作區及其數據的訪問權限。此操作無法撤銷。",
  avatarAppearance: "頭像外觀",
  uploadImage: "上傳圖片",
  successfullySaved: "成功儲存",
  errorSave: "您的更改無法儲存",
  copyURL: "複製 URL",
  copyUrl: "複製 URL 到剪貼簿",
  copyCardUrl: "將卡片網址複製到剪貼簿",
  copyPageUrl: "將頁面網址複製到剪貼板",
  copyBoardUrl: "將看板網址複製到剪貼簿",
  copySpaceUrl: "將空間 URL 複製到剪貼簿",
  copyGitBranchNameToClipboard: "將 git 分支名稱複製到剪貼簿",
  copyGitBranchName: "複製 git 分支名稱",
  branchCopiedToClipboard: "Git 分支名稱已複製到剪貼簿",
  subscribe: "訂閱",
  unsubscribe: "取消訂閱",
  pullRequestAutomation: "拉取請求自動化",
  prAutomationDescription:
    "在 GitHub 中更新拉取請求時移動 Superthread 中的卡片。",
  whenACardIsLinkedToPR: "當卡片連結到拉取請求時",
  whenPRTargetsTheBranch: "當拉取請求針對分支時",
  addBranchSpecificAutomation: "添加分支特定的自動化",
  automationMustHaveBranchName: "自動化必須有一個分支名稱。這些規則將被忽略。",
  addBranchSpecificAutomationErrorAlreadyExists:
    "已經有一個自動化用於該分支名稱。這些規則將被忽略。",
  invalidGitBranchName: "這不是有效的分支名稱。這些規則將被忽略。",
  branchSpecificAutomationAdded: "分支特定的自動化已添加。",
  branchSpecificAutomationUpdated: "分支特定的自動化已更新。",
  branchSpecificAutomationRemoved: "分支特定的自動化已移除。",
  deleteAutomation: "刪除自動化",
  deleteThisAutomation: "刪除此自動化",
  deleteAutomationConfirmation: "這些規則將被刪除且無法恢復。",
  whenPRChangesTo: "當 PR 更改為",
  moveCardToList: "將卡片移至列表",
  doNotMove: "不要移動",
  draftPROpened: "草稿 PR 已開啟",
  pROpened: "PR 已開啟",
  pRReviewRequest: "PR 審核請求",
  pRMerged: "PR 已合併",
  pRClosed: "PR 已關閉",
  noListInBoard: "此看板中沒有清單",
  unassigned: "未分配",
  viewParentCard: "查看父卡片",
  changeParentCard: "更改父卡片",
  removeParentCard: "移除父卡片",
  goToParentCard: "前往父卡片",
  discardAndClose: "放棄並關閉",
  changeStatus: "更改狀態",
  createCardsInSelectedBoard: "總是在選定的看板中建立卡片",
  createCardIn: "建立卡片於",
  maxFileSize: "最大文件大小：5MB",
  addAttachment: "新增附件",
  createChecklist: "建立核對清單",
  assignedToMe: "分配給我",
  movedTAaNewList: "移動到新清單",
  moved: "已移動",
  published: "已發佈",
  cardComments: "卡片評論",
  pageComments: "頁面評論（包括線程中的回覆）",
  movedBetweenSpaces: "移動到不同的空間",
  addedToASpace: "將你新增到一個空間",
  noduedate: "沒有到期日",
  ["now+2d"]: "2 天後",
  ["now+3d"]: "3 天後",
  ["now+1w"]: "1 週後",
  ["now+2w"]: "2 週後",
  ["now+3w"]: "3 週後",
  ["now+1M"]: "1 個月後",
  ["now+2M"]: "2 個月後",
  ["now+3M"]: "3 個月後",
  ["now+6M"]: "6 個月後",
  ["now+1y"]: "1 年後",
  now: "今天",
  nowActivity: "現在",
  ["now-1h"]: "1 小時前",
  ["now-4h"]: "4 小時前",
  ["now-1d"]: "昨天",
  ["now-2d"]: "2 天前",
  ["now-3d"]: "3 天前",
  ["now-1w"]: "1 週前",
  ["now-2w"]: "2 週前",
  ["now-3w"]: "3 週前",
  ["now-1M"]: "1 個月前",
  ["now-2M"]: "2 個月前",
  ["now-3M"]: "3 個月前",
  ["now-6M"]: "6 個月前",
  ["now-1y"]: "1 年前",
  anywhereYouAreMentioned: "任何提到你的地方（無論是否訂閱等）",
  anyCommentsOnResources: "你訂閱的資源上的任何評論。",
  ifYouAreMemberOfABoard: "如果你是看板的成員：",
  manageMembers: "管理成員",
  manageWhoHasAccess: "管理誰可以訪問此工作區",
  active: "活躍",
  suspended: "已暫停",
  inviteMembers: "邀請成員",
  inviteToWorkspace: "邀請人員加入 %{workspaceName} 工作區",
  emailAddress: "電子郵件地址",
  inviteAs: "邀請為",
  teamMembers: "團隊成員",
  gitHubConnected: "GitHub 成功連接",
  nothingToShow: "這裡沒有顯示的內容",
  findTagsOrCreateNew: "查找標籤或創建新標籤",
  deleteTag: "刪除標籤",
  addNewBoardOrPage: "添加新看板或頁面",
  spaceSettings: "空間設置",
  rename: "重命名",
  changeIcon: "更改圖標",
  addToFavorites: "添加到收藏夾",
  removeFromFavorites: "從收藏夾中移除",
  viewmoreassignees: "查看更多被指派者",
  noassignee: "無被指派者",
  currentuser: "當前用戶",
  aPrivateSpace: "私人空間",
  areYouSureYouWantToRemove:
    "你確定要移除他們嗎？他們將失去對此工作區的訪問權限。",
  areYouSureYouWantToLeave:
    "你確定要離開此工作區嗎？你需要邀請才能重新獲得訪問權限。",
  youAreTheOnlyPersonInThisPrivateSpace:
    "你是此私人空間中唯一的人。如果你離開，將無人能夠訪問。如果你的組織仍需要訪問，請在離開前邀請其他人。",
  whenYouLeaveAPrivateSpace:
    "當你離開私人空間時，你將無法再看到其任何看板或頁面。要重新加入，你需要再次被邀請。",
  youCanRejoinThePublicSpace: "你可以從空間屏幕重新加入該空間。",
  areYouSureYouWantToRevoke: "你確定要撤銷他們對此工作區的邀請嗎？",
  areYouSureYouWantToTransferOwnership:
    "你確定要轉讓此工作區的所有權嗎？只有新所有者能夠撤銷此操作。",
  transferOwnership: "轉讓所有權",
  transferSpaceOwnershipConfirmed: "空間所有權已轉讓",
  transferSpaceOwnershipShort: "你必須先轉讓所有權才能離開",
  transferSpaceOwnershipDescription:
    "如果你將 %{name} 設為此空間的所有者，你將不再是所有者，並將被更改為成員。",
  transferSpaceOwnershipBeforeLeaving:
    "你必須將此空間的所有權轉讓給其他人才能離開。請前往空間設置以將所有權轉讓給其他人。",
  confirm: "確認",
  revoke: "撤銷",
  notFound: "未找到",
  itemNotFound: "未找到項目",
  urlDoesntLeadAnywhere: "該 URL 無法引導至任何地方",
  itemMightBeDeleted: "該項目可能已被刪除，或者你可能無權訪問",
  deleteItem: "刪除 %{item}",
  deleteSpace: "刪除空間",
  ifYouWantToDeleteSpace: "如果你想刪除此空間，請在下方輸入其名稱。",
  ifYouWantToDeleteResource:
    "如果你想刪除此 %{resourceType}，請在下方輸入其名稱。",
  ifYouWantToArchiveResource:
    "如果你想存檔此 %{resourceType}，請在下方輸入其名稱。",
  typeTheNameOfTheSpace: "輸入空間名稱",
  removeMember: "移除成員",
  leaveWorkspace: "離開工作區",
  revokeInvite: "撤銷邀請",
  invited: "已邀請",
  pending: "待處理",
  admin: "管理員",
  owner: "擁有者",
  guest: "訪客",
  inviteSent: "邀請已發送",
  resendInvite: "重新發送邀請",
  whatsNew: "最新消息",
  viewUpdates: "查看我們每週更新日誌中的更新",
  whenYouCreateTags:
    "當您從卡片創建標籤時，它們僅作為該空間的標籤保存。在此處創建通用標籤（例如 bug），以便在所有空間中使用。如果存在相同名稱的空間級標籤，我們將其合併到工作區標籤中。",
  merge: "合併",
  theSpace: "該空間",
  haveSameTags: "有相同名稱的標籤。",
  doYouWantToMerge: "您要將這些合併到新的工作區標籤中嗎？",
  tagWithThisNameWorkspace: "具有此名稱的工作區標籤已存在",
  tagWithThisNameSpace: "該空間中已存在具有此名稱的標籤",
  editTag: "編輯標籤",
  workspaceTags: "工作區標籤",
  manageTags: "管理在所有空間中共享的標籤",
  youCantUndo: "您無法撤銷此操作。",
  merge2spaceTags: "具有相同名稱的標籤合併到工作區標籤中？",
  areYouSureYouWantToDelete:
    "您確定要刪除“%{resourceTitle}”%{resourceType}嗎？",
  uploaded: "已上傳",
  cardCreatedInResource: "在 ’%{resourceName}’ %{resourceType} 中創建的卡片",
  ["global.label.createIn"]: "創建於",
  rememberBoard: "記住看板",
  cardTitle: "卡片標題",
  pageTitle: "頁面標題",
  cardDescription: "卡片描述...",
  editAsignees: "編輯受指派者",
  actionFailed: "操作失敗",
  thisBoardIsEmpty: "此看板為空。請先創建一個列表。",
  changesAreSavedAuto: "更改已自動保存",
  untitledCard: "無標題卡片",
  editAssignees: "編輯受指派者",
  showChildCards: "顯示子卡片",
  hideChildCards: "隱藏子卡片",
  createAndManageSpaces: "創建和管理空間",
  thereAreNoListInBoard: "看板中沒有列表。",
  pageMovedToParent: "頁面移動到父級",
  subscribedToResourceUpdates: "已訂閱 %{name} 更新",
  unsubscribedFromResourceUpdates: "已取消訂閱 %{name} 更新",
  subscribingToResourceUpdatesFailed: "訂閱 %{name} 更新失敗",
  unsubscribingFromResourceUpdatesFailed: "取消訂閱 %{name} 更新失敗",
  couldntArchiveCard: "無法歸檔卡片。",
  cardRestored: "卡片已恢復",
  dueOn: "到期日",
  today: "今天",
  yesterday: "昨天",
  attached: "已附加",
  removed: "已移除",
  updatedTheStartDate: "將開始日期更新為",
  setTheStartDate: "將開始日期設為",
  removedStartDate: "已移除開始日期",
  updatedTheDueDate: "將到期日更新為",
  setTheDueDate: "將到期日設為",
  removedDueDate: "已移除到期日",
  changedStausFrom: "將狀態從",
  editStatus: "編輯狀態",
  editName: "編輯名稱",
  numberOfCards: "卡片數量",
  createdCard: "已建立卡片",
  createdEpic: "已建立專案",
  people: "人員",
  assignedMember: "已指派",
  archivedTheCard: "已封存卡片",
  restoredTheCard: "已恢復卡片",
  archivedTheEpic: "已封存專案",
  restoredTheEpic: "已恢復專案",
  theCardDescription: "卡片描述",
  theCardTitle: "卡片標題",
  theEpicDescription: "專案描述",
  theEpicTitle: "專案標題",
  ["quickPage.title.attachImageFrom"]: "從...附加圖片",
  ["quickPage.title.attachCoverImageFrom"]: "從...附加封面圖片",
  chooseWorkspaceToConnectIntegration:
    "選擇一個工作區以連接 %{integrationName}",
  connectSuperthreadWith: "將 Superthread 連接到 %{integrationName}",
  zapierIntegradionDescripiton:
    "Zapier 讓您可以建立自訂工作流程，將 Superthread 與幾乎任何其他應用程式連接：Typeform、Gmail、Intercom、Google Forms、Zendesk、Airtable、Front 等等。",
  connectToZapier: "將 Zapier 連接到 Superthread",
  zapier: "Zapier",
  openZapier: "開啟 Zapier",
  allow: "允許",
  integrationWillHave:
    "%{integrationName} 將擁有讀寫您工作區中卡片、看板和頁面的權限。",
  youMayBeSharing: "您可能會與此網站或應用程式分享敏感資訊。您可以隨時在您的",
  stSettings: "Superthread 設定中查看或移除存取權",
  seeIntegration: "查看 %{integrationName} 的",
  privacyPolicy: "隱私政策",
  termsOfService: "服務條款",
  makeSureYouTrust: "確保您信任 %{integrationName}",
  integrationIsRequesting: "%{integrationName} 正在請求存取",
  previewStInSlack: "在 Slack 中預覽 Superthread 連結",
  lookingForSlackNotifications: "尋找 Slack 通知？",
  turnThemOnInYour: "在您的",
  notificationsSettings: "通知設定中開啟它們",
  connectToSlack:
    "連接到 Slack 以便在 Slack 訊息中包含連結時查看來自 Superthread 卡片和頁面的關鍵資訊。",
  orLc: "或",
  useBoardsToVisualise:
    "使用看板來視覺化您的工作流程、追蹤團隊的進度，並計劃接下來要做的事情。創建多個看板以保持組織有序。",
  collaborativeDocuments:
    "協作文件包含文字、圖片、markdown和內嵌評論。做筆記、撰寫規格、建立維基或公開分享資訊。",
  filterAcrossTheEntire:
    "在整個工作區套用篩選，建立包含所有指派給你的卡片的已儲存篩選器，或是全域臭蟲待辦。已儲存篩選器可以設定為私人或與團隊分享。",
  useFiltersToCreate: "使用篩選器建立只含你想看卡片的自訂已儲存篩選器",
  kanbanBoardsUc: "看板",
  importYourExistingTasksFrom: "從中導入您現有的任務",
  importTasks: "導入任務",
  leaveSpace: "離開空間",
  viewSpace: "查看空間",
  deleted: "%{name} 已刪除",
  leaveNamedSpace: "離開 %{name} 空間？",
  leaveNamedPrivateSpace: "離開 %{name} 私人空間？",
  deleteAndLeaveNamedPrivateSpace: "刪除並離開 %{name} 私人空間？",
  youLeftNamedSpace: "您已離開 %{name} 空間。",
  youCannotLeaveTheSpace: "您無法離開此空間",
  joinSpace: "加入空間",
  joinThisSpace: "加入此空間",
  hasUnsupportedFileType: "具有不支持的文件類型",
  maxAllowedImageSize: "允許的最大圖像大小為",
  maxAllowedImageResolution: "允許的最大圖像解析度為",
  movedFromSpace: "從空間移動",
  untitledPage: "無標題頁面",
  hideChildPages: "隱藏子頁面",
  showSubpages: "顯示子頁面",
  addedTo: "已添加到",
  addMembers: "添加成員...",
  removedFrom: "已從中移除",
  viewMembers: "查看成員",
  enableScrollFocus: "在側邊欄中顯示當前項目",
  copyLinkToHeading: "複製標題的鏈接",
  joined: "已加入",
  addOwner: "添加擁有者",
  noOwner: "無擁有者",
  setOwner: "設置擁有者",
  font: "字體",
  addNewFolder: "創建文件夾",
  deletedSuccesfully: "已從收藏中移除",
  addedSuccesfully: "已添加到收藏",
  clickToUpdate: "點擊以更新",
  NewVersionAvailable: "有新版本的應用程序可用",
  addedChildCard: "已添加子卡片",
  removedChildCard: "已移除子卡片",
  removedChecklist: "已移除清單",
  addedChecklist: "已創建清單",
  addedChecklists: "已創建清單",
  markedAsIncomplete: "標記為未完成",
  completedChecklistItem: "已完成",
  addedParentCard: "已添加父卡片",
  removedParentCard: "已移除父卡片",
  changedParentCardFrom: "已更改父卡片從",
  deleteFolder: "刪除資料夾",
  renameFolder: "重新命名資料夾",
  lockSidebar: "保持側邊欄開啟",
  hideSidebar: "隱藏側邊欄",
  appearance: "外觀",
  changeHowSuperthreadLooksAndFeels: "更改 Superthread 的外觀和感覺",
  matchSistemSettings: "匹配系統設置",
  darkMode: "深色模式",
  lightMode: "淺色模式",
  darkGreyMode: "深灰色模式",
  darkBlueMode: "深藍色模式",
  lightBlueMode: "淺藍色模式",
  year: "年",
  quarter: "季度",
  month: "月",
  addNewPageInside: "新增子頁面",
  addChildPage: "新增子頁面",
  theme: "主題",
  boardSettings: "看板設置",
  reaction: "反應",
  inbox: "通知",
  resolve: "解決",
  unresolved: "未解決",
  unresolve: "取消解決",
  unresolvedOnly: "僅未解決",
  resolved: "已解決",
  unresolveComment: "取消解決評論",
  resolveComment: "解決評論",
  commentResolved: "評論已解決",
  commentUnresolved: "評論未解決",
  resolvedOnly: "僅已解決",
  allComments: "所有評論",
  noUnresolvedComments: "沒有未解決的評論",
  noResolvedComments: "沒有已解決的評論",
  noComments: "沒有評論",
  about: "關於",
  markAsRead: "標記為已讀",
  markAsUnread: "標記為未讀",
  markAllAsResolved: "全部標記為已解決",
  showUnresolved: "顯示未解決",
  showResolved: "顯示已解決",
  noNotifications: "沒有通知",
  noNewNotifications: "沒有新通知",
  noUnresolvedNotifications: "沒有未解決的通知",
  youCanShow: "您可以顯示",
  notificationsInstead: "通知代替",
  subscribeToGetNotifications: "訂閱某些內容，您將收到活動通知",
  selectANotificationToViewIt: "選擇一個通知以查看",
  youCanMarkANotificationAs: "您可以將通知標記為",
  unreadOr: "未讀或",
  resolveIt: "解決它",
  inboxNotificationsAreUnresolved: "通知會保持未解決狀態，直到您解決它們",
  notificationsAreNew: "如果您之前未見過通知，它們就是新的",
  wantNotificationsIn: "想要通知在",
  slaskQuestionMarkVisit: "Slack？訪問",
  noCardsMatchChosenFilter: "沒有符合所選篩選條件的卡片",
  noCardsFound: "未找到卡片",
  boardMoved: "看板已移動",
  pageMoved: "頁面已移動",
  openPage: "打開頁面",
  hasBeenDeleted: "已被刪除",
  deletedResourcePlain: "此資源已被刪除。",
  deletedResourceWithName: "此%{name}已被刪除。",
  this: "這個",
  andTheEntire: "和整個",
  reactionsToYourComments: "對您評論的反應",
  youWereRemoved: "您已被移除",
  fromPrivateSpace: "從私人空間",
  privateSpaceDesc: "此空間是私人的，因此您無法查看其名稱或內容",
  privateSpace: "私人空間",
  everything: "所有內容",
  taskIsOverdue: "任務已逾期",
  endDateIsBeforeStartDate: "結束日期早於開始日期",
  moveCardIntoBoard: "卡片已移動到看板",
  inList: "在列表中",
  searchForParentCard: "搜索父卡片",
  icons: "圖標",
  emojis: "表情符號",
  custom: "自定義",
  moveToBoard: "移動到看板",
  previous: "上一個",
  manualOrder: "手動排序",
  sortedBy: "排序方式",
  toCancelDrag: "取消拖動",
  groupBy: "分組依據",
  subpageCreated: "子頁面已創建",
  tableOfContents: "目錄",
  editWorkspaceTagsInSettings: "在設置中編輯工作區標籤",
  sideDocked: "側邊停駐",
  modalOverlay: "模態覆蓋",
  cardLayout: "卡片佈局",
  switchLayout: "切換佈局",
  showSidebar: "顯示側邊欄",
  notags: "無標籤",
  resetLayoutToBoardDefault: "重置佈局為看板默認",
  alreadyOpen: "%{resource}已經打開",
  defaultBoardLayout: "默認看板佈局",
  defaultBoardLayoutDescription: "每個人將默認看到此佈局。此設置可以稍後更改。",
  boardDescription: "卡片被分組到列中",
  listDescription: "卡片在垂直列表中，分成多組",
  timelineDescription: "根據開始和截止日期的時間線",
  calendarDescription: "卡片會在到期日放置",
  boardName: "看板名稱",
  memberRemoved: "成員已移除",
  resetLayoutToViewDefault: "重置訂單為默認",
  earliestDueDate: "最早截止日期",
  highestPriority: "最高優先級",
  largestEstimate: "最大估算",
  STIsMostUseful: "當您與他人合作時，Superthread 是最有用的。",
  readOnly: "閱讀僅限",
  boardWillNotShowOnPublicPage: "此看板不會顯示在公共頁面上",
  removeBoard: "移除板子",
  noSprints: "Sprints將從最新到最早列出在這裡",
  noNonSprintBoardsInThisSpace: "此空間中沒有非sprint看板",
  inviteToWorkspaceDescription: "若要將現有成員添加到空間，請前往空間設置",
  alreadyMembersOfWorkspace:
    "有些人已經在工作區中。他們將被添加到下面選擇的任何相關空間。",
  information: "資訊",
  success: "成功",
  error: "錯誤",
  warning: "警告",
  typeSomething: "輸入一些內容...",
  invite: "邀請",
  latest: "最新",
  cardChildrenTitle: "子卡片",
  childCards: "子卡片",
  members: "成員",
  removeFromCard: "從卡片中移除",
  displayName: "顯示名稱",
  firstName: "名字",
  lastName: "姓氏",
  update: "更新",
  openSuperthread: "打開 Superthread",
  infoNotification: "資訊通知",
  errorNotification: "錯誤通知",
  alertNotification: "警報通知",
  successNotification: "成功通知",
  SignInIntoExistingWorkspace: "登入現有工作區",
  preferences: "偏好",
  pages: "頁面",
  gridView: "網格視圖",
  listView: "列表檢視",
  lastCreated: "最後建立",
  lastUpdated: "最後更新",
  searchMembers: "搜尋成員",
  or: "Or",
  add_collaborators: "添加協作者",
  selectWorkspace: "選擇工作區",
  selectWorkspaceIntegrations: "選擇一個工作區進行整合",
  change: "更改",
  createNewWorkspace: "創建新工作區",
  notSeeingYourWorkspace: "看不到您的工作區？嘗試不同的電子郵件：",
  dismiss: "忽略",
  load: "加載",
  youAlreadyHave: "您已經有",
  openBoard: "打開看板",
  cardCannotBeMovedDirectlyToSpace: "卡片不能直接移動到空間中。",
  clickToRename: "點擊重命名",
  info: "信息",
  clearAllFilters: "清除所有篩選器",
  is: "是",
  is_not: "不是",
  includes: "包括",
  excludes: "排除",
  fullscreen: "全螢幕",
  commentsActivity: "評論和活動",
  show: "顯示",
  newestFirst: "最新優先",
  oldestFirst: "最舊優先",
  pageCreated: "頁面已創建",
  ["quickPage.label.setAsDefaultSpace"]: "設為默認空間",
  createNewList: "創建新列表",
  enterListName: "輸入列表名稱",
  listStatus: "列表狀態",
  print: "列印",
  reactedWith: "回應了",
  you: "您",
  cannotModidyListStatus: "當已添加%{resourceType}時，無法修改列表狀態",
  onlineAgain: "您已重新連線",
  youAreOffline: "您已離線",
  exploring: "探索中",
  deactivated: "已停用",
  deleteView: "刪除已儲存篩選器",
  saveAsNewView: "另存為新的已儲存篩選器",
  noResults: "沒有結果",
  thisFilterDoesNotMatch: "此篩選器不匹配任何卡片",
  rememberChoice: "記住選擇",
  electronOpenInApp: "在應用中打開",
  electronOpenInDesktopApp: "在桌面應用中打開",
  electronOpenLinksInDesktopApp: "在桌面應用中打開鏈接",
  electronAutoOpenLinksInDesktopApp: "自動在桌面應用中打開Superthread鏈接",
  electronCurrentLinkOpenedInApp: "當前鏈接已在桌面應用中打開",
  electronAppIsInstalled: "看起來您已安裝應用",
  electronUserMentioned: "提到您",
  electronResourceMoved: "移動了一個",
  electronMemberAdded: "將您添加到一個",
  electronMemberRemoved: "將您從一個中移除",
  electronCommentAdded: "添加了一條新評論",
  electronResourceArchived: "歸檔了一個",
  electronUserReacted: "回應：",
  results: "結果",
  tasks: "任務",
  updateAppToEditPage: "請更新應用程式以編輯此頁面",
  electronRecentlyViewed: "最近查看",
  electronOpenDesktopApp: "打開桌面應用程式",
  electronRedirectingToApp: "正在重定向到桌面應用程式...",
  updateAppToEditComment: "請更新應用程式以編輯此評論",
  updateAppToEditCard: "請更新應用程式以編輯此卡片",
  connectToImporter: "連接到%{importerName}",
  accessToken: "存取權杖",
  installationCloudHostname: "安裝 / 雲端主機名稱",
  findInYour: "在您的",
  emailAddressYouUseFor: "用於%{importerName}帳戶的電子郵件地址",
  selectWhich: "選擇哪個",
  selectBoardsToImport: "選擇您想要從%{boardEq}匯入%{cardEq}的%{boardEq}",
  importYourExistingNameToST:
    "將您現有的%{importerName} %{boardEq}匯入到Superthread",
  jiraBoardMapingSubtitle: "選擇您想從Jira匯入的看板。",
  trelloBoardMapingSubtitle: "選擇您想從Trello匯入的看板。",
  shortcutBoardMapingSubtitle: "選擇要從中匯入故事的團隊和工作流程。",
  jiraQuickImportText:
    "所有團隊將被匯入到一個名為‘jira-import’的空間。您可以輕鬆地從那裡重新命名和重新組織您的看板。",
  trelloQuickImportText:
    "所有團隊將被匯入到一個名為‘trello-import’的空間。您可以輕鬆地從那裡重新命名和重新組織您的看板。",
  shortcutQuickImportText:
    "每個‘team-workflow’看板將被匯入到一個名為‘shortcut-import’的空間。您可以輕鬆地從那裡重新命名和重新組織您的看板。",
  jiraCustomImportText: "選擇要匯入的看板，以及它們應該被匯入到哪些空間。",
  trelloCustomImportText: "選擇要匯入的看板，以及它們應該被匯入到哪些空間。",
  shortcutCustomImportText:
    "選擇要匯入的‘team-workflow’看板，以及它們應該被匯入到哪些空間。",
  superthreadSpace: "Superthread空間",
  mapImporterUsersToSTUSers:
    "將%{importerName}用戶映射到Superthread用戶（或邀請缺失的用戶）以保留卡片成員、創建者和活動。",
  startImport: "開始匯入",
  wellLetYouKnowWhenImportFinishes: "匯入完成時，我們會通知您",
  feelFreeToContuinueUsingST: "隨時繼續使用Superthread",
  dontImportThisUser: "不要匯入此用戶",
  matchToAnExistingSTUser: "匹配到現有的Superthread用戶",
  createANewUser: "創建新用戶（電子郵件邀請）",
  projectsCannotBeMovedToSpaces: "專案無法移動到空間",
  importOpenStories: "匯入開放的故事",
  importOpenStoriesDesc: "未解決或已開啟的故事將以其現有狀態匯入。",
  importStaleStories: "匯入過時的故事",
  importStaleStoriesDesc:
    "超過6個月未開啟的故事被視為過時。它們將被匯入到存檔中，並可以稍後取消存檔。",
  wedLikeToTake: "我們想花",
  thirtySeconds: "30秒",
  toShowYouAround: "帶您四處看看",
  getStarted: "開始使用",
  youCanAlways: "您可以隨時從側邊欄的幫助部分重新訪問此教程",
  youreGoodToGo: "您可以開始了。",
  quickStart: "快速入門教程",
  getToKnow: "在30秒內了解Superthread",
  desktopApp: "桌面應用程式",
  thisLinkWasOpenedInApp: "此連結已在桌面應用程式中打開",
  openHereInstead: "改為在此打開",
  browseAndManageSpaces: "瀏覽和管理空間",
  manageSpaces: "管理空間",
  searchSpaces: "搜尋空間",
  createSpace: "建立空間",
  addADescription: "新增描述",
  showingNumberOfSpaces: "顯示 %{totalNum} 個空間中的 %{num} 個結果",
  noResultsFoundFor: "未找到 ”%{query}” 的結果",
  changeDescription: "更改描述",
  contents: "內容",
  createSpaceSubtitle:
    "空間包含相關的看板、任務和頁面。您可能會有每個團隊或業務領域的空間。",
  spaceNameAndIcon: "空間名稱和圖示",
  somethingShortAndClear: "簡短且清晰",
  youCanChangeThisLater: "您可以稍後更改此項",
  descritionOptional: "描述（可選）",
  whatIsThisSpaceFor: "這個空間的用途是什麼？",
  addPeopleToSpaceOptional: "將人員添加到此空間（可選）",
  addPeople: "添加人員",
  addPeopleSubtitle:
    "如果您邀請不屬於 %{workspaceName} 工作區的人，他們將被添加到其中。",
  openSpace: "開放空間",
  openSpaceSubtitle: "工作區的所有成員都可以瀏覽和加入開放空間",
  privateSpaceSubtitle:
    "工作區成員無法查看或加入私人空間，除非他們被現有成員邀請",
  inviteNewPeople: "邀請新成員",
  inviteeEmailAddress: "被邀請者的電子郵件地址",
  inviteSectionSubtitle: "他們將被邀請加入整個工作區，而不僅僅是這個空間。",
  couldntCreateSpace: "無法創建空間，請再試一次。",
  spaceCreated: "空間已創建。",
  emailAlreadyAdded: "電子郵件已添加",
  addingSomeMembersFailed: "添加某些成員失敗",
  founder: "創始人",
  director: "主管",
  teamLead: "團隊領導",
  individualContributor: "個人貢獻者",
  softwareEngineering: "軟體工程",
  design: "設計",
  productManagement: "產品管理",
  marketing: "行銷",
  finance: "財務",
  development: "開發",
  marketer: "行銷人員",
  sales: "銷售",
  clickToView: "點擊查看",
  clickToDownload: "點擊下載",
  business: "商業",
  pickAllThatApply: "選擇所有適用項目",
  pickOne: "選擇一項",
  customerSupport: "客戶支持",
  humanResources: "人力資源",
  socialMedia: "社交媒體",
  wordOfMouth: "口碑",
  searchEngine: "搜尋引擎",
  advertising: "廣告",
  searchForSpaceOrBoard: "搜尋空間或看板",
  starTypingToSearchFor: "開始輸入以搜尋",
  ["my-work"]: "我的卡片",
  ["myWork.assigned"]: "指派給%{userName}",
  ["myWork.created"]: "由%{userName}建立",
  ["myWork.notes"]: "筆記",
  ["myWorkNoResults.created"]: "沒有由您建立的卡片",
  ["myWorkNoResults.assigned"]: "沒有指派給您的卡片",
  ["memberNoResults.assigned"]: "沒有指派給%{userName}的卡片",
  ["memberNoResults.created"]: "沒有由%{userName}建立的卡片",
  newCard: "新卡片",
  addedCommentHiddenByFilter: "新增的評論被篩選器隱藏",
  createdCardHiddenByFilter: "建立的卡片可能被篩選器隱藏",
  viewMyWork: "查看我的卡片",
  viewWork: "查看 %{displayName} 的卡片",
  removeFromSpace: "從空間中移除",
  assignedInThisBoard: "在此看板中指派",
  layout: "佈局",
  createdCardMovedSortOrder: "建立的卡片可能因排序順序而移動",
  createCardGroupBy: "卡片已新增至%{list}。",
  canNotMoveCardInsameBoard: "無法在同一看板中移動卡片。",
  latestReply: "最新回覆",
  replyLabel: "回覆",
  totalReplies: "總回覆數",
  olderReplies: "較舊的回覆",
  leaveReply: "留下回覆...",
  hideReplies: "隱藏回覆",
  showReplies: "顯示回覆",
  oneReply: "回覆",
  discardComment: "捨棄評論？",
  areYouSureYouWantToDiscard: "您確定要捨棄您的評論嗎？",
  skipToEnd: "跳至結尾",
  priority: "優先級",
  noPriority: "無優先級",
  urgent: "緊急",
  high: "高",
  medium: "中",
  low: "低",
  priorities: "優先級",
  changedThePriorityFrom: "將優先級從更改為",
  changedTheEstimateFrom: "將估算從更改為",
  setThePriorityTo: "將優先級設為",
  setTheEstimateTo: "將估算設為",
  removedTheEstimate: "移除估算",
  thereAreNoPages: "此空間中沒有頁面。",
  createNewPageOrDrag: "在側邊欄中建立新頁面，或將現有頁面拖入此空間。",
  thereAreNoBoards: "此空間中沒有看板。",
  createNewBoardOrDrag: "在側邊欄中建立新看板，或將現有看板拖入此空間。",
  commentsOnly: "僅評論",
  activityOnly: "僅活動",
  seeCardsWithThisTag:
    "查看具有此標籤的卡片（計數包括可能不在其他地方顯示的卡片）",
  noResultsForThatName: "該名稱沒有結果",
  youCan: "您可以",
  createASpace: "創建一個空間",
  named: "命名為 ”%{query}”",
  estimate: "估算",
  onePoint: "1 點",
  numberOfPoints: "%{num} 點",
  extraSmall: "特小",
  small: "小",
  mediumSize: "中",
  large: "大",
  extraLarge: "特大",
  noEstimate: "無估算",
  settingsProjectsPreferencesSubtitle: "這些設定將影響空間的所有成員",
  howCardsAreEstimated: "此空間中卡片的估算方式",
  disableCardEstimationForThisSpace: "禁用此空間的卡片估算",
  fibonacciPoints: "斐波那契點數",
  exponentialPoints: "指數點數",
  tshirtSizes: "T恤尺寸",
  setEstimate: "設定估算",
  emailNotificationHelperText:
    "每個工作日發送一封包含您自上次電子郵件以來未查看通知的電子郵件",
  estimated: "已估算",
  cardSpaceEstimationTurnedOff: "此卡片屬於已關閉估算的空間",
  totalEstimatePointsTooltipContent:
    "在 %{numOfCards} 張卡片中共估算 %{totalPoints} 點",
  estimates: "估算",
  assignItTo: "分配給",
  searchForACard: "搜索卡片",
  createACard: "創建卡片",
  archivedCardsAreHidden: "已存檔的卡片被隱藏",
  enterANameAbove: "在上方輸入名稱",
  chooseFiltersYouWouldLike: "然後在篩選欄中選擇您想要的篩選器",
  cannotCreateViewOnMobile: "你無法在行動裝置上建立已儲存篩選器。",
  viewCardInBoard: "在其自己的看板中查看卡片",
  guestsMustBeAddedToOneSpace: "訪客必須至少被添加到一個空間",
  createCard: "創建卡片",
  suggestedBasedOnTitle: "根據標題的建議",
  acceptSuggestion: "接受建議",
  rejectSuggestion: "拒絕建議",
  suggestionPlaceholderText: "建議...",
  changeEmail: "更改電子郵件",
  logOutAndContinue: "登出並繼續",
  confirmAccountOwnership: "確認帳戶所有權",
  reauthenticateEmailDescription:
    "為了保持您的帳戶安全，我們需要您重新登錄。然後您將能夠選擇新的電子郵件地址並完成此過程。",
  enterANewEmail: "輸入新的電子郵件地址：",
  resendLoginCode: "重新發送登錄代碼",
  emailAddressTakenByAnotherUser: "電子郵件地址已被其他用戶使用",
  assistant: "助手",
  changeTone: "更改語氣",
  simplify: "簡化",
  summarize: "總結",
  translate: "翻譯",
  generate: "生成",
  replaceText: "替換文字",
  insertBelow: "插入在下方",
  assistanceWith: "您需要什麼幫助？",
  copiedToClipboard: "已複製到剪貼簿",
  academic: "學術",
  casual: "隨意",
  confident: "自信",
  friendly: "友好",
  neutral: "中立",
  professional: "專業",
  aiFeatures: "AI 功能",
  emailDigestSentAt: "電子郵件摘要於",
  inYourTimezone: "在您的時區 (%{timezone})",
  timezone: "時區",
  setAutomatically: "自動設置",
  searchTimezone: "搜尋時區",
  changeYourTimezoneInProfile: "在個人資料中更改您的時區。",
  enableNotificationsFirst: "首先啟用 %{type} 通知",
  turnOnAIAssitantInFormatingToolbar: "在文字格式工具欄中開啟 AI 助手",
  superthreadSendingDataTo:
    "請注意，如果您為工作區啟用此功能，即表示您同意 Superthread 傳送數據至",
  experimentalFeatureMayChangeFunctionality:
    "此實驗性功能可能會在功能和定價上有所變動。",
  contactUsToEnable: "聯繫我們以啟用此功能。",
  boardOpenedInTheBackground: "%{boardTitle} 看板已在背景中打開",
  resetFilters: "重置篩選器",
  ["create_space.title"]: "創建一個空間",
  ["create_space.tooltip"]: "為您的團隊工作創建一個家",
  ["create_private_space.title"]: "創建私人空間",
  ["create_private_space.tooltip"]: "只有您邀請的人才能看到私人空間",
  ["invite_user.title"]: "邀請其他人",
  ["invite_user.tooltip"]: "邀請您的團隊成員加入工作區，以便他們可以跟蹤工作",
  ["mention_anything.title"]: "提及某事",
  ["mention_anything.tooltip"]: "使用 @ 鍵在任何可以書寫的地方提及某事",
  ["mention_something.title"]: "提及某事",
  ["mention_something.tooltip"]: "使用 @ 鍵在任何可以書寫的地方提及某事",
  ["add_child_card.title"]: "添加子卡片",
  ["add_child_card.tooltip"]: "子卡片幫助您將工作分解為更小的任務",
  ["visit_inbox.title"]: "查看你的通知",
  ["visit_inbox.tooltip"]: "透過通知掌握所有你訂閱的內容",
  ["move_page.title"]: "移動頁面",
  ["move_page.tooltip"]: "在側邊欄中拖動頁面以隨意移動",
  ["create_subpage.title"]: "創建子頁面",
  ["create_subpage.tooltip"]: "子頁面存在於其他頁面內，幫助您結構化文檔",
  ["add_page_icon.title"]: "添加頁面圖標",
  ["add_page_icon.tooltip"]: "頁面圖標幫助您在搜尋和側邊欄中再次找到頁面",
  ["add_page_cover.title"]: "添加頁面封面圖片",
  ["add_page_cover.tooltip"]: "用封面圖片設置頁面的基調",
  ["quick_card_shortcut.title"]: "快速卡片快捷鍵 (C)",
  ["quick_card_shortcut.tooltip"]: "在任何地方按 C 鍵創建卡片",
  ["quick_page_shortcut.title"]: "快速頁面快捷鍵 (P)",
  ["quick_page_shortcut.tooltip"]: "在任何地方按 P 鍵創建頁面",
  ["create_card.title"]: "創建卡片",
  ["create_card.tooltip"]: "為每個您想追蹤的任務建立卡片",
  ["comment_on_card.title"]: "在卡片上評論",
  ["comment_on_card.tooltip"]: "在卡片上寫下更新或記錄您的想法",
  ["search_shortcut.title"]: "使用 ⌘+K 找到某些東西",
  ["search_shortcut.tooltip"]: "使用此快捷鍵快速在任何地方打開全域搜尋",
  ["create_board.title"]: "建立看板",
  ["create_board.tooltip"]: "追蹤子團隊或專案的工作",
  ["upload_avatar.title"]: "上傳頭像",
  ["upload_avatar.tooltip"]: "幫助人們在應用程式中識別您",
  ["create_page.title"]: "建立頁面",
  ["create_page.tooltip"]: "使用頁面捕捉知識和想法",
  ["set_your_name.title"]: "設定您的名字",
  ["set_your_name.tooltip"]: "您的名字將在整個應用程式中使用",
  ["create_quick_card.title"]: "快速卡片快捷鍵 (C)",
  ["create_quick_card.tooltip"]: "在任何地方按下 C 鍵即可創建卡片",
  ["create_quick_page.title"]: "快速頁面快捷鍵 (P)",
  ["create_quick_page.tooltip"]: "在任何地方按下 P 鍵即可創建頁面",
  ["open_search_modal.title"]: "使用 ⌘+K 尋找內容",
  ["open_search_modal.tooltip"]: "隨時快速開啟搜尋以找到您的資源",
  ["check_your_notifications.title"]: "查看你的通知",
  ["check_your_notifications.tooltip"]: "透過通知掌握所有你訂閱的內容",
  ["change_board_layout.title"]: "嘗試不同的看板版面",
  ["change_board_layout.tooltip"]: "了解不同版面如何協助您管理工作",
  ["try_slash_command.title"]: "試試斜線指令",
  ["try_slash_command.tooltip"]: "輸入 / 以查看可用指令清單",
  ["move_card.title"]: "移動卡片",
  ["move_card.tooltip"]: "將卡片移動到不同的看板或狀態",
  ["add_card_cover_image.title"]: "新增卡片封面圖片",
  ["add_card_cover_image.tooltip"]: "為卡片新增封面圖片以獲得更好的視覺效果",
  aCardMustHaveATitle: "卡片必須有一個標題",
  showAll: "顯示全部",
  showLess: "顯示較少",
  hideEmptyGroups: "隱藏空群組",
  showAnotherAssignee: "顯示另一位受讓人",
  showAnotherTags: "顯示其他標籤",
  spaceMembers: "空間成員",
  addExistingMembers: "添加現有成員",
  inviteNewMembers: "邀請新成員",
  spaceDetails: "空間詳情",
  makeBoardFullWidth: "使看板全寬",
  askAiAssistantSearch: "根據您的卡片、頁面和筆記詢問 AI",
  backToSearchResults: "返回搜尋結果",
  sources: "來源",
  askAiQuestionLong: "問題應至少有 10 個字元。",
  spaceSprintsSettings: "%{space} 空間衝刺設置",
  turnOnSprintsForThisSpace: "為此空間開啟衝刺",
  turnOnSprintsDesc:
    "將在此空間的側邊欄中添加一個“衝刺”部分。衝刺是一個具有開始和結束日期的看板。當一個衝刺完成後，下一個將自動開始。",
  ownersAdminsCanTurnOnSprints:
    "只有工作區擁有者、管理員和空間創建者可以更改此設置",
  onlyOwnerOfPrivateSpace: "只有私人空間的擁有者可以更改此設置",
  onlySpaceOwnerCanModifyMembers: "只有擁有者可以更改空間成員",
  cannotModifySpaceOwner: "您無法更改空間擁有者",
  sprintLength: "衝刺長度",
  weeks: "週",
  sprintStartOn: "衝刺開始於",
  coolDownPeriod: "衝刺之間的冷卻期",
  coolDownPeriodDesc:
    "每個衝刺之間將添加一個冷卻期。這些對於例如回顧和清理活動很有用。",
  coolDownPeriodLength: "冷卻期長度",
  sprintBoardStatuses: "衝刺看板狀態",
  sprintBoardStatusesDesc:
    "此空間中的每個衝刺使用相同的狀態。您必須至少有每種狀態類型的一個。“待辦事項”狀態類型不可用。",
  addStatus: "添加狀態",
  dueInDays: "在 %{days} 天內到期",
  sprints: "衝刺",
  addSprint: "添加衝刺",
  sprint: "衝刺",
  openSprint: "開啟衝刺",
  renameSprint: "重命名衝刺",
  markAsComplete: "標記為完成",
  changeSprintDates: "更改衝刺日期",
  changeSprintDatesFor: "更改%{sprintName}的日期",
  cancelSprint: "取消衝刺",
  changeDates: "更改日期",
  chooseNewStartAndEndDates: "選擇%{sprintName}的新開始或結束日期",
  renameSprintDescription: "輸入衝刺的新名稱。",
  startDateIsEarlierThanPreviousEndDate: "開始日期與上一個衝刺的結束日期重疊",
  enterSprintName: "輸入衝刺名稱",
  cancelSprintWarning: "此看板中所有未完成的卡片將被移至取消狀態。",
  dontCancel: "不要取消",
  upgradePlan: "升級計劃",
  choosePlan: "選擇計劃",
  upgradePrivateSpaceTitle: "升級以獲得私人空間",
  upgradePrivateSpaceDescription: "您可以在付費計劃中創建私人空間。",
  upgradePlanBadgeTooltip:
    "只有擁有者（%{spaceOwner}）和管理員可以更改工作區計劃",
  upgradeUserRolesTitle: "升級以獲得用戶角色",
  upgradeUserRolesDescription: "您可以在付費計劃中選擇非管理員用戶角色。",
  upgradedWorkspace: "您的工作區已升級！",
  workspaceSubscriptionChanged: "您的工作區訂閱已更改",
  sprintSettings: "衝刺設置",
  electronDownloadApp: "下載應用程式",
  electronDownloadAppDescription:
    "我們僅支持macOS。如果有Windows應用程式的需求，請告訴我們。",
  macArm64Label: "蘋果矽晶",
  macx64Label: "Apple Intel",
  windowsx64Label: "Windows",
  mailCopiedToClipboard: "電子郵件已複製到剪貼板",
  cardsWithNoSprint: "沒有衝刺的卡片",
  showCardsFrom: "顯示卡片來自",
  yourColor: "您的顏色",
  thisColorWillHelp: "此顏色將幫助其他人識別您在某些地方。",
  logo: "標誌",
  prStateOpen: "%{count}個開啟",
  prStateClosed: "%{count}個關閉",
  prStateMerged: "%{count}個合併",
  invitingPeopleToWorkspace: "只有管理員可以邀請新成員加入此工作區",
  upgradePublicPageIndexingTitle: "升級以進行搜索引擎索引",
  upgradePublicPageIndexingDescription: "您可以在付費計劃中開啟搜索引擎索引。",
  shortcutWarningText: "任何未分配給團隊的Shortcut故事將不會被導入。",
  coolDown: "冷卻",
  noBoardsOrPages: "沒有看板或頁面",
  language: "語言",
  usersWork: "%{name}的工作",
  renameAttachment: "重命名附件",
  deleteAttachment: "刪除附件",
  timelineLayoutDescription: "升級您的工作區計劃以使用時間線佈局。",
  calendarLayoutDescription: "升級您的工作區計劃以使用日曆佈局。",
  upgradeTemplatesDescription: "升級您的工作區計劃以使用模板。",
  upgradeRoadmapAndProjectsDescription: "升級您的工作區計劃以使用專案。",
  upgradeViewsDescription: "升級工作區方案以儲存已儲存篩選器。",
  createNewItem: "創建新項目",
  statusType: "狀態類型",
  spaceLimitReached: "已達到空間限制。您可以刪除一些空間以創建更多。",
  freePlanUsageLimits: "免費方案使用限制",
  item: "項目",
  usage: "使用情況",
  limitReachedLong: "如果達到限制，您需要刪除項目或升級方案才能創建新項目。",
  limitReached: "已達到限制",
  resourceAndContentWillBeDeleted:
    "%{resourceType} ”%{resourceTitle}” 及其內容將被永久刪除，無法恢復。",
  resourceWillBeDeleted:
    "%{resourceType} ”%{resourceTitle}” 將被永久刪除，無法恢復。",
  epicWillBeDeleted:
    "%{resourceType} ”%{resourceTitle}” 將被永久刪除，無法恢復。任何已添加到項目的卡片將不會被刪除。",
  listNameLabel: "列表名稱",
  deleteList: "刪除列表",
  hideColumn: "Hide column",
  selectAllInColumn: "Select all in column",
  selectAllInBoard: "Select all in board",
  showColumn: "Show",
  hiddenColumns: "Hidden lists",
  hiddenByLayoutToggle: "This list is hidden by the layout toggle",
  itemName: "項目名稱",
  moveCardIntoSprint: "卡片已移動到衝刺 %{sprintName}",
  addView: "新增已儲存篩選器",
  timeCreatedSort: "創建時間",
  timeUpdatedSort: "更新時間",
  dueDateSort: "到期日",
  noSprintsLabel: "無衝刺",
  createdViaEmailFrom: "通過電子郵件創建",
  couldNotBeVerified: "無法驗證",
  createCardsViaEmailTitle: "通過電子郵件在此看板中創建卡片",
  createCardsViaEmailDescription:
    "如果有人向一個電子郵件地址發送消息，則在此看板中創建一張卡片。",
  onlyCurrentAddressWillWork: "只有當前顯示的地址有效。",
  regenerate: "重新生成",
  emailCopiedToClipboard: "電子郵件已複製到剪貼板",
  emailRegenerated: "電子郵件已重新生成",
  slackChannelNotifications: "Slack 頻道通知",
  slackChannelNotificationsTitle: "將此看板中的卡片通知發送到 Slack 頻道",
  slackChannelNotificationsDescriptionDisabled:
    "將打開一個 Slack 窗口並要求您選擇一個頻道",
  slackChannelNotificationsDescriptionEnabled:
    "此看板的通知已發送到 Slack 中的 %{channel}。",
  slackIntegrationError: "無法啟用 Slack 集成。請重試",
  boardDoesNotExists: "該看板不存在",
  boardActivity: "看板活動",
  sendTo: "發送到",
  slackPrivateMessage: "私人消息",
  slackPrivateGroup: "私人對話",
  slackPrivateChannel: "私人頻道",
  webhookNotificationCardCreatedOnBoard: "在此看板上創建的卡片",
  webhookNotificationCardMovedToBoard: "卡片已移動到此看板",
  webhookNotificationCardAddedBoard: "卡片已添加/移動到看板",
  webhookNotificationCardAddedList: "卡片已添加/移動到狀態",
  webhookNotificationCardCommented: "在看板上的卡片留下的評論（不包括回覆）",
  webhookNotificationCardDueDate: "卡片到期日即將到來/已過期",
  folder: "文件夾",
  yourSpaces: "您的空間",
  quoteReply: "引用並回覆",
  itemHasBeenDeleted: "%{resourceType} 已被刪除",
  deletedNotification: "已刪除",
  searchForBoard: "搜索看板",
  activeSprintText: "目前",
  loadMoreSprints: "載入更多短衝",
  try: "嘗試",
  ["add_workspace_logo.title"]: "新增工作區標誌",
  ["add_workspace_logo.tooltip"]: "上傳標誌",
  ["customise_your_profile.title"]: "自訂您的個人資料",
  ["customise_your_profile.tooltip"]: "新增個人資料照片",
  ["import_tasks.title"]: "匯入任務",
  ["import_tasks.tooltip"]: "從 Trello、Jira 或 Shortcut 匯入",
  ["view_keyboard_shortcuts.title"]: "查看鍵盤快捷鍵",
  ["view_keyboard_shortcuts.tooltip"]: "打開鍵盤快捷鍵表",
  ["connect_slack.title"]: "連接 Slack",
  ["connect_slack.tooltip"]: "開啟 Slack 通知",
  seeAllWorkspaces: "查看所有工作區",
  workspaceSettings: "設定與偏好",
  switchToRecentWorkspace: "切換到最近的工作區",
  icon: "圖示",
  addToSprint: "新增到短衝",
  addToProject: "新增到專案",
  goToProject: "前往專案",
  addTags: "新增標籤",
  cancelled: "已取消",
  sprintBoards: "短衝看板",
  sprintSettingsBoardsDescription: "這些設定適用於此空間中的所有短衝",
  addedCard: "已新增卡片",
  removedCard: "已移除卡片",
  addNewCard: "新增新卡片",
  addExistingCard: "新增現有卡片",
  changeEpicOrParent: "更改專案或父項",
  cardAlreadyHasEpicOrParent:
    "選擇的卡片已經有專案或父卡片。如果您將其新增到此專案，它們將被更改。",
  changeEpic: "更改專案",
  childCardIsPartOfEpic: "子卡片是專案 ”%{epicName}” 的一部分。",
  parentCardHasNoEpic: "父卡片沒有專案。",
  parentCardIsPartOfEpic: "父卡片是專案 ”%{epicName}” 的一部分。",
  childCardsEpicWillBeRemoved: "如果您繼續，子卡片的專案將被移除。",
  childCardsEpicWillChangeToParents:
    "如果您繼續，子卡片的專案將更改為父卡片的專案。",
  removeEpic: "移除專案",
  epicWillNoLongerBeAssociated:
    "如果您將子卡片從其父卡片中移除，它將不再與專案 ”%{epicName}” 關聯。",
  childCardAlreadyHasParent:
    "子卡片已經有父項。如果您繼續，父項將更改為此卡片。",
  cardsDirectlyAddedToEpicCantHaveParent: "直接新增到專案的卡片不能有父卡片",
  epicNoTagsFound: "未找到標籤。專案只能使用工作區標籤",
  cannotChangeStatusForCardsInFinishedSprint: "無法更改已完成短衝中的卡片狀態",
  cannotChangeStatusForArchivedCards: "無法更改已封存卡片的狀態",
  cantMoveArchivedCardToSprint: "無法將已封存的卡片移動到短衝",
  relatedTo: "相關於",
  changePriority: "更改優先順序",
  changeEstimate: "更改估算",
  changeTags: "更改標籤",
  changeSprint: "更改短衝",
  goToSprint: "前往短衝",
  pastSprints: "過去的短衝",
  currentAndPlannedSprints: "當前和計劃中的短衝",
  seeAllSprints: "查看所有短衝",
  currentAndNextSprint: "當前和下一個短衝",
  branchSpecificAutomationAddFailed: "無法新增分支特定的自動化。",
  branchSpecificAutomationUpdateFailed: "無法更新分支特定的自動化。",
  branchSpecificAutomationRemoveFailed: "無法移除分支特定的自動化。",
  thereAreNoCurrentOrPlannedSprints: "沒有當前或計劃中的短衝",
  thereIsNoCurrentOrNextSprint: "沒有當前或下一個短衝",
  movedCardFrom: "已將卡片從",
  movedEpicFrom: "已將專案從",
  rolledCardFrom: "已將卡片滾動從",
  sprintMarkedAsCompleted: "短衝標記為已完成",
  sprintMarkedAsCancelled: "短衝標記為已取消",
  cardIsParent: "卡片是父項",
  cardIsChild: "卡片是子項",
  cardIsRelated: "卡片是相關項",
  parentCard: "父卡片",
  moveTo: "移動到...",
  pageMovedTo: "頁面已移動到",
  thisSpaceIsEmpty: "此空間為空",
  createSomethingToGetStarted: "創建一些內容以開始",
  visualiseYourWorkflow: "可視化您的工作流程、追蹤工作並保持井然有序",
  captureImportantInformation: "捕捉重要信息，與他人協作，並分享至網絡",
  organiseWorkIntoSprints: "將工作組織成一段段時間，以便更輕鬆地計劃",
  filterYourWorkspaceToCreateViews:
    "篩選你的工作區以建立已儲存篩選器並與團隊分享。",
  turnOnSprints: "開啟短衝",
  cardViews: "卡片視圖",
  convert: "轉換",
  convertCardToEpic: "將卡片轉換為專案",
  couldNotConvertCardToEpic: "無法將卡片轉換為專案",
  cardSuccessfullyConvertedToEpic: "卡片成功轉換為專案",
  convertedCardWillLose: "如果您將此卡片轉換為專案，它將失去其%{arr, list}。",
  convertedThisCardToEpic: "將此卡片轉換為專案",
  spaceLevelTags: "空間級標籤",
  effortEstimate: "工作量估算",
  existingEpic: "現有專案",
  roadmapMustHaveAtLeastOneStatus: "專案看板必須至少有一個狀態",
  chosenPageIsAlreadySubpage: "選擇的頁面已經是當前頁面的子頁面",
  searchForResults: "搜索以顯示結果",
  parentCardIs: "父卡片是...",
  projectIs: "專案是...",
  convertedTo: "轉換為",
  moveToCompletedSprint: "移動到已完成的短衝？",
  onlyDoneCardsCanBeMovedToCompletedSprint:
    "只有“完成”的卡片可以移動到已完成的短衝。此卡片將更改為“完成”並移動。",
  removeCardFromProject: "從專案中移除卡片",
  roadmapOpenedInTheBackground: "專案已在背景中打開",
  unfavouriteCurrentSprint: "取消收藏當前短衝",
  favouriteCurrentSprint: "收藏當前短衝",
  unfavouriteNextSprint: "取消收藏下一個短衝",
  favouriteNextSprint: "收藏下一個短衝",
  unfavouriteSprintName: "取消收藏 %{sprintName}",
  favouriteSprintName: "收藏 %{sprintName}",
  currentSprint: "當前短衝",
  parentWillBeRemovedIfAddToProject:
    "如果您將此卡片添加到專案中，父卡片將被移除，因為卡片會從父卡片繼承專案",
  cannotArchiveCardFromSprint: "無法從短衝中歸檔卡片",
  sprintCompleted: "短衝已完成",
  sprintCancelled: "短衝已取消",
  sprintDatesChanged: "短衝日期已更改",
  myWorkAndNotes: "我的卡片與筆記",
  notes: "我的筆記",
  suggestedActions: "建議的操作",
  noSuggestedActions: "沒有建議的操作",
  noChanges: "沒有變更",
  changes: "變更",
  cardUpdatedSuccessfully: "卡片更新成功",
  commentAddedSuccessfully: "評論添加成功",
  updateCard: "更新卡片",
  moveCard: "移動卡片",
  assignMembers: "分配成員",
  removeMembers: "移除成員",
  generatingSuggestedActions: "正在生成建議的操作",
  replaceContent: "替換內容",
  appendContent: "附加內容",
  addDescription: "添加描述",
  addDueDate: "添加截止日期",
  setTitle: "設置標題",
  reject: "拒絕",
  accept: "接受",
  finaliseDetails: "完成細節",
  tidyUp: "整理",
  convertTo: "轉換為...",
  newNote: "新筆記",
  searchNotes: "搜索筆記...",
  favouriteNote: "收藏筆記",
  archiveNote: "歸檔筆記",
  deleteNote: "刪除筆記",
  original: "原始",
  tidied: "已整理",
  untitledNote: "未命名筆記",
  enhanced: "增強",
  minimize: "最小化",
  maximize: "最大化",
  createNewNote: "創建新筆記",
  youDontHaveAnyNotes: "您還沒有任何筆記",
  transcript: "文字記錄",
  assignedCards: "已分配的卡片",
  createdCards: "已創建的卡片",
  noTranscriptAvailable: "沒有可用的文字記錄",
  enhanceNotesUsingMacApp:
    "Superthread 可以從您的會議中轉錄音頻以生成增強筆記。轉錄僅在 macOS 的 Superthread 桌面應用程式中可用。",
  downloadApp: "下載應用程式",
  enhance: "增強",
  macIntel: "Mac Intel",
  appleSilicon: "蘋果矽晶",
  enhanceNotesUsingAI: "使用 AI 增強您的筆記",
  showTranscript: "顯示文字記錄",
  epicCreated: "專案已建立",
  analysingTranscript: "分析文字記錄",
  comparingYourNotes: "比較您的筆記",
  readingYourNotes: "閱讀您的筆記",
  enhancingYourNotes: "增強您的筆記",
  finished: "完成",
  note: "筆記",
  epicMustHaveTitle: "專案必須有標題",
  seeAllNotes: "查看所有筆記",
  autoSaved: "自動儲存",
  projectsAreTrackedOnRoadmap: "專案會在專案看板上被追蹤",
  addCardsToProject: "將卡片添加到此專案",
  projectEmptyStateDescription:
    "專案是一項由工作區中多張卡片組成的大型工作。在欄中創建專案，或編輯預設狀態。",
  cardInProjectEmptyStateFooter: "一張卡片只能屬於一個專案",
  addCardsThatContributeToProject: "添加有助於此專案的卡片。您可以",
  noProject: "無專案",
  noteTemplates: "筆記範本",
  noteTemplatesSettingsSubtitle: "使用範本快速更改筆記格式",
  noNoteTemplates: "無筆記範本",
  createNoteTemplate: "創建筆記範本",
  sections: "部分",
  sectionHeading: "部分標題",
  sectionDescriptionPlaceholder: "此部分應專注於...",
  addSection: "添加部分",
  superthread: "Superthread",
  deletedTemplate: "範本已刪除",
  autoEnhanced: "自動增強",
  meetingContext: "會議背景",
  meetingContextPlaceholder: "提供會議概述以及您希望從中獲得的內容...",
  meetingContextDescription:
    "這有助於 Superthread 瞭解在增強您的筆記時應專注於什麼",
  duplicateTemplate: "複製範本",
  favouriteTemplates: "收藏範本",
  introduction: "介紹",
  sampleSectionDescription:
    "捕捉會議開始時閒聊中的任何有趣話題。忽略有關天氣的討論。",
  allowSuperthreadToTranscribe: "允許 Superthread 轉錄您的會議",
  superthreadCanEnhance:
    "Superthread 可以通過直接從您的筆記本電腦轉錄音頻來增強您的筆記，無需會議機器人。它適用於面對面和虛擬會議，並可完全控制何時開啟。您的音頻絕不會被存儲或用於其他用途。",
  transcribeYourVoice: "轉錄您的聲音",
  transcribeOthersVoice: "轉錄他人的聲音",
  allowMicrophoneCapture: "允許麥克風捕捉",
  allowSystemAudioCapture: "允許系統音頻捕捉",
  microphoneAccessNotAllowedTitle: "手動允許麥克風訪問",
  microphoneAccessNotAllowedDesc1: "之前未允許麥克風訪問，因此您需要手動允許。",
  microphoneAccessNotAllowedDesc2:
    "在 macOS 中，前往系統設定 > 隱私與安全性 > 麥克風，然後允許“Superthread”應用程式。",
  microphoneAccessNotAllowedDesc3:
    "完成後，請退出並重新開啟此應用程式，然後返回此處。",
  systemAccessNotAllowedTitle: "手動允許系統音訊存取",
  systemAccessNotAllowedDesc1: "系統音訊存取先前未被允許，因此您需要手動允許。",
  systemAccessNotAllowedDesc2:
    "在 macOS 中，前往系統設定 > 隱私與安全性 > 螢幕與系統音訊錄製 > 僅系統音訊錄製，然後允許“Superthread”應用程式。",
  systemAccessNotAllowedDesc3:
    "完成後，請退出並重新開啟此應用程式，然後返回此處。",
  editNoteTemplate: "編輯筆記範本",
  viewNoteTemplate: "查看筆記範本",
  viewTranscript: "查看文字記錄",
  transcribeHereInstead: "改在這裡轉錄？",
  currentlyTranscribingAnotherNote:
    "筆記“%{noteTitle}”目前正在轉錄。您想停止那裡的轉錄並改在這裡轉錄嗎？",
  transcribeHere: "在這裡轉錄",
  resume: "繼續",
  pause: "暫停",
  transcribe: "轉錄",
  currentlyTranscribing: "目前正在轉錄",
  transcribingOnlyAvailableOnMac: "轉錄僅在 macOS 應用程式中可用",
  transcribingOnlyAvailableOnDesktop: "轉錄僅在桌面應用程式中可用",
  transcribingOnlyAvailableOnNewerMacVersions:
    "轉錄僅在 macOS 14.2 及更新版本中可用",
  startTranscription: "開始轉錄",
  stopTranscription: "停止轉錄",
  openTranscribingNote: "打開轉錄筆記",
  notesSettings: "筆記設定",
  theseSettingsArePersonalToYou: "這些設定是個人專屬的",
  transcriptionJargonTitle: "術語",
  transcriptionJargonPlaceholder: "技術術語、不常見的名稱、專案名稱等。",
  transcriptionJargonDescription:
    "添加任何您認為音訊轉錄可能有問題的詞。用逗號分隔詞語。",
  selectANote: "選擇一個筆記",
  noteDoesntExist: "筆記不存在",
  deleteSection: "刪除部分",
  untitledSection: "未命名部分",
  messageAgentAssistant: "訊息代理助手",
  initialAgentMessage: "我在這裡幫助您為代理撰寫指令。讓我知道您希望它做什麼。",
  agentMessageError: "發生錯誤。請再試一次。",
  agentInstructions: "代理指令",
  agentIcon: "代理圖示",
  agentName: "代理名稱",
  agentNamePlaceholder: "代理名稱",
  agentInvalidNameError: "請輸入有效的名稱。",
  agentSkill: "技能",
  agentRepository: "儲存庫",
  agentRepositoryPlaceholder: "https://github.com/org/repo",
  agentInvalidRepositoryError: "請輸入有效的儲存庫URL。",
  agentRefOptional: "參照（選填）",
  agentTarget: "目標",
  agentAutoCreatePr: "自動建立PR",
  agentOpenAsCursorGithubApp: "以Cursor GitHub應用程式開啟",
  agentSkipReviewerRequest: "略過審閱者請求",
  agentBranchNameOptional: "分支名稱（選填）",
  agentApiKey: "API金鑰",
  agentApiKeyPlaceholder: "Cursor API金鑰",
  agentApiKeyHelpText: "在後端加密儲存。更新時留空以保留現有金鑰。",
  agentCustomInstructionsOptional: "自訂指令（選填）",
  agentCustomInstructionsPlaceholder:
    "描述此代理應如何運作。這些指令會加在每個提示的前面。",
  agentRuns: "代理執行",
  agentRunsColumnId: "ID",
  agentRunsColumnCreated: "建立時間",
  agentRunsColumnStatus: "狀態",
  agentRunsColumnInputTokens: "輸入權杖",
  agentRunsColumnOutputTokens: "輸出權杖",
  agentRunsColumnIterations: "迭代",
  agentAttachedResources: "已附加資源",
  agentAttachmentResource: "資源",
  agentAttachmentTimeAttached: "附加時間",
  agentAttachmentAttachedBy: "附加者",
  agentDetach: "分離",
  agentAddAgent: "新增代理",
  agentAddAgentDescription: "建立新的Cursor Cloud代理範本。",
  agents: "代理",
  agentNewAgent: "新建代理",
  agentUpdateAgent: "更新代理",
  agentDeleteAgent: "刪除代理",
  agentDeleteConfirmation: "您確定要刪除此代理嗎？此操作無法復原。",
  agentCreatedSuccessfully: "代理建立成功。",
  agentUpdatedSuccessfully: "代理更新成功。",
  agentDeletedSuccessfully: "代理刪除成功。",
  agentLaunchedSuccessfully: "代理啟動成功。",
  agentLaunchFailed: "代理啟動失敗。",
  agentPromptSetSuccessfully: "代理提示設定成功。",
  agentPromptSetFailed: "代理提示設定失敗。",
  agentResetConversationHistory: "重置對話歷史",
  agentSelectThisInstruction: "選擇此指令",
  agentDebug: "[DEBUG]",
  agentIterationId: "迭代ID：",
  agentStatus: "狀態：",
  agentReasoning: "推理：",
  agentFunctions: "函式：",
  agentTriggers: "觸發器：",
  agentFallbackName: "代理",
  agentWorkOnThisCard: "處理此卡片",
  agentActive: "代理已啟用",
  agentSkillCursor: "Cursor",
  agentSkillSuperthread: "Superthread",
  version: "版本",
  templateWithChildCardsNotAllowed:
    "只有當範本沒有自己的子項時，您才能將範本應用於子卡片",
  copyNoteToClipboard: "複製筆記到剪貼簿",
  noteCopiedToClipboard: "筆記已複製到剪貼簿",
  copyTranscriptToClipboard: "複製文字記錄到剪貼簿",
  transcriptCopiedToClipboard: "文字記錄已複製到剪貼簿",
  anyoneWithThisLinkCanViewNote: "任何擁有此連結的人都可以查看筆記",
  notesEnhancedBySuperthread: "由 Superthread 增強的筆記",
  connectGoogleCalendar: "連接 Google 日曆",
  googleCalendarIntegration: "Google 日曆整合",
  googleCalendarIntegrationSubtitle:
    "連接到您的 Google 日曆，以便輕鬆為即將到來的會議創建筆記",
  calendarAccountConnected: "日曆帳戶已連接",
  disconnect: "斷開連接",
  showCalendarMeetingsUpTo: "在筆記列表中顯示最多",
  dayAheadInNotesList: "天前的日曆會議",
  daysAheadInNotesList: "天前的日曆會議",
  eventTypesToIncludeInNotesList: "要在筆記列表中包含的事件類型",
  ["calendar.all_day"]: "全天事件，包括多日事件",
  ["calendar.event_link"]: "沒有會議連結的事件",
  ["calendar.participants"]: "只有一位參加者的事件",
  createNoteFromUpcomingMeeting: "從即將到來的會議創建筆記",
  noUpcomingMeetings: "沒有即將到來的會議。您可以更改時間範圍",
  seeUpcomingMeetings: "在這裡查看即將到來的會議",
  searchForAnApp: "搜尋應用程式...",
  meetingAppsWatched: "%{num} 個會議應用程式被監控",
  automaticMeetingDetectionTitle: "自動會議檢測",
  automaticMeetingDetectionDescription:
    "Superthread 檢測到會議應用程式正在使用麥克風並通知您創建筆記",
  joinMeetingFromNote: "加入 %{provider} 會議 (%{time})",
  searchPlaceholderAskAiNotes: "詢問有關您的筆記的問題...",
  askAi: "詢問 AI",
  transcribeHereInsteadPositive: "改在這裡轉錄",
  notesAreBetterWithOurApp: "使用我們的應用程式，筆記更佳",
  downloadTheMacOSApp: "下載 macOS 應用程式",
  toTranscribeMeetings: "來轉錄會議",
  notifyUpcomingMeetingsTitle: "通知我即將到來的日曆會議",
  notifyUpcomingMeetingsDescription:
    "如果會議即將開始，Superthread 會通知您並提供創建新筆記的選項。",
  macOSApp: "macOS 應用程式",
  requiresMacosAppOne: "需要",
  requiresMacosAppTwo: "macOS 應用程式。",
  meetingsMenuBarTitle: "在選單列應用程式旁顯示即將到來的日曆會議",
  meetingsMenuBarDescription:
    "當天的下一個會議將顯示在選單列的 Superthread 圖標旁。",
  meetingName: "會議名稱",
  meetingTime: "會議時間",
  searchLanguage: "搜尋語言",
  ["get_started_notes.title"]: "開始使用筆記",
  ["get_started_notes.tooltip"]: "會議轉錄和 AI 增強筆記",
  transcriptionNotAvailableOnPlan: "此方案不提供轉錄功能。點擊查看可用方案",
  openLinksInDesktopAppTitle: "登入時開啟桌面應用程式",
  openLinksInDesktopAppDescription: "登入時自動開啟 Superthread 桌面應用程式",
  automaticallyStartTranscription: "自動開始轉錄",
  wheneverICreateANote: "每當我創建筆記時",
  onlyWhenITakeNotesForMeeting: "僅當我為會議做筆記時",
  learnMore: "了解更多",
  withAnInteractiveVideoTutorial: "通過互動式視頻教程",
  newToNotes: "對筆記不熟悉？",
  onlyWhenITakeNotesForMeetingSubtitle:
    "如果您在開始時間前最多 5 分鐘從日曆事件創建筆記，或從筆記加入視頻通話",
  instantEmail: "即時電子郵件",
  emailDigest: "電子郵件摘要",
  instantEmailNotifications: "即時電子郵件通知",
  goToLatest: "前往最新",
  meetingAndTranscriptionSettings: "會議和轉錄設置",
  meetingAndTranscriptionSettingsSubtitle: "這些設置只能在",
  customiseNotesSettingsOne: "或自定義您的",
  customiseNotesSettingsTwo: "筆記設置",
  enableSubGroupBy: "子組依據",
  boardLimitReached: "已達到看板限制。您可以刪除一些看板以創建更多。",
  alphabetical: "按字母順序",
  chronological: "按時間順序",
  numeric: "數字",
  role: "角色",
  invitesPending: "邀請待處理",
  standardMembers: "標準成員",
  guests: "訪客",
  selected: "已選擇",
  bulkActions: "批量操作",
  parentCardWasRemoved: "父卡已被移除。",
  cardRemovedFromProject: "卡已從項目中移除。",
  inactiveMembers: "非活躍成員",
  viewOnlyGuests: "僅查看訪客",
  memberType: "成員類型",
  noGroup: "無群組",
  showEmptyGroups: "顯示空群組",
  notJoined: "未加入",
  inactive: "非活躍",
  imported: "已導入",
  addToSpace: "添加到空間",
  memberAddedToSpace: "已將 1 位成員添加到 %{space} 空間",
  membersAddedToSpace: "已將 %{count} 位成員添加到 %{space} 空間",
  cannotRemoveSpaceOwner: "無法移除空間擁有者",
  pageUsageDescription:
    "使用量是內容和歷史編輯的組合，可能會隨著時間的推移繼續增長",
  pageUsage: "頁面使用量",
  pageUsageWarning:
    "警告：如果使用量達到 100%，您的更改可能不會被保存。考慮創建子頁面或移動到新頁面",
  jobDescription: "工作描述",
  jobDescriptionPlaceholder: "輸入工作描述",
  letPeopleKnowWhatYouDo:
    "讓人們知道你在做什麼。這也有助於 Superthread 創建更相關的增強筆記。",
  workspaceDescriptionLabel: "工作區描述",
  workspaceDescriptionPlaceholder: "輸入工作區描述",
  notesTutorial: "筆記教程",
  learnHowToUseSuperthreadNotes: "學習如何使用 Superthread 筆記",
  myTemplates: "我的模板",
  otherTemplates: "其他模板",
  meetingDate: "會議日期",
  attendees: "參加者",
  withMeeting: "有會議",
  withoutMeeting: "無會議",
  futureMeetings: "未來會議",
  noMeetingDate: "無會議日期",
  noAttendees: "無參加者",
  metadata: "元數據",
  date: "日期",
  cardDueSoon: "卡即將到期",
  cardOverdue: "卡已過期",
  cardAddedToBoardList: "卡已添加到看板或列表",
  pageCommentStatusUpdate: "頁面評論標記為已解決/未解決",
  meetingNotes: "會議筆記",
  regularNotes: "常規筆記",
  editAttendees: "編輯參加者",
  editMeetingDate: "編輯會議日期",
  editMeetingTime: "編輯會議時間",
  meetingDetails: "會議詳情",
  addMeetingDetails: "新增會議詳情",
  copyEmail: "複製電子郵件",
  removeAttendee: "移除與會者",
  hours: "小時",
  minutes: "分鐘",
  removeFromWorkspace: "從工作區移除",
  removeMembersDescription:
    "您確定要從工作區移除 %{count} 位成員嗎？此操作將立即撤銷他們的訪問權限",
  cantIncludeYourselfInBulkRemoval: "您不能將自己包括在批量成員移除中",
  changeRole: "更改角色",
  ownerRolesCannotBeModifiedBulkActions: "無法通過批量操作修改擁有者角色",
  roleChangesOnlyForActiveMembers: "角色更改僅適用於活躍成員",
  allSelectedMembersHaveSelectedRole: "所有選定的成員已經擁有選定的角色",
  successfullyChangedRoleForMember: "成功更改 %{count} 位成員的角色",
  successfullyChangedRolesForMembers: "成功更改 %{count} 位成員的角色",
  includedPeople: "包含的人",
  includedPeopleSubtitle: "最多選擇 %{numberOfPeople} 人",
  selectMembers: "選擇成員",
  noMemberSelected: "未選擇成員",
  schedule: "排程",
  startToGenerateReportOne: "開始生成議程",
  startToGenerateReportTwo: "問題詢問後的分鐘數",
  timeNextRun: "下次運行時間",
  timeNextReport: "下次報告時間",
  timeLastRun: "上次運行時間",
  timeLastReport: "上次報告時間",
  scheduleSubtitle: "在運行開始和議程生成之間，您將無法更改排程",
  startAskingQuestionsAt: "開始詢問問題的時間",
  days: "天",
  agendaDelay: "團隊簽到議程延遲",
  upgradePlanToUseRoadmapAndProjectsTitle: "升級您的計劃以使用專案",
  upgradePlanToUseRoadmapAndProjectsDescription:
    "專案存在於專案看板。專案讓你可以把所有相關卡片集中在同一處，並讓所有人保持最新狀態。",
  weekdays: "工作日",
  weekends: "週末",
  question: "問題",
  submit: "提交",
  previouslyAnswered: "先前已回答：",
  allQuestionsAnswered: "所有問題均已回答。",
  noReportTitle: "沒有可用的建議報告",
  noReportDescription:
    "您的團隊檢查的建議報告尚未準備好。一旦準備好供您輸入，您將收到通知。",
  whatChanged: "有什麼變化？",
  clarificationQuestionReject: "不，我沒有要添加的內容",
  reportFromPastTitle: "這是來自過去的用戶報告通知",
  reportFromPastDescription: "查看通知以查找是否有新的報告通知",
  userSuggestedReportNotificationSidebar: "請回答這些檢查問題",
  userFinalReportNotificationSidebar: "您的最終檢查報告已準備好",
  getStartedWithSuperthread: "開始使用Superthread",
  whatDoYouIntendToUseSuperthreadFor: "您打算將Superthread用於什麼？",
  thisWillHelpUsTailorYourExperience:
    "這將幫助我們根據您的需求量身定制您的體驗。",
  chooseAUseCase: "選擇一個使用案例",
  whereDidYouHearAboutSuperthread: "您是從哪裡聽說Superthread的？",
  yourFeedbackHelpsUsImproveHowWeReach:
    "您的反饋幫助我們改進如何接觸像您這樣的人。",
  twitter: "X（Twitter）",
  reddit: "Reddit",
  linkedin: "LinkedIn",
  substack: "Substack",
  ads: "廣告",
  other: "其他",
  ["onboarding.software_development"]: "軟體開發",
  ["onboarding.recruitment"]: "招聘",
  ["onboarding.marketing"]: "行銷",
  ["onboarding.customer_support"]: "客戶支持",
  ["onboarding.other"]: "其他",
  "onboardingListTasks.committed.heading": '你的「"待辦事項"」有哪些？',
  "onboardingListTasks.started.heading": '你現在正在「"進行中"」的任務是什麼？',
  "onboardingListTasks.completed.heading": '哪些任務已經「"已完成"」？',
  ["onboardingListTasks.committed.0"]: "為我的團隊評估 Superthread 🧐",
  ["onboardingListTasks.committed.1"]: "取消我的 Trello 訂閱 🙈",
  ["onboardingListTasks.committed.2"]: "替團隊買甜甜圈 🍩",
  ["onboardingListTasks.started.0"]: "我那堆積如山的支出 🤑",
  ["onboardingListTasks.started.1"]: "規劃我的下次旅行 🏝️️",
  ["onboardingListTasks.started.2"]: "登上 K2 峰 🏔️",
  ["onboardingListTasks.completed.0"]: "已續訂 ChatGPT ✨",
  ["onboardingListTasks.completed.1"]:
    "發佈了 100% 真實（非 AI）的 LinkedIn 貼文",
  ["onboardingListTasks.completed.2"]: "雇用一位真正的社群媒體經理 😅",
  ["onboarding.quote.0"]: "計劃本身毫無價值，但規劃過程卻是無比重要。",
  ["onboarding.quote.author.0"]: "德懷特·D·艾森豪威爾",
  ["onboarding.quote.1"]: "未能計劃，就是計劃失敗。",
  ["onboarding.quote.author.1"]: "溫斯頓·邱吉爾",
  ["onboarding.quote.2"]: "最困難的事是下定決心去行動，其餘的只是堅持而已。",
  ["onboarding.quote.author.2"]: "阿梅莉亞·艾爾哈特",
  ["onboarding.quote.3"]: "每花一分鐘整理，就能多出一小時的時間。",
  ["onboarding.quote.author.3"]: "班傑明·富蘭克林",
  ["onboarding.quote.4"]: "天賦能贏得比賽，但團隊合作才能贏得冠軍。",
  ["onboarding.quote.author.4"]: "麥可·喬丹",
  ["onboarding.quote.5"]: "當你整理好自己的生活時，人生才真正開始。",
  ["onboarding.quote.author.5"]: "近藤麻理惠",
  ["onboarding.trustedBy.description"]:
    "加入 10,000+ 家透過 Superthread 完成更多工作的公司",
  ["onboarding.video.text1"]: "恭喜你 🎉",
  ["onboarding.video.text2"]: "你剛剛只用",
  ["onboarding.video.text3"]: "先喘口氣……",
  forExample: "例如",
  createYourProfile: "建立你的個人資料",
  createYourProfileDescription: "這將是你在 Superthread 中的呈現方式",
  createYourProfileInputDesc: "你之後可以更改",
  someonesWorkspace: "%{userName}的工作區",
  someonesPrivateSpace: "%{userName}的私人空間",
  someonesBoard: "%{userName}的看板",
  chooseYourVibe: "選擇你的氛圍",
  chooseYourVibeDescription: "至少選擇 2 個，這只是好玩用的",
  exampleCardTitle:
    '👋 把我拖到 "The essentials" 看板裡，然後看看裡面有些什麼吧',
  exampleListTitle: "👀 看這裡",
  browseArchivedCards: "瀏覽已歸檔的卡片",
  cardIsArchived: "卡片已歸檔",
  yourSessionHasTimedOut: "您的會話已超時。",
  reloadPage: "重新加載頁面",
  moreActions: "更多操作",
  copyTitles: "複製標題",
  copyTitlesAsLinks: "將標題複製為鏈接",
  changingTags: "更改標籤",
  subscribingToResourceUpdates: "訂閱資源更新",
  unsubscribingFromResourceUpdates: "取消訂閱資源更新",
  removingFromFavourites: "從收藏中移除",
  addingToFavourites: "添加到收藏",
  changingAssignees: "更改被指派者",
  changingDates: "更改日期",
  changingStatus: "更改狀態",
  processed: "已處理",
  clearSelection: "清除選擇",
  createPAT: "建立權杖",
  createPATLong: "建立個人存取權杖",
  patName: "權杖名稱",
  patNamePlaceholder: "簡短描述名稱...",
  expiration: "到期",
  patExpirationTimeSubtitle: "權杖將在選定的天數後自動過期，並且不能再使用。",
  expirationTimeSelect: "此權杖將在以下時間過期：",
  selectExpirationTime: "選擇到期時間",
  patNoExpirationWarningTitle: "永不讓此權杖過期？",
  patNoExpirationWarningDescription:
    "選擇不過期可能會讓您的權杖在被洩露時無限期地處於危險中。過期的權杖有助於降低長期安全風險。",
  day: "天",
  patDropdownOptionOne: "7 天",
  patDropdownOptionTwo: "30 天",
  patDropdownOptionThree: "60 天",
  patDropdownOptionFour: "90 天",
  noExpiration: "無到期",
  invalidPATExpirationDate: "到期日期需要在未來",
  personalAccessTokens: "個人存取權杖",
  personalAccessTokensSubtitle: "生成個人存取權杖以與 Superthread API 互動",
  searchPATs: "搜尋權杖",
  noPATs: "無個人存取權杖",
  noPATsSubtitle: "您可以在上方建立個人存取權杖",
  noPATsSubtitleAdmin: "您可以從“API 存取”畫面建立個人存取權杖",
  revokePatConfirmation: "您確定要撤銷“%{patName}”權杖嗎？",
  lastUsed: "上次使用",
  revokePatDescription:
    "任何使用此權杖的應用程式或腳本將無法再存取 Superthread API。此操作無法撤銷。",
  never: "從未",
  patLimitReachedTooltip: "已達到 %{limit} 個 PAT 的限制",
  newPatCreated: "複製您的個人存取權杖",
  newPatCreatedDescriptionOne: "請務必立即複製您的權杖。",
  newPatCreatedDescriptionTwo: "您將無法再次看到它！",
  tokenCopiedToClipboard: "權杖已複製到剪貼簿",
  proceed: "繼續",
  copyToken: "複製權杖",
  timeExpires: "時間到期",
  patRevokedSuccessfully: "PAT 撤銷成功",
  failedToRevokePat: "撤銷 PAT 失敗",
  stop: "停止",
  online: "在線",
  disconnected: "已斷線",
  apiAccess: "API 存取",
  apiAccessSubtitle:
    "Superthread 的 API 讓你建立自訂整合。你需要以下資訊才能發送請求",
  workspaceIdDescription: '在 API 中稱為 "team_id"',
  userIdDescription: '在 API 中稱為 "user_id"',
  viewDocs: "查看 API 文件",
  user: "使用者",
  createPatSubtitle: "使用個人存取權杖存取 API 時，所有操作都歸因於您個人",
  expirationReminderText: "我們會在您的權杖到期前一天發送提醒電子郵件給您。",
  securityAndAccess: "安全性與存取",
  securityAndAccessSubtitle:
    "工作區的成員可以建立個人存取權杖以與 Superthread API 互動。管理員可以在此處檢視和撤銷它們。",
  youOnlyHavePermissionToViewContent: "您只有權限查看內容",
  namedSpace: "%{space} 空間",
  contactEmailToRequestEditAccess: "聯絡 %{email} 以請求編輯存取權。",
  viewOnly: "僅限檢視",
  viewOnlySubtitle: "不是空間成員的人和沒有編輯權限的成員只能檢視",
  canEdit: "可以編輯",
  canView: "可以檢視",
  thisSpaceIsViewOnly: "此空間僅限檢視",
  upgradeViewOnlySpacesDescription: "您可以在付費方案中創建僅限檢視的空間。",
  changeToViewOnlySpaceTitle: "更改為僅限檢視空間？",
  changeToViewOnlySpace:
    "此空間的所有現有成員在更改為僅限檢視後仍將是成員。除非被邀請，否則無法加入新成員。",
  changeToViewOnly: "更改為僅限檢視",
  completeSprint: "完成衝刺",
  completeSprintWarning:
    "所有未完成的卡片將被轉移到下一個衝刺。如果沒有即將到來的衝刺，將自動創建一個。",
  hideEmptyColumns: "隱藏空列",
  hideEmptyRows: "隱藏空行",
  rememberAssignees: "記住受讓人",
  rememberAssigneesTooltip: "創建卡片時始終使用這些受讓人",
  recentlyUsedBoards: "最近使用的看板",
  recent: "最近",
  copyAsMarkdown: "將內容複製為Markdown",
  copiedAsMarkdown: "已複製為Markdown",
  checklists: "清單",
  duplicateCards: "重複卡片",
  blockedByCards: "被卡片阻擋",
  blockingCards: "阻擋卡片",
  allChangesSavedToSuperthread: "所有更改已保存到Superthread",
  synced: "已同步",
  syncing: "正在同步",
  aFewSecondsAgo: "幾秒鐘前",
  lastSynced: "上次同步",
  transcriptionIndicatorTitle: "顯示現場會議指示器",
  transcriptionIndicatorDescription:
    "會議指示器浮動在屏幕上方，顯示轉錄何時啟用",
  seeDetailedFeaturesComparison: "查看詳細功能比較",
  parentPage: "父頁面",
  subPages: "子頁面",
  chatWithHuman: "與真人聊天",
  chatWithHumanDescription: "與Superthread團隊進行現場聊天",
  helpCentre: "幫助中心",
  helpAndAiSupport: "幫助文章和AI支持",
  upgradeGoSquaredDescription: "升級您的方案以獲得應用內聊天支持",
  searchActions: "搜索操作",
  teamSpaces: "團隊空間",
  highToLow: "從高到低",
  lowToHigh: "從低到高",
  largestFirst: "最大優先",
  smallestFirst: "最小優先",
  descending: "降序",
  ascending: "升序",
  orderBy: "排序方式",
  workspaceURL: "工作區 URL",
  newWorkspaceURL: "新的工作區 URL",
  changeWorkspaceURL: "更改工作區 URL",
  changeWorkspaceURLWarning:
    "更改工作區 URL 將會導致在 Superthread 外部（例如郵件、Slack 或外部網站）分享的卡片、頁面和看板的連結失效。",
  enterWorkspaceURL: "輸入工作區 URL",
  workspaceNameDescription:
    "此內容會顯示在側邊欄頂部、選單和電子郵件中。大多數人會將其設為公司或組織的名稱。",
  workspaceURLDescription:
    "工作區 URL 只能包含小寫字母、數字和連字號。更改它會導致您在 Superthread 外部分享的所有現有連結失效，因此最好不要經常更改。",
  workspaceDescriptionDescription:
    "對您的公司/組織所做工作的簡單說明。這有助於在使用 Superthread AI 功能（例如會議筆記摘要）時提供上下文。",
  teamReports: "團隊報告",
  teamReportsSubtitle: "Superthread 可以根據您的團隊工作生成自定義報告",
  searchReports: "搜尋報告",
  createReport: "建立報告",
  editReport: "編輯報告",
  deleteReport: "刪除報告",
  deleteReportDescription: "報告 “%{reportName}” 將被刪除",
  noReports: "沒有報告",
  noReportsSubtitle: "您可以在上方創建報告",
  reportName: "報告名稱",
  reportNamePlaceholder: "例如：「工程站會」",
  enabled: "已啟用",
  includedMembers: "包含的成員",
  customInstructions: "自定義指令",
  customInstructionsSubtitle: "這些指令幫助我們生成您的最終報告",
  generateReport: "生成報告",
  generateReportAt: "生成報告在",
  teamReport: "團隊報告",
  customAiGeneratedReports: "自定義 AI 生成的報告",
  recentInstructions: "最近指令",
  instructionsForAi: "指令用于 AI",
  accountRole: "帳戶角色",
  doNotGroup: "不分組",
  membersRemoved: "已移除 %{count} 個成員",
  youAreAboutToAddMemberToPrivateSpace:
    '您即將新增成員到私人空間。他們將能夠查看此空間內的所有內容。若您按下 "確認"，該成員將被加入此空間，並會向空間擁有者發送電子郵件。',
  addMemberToPrivateSpace: "新增成員到私人空間？",
  versions: "版本",
  restoreThisVersionConfirmTitle: "恢復此版本？",
  restoreThisVersionConfirmDescription:
    "您目前的頁面將被來自 %{date} 的此版本取代。",
  versionSuccessfullyRestored: "版本恢復成功",
  versionRestoredBy: "版本由 %{userName} 恢復",
  contentReplacedBy: "內容由 %{userName} 替換",
  failedToRestoreVersion: "恢復版本失敗",
  currentVersion: "當前版本",
  versionLockedDescription: "請升級您的計劃以查看超過 %{days} 天的版本",
  cardCoverImageSettingsTitle: "卡片背景圖片",
  cardCoverToggleTitle: "在卡片上顯示背景圖片",
  cardCoverToggleDescription:
    "這將為您提供在卡片上顯示背景圖片的選項。啟用此功能後，預設情況下，附件中的第一張圖片將自動設為卡片的背景圖片。",
  removeCoverImage: "移除背景圖片",
  setAsCoverImage: "設為背景圖片",
  meetingStart: "會議開始",
  meetingEnd: "會議結束",
  meetingLinks: "會議連結",
  meetingOrganiser: "會議主辦人",
  coverImageRemoved: "背景圖片已移除",
  coverImageSet: "背景圖片已設定",
  coverImageSetFailed: "設定背景圖片失敗",
  anyoneWithThisLinkCanViewBoard: "任何擁有此連結的人都可以查看看板",
  createAViewOnlyVersionOfBoard: "在可分享的連結上建立看板的僅查看版本",
  boardIsSharedPublicly: "此看板已在網路公開分享。",
  learnMoreAboutPublicBoards: "深入瞭解 Superthread 公開看板",
  trySuperthread: "試用 Superthread",
  showBoardInfo: "顯示看板資訊",
  weCouldntFindThatBoard: "我們找不到該看板",
  itMayHaveBeenUnpublished: "它可能已被取消發佈，或 URL 錯誤。",
  allInOneProjectManagement: "一體化專案管理。",
  tryItNow: "立即試用",
  thisPublicBoardIsViewOnly: "此公共板僅供查看。",
  customiseSidebar: "自訂側邊欄",
  customiseSidebarFavouritesDescriptionOne: "您標記的卡片、頁面、看板或檢視",
  customiseSidebarFavouritesDescriptionTwo: "將顯示在此處。",
  customiseSidebarYourSpacesDescription:
    "您所屬的空間將顯示在此處。加入或離開空間以編輯此部分。",
  sidebarUpdated: "側邊欄已更新",
  myProfile: "我的個人資料",
  sectionHiddenFromSidebar: "從側邊欄隱藏的部分",
  pin: "釘選",
  sectionPinnedToSidebar: "釘選到側邊欄的部分",
  worksapceSettings: "工作區設定",
  hideFromSidebar: "從側邊欄隱藏",
  createACopyOfThisBoard: "建立此看板的副本。活動和評論將不會被複製。",
  chooseWhereToDuplicateBoard: "選擇複製看板的位置",
  copyAllCardsIntoNewBoard: "將所有卡片複製到新看板",
  editCover: "編輯封面圖片",
  toggleCoverImageFit: "更改縮放",
  imFeelingLucky: "手氣不錯",
  viewWord: "檢視",
  saveAsTemplate: "另存為範本",
  // Keyboard shortcuts cheatsheet
  ["keyboardShortcuts.title"]: "鍵盤快速鍵",
  ["keyboardShortcuts.description"]: "更快地使用快速鍵組合工作",
  ["keyboardShortcuts.or"]: "或",
  ["keyboardShortcuts.then"]: "然後",
  ["keyboardShortcuts.proTip"]: "專業提示：",
  ["keyboardShortcuts.searchPlaceholder"]: "搜尋快速鍵...",
  ["keyboardShortcuts.noResults"]: "找不到快速鍵",
  // Sections
  ["keyboardShortcuts.sectionGeneral"]: "一般",
  ["keyboardShortcuts.sectionBoardsLists"]: "看板 / 列表",
  ["keyboardShortcuts.sectionCards"]: "卡片",
  ["keyboardShortcuts.sectionDropdownsMenus"]: "下拉選單與選單",
  ["keyboardShortcuts.sectionNotificationsInbox"]: "通知收件匣",
  ["keyboardShortcuts.sectionTextEditor"]: "文字編輯器",
  ["keyboardShortcuts.sectionMarkdownFormatting"]: "Markdown 格式",
  // General
  ["keyboardShortcuts.searchForAnything"]: "搜尋任何內容",
  ["keyboardShortcuts.saveOrSubmit"]: "儲存或提交",
  ["keyboardShortcuts.closeOrGoBack"]: "關閉或返回",
  ["keyboardShortcuts.createNewCard"]: "建立新卡片",
  ["keyboardShortcuts.createNewPage"]: "建立新頁面",
  ["keyboardShortcuts.createNewNote"]: "建立新筆記",
  ["keyboardShortcuts.showHideSidebar"]: "顯示／隱藏側邊欄",
  ["keyboardShortcuts.viewAllKeyboardShortcuts"]: "檢視所有鍵盤快速鍵",
  // Boards / lists
  ["keyboardShortcuts.selectCardAbove"]: "選取上方卡片",
  ["keyboardShortcuts.selectCardBelow"]: "選取下方卡片",
  ["keyboardShortcuts.selectLeftCard"]: "選取左側卡片",
  ["keyboardShortcuts.selectRightCard"]: "選取右側卡片",
  ["keyboardShortcuts.openSelectedCard"]: "打開所選卡片",
  ["keyboardShortcuts.closeTheCard"]: "關閉卡片",
  ["keyboardShortcuts.moveCardUp"]: "上移卡片",
  ["keyboardShortcuts.moveCardDown"]: "下移卡片",
  ["keyboardShortcuts.moveCardLeft"]: "左移卡片",
  ["keyboardShortcuts.moveCardRight"]: "右移卡片",
  ["keyboardShortcuts.addCardToMultiSelect"]: "將卡片加入多重選取",
  ["keyboardShortcuts.selectRangeOfCards"]: "選取卡片範圍",
  ["keyboardShortcuts.selectAllCards"]: "選取所有卡片",
  ["keyboardShortcuts.clearMultiSelect"]: "清除多重選取",
  ["keyboardShortcuts.addCardInlineAndOpen"]: "直接新增卡片並開啟",
  ["keyboardShortcuts.addBoardFilter"]: "新增看板篩選器",
  // Cards
  ["keyboardShortcuts.renameTitle"]: "重新命名標題",
  ["keyboardShortcuts.assignUnassignYourself"]: "分配/取消分配自己",
  ["keyboardShortcuts.statusList"]: "狀態／列表",
  ["keyboardShortcuts.assignees"]: "負責人",
  ["keyboardShortcuts.tags"]: "標籤",
  ["keyboardShortcuts.setDueDate"]: "設定截止日期",
  ["keyboardShortcuts.submitComment"]: "提交評論",
  ["keyboardShortcuts.copyGitBranchName"]: "複製所選卡片的 git 分支名稱",
  ["keyboardShortcuts.copyCardAsMarkdown"]: "將卡片內容複製為 Markdown",
  // Dropdowns and menus
  ["keyboardShortcuts.moveFocusDown"]: "焦點下移",
  ["keyboardShortcuts.moveFocusUp"]: "焦點上移",
  ["keyboardShortcuts.selectAndClose"]: "選取並關閉",
  ["keyboardShortcuts.addFocusedItemToSelection"]: "將焦點項目加入選取",
  ["keyboardShortcuts.closeTheMenu"]: "關閉選單",
  // Notifications inbox
  ["keyboardShortcuts.selectNextNotification"]: "選取下一則通知",
  ["keyboardShortcuts.selectPreviousNotification"]: "選取上一則通知",
  ["keyboardShortcuts.resolveNotification"]: "標記通知為已處理",
  // Text editor
  ["keyboardShortcuts.textEditorNote"]: "在卡片描述、評論或頁面中，您可以：",
  ["keyboardShortcuts.mentionAnybodyOrAnything"]: "提及任何人或任何內容",
  ["keyboardShortcuts.openSlashMenu"]: "開啟斜線選單以取得格式選項",
  ["keyboardShortcuts.addEmoji"]: "加入表情符號（短代碼）",
  ["keyboardShortcuts.boldSelectedText"]: "將選取文字加粗",
  ["keyboardShortcuts.italiciseSelectedText"]: "將選取文字斜體",
  ["keyboardShortcuts.strikethroughSelectedText"]: "將選取文字加刪除線",
  ["keyboardShortcuts.proTipUrlPaste"]:
    "如果您的剪貼簿有網址，可以將其貼到高亮文字上，將該文字轉為連結。",
  // Markdown formatting
  ["keyboardShortcuts.markdownItalic"]: "斜體",
  ["keyboardShortcuts.markdownBold"]: "粗體",
  ["keyboardShortcuts.markdownHeading1"]: "標題 1",
  ["keyboardShortcuts.markdownHeading2"]: "標題 2",
  ["keyboardShortcuts.markdownHeading3"]: "標題 3",
  ["keyboardShortcuts.markdownBulletList"]: "項目符號清單",
  ["keyboardShortcuts.markdownNumberedList"]: "編號清單",
  ["keyboardShortcuts.markdownChecklist"]: "核取清單",
  ["keyboardShortcuts.markdownStrikethrough"]: "刪除線",
  ["keyboardShortcuts.markdownHorizontalDivider"]: "水平分隔線",
  ["keyboardShortcuts.markdownInlineCode"]: "行內程式碼",
  ["keyboardShortcuts.markdownCodeBlock"]: "程式碼區塊",
  publicBoardIsViewOnly: "此公開看板僅供檢視。",
  duplicateToMyWorkspace: "複製到我的工作區",
  levelUp: "升級",
  core_knowledge: "核心知識",
  organise_work: "組織工作",
  shape_your_workspace: "塑造你的工作區",
  capture_knowledge: "擷取知識",
  advanced_features: "進階功能",
  helper: "助手",
  organiser: "組織者",
  shaper: "塑造者",
  master: "大師",
  youHaveUnlocked: "你已解鎖",
  rank: "等級",
  trelloDescription:
    "登入您的 Trello 帳戶以選擇要匯入的看板。Superthread 只會匯入您選擇的看板中的資料。",
  importQueued: "匯入已排隊",
  viewLink: "查看連結",
  removeLink: "刪除連結",
  linkAdded: "連結已新增",
  errorAddingLink: "新增連結時發生錯誤",
  // PWYW Psychological Messages
  ["billing.pwyw.losingMoney"]: "感謝咖啡",
  ["billing.pwyw.barelyCovering"]: "感謝啤酒",
  ["billing.pwyw.breakeven"]: "收支平衡 — 不賺不賠",
  ["billing.pwyw.belowFair"]: "略低於公平價格",
  ["billing.pwyw.fairPrice"]: "公平價格,謝謝!",
  ["billing.pwyw.awesome"]: "您真棒!",
  ["billing.pwyw.bestHuman"]: "您簡直是最棒的人!",
  ["billing.pwyw.topTier"]: "這到底是什麼意思?",
  // PWYW UI Labels
  ["billing.pwyw.title"]: "隨心支付",
  // Enterprise Tier Updates
  ["billing.enterpriseSubtitle"]: "適用於有嚴格要求的企業",
  ["billing.seatCount"]: "%{count} 個席位",
  ["billing.annualBilling"]: "年度計費",
  ["billing.versionHistory"]: "%{count} 天版本歷史",
  ["billing.expertOnboarding"]: "專家入門指導",
  ["billing.nextPaymentOn"]: "下次付款日期：{date}",
  ["billing.paymentsWillStopOn"]: "付款將於 %{date} 停止",
  ["billing.youAreOnPlan"]: "您正在使用「%{planName}」方案",
  ["billing.cancelPlan"]: "Cancel subscription",
  ["billing.confirmPriceChangeTitle"]: "Confirm price change",
  ["billing.confirmPriceChangeDescription"]:
    "Your subscription will be changed to %{price} on your next invoice.",
  ["billing.priceChangeSuccess"]: "價格變更成功！",
  ["billing.priceChangeFail"]:
    "價格變更失敗。如果問題仍然存在，請聯絡支援團隊。",
  ["billing.choosePlanSectionTitle"]: "Choose a plan",
  ["billing.choosePlanSectionDescription"]:
    "Upgrading your plan removes your workspace limits",
  ["billing.youSetThePrice"]: "You set the price",
  ["billing.upgradeToRemoveUsageLimits"]: "Upgrade to remove usage limits",
  ["billing.fairPrice"]: "Fair %{period} pricing",
  ["billing.startsAt"]: "Starts at",
  ["billing.perYear"]: "/ year",
  ["billing.perMonth"]: "/ month",
  createMissingTags: "建立缺少的標籤",
  createMissingTagsDescription: "如果 %{space} 空間中不存在，請建立標籤",
  createACopyOfThisCard: "建立此卡片的副本。活動和評論不會被複製。",
  chooseWhereToDuplicateCard: "選擇要複製卡片的位置",
  cardWillBeAddedToBottomOfList: "卡片將被新增至清單底部",
  learnFavourites: "學習我的最愛",
  learnFavouritesDescription: "建立您的個人基地",
  learnFavouritesMission: "透過將最重要的工作固定到側邊欄，讓它成為您自己的。",
  commandMastery: "命令精通",
  commandMasteryDescription: "您隱藏的工具箱",
  commandMasteryMission: "我們的動態系統靈活，可幫助您擴展。",
  notesCourse: "AI 會議、轉錄和筆記範本",
  notesCourseDescription: "您的智慧會議助手",
  notesCourseMission:
    "AI 轉錄為您的團隊提供清晰度 - 捕獲所說的一切，組織見解，並神奇地將討論轉化為行動 ✨",
  cardMastery: "卡片精通",
  cardMasteryDescription: "您可以感受到的速度",
  cardMasteryMission:
    "Superthread 專為速度而打造。一旦您熟悉了，您將飛快地完成工作。",
  learnSidedockView: "學習側停靠視圖",
  learnSidedockViewDescription: "您的深度專注夥伴",
  learnSidedockViewMission:
    "Superthread 中的所有內容都是為簡單性和靈活性而設計的，包括視圖。",
  spacesMastery: "空間精通 - 平靜的指揮中心",
  spacesMasteryDescription: "以您的方式創建組織的空間",
  spacesMasteryMission:
    "空間適應您的工作流程 - 按部門、客戶、項目。像您想要的那樣靈活工作。",
  curator: "策展人",
  artisan: "工匠",
  scribe: "抄寫員",
  speedster: "速度達人",
  navigator: "導航員",
  architect: "建築師",
  favourite_board: "收藏看板",
  favourite_card: "收藏卡片",
  favourite_page: "收藏頁面",
  reorder_favourites: "重新排序我的最愛",
  add_table_to_card: "/Table 在卡片描述中",
  add_callout_to_card: "/Callout 在卡片描述中",
  embed_youtube_to_page: "/YouTube 在頁面中",
  embed_board_to_page: "/Board 在頁面中嵌入看板",
  transcribe_meeting: "轉錄會議",
  view_transcript_action: "查看轉錄",
  pause_meeting_for_summary: "暫停結束並獲取自動摘要",
  change_notes_template: "更改筆記範本（投資者會面、腦力激盪、1對1 等）",
  convert_notes_to_cards: "將筆記轉換為卡片",
  use_arrow_keys_action: "使用箭頭鍵",
  use_option_arrows: "使用 Option + 箭頭",
  use_bulk_actions: "使用批量操作",
  use_magic_cover_image: "使用魔術封面圖片",
  set_parent_card_action: "設定父卡片",
  open_side_dock_view_action: "打開側停靠視圖",
  view_card_in_sidebar: "在側邊欄中查看其他卡片",
  view_page_in_sidebar: "在側邊欄中查看其他頁面",
  create_client_space: "創建一個名為「新客戶」的空間",
  create_department_space: "創建一個名為「新部門」的空間",
  create_board_in_client_space:
    "在您的新客戶空間內創建一個名為「新客戶看板」的看板",
  create_board_in_department_space:
    "在您的新部門空間內創建一個名為「新部門看板」的看板",
  create_card_in_board: "在您的新客戶看板內創建一張名為「新卡片」的卡片",
  move_card_between_spaces: "將您的新卡片從新客戶拖到新部門",
  onboardingNewClientSpace: "新客戶",
  onboardingNewDepartmentSpace: "新部門",
  onboardingNewClientBoard: "新客戶看板",
  onboardingNewDepartmentBoard: "新部門看板",
  onboardingNewCard: "新卡片",
  moveBoard: "移動看板",
  moveBoardDescription:
    "此看板中使用的某些標籤在 %{space} 空間中不存在，將從卡片中刪除。",
  missingTags: "缺少的標籤",
  createMissingTagsInSpaceDescription:
    "如果 %{space} 空間中不存在標籤，則建立標籤",
  cardLimitReached: "已達到卡片限制",
  cardLimitReachedDescription:
    "您的工作區使用的是免費方案。刪除一些舊卡片或升級以移除限制。",
  forms: "表單",
  createForm: "建立表單",
  editForm: "編輯表單",
  saveForm: "儲存表單",
  formCreated: "表單已建立",
  formUpdated: "表單已更新",
  formSubmitted: "表單已提交",
  failedToSubmitForm: "提交表單失敗",
  submitForm: "提交表單",
  noFormsForThisBoard: "此看板沒有表單",
  formsSettingsDescription: "為此看板建立和管理表單",
  formNameAndIcon: "表單名稱和圖示",
  formNameCannotBeEmpty: "表單名稱不能為空",
  thisIsHowPeopleWillSeeForm: "這是人們看到您表單的方式",
  formDescription: "表單描述",
  descriptionWillBeShownOnPublicForm: "描述將顯示在公開表單上",
  enterFormDescription: "輸入表單描述",
  formFields: "表單欄位",
  addFieldsForUsersToFillOut: "新增供使用者填寫的欄位",
  fieldType: "欄位類型",
  selectTypeOfField: "選擇欄位類型",
  fieldLabel: "欄位標籤",
  fieldLabelCannotBeEmpty: "欄位標籤不能為空",
  enterFieldLabel: "輸入欄位標籤",
  addField: "新增欄位",
  editField: "編輯欄位",
  placeholder: "佔位符",
  optionalPlaceholderText: "可選佔位符文字",
  enterPlaceholder: "輸入佔位符",
  required: "必填",
  makeThisFieldRequired: "將此欄位設為必填",
  option: "選項",
  addOption: "新增選項",
  addOptionsForThisField: "為此欄位新增選項",
  atLeastTwoOptionsRequired: "至少需要兩個選項",
  enterText: "輸入文字",
  enterNumber: "輸入數字",
  enterEmail: "輸入電子郵件",
  enterPhoneNumber: "輸入電話號碼",
  enterUrl: "輸入網址",
  selectDate: "選擇日期",
  selectOption: "選擇選項",
  dragAndDropOrClick: "拖放或點擊上傳",
  yes: "是",
  no: "否",
  titleAZ: "標題 A-Z",
  titleZA: "標題 Z-A",
  shortText: "短文字",
  longText: "長文字",
  number: "數字",
  dropdown: "下拉選單",
  checkbox: "核取方塊",
  phone: "電話",
  link: "連結",
  maximumCharactersAllowed: "允許的最大字元數",
  pleaseEnterValidNumber: "請輸入有效數字",
  pleaseSelectDate: "請選擇日期",
  pleaseSelectOption: "請選擇選項",
  pleaseUploadFile: "請上傳檔案",
  pleaseSelectAtLeastOneOption: "請至少選擇一個選項",
  pleaseProvideValidEmail: "請提供有效的電子郵件",
  pleaseEnterValidPhoneNumber: "請輸入有效的電話號碼",
  pleaseEnterValidUrl: "請輸入有效的網址",
  thisFieldIsRequired: "此欄位為必填",
  congratulations: "恭喜",
  nextLevel: "下一關",
  fieldDescription: "欄位描述",
  enterFieldDescription: "輸入欄位描述",
  selectCardProperty: "選擇卡片屬性",
  chooseWhichPropertyToMapTo: "選擇要映射的屬性",
  pleaseSelectACardProperty: "請選擇一個卡片屬性",
  cardProperty: "卡片屬性",
  selectPriority: "選擇優先級",
  selectAssignees: "選擇負責人",
  selectDueDate: "選擇截止日期",
  noTagsAvailable: "沒有可用的標籤",
  allowMultipleSelections: "允許多選",
  allowUsersToSelectMultipleOptions: "允許用戶選擇多個選項",
  selectOptions: "選擇選項",
  itemsSelected: "已選擇 %{count} 項",
  cardPropertyAlreadyAddedToForm: "該卡片屬性已新增到表單中",
  formNotFound: "找不到表單",
  formNotFoundDescription: "此表單可能已被刪除或不再可用。",
  thankYou: "謝謝！",
  responseSubmitted: "您的回覆已提交。",
  submitAnother: "提交另一個",
  submitting: "正在提交",
  publicFormSubmission: "公開表單提交",
  projectHealth: "專案健康狀況",
  projectHealthUpdates: "專案健康狀況更新",
  allUpdates: "所有更新",
  onTrack: "進展順利",
  atRisk: "存在風險",
  offTrack: "進度落後",
  notExpected: "無需更新",
  stale: "過期",
  healthStatusNeedsUpdating: "需要更新",
  markedProjectAsStaleDueToLackOfUpdate:
    "因未按時提供健康狀況更新而將專案標記為過期",
  downgradedHealthStatusAutomaticallyFrom: "自動降級健康狀況從",
  revertedHealthStatusFrom: "恢復健康狀況從",
  healthStatusMarkedStaleAutomaticallyPleaseUpdate:
    "健康狀況已自動標記為過期，請發佈更新！",
  healthStatusDowngradedAutomaticallyDueToInactivity: "健康狀況已自動降級為",
  healthUpdateOnly: "僅健康狀況更新",
  keepYourTeamInformed: "讓團隊隨時了解情況",
  shareProjectHealthUpdatesWithYourTeam: "與團隊分享專案健康狀況更新",
  newProjectUpdate: "新專案更新",
  projectHealthUpdate: "專案健康狀況更新",
  latestUpdate: "最新更新",
  viewOlderUpdates: "查看舊更新",
  hideOlderUpdates: "隱藏舊更新",
  previousUpdates: "先前的更新",
  writeYourUpdate: "撰寫簡短更新以告知大家此專案的狀態...",
  postUpdate: "發佈更新",
  healthPeriodConfiguration: "更新頻率",
  healthPeriodDescription:
    "設定此專案應多久更新一次。錯過更新將把健康狀況標記為過期。設定為 0 以停用。",
  noHealthUpdates: "無健康狀況更新",
  noHealthUpdatesDescription:
    "沒有要顯示的更新。活躍專案的最新健康狀況更新將顯示在此處。嘗試調整篩選器以查看更多內容。",
  healthPeriodUpdatedSuccessfully: "過期期限已成功更新",
  healthPeriodUpdateFailed: "更新過期期限失敗",
  deleteLatestHealthUpdateWarning:
    "您即將刪除此專案的最新健康狀況更新。如果繼續，健康狀況將恢復到之前的更新。",
  healthStatusWasChangedTo: "項目的健康狀況已更改為",
  healthStatusRemainedAt: "項目的健康狀況保持在",
  healthStatusWasRevertedTo: "項目的健康狀況已恢復為",
  regenerateUrlForForm: "重新產生 %{formName} 的公開連結",
  regenerateUrlForFormDescription:
    "這將使目前的公開連結失效。使用現有連結的任何人將無法再存取此表單。",
  formUrlRegenerated: "表單連結已重新產生",
  claimLastRank: "Claim last rank",
};

export default zhHant as Translations;
