import { Translations } from "../types";

const bs: Translations = {
  search: "Pretraga...",
  close: "Zatvori",
  send: "Pošalji",
  resendInviteLink: "Pošalji link ponovo",
  addComment: "Dodaj komentar",
  comment: "Komentariši",
  writeComment: "Napiši komentar...",
  comments: "KOMENTARI",
  createBoard: "Kreiraj ploču",
  createPage: "Kreiraj stranicu",
  delete: "Izbriši",
  edit: "Uredi",
  remove: "Izbriši",
  done: "Gotovo",
  enterBoardTitle: "Unesite naziv ploče",
  create: "Kreiraj",
  untitled: "Nenaslovljeno",
  containsNoContent: "Bez sadržaja.",
  ama: "AMA",
  me: "Ja",
  assigned: "Dodijeljeno",
  mentions: "Pominjanja",
  visited: "posjećeno",
  saved: "sačuvano",
  notifications: "Obavijesti",
  selectWhereWwhenWillNotified: "Odaberite gdje i kada ćete biti obaviješteni",
  recivePersonalNotification: "Primajte lična obavještenja u Slacku",
  notifyMe: "Obavijesti me kada",
  save: "Sačuvaj",
  saveChanges: "Sačuvaj izmjene",
  archived: "Arhivirano",
  archive: "Arhiviraj",
  cardArchived: "Ova kartica je arhivirana.",
  cellMerge: "Spajanje ćelija",
  new: "Novo",
  view: "Pogled",
  signOut: "Odjava",
  leave: "Napusti",
  browseAllSpaces: "Pretražuj sve prostore",
  preview: "Pregledaj",
  goToCard: "Idi do kartice",
  zoomIn: "Uvećaj",
  zoomOut: "Umanji",
  notFoundPageHeader: "Naišli smo na problem...",
  notFoundPageContent:
    "Nismo sigurni šta nije uredu. Možete se vratiti nazad na prethodnu stranicu ili kontaktirati službu za podršku.",
  addCard: "Dodaj karticu",
  next: "Slijedeći",
  addToCard: "Dodaj u karticu",
  checklist: "Čeklista",
  moveList: "Pomjeri listu",
  board: "Ploča",
  timeline: "Timeline",
  templates: "Predlošci",
  cardTemplates: "Predlošci kartica",
  pageTemplates: "Predlošci stranica",
  saveCardContentYouRepeatedlyUse:
    "Sačuvajte sadržaj koji često koristite i primijenite ga kada kreirate kartice",
  savePageContentYouRepeatedlyUse:
    "Sačuvajte sadržaj koji često koristite i primijenite ga kada kreirate stranice",
  createCardTemplate: "Kreirajte predložak kartice",
  editCardTemplate: "Uredite predložak kartice",
  searchTemplates: "Pretražite predloške",
  name: "Naziv",
  noCardTemplates: "Nema predložaka kartica",
  noPageTemplates: "Nema predložaka stranica",
  calendar: "Kalendar",
  showAllCards: "Prikaži sve kartice",
  hideAllCards: "Sakrij sve kartice",
  showWeekends: "Prikaži vikende",
  youCanCreateATemplateAbove: "Možete kreirati predložak iznad",
  youCanCreateABoardFrom: "Možete kreirati ploču sa sidebara aplikacije",
  createPageTemplate: "Kreirajte predložak stranice ",
  editPageTemplate: "Uredite predložak stranice",
  templateNameAndIcon: "Naziv predloška i ikona",
  thisIsHowPeopleFindTemplate: "Ovako će ljudi kasnije pronaći vaš predložak",
  shortAndDescriptive: "Kratko i opisno",
  templateNameCannotBeEmpty: "Naziv predloška ne može biti prazan",
  templateSpace: "Predložak prostora",
  whichSpacesWillThisTemplateBeAvailableIn:
    "U kojim će prostorima ovaj predložak biti dostupan?",
  templateSpaceShouldHaveAtLeastOneSpaceSelected:
    "Predložak prostora mora imati barem jedan odabrani prostor",
  noSpacesFound: "Nema pronađenih prostora.",
  allSpaces: "Svi prostori",
  peopleWillBeAbleToEditThisAfterTheyApplyTheTemplate:
    "Ljudi će moći uređivati ovo nakon što primijene predložak",
  theseWillBeAddedToTheCardYouApplyTheTemplateTo:
    "Ovo će biti dodano kartici na koju primijenite predložak",
  taskDescription: "Opis kartice",
  pageBody: "Tijelo stranice",
  saveTemplate: "Spremi predložak",
  templateNotFound: "Predložak nije pronađen",
  addAssignees: "Dodaj dodjeljivače",
  setTags: "Postavi oznake",
  selectAll: "Odaberi sve",
  createInThisBoard: "Kreiraj u ovoj ploči",
  setThisStatus: "Postavi ovaj status",
  chooseABoard: "Odaberite ploču",
  chooseABoardToUseThisField: "Odaberite ploču da biste koristili ovo polje",
  ifYouLeaveThisPageAnyChangesWillBeLost:
    "Ako napustite ovu stranicu, sve promjene koje ste napravili na ovom predlošku bit će izgubljene.",
  areYouSureYouWantToDeleteTheTemplate:
    "Da li ste sigurni da želite izbrisati %{templateName} predložak?",
  applyTemplate: "Primijeni predložak",
  noTemplates: "Nema predložaka.",
  manageTemplates: "Upravljajte predlošcima",
  uploadFilesForTemplatesIsDisabled:
    "Prijenos datoteka za predloške onemogućen",
  uploadFilesIsDisabled: "Prijenos datoteka onemogućen",
  noTagsFoundSelectBoardToSeeTags:
    "Nema pronađenih oznaka. Odaberite ploču da biste vidjeli dostupne oznake u tom prostoru ili",
  createNewWorkspaceTagInSettings:
    "kreirajte novu oznaku radnog prostora u postavkama.",
  noTitle: "Nema naslova",
  addChecklist: "Dodaj čeklistu",
  title: "Naslov",
  add: "Dodaj",
  addItem: "Dodaj novu stavku",
  archiveList: "Arhiviraj listu",
  actions: "Akcije",
  reply: "Odgovori",
  replies: "Odgovora",
  description: "Opis",
  cardDescriptionPlaceholder: "Napišite detaljni opis...",
  templateDescriptionPlaceholder: "Unesite opis...",
  card: "Kartica",
  space: "Prostor",
  spaces: "Prostori",
  page: "Stranica",
  workspaceLabel: "Unesite ime radnog prostora",
  workspacePlaceholder: "Ime radnog prostora",
  download: "Preuzmi",
  move: "Premjesti",
  background: "Pozadina",
  share: "Podijeli",
  createNewPage: "Kreiraj novu stranicu",
  createNewBoard: "Kreiraj novu ploču",
  newBoard: "Nova ploča",
  addNewBoard: "Dodaj novu ploču",
  oneColumn: "1 kolona",
  twoColumns: "2 kolone",
  previewStillUpdating: "Pregled se još uvijek ažurira...",
  emptyPage: "Prazna stranica",
  searchSuperthread: "Pretraži Superthread",
  cancel: "Otkaži",
  cancelAndDiscard: "Otkaži i odbaci",
  makeItPrivate: "Učini privatnim",
  privateSpaceDescription:
    "Kada je prostor postavljen kao privatni moguće mu se pridružiti samo putem poziva.",
  boards: "Ploče",
  linkTextLabel: "Naziv",
  linkUrlLabel: "Adresa",
  linkTextPlaceholder: "Dodaj naziv...",
  linkUrlPlaceholder: "Dodaj adresu...",
  editList: "Uredi listu",
  copyList: "Kopiraj listu",
  sortBy: "Poredaj po...",
  moveAllCards: "Pomjeri sve kartice",
  archiveAllCards: "Arhiviraj sve kartice",
  open: "Otvori",
  editTitle: "Izmijeni naziv",
  editTags: "Izmijeni oznake",
  editMembers: "Izmijeni članove",
  copy: "Kopiraj",
  attachment: "Privitak",
  startDate: "Datum početka",
  dueDate: "Rok završetka",
  cover: "Naslovna fotografija",
  tags: "Oznake",
  activity: "Aktivnost",
  created: "Kreirano",
  updated: "Ažurirano",
  timePeriod: "Vremenski period",
  netChange: "Neto promjena",
  last7Days: "Zadnjih 7 dana",
  last14Days: "Zadnjih 14 dana",
  last30Days: "Zadnjih 30 dana",
  between: "između",
  deletedCards: "Izbrisane kartice smanjuju broj",
  convertToCard: "Pretvori u karticu",
  searchForTag: "Traži oznaku",
  createTag: "Kreiraj oznaku",
  tagName: "Ime oznake",
  editTagName: "Uredi ime oznake",
  hideCheckedItems: "Sakrij završene stavke",
  showCheckedItems: "Prikaži završene stavke",
  deleteChecklist: "Izbriši čeklistu",
  attachments: "Privitci",
  versionHistory: "Historija",
  profile: "Profil",
  settings: "Postavke",
  email: "Email",
  firstNamePlaceholder: "Unesite ime",
  lastNamePlaceholder: "Unesite prezime",
  displayNamePlaceholder: "Unesite ime za prikaz",
  profileBasicInfoSubtitle: "Personalni i kontakt podaci",
  uploadProfileImageRule:
    "Slika treba da bude PNG, GIF ili JPG format maksimalne veličine od 3 MB. Prijenos slike će zamijeniti boju vašeg avatara u cijeloj aplikaciji.",
  workspaceLogo:
    "Odaberite logo za svoj workspace. Preporučena veličina je 256x256px",
  logoSaved: "Logo sačuvan",
  logoRemoved: "Logo uklonjen",
  removeCover: "Izbriši naslovnu fotografiju",
  uploadCoverImage: "Postavi novu fotografiju",
  list: "Lista",
  addChildCard: "Dodaj child karticu",
  newChildCard: "Kreirajte novu child karticu",
  searchForCard: "Potražite postojeću karticu",
  cancelSearch: "Otkaži pretragu",
  computer: "Kompjuter",
  setDueDate: "Postavi rok završetka",
  months:
    "Januar,Februar,Mart,April,Maj,Juni,Juli,August,Septembar,Oktobar,Novembar,Decembar",
  monthsAbbreviation: "Jan,Feb,Mar,Apr,Maj,Jun,Jul,Aug,Sep,Okt,Nov,Dec",
  daysAbbreviation: "PO,UT,SR,ČE,PE,SU,NE",
  daysAbbreviationLong: "Pon,Uto,Sri,Čet,Pet,Sub,Ned",
  weekDays: "Ponedjeljak,Utorak,Srijeda,Četvrtak,Petak,Subota,Nedjelja",
  time: "Vrijeme",
  dueDateReminder: "Podsjetnik na rok",
  weekBefore: "Sedmica prije",
  daysBefore: "Dana prije",
  dayBefore: "Dan prije",
  hoursBefore: "Sati prije",
  hourBefore: "Sat prije",
  onTime: "Na vrijeme",
  none: "Nijedan",
  due: "Rok",
  insertFile: "Umetni datoteku",
  addImage: "Dodaj sliku",
  edited: "uređeno",
  insert: "Umetni",
  deleteAttachment: "Ukloni privitak",
  overdue: "Isteklo",
  continue: "Nastavi",
  createdBy: "Kreirao",
  press: "Pritisni",
  toClose: "za izlaz",
  useArrowKeys: "Koristi tipke sa strelicama",
  toNavigate: "za navigaciju, odaberite sa",
  cards: "Kartice",
  on: "na",
  sending: "Slanje pozivnog linka..",
  inviteDoesntExist: "Pozivni link ne postoji.",
  newInviteLinkSent: "Poslali smo vam novi pozivni link, provjerite vaš email.",
  inviteLinkAccepted: "Pozivni link je već prihvaćen.",
  inviteNoLongerValid:
    "Pozivni link nije više validan - molimo vas zatražite novi.",
  inviteCodeIncorrect:
    "Kod za pozivni link nije ispravan. Kliknite ispod za novi link.",
  spaceAccess: "Pristup prostoru",
  changeToPrivateSpace:
    "Svi postojeći članovi ovog prostora će i dalje biti članovi nakon što postane privatni. Nijedan novi član se neće moći pridružiti osim ako nisu pozvani.",
  changeToOpenSpace:
    "Svi članovi workspace-a moći će pronaći i pridružiti se ovom prostoru, te vidjeti njegov sadržaj.",
  changeToPrivate: "Promijeni u privatni",
  changeToOpen: "Promijeni u javni",
  changeToPrivateSpaceTitle: "Promijeni u privatni prostor?",
  changeToOpenSpaceTitle: "Promijeni u javni prostor?",
  ownersAdminsCreatorOfSpace:
    "Samo vlasnici workspace-a, administratori i kreator prostora mogu promijeniti ovu postavku",
  onlyOwnerOfPrivateSpace:
    "Samo vlasnik privatnog prostora može promijeniti ovu postavku",
  onlySpaceOwnerCanModifyMembers:
    "Samo vlasnik prostora može mijenjati članove",
  cannotModifySpaceOwner: "Ne možete mijenjati vlasnika prostora",
  pageTitlePlaceholder: "Dodaj ime ovom dokumentu",
  markAllAsRead: "Označi sve kao pročitano",
  addTo: "Dodao te na",
  removeFrom: "Izbrisao te iz",
  movedTo: "%{name} pomjeren",
  commented: "Komentarisano",
  mentioned: "Spominjani ste",
  dropFilesLabel: "ispusti datoteke ovdje",
  back: "Nazad",
  hasDueDate: "Ima rok završetka",
  dueSoon: "Uskoro ističe rok",
  dueToday: "Rok završetka danas",
  epic: "Projekt",
  epics: "Projekti",
  searchForEpic: "Potraži projekt",
  changedEpicFrom: "promijenio projekt iz",
  addedToEpicCard: "dodao karticu u projekt",
  removedFromEpicCard: "uklonio karticu iz projekta",
  epicInherited: "naslijedio projekt",
  untitledView: "Pogled bez naslova",
  cannotSaveUntitledView: "Ne možete spasiti pogled bez naslova",
  viewSaved: "pogled je spašen",
  pagePlaceholder: "Počnite pisati nešto :)",
  newViewTitele: "Naslov novog pogleda",
  ["global.placeholder.pagePlaceholder"]: "Počnite pisati nešto :)",
  viewAll: "Prikaži sve",
  filterByUnread: "Prikaži nepročitane",
  pagePublished: "Stranica objavljena",
  restore: "Vrati",
  cardPathArchivedBoard: "Ova kartica je dio arhivirane ploče",
  boardArchived: "Ova ploča je arhivirana.",
  pageArchived: "Ova stranica je arhivirana.",
  restoreMakeChange: "Klikni ovdje za vraćanje.",
  boardUpdated: "Board ažuriran",
  defaultBoardLayoutChangedTo:
    "Predefinisani izgled board-a je promijenjen na %{layoutStyle}",
  esc: "Esc",
  assignee: "Dodjeli",
  findMembers: "Pretraži članove...",
  inviteExternalPeople: "Pozovite spoljne ljude",
  notInThisSpace: "Nisu u ovom prostoru",
  notWorkspaceMember: "Izgleda da se tražena osoba ne nalazi u vašem timu",
  deleteView: "Izbriši pogled",
  anchorLinkErrorMessage: "Nemoguće pronaći link",
  childCard: "Child card",
  parentCards: "Roditeljske kartice",
  blocking: "Blokirajuće",
  blocked: "Blokirane",
  favourites: "Favoriti",
  dragOr: "Prevucite ili",
  somethingHere: "nešto ovdje",
  linkCopiedToClipboard: "Link je kopiran u međuspremnik.",
  tomorrow: "Sutra",
  invitationsSent: "Pozivnice poslane!",
  retry: "Pokušaj ponovo",
  undo: "Poništi",
  tagExists: "Oznaka već postoji",
  removeChildCardFail: "Neuspješno uklanjanje child kartice",
  moveChildCardFail: "Neuspješno pomjeranje child kartice",
  addChildCardFail: "Neuspješno dodavanje child kartice",
  cantRemoveMembers: "Ne možete ukloniti članove iz prvog prostora",
  cantRemoveMembersFromSpace: "Ne možete ukloniti članove space-a",
  cannotModifyMembers: "Ne možete mijenjati članove",
  inactiveMembersCannotBeAdded: "Neaktivni članovi ne mogu biti dodani",
  duplicate: "Dupliciraj",
  setParentCard: "Dodaj roditeljsku karticu",
  duplicateCard: "Dupliciraj karticu",
  duplicateTo: "Dupliciraj u",
  duplicateDefaultTitle: "Unesite naslov kartice (defaults u original)",
  duplicates: "Duplicira",
  duplicateOf: "Duplikat od",
  markAsBlockedBy: "Označi kao blokirano od strane",
  markAsBlocking: "Označi kao blokiranje",
  markAsRelatedTo: "Označi kao povezano sa",
  markAsDuplicateOf: "Označi kao duplikat",
  blocks: "Blokira",
  blockedBy: "Blokirano od",
  related: "Povezano",
  relatedEpics: "Povezani projekti",
  markedEpicAsBlocking: "je označio ovaj projekta kao blokirajuću",
  markedEpicAsBlockedBy: "je označio ovaj projekta kao blokiranu od strane",
  markedEpicAsRelated: "je označio ovaj projekta kao povezanu sa",
  markedEpicAsDuplicate: "je označio ovaj projekta kao duplikat od",
  relatedCards: "Povezane kartice",
  markedCardAsBlocking: "je označio ovu karticu kao blokirajuću",
  markedCardAsBlockedBy: "je označio ovu karticu kao blokiranu od strane",
  markedCardAsRelated: "je označio ovu karticu kao povezanu sa",
  markedCardAsDuplicate: "je označio ovu karticu kao duplikat od",
  removedCardRelationship: "je uklonio vezu",
  noListsInBoard: "Nema listi u ploči",
  noBoardsInSpace: "Nema ploča u prostoru",
  noBoardsInThisSpace: "Nema ploča u ovom prostoru",
  emptyList: "Prazna lista",
  cardDuplicated: "Kartica duplicirana",
  viewDuplicated: "Pogled dupliciran",
  viewDeleted: "Pogled izbrisan",
  cardDuplicateFailed: "Dupliciranje kartice nije uspjelo",
  viewDuplicateFailed: "Dupliciranje pogleda nije uspjelo",
  cantUndoneAction: "Ova akcija ne može biti opozvana",
  deleteCommentPopupMessage: "Da li ste sigurni da želite izbrisati komentar?",
  deleteMessage: "Izbriši komentar",
  eachSpaceCanContain: "Svaki prostor može sadržavati kartica koliko želite",
  browseSpaces: "Pretražite prostore",
  popupSpaceDescription:
    "Vaš workspace je organizovan u prostore. Oni mogu biti nazvani kao tim, tema, ili mogu biti fokusirani na specifičan dio posla",
  eachSpaceCanContainMultiple: "Svaki prostor može sadržavati više ",
  pagesLowercase: "stranice",
  kanbanBoards: "kanban ploča",
  and: "i",
  removeFromParent: "Ukloni iz roditelja",
  removeChildCard: "Izbriši child karticu",
  editChildCardDetails: "Uredi detalje child kartice",
  copyLink: "Kopiraj link",
  childCardTitleNotUpdated: "Naziv child kartice nije promijenjen.",
  addNewChildCard: "Dodaj novu child karticu",
  enterCardTitleOrFind: "Unesite naziv kartice ili pronađite postojeću karticu",
  createNewCard: "Kreiraj novu karticu",
  unsplashImage: "Unsplash slika",
  publishesSubpagesButNoComments: "Objavljuje podstranice, ali ne i komentare.",
  pageIsSharedToWeb: "Stranica je javno podijeljena.",
  shared: "Podijeljeno",
  openSharedPage: "Otvori podijeljenu stranicu",
  pageIsSetToPrivate: "Stranica je privatna",
  profileSettings: "Postavke profila",
  switchWorkspace: "Promijenite workspace",
  archivedItems: "Arhivirano",
  logOut: "Odjavi se",
  helpFeedback: "Pomoć i Feedback",
  help: "Pomoć",
  joinSlack: "Pridruži se našoj Slack zajednici",
  askQuestions: "Postavite pitanja i pomozite drugima",
  contactUs: "Kontaktirajte nas",
  letUsKnow: "Dajte nam doznanja ako imate problem ili pitanje",
  assign: "Dodjeli",
  pageIsNoLongerShared: "Stranica više nije javno podijeljena",
  favourite: "Dodaj u omiljene",
  unfavourite: "Ukloni iz omiljenih",
  allowSearchEngines: "Dozvoli pretraživačima da indeksiraju stranicu",
  searchEngineIndexing: "Indeksiranje pretraživača",
  searchIndexingEnabled: "Indeksiranje pretraživača uključeno",
  searchIndexingDisabled: "Indeksiranje pretraživača isključeno",
  attachIconFrom: "Dodajte ikonu iz...",
  addIcon: "Dodajte ikonu",
  addCoverImage: "Dodajte pozadinsku sliku",
  pageDuplicated: "Stranica je duplicirana",
  pageDuplicateFailed: "Dupliciranje stranice nije uspjelo",
  copyOf: "Kopija od",
  displayNameDescription:
    "Ovo može biti vaše ime ili nadimak - kako god želite da vas ljudi pozivaju u Superthread-u",
  integrations: "Integracije",
  importer: "Importer",
  github: "GitHub",
  gitlab: "GitLab",
  jira: "Jira",
  trello: "Trello",
  importFrom: "Uvoz sa",
  usersToSuperthreadUsers: "korisnice u Superthread korisnike",
  issues: "probleme",
  teams: "timove",
  selectYour: "Odaberite svoje",
  setUpImport: "Podesi uvoz",
  importHistory: "Historija uvoza",
  runImport: "Pokrenite uvoz",
  start: "Počni",
  started: "Počelo",
  DontImport: "Ne uvozit",
  dontImportUsers: "Don't import users",
  ImportUsers: "Import users",
  selectUser: "Odaberi korisnika",
  inviteByEmail: "Pozovi sa email adresom",
  users: "korisnici",
  options: "Opcije",
  chooseAditionslOptions: "Odaberite dodatne opcije",
  importAttachments: "Uvezite priloge",
  includeCardCoverImages: "Uključite slike naslovnice kartice",
  importInProgress: "Uvoz u procesu",
  importError: "Uvoz završen sa greskom",
  importSuccess: "Uvoz završen",
  importUnstarted: "Uvoz nije počeo",
  timeStarted: "Vrijeme početka",
  completed: "Završeno",
  showCompleted: "Prikaži završeno",
  details: "Detalji",
  finish: "Završi",
  validEmail: "Molimo unesite ispravnu email adresu",
  emailAdresses: "E-mail adrese, odvojene zarezima",
  addToSpaces: "Dodaj u prostore",
  addSpaces: "Dodaj prostore",
  browseProjects: "Pretražuj sve prostore",
  createAndBrowseSpaces: "Kreirajte i pretražujte prostore",
  nameIsRequired: "Ime je potrebno",
  noProjectFound: "Nema više prostora za dodati!",
  memberExplanation:
    "Članovi mogu pretraživati i pridružiti se bilo kojem prostoru u workspace-u",
  adminExplanation: "Admini imaju povećani pristup postavkama workspace-a",
  guestExplanation:
    "Gosti imaju ograničen pristup u workspace-u i mogu vidjeti samo prostore u koje su dodani",
  connect: "Poveži se",
  selectBoardImport: "Odaberite ploče koje želite uvesti.",
  selectUsersImport: "Odaberite korisnike koje želite uvesti.",
  notImportArchivedIssues: "Nećemo uvoziti arhivirane probleme",
  importTasksIntoSuperthread: "Uvezite postojeće zadatke u Superthread.",
  connectAccount: "Povežite svoj račun",
  completedOn: "Završen",
  importedBy: "Uvezen od:",
  timeCreated: "Vrijeme kada je napravljeno:",
  numberOfImportedBoards: "Broj uvezenih ploča:",
  numberOfImportedUsers: "Broj uvezenih korisnika:",
  importingIsFinished: "Uvoz je završen",
  importing: "Uvoz",
  selectService:
    "Odaberite iz koje usluge trebamo uvesti probleme. Zatražit ćemo vaše detalje o autentifikaciji kako bismo mogli pristupiti njihovom API-ju. Nećemo uvoziti nikakve podatke dok ne potvrdite sve opcije u završnom koraku procesa.",
  account: "Račun",
  importers: "Uvozi",
  general: "General",
  manageWorkspaceSettings: "Upravljajte općim postavkama workspace-a",
  avatarAppearance: "Izgled avatara",
  uploadImage: "Učitaj sliku",
  successfullySaved: "Uspješno spremljeno",
  errorSave: "Vaše promjene nisu mogle biti sačuvane",
  copyURL: "Kopiraj URL",
  copyUrl: "Kopira URL u međuspremnik",
  copyCardUrl: "Kopiraj URL kartice u međuspremnik",
  copyPageUrl: "Kopiraj URL stranice u međuspremnik",
  copyBoardUrl: "Kopiraj URL ploče u međuspremnik",
  copySpaceUrl: "Kopiraj URL prostora u međuspremnik",
  copyGitBranchNameToClipboard: "Kopiraj ime git grane u međuspremnik",
  copyGitBranchName: "Kopiraj ime git grane",
  branchCopiedToClipboard: "Ime git grane kopirana u međuspremnik",
  subscribe: "Pretplati se",
  unsubscribe: "Ukloni pretplatu",
  pullRequestAutomation: "Pull request automatizacija",
  prAutomationDescription:
    "Premjestite kartice u Superthreadu kada se pull requestovi ažuriraju na GitHubu.",
  whenACardIsLinkedToPR: "Kada je kartica povezana sa pull requestom",
  whenPRTargetsTheBranch: "Kada pull request cilja granu",
  addBranchSpecificAutomation: "Dodaj automatizaciju specifičnu za granu",
  automationMustHaveBranchName:
    "Automatizacija mora imati ime grane. Ova pravila će biti ignorisana.",
  addBranchSpecificAutomationErrorAlreadyExists:
    "Već postoji automatizacija za to ime grane. Ova pravila će biti ignorisana.",
  invalidGitBranchName:
    "To nije važeće ime grane. Ova pravila će biti ignorisana.",
  branchSpecificAutomationAdded:
    "Dodana je automatizacija specifična za granu.",
  branchSpecificAutomationUpdated:
    "Ažurirana je automatizacija specifična za granu.",
  branchSpecificAutomationRemoved:
    "Uklonjena je automatizacija specifična za granu.",
  deleteAutomation: "Izbrišite automatizaciju",
  deleteThisAutomation: "Izbrišite ovu automatizaciju",
  deleteAutomationConfirmation:
    "Ovaj skup pravila će biti trajno izbrisan i ne može se vratiti.",
  whenPRChangesTo: "Kada se PR promijeni u",
  moveCardToList: "Pomjeri karticu u listu",
  doNotMove: "Ne pomjeraj",
  draftPROpened: "Otvoren PR nacrt",
  pROpened: "PR otvoren",
  pRReviewRequest: "PR zahtjev za pregled",
  pRMerged: "PR spojen",
  pRClosed: "PR zatvoren",
  noListInBoard: "Nema listi u ovoj ploči",
  unassigned: "Nije dodijeljeno",
  viewParentCard: "Pogledaj roditeljsku karticu",
  changeParentCard: "Promjeni roditeljsku karticu",
  removeParentCard: "Ukloni roditeljsku karticu",
  maxFileSize: "(maksimalna veličina fajla: 5 MB)",
  addAttachment: "Dodaj datoteku",
  createChecklist: "Dodaj čeklistu",
  assignedToMe: "Dodijeljeno meni",
  movedTAaNewList: "Pomjereno na novu listu",
  moved: "Pomjereno",
  published: "Objavljeno",
  cardComments: "Komentari kartica",
  pageComments: "Komentari stranica (uključujući odgovore u nitima)",
  movedBetweenSpaces: "Premješteno između prostora",
  addedToASpace: "Dodan u prostor",
  anywhereYouAreMentioned:
    "Gdje god ste spomenuti (bez obzira na status pretplate itd.)",
  anyCommentsOnResources: "Svi komentari na resurse koje gledate.",
  ifYouAreMemberOfABoard: "Ako ste član ploče:",
  manageMembers: "Organizujte članove",
  manageWhoHasAccess: "Odredite ko ima pristup ovom workspace-u",
  active: "Aktivan",
  suspended: "Suspendiran",
  inviteMembers: "Pozovite članove",
  emailAddress: "Email adresa",
  inviteAs: "Pozovite kao",
  teamMembers: "Članovi tima",
  gitHubConnected: "Uspješno ste se povezali na GitHub",
  nothingToShow: "Nema ništa za prikazat",
  findTagsOrCreateNew: "Pronađi tagove ili kreiraj novi",
  deleteTag: "Izbriši oznaku",
  rename: "Preimenuj",
  changeIcon: "Promijeni ikonu",
  areYouSureYouWantToRemove:
    "Da li ste sigurni da ih želite ukloniti? Oni će izgubiti pristup workspace-u.",
  areYouSureYouWantToLeave:
    "Da li ste sigurni da želite napustiti ovaj workspace? Trebat ćete biti ponovo pozvani da biste dobili pristup.",
  areYouSureYouWantToRevoke:
    "Da li ste sigurni da želite otkazati njihov poziv u ovaj workspace?",
  areYouSureYouWantToTransferOwnership:
    "Jeste li sigurni da želite prenijeti vlasništvo ovog workspace-a? Samo novi vlasnik će to moći poništiti.",
  transferOwnership: "Prenesite vlasništvo",
  transferSpaceOwnershipConfirmed: "Vlasništvo je preneseno",
  transferSpaceOwnershipShort:
    "Prenesite vlasništvo ovog workspace-a na drugog člana",
  transferSpaceOwnershipDescription:
    "Prenesite vlasništvo ovog workspace-a na drugog člana. Samo novi vlasnik će to moći poništiti.",
  transferSpaceOwnershipBeforeLeaving:
    "Prenesite vlasništvo ovog workspace-a na drugog člana prije nego što napustite workspace.",
  confirm: "Potvrdi",
  revoke: "Otkaži",
  notFound: "Nije pronađeno",
  itemNotFound: "Stavka nije pronađena",
  urlDoesntLeadAnywhere: "Taj URL ne vodi nikuda",
  itemMightBeDeleted: "Stavka je možda izbrisana ili joj nemate pristup",
  deleteSpace: "Izbriši prostor",
  ifYouWantToDeleteResource:
    "Ako želite da izbrišete ovaj %{resourceType}, upišite njegovo ime ispod.",
  typeTheNameOfTheSpace: "Upišite ime prostora",
  removeMember: "Ukloni člana",
  leaveWorkspace: "Napusti workspace",
  revokeInvite: "Otkaži poziv",
  invited: "Pozvan",
  pending: "Na čekanju",
  admin: "Admin",
  owner: "Vlasnici",
  guest: "Gost",
  inviteSent: "Poziv je poslan",
  resendInvite: "Pošaljite ponovo poziv",
  whatsNew: "Šta je novo",
  viewUpdates: "Pogledajte update u našem sedmičnom changelog-u",
  fullscreen: "Cijeli zaslon",
  whenYouCreateTags:
    "Kada kreirate oznake direktno na kartici, one se spremaju kao prilagođene oznake samo za taj prostor. Možete ponovo koristiti uobičajene oznake (npr. bug) u svim svojim prostorima tako što ćete ih umjesto toga kreirati ovdje. Da bi stvari bile uredne, spojit ćemo oznake prostora s istim imenom u novi radni prostor.",
  merge: "Spojite",
  theSpace: "Prostor",
  haveSameTags: "imaju oznake sa istim imenom.",
  doYouWantToMerge: "Da li želite spojiti ove oznake u novu workspace oznaku?",
  tagWithThisNameWorkspace: "Želite li ih spojiti u novu oznaku workspace-a?",
  tagWithThisNameSpace: "Oznaka s ovim imenom već postoji u prostoru",
  editTag: "Uredite oznaku",
  workspaceTags: "Workspace oznake",
  manageTags: "Upravljajte oznakama koje se dijele u svim prostorima",
  youCantUndo: "Ne možete vratiti ovu radnju.",
  merge2spaceTags:
    "With the same name into the workspace tag? Sa istim imenom u workspace oznaku?",
  areYouSureYouWantToDelete:
    'Jeste li sigurni da želite izbrisati "%{resourceTitle}" %{resourceType}?',
  uploaded: "Učitano",
  cardCreatedInResource: "Kartica kreirana u '%{resourceName}' %{resourceType}",
  ["global.label.createIn"]: "Kreiraj u",
  rememberBoard: "Postavi kao zadanu ploču",
  cardTitle: "Naziv kartice",
  pageTitle: "Naslov stranice",
  cardDescription: "Opis kartice...",
  editAsignees: "Uredite dodjeljivače",
  thisBoardIsEmpty: "Ova ploča je prazna. Prvo kreirajte listu.",
  pageCreated: "Stranica je kreirana",
  ["quickPage.label.setAsDefaultSpace"]: "Postavi kao zadani prostor",
  changesAreSavedAuto: "Izmjene spremljene automatski",
  untitledCard: "Nenaslovljena kartica",
  editAssignees: "Uredi članove",
  showChildCards: "Prikaži podkartice",
  hideChildCards: "Sakrij podkartice",
  createNewList: "Napravi novu listu",
  enterListName: "Unesite ime liste",
  listStatus: "Status liste",
  couldntArchiveCard: "Kartica nije arhivirana.",
  cardRestored: "Kartica je vraćena",
  dueOn: "Završava se",
  today: "Danas",
  yesterday: "Jučer",
  cannotModidyListStatus:
    "Nije moguće mijenjati status liste ako su kartice dodane.",
  attached: "zakačio",
  removed: "uklonio",
  updatedTheStartDate: "ažurirao datum početka na",
  setTheStartDate: "postavio datum početka na",
  removedStartDate: "uklonio datum početka",
  updatedTheDueDate: "azurirao datum u",
  setTheDueDate: "postavio datum u",
  removedDueDate: "uklonio datum",
  changedStausFrom: "promijenio status iz",
  createdCard: "kreirao karticu",
  createdEpic: "kreirao projekt",
  people: "osobe",
  assignedMember: "dodao",
  archivedTheCard: "arhivirao karticu",
  restoredTheCard: "vratio karticu",
  archivedTheEpic: "arhivirao projekt",
  restoredTheEpic: "vratio projekt",
  theCardDescription: "opis kartice",
  theCardTitle: "naslov kartice",
  theEpicDescription: "opis projekta",
  theEpicTitle: "naslov projekta",
  ["quickPage.title.attachImageFrom"]: "Zakači sliku sa...",
  ["quickPage.title.attachCoverImageFrom"]: "Zakači naslovnu sliku sa...",
  chooseWorkspaceToConnectIntegration:
    "Odaberite workspace za povezivanje sa %{integrationName}",
  connectSuperthreadWith: "Povežite Superthread sa %{integrationName}",
  zapierIntegradionDescripiton:
    "Zapier vam omogućava da izgradite prilagođene radne tokove koji povezuju Superthread sa gotovo bilo kojom drugom aplikacijom. Povezive aplikacije uključuju: Typeform, Gmail, Intercom, Google Forms, Zendesk, Airtable, Front i mnoge druge.",
  connectToZapier: "Povežite Zapier sa Superthread-om",
  zapier: "Zapier",
  openZapier: "Otvori Zapier",
  allow: "Dopusti",
  integrationWillHave:
    "%{integrationName} će imati pristup čitanju i pisanju karticama, pločama i stranicama u vašem workspace-u.",
  youMayBeSharing:
    "Možda dijelite osjetljive informacije s ovom web lokacijom ili aplikacijom. Uvijek možete vidjeti ili ukloniti pristup u svojim",
  stSettings: "Superthread postavkama",
  seeIntegration: "Vidite %{integrationName}",
  privacyPolicy: "Politika privatnosti",
  termsOfService: "Uslovi korištenja",
  makeSureYouTrust: "Uvjerite se da vjerujete %{integrationName}",
  integrationIsRequesting: "%{integrationName} traži pristup",
  previewStInSlack: "Pregledajte Superthread veze u Slacku",
  lookingForSlackNotifications: "Tražite Slack notifikacije?",
  turnThemOnInYour: "Upalite ih u vašim",
  notificationsSettings: "Postavkama notifikacija",
  connectToSlack:
    "Povežite se na Slack da pregledate ključne informacije sa Superthread kartica i stranica kada timovi zalijepe veze na njih u Slack poruke.",
  orLc: "ili",
  useBoardsToVisualise:
    "Koristite ploče da vizualizujete svoj tok posla, pratite napredak svog tima i planirate šta dalje. Napravite više ploča kako biste stvari organizirali.",
  collaborativeDocuments:
    "Kolaborativni dokumenti s tekstom, slikama, smanjenjem vrijednosti i umetnutim komentarima. Vodite bilješke, pišite specifikacije, napravite wiki ili javno dijelite informacije.",
  filterAcrossTheEntire:
    "Filtrirajte po cijelom radnom prostoru kako biste stvorili prikaz svih kartica koje su vam „dodijeljene” ili možda kreirajte globalni zaostatak „bugova”. Pregledi mogu biti privatni ili podijeljeni s vašim timom.",
  useFiltersToCreate:
    "Koristite filtere da napravite novi pogled samo sa karticama koje zelite vidjeti",
  kanbanBoardsUc: "Kanban ploče",
  importYourExistingTasksFrom: "Uvezite svoje postojeće zadatke iz",
  importTasks: "Uvezite zadatke",
  leaveSpace: "Napusti prostor",
  joinSpace: "Pridruži se prostoru",
  joinThisSpace: "Pridruži se ovom prostoru",
  hasUnsupportedFileType: "ima nepodržan tip datoteke",
  maxAllowedImageSize: "Maksimalna dozvoljena veličina slike je",
  maxAllowedImageResolution: "Maksimalna dozvoljena rezolucija slike je",
  movedFromSpace: "maknuo iz prostora",
  onlineAgain: "Ponovo ste na mreži",
  youAreOffline: "Nemate interneta",
  untitledPage: "Stranica bez naslova",
  hideChildPages: "Sakrij podstranice",
  showSubpages: "Prikaži podstranice",
  addedTo: "dodan u",
  addMembers: "Dodaj članove...",
  removedFrom: "uklonjen iz",
  viewMembers: "Pogledaj članove",
  copyLinkToHeading: "Kopiraj link naslova",
  joined: "Pridružen",
  addOwner: "Dodaj vlasnika",
  noOwner: "Nema vlasnika",
  setOwner: "Postavi vlasnika",
  font: "Font",
  clickToUpdate: "Klikni za ažuriranje",
  NewVersionAvailable: "Nova verzija aplikacije je dostupna",
  deactivated: "deaktiviran",
  addedChildCard: "dodao pod karticu",
  removedChildCard: "uklonio pod karticu",
  removedChecklist: "uklonio checklistu",
  addedChecklist: "dodao checklistu",
  addedChecklists: "dodao checkliste",
  markedAsIncomplete: "označio kao nezavršeno",
  completedChecklistItem: "završio",
  addedParentCard: "dodao roditelj karticu",
  removedParentCard: "uklonio roditelj karticu",
  deleteFolder: "Izbriši datoteku",
  renameFolder: "Preimenuj datoteku",
  myViews: "Moji pogledi",
  workspaceViews: "Workspace pogledi",
  lockSidebar: "Zaključaj sidebar",
  hideSidebar: "Sakrij sidebar",
  appearance: "Izgled",
  changeHowSuperthreadLooksAndFeels:
    "Promijeni kako Superthread izgleda i radi",
  matchSistemSettings: "Podudaranje sa sistemskim postavkama",
  darkMode: "Tamni mod",
  lightMode: "Svijetli mod",
  darkGreyMode: "Tamno sivi mod",
  darkBlueMode: "Tamno plavi mod",
  lightBlueMode: "Svijetlo plavi mod",
  year: "Godina",
  quarter: "Kvartal",
  month: "Mjesec",
  addNewPageInside: "Dodaj novu podstranicu",
  theme: "Tema",
  boardSettings: "Postavke ploče",
  inbox: "Inbox",
  resolve: "Riješi",
  reactionsToYourComments: "Reakcije na vaše komentare",
  taskIsOverdue: "Zadatak je zakašnjeo",
  endDateIsBeforeStartDate: "Krajnji datum je prije početnog datuma",
  icons: "Ikone",
  emojis: "Emodžiji",
  boardWillNotShowOnPublicPage: "Ploča se neće prikazati na javnoj stranici",
  moveCardIntoSprint: "Kartica je premještena u ciklus %{sprintName}",
  noSprintsLabel: "Nema ciklusa",
  searchForBoard: "Pretraži ploču",
  activeSprintText: "Trenutni",
  loadMoreSprints: "Učitaj više ciklusa",

  // Onboarding
  emailLabel: "Vaš email",
  passwordLabel: "Lozinka",
  checkEmail: "Provjeri email",
  haveSent: "Mi smo poslali ",
  sixDigit: "6 brojeva",
  teamName: "Ime vašeg tima?",
  spaceNameLabel: "Ime prostora",
  spaceNamePlaceHolder: "npr. web-trgovina",
  min3Characters: "Mora biti minimum 3 karaktera.",
  invite: "Pozovi",
  latest: "Zadnje",
  cardChildrenTitle: "Child kartice",
  members: "Članovi",
  removeFromCard: "Ukloni iz kartice",
  displayName: "Korisničko ime",
  firstName: "Ime",
  lastName: "Prezime",
  update: "Spremi",
  openSuperthread: "Otvori Superthread",
  infoNotification: "Info",
  errorNotification: "Greška",
  alertNotification: "Upozorenje",
  successNotification: "Uspjeh",
  SignInIntoExistingWorkspace: "Prijavi se u postojeći workspace",
  pages: "Stranice",
  gridView: "Grid",
  listView: "Lista",
  member: "Član",
  notMember: "Nije član",
  watch: "Posmatraj",
  unwatch: "Ne posmatraj",
  commentsActivity: "Komentari i aktivnosti",
  show: "Prikaži",
  newestFirst: "Najnovije prvo",
  oldestFirst: "Najstarije prvo",
  exploring: "Istraživanje",
  saveAsNewView: "Spasi kao novi pogled",
  noResults: "Nema rezultata",
  rememberChoice: "Zapamti izbor",
  electronOpenInApp: "Otvori u aplikaciji",
  electronOpenInDesktopApp: "Otvori u desktop aplikaciji",
  electronOpenLinksInDesktopApp: "Otvori linkove u desktop aplikaciji",
  electronAutoOpenLinksInDesktopApp:
    "Automatski otvori Superthread linkove u desktop aplikaciji",
  electronCurrentLinkOpenedInApp:
    "Trenutni link je otvoren u desktop aplikaciji",
  electronAppIsInstalled: "Izgleda da imate instaliranu aplikaciju",
  electronUserMentioned: "vas je spomenuo/la",
  electronResourceMoved: "je pomjerio/la",
  electronMemberAdded: "vas je dodao/la u",
  electronMemberRemoved: "vas je uklonio/la iz",
  electronCommentAdded: "je dodao/la novi komentar",
  electronResourceArchived: "je arhivirao/la",
  electronUserReacted: "je reagirao/la:",
  results: "Rezultati",
  tasks: "Zadaci",
  electronRecentlyViewed: "Nedavno posjeceno",
  electronOpenDesktopApp: "Otvori desktop aplikaciju",
  electronRedirectingToApp: "Preusmjeravanje na desktop aplikaciju...",
  connectToImporter: "Poveži se sa %{importerName}",
  accessToken: "Pristupni token",
  installationCloudHostname: "instalacija / cloud ime hosta",
  findInYour: "Pronađi u",
  emailAddressYouUseFor:
    "Email adresu koju koristiš za svoj %{importerName} račun",
  selectWhich: "Odaberi koje",
  selectBoardsToImport: "Izaberi %{boardEq} iz kojih ćeš uvesti %{cardEq}",
  importYourExistingNameToST:
    "Uvezi postojeće %{importerName} %{boardEq} u Superthread",
  superthreadSpace: "Superthread prostor",
  mapImporterUsersToSTUSers:
    "Mapiraj %{importerName} korisnike u Superthread korisnike (ili pozovite one koji fale) da sačuvate korisnike, kreatore i aktivnosti.",
  startImport: "Pokreni uvoz",
  wellLetYouKnowWhenImportFinishes: "Obavijestit ćemo vas kada uvoz završi",
  feelFreeToContuinueUsingST: "Slobodno nastavite koristiti Superthread",
  dontImportThisUser: "Nemoj uvoziti ovog korisnika",
  matchToAnExistingSTUser: "Mapiraj na postojećeg Superthread korisnika",
  createANewUser: "Kreirajte novog korisnika (poziv e-poštom)",
  // importEpics: 'Uvezi epics',
  // importEpicsDesc: "Epics će biti uvezeni u zasebnu Superthread ploču nazvanu 'Epics'.",
  importOpenStories: "Uvezi otvorene priče",
  importOpenStoriesDesc:
    "Neriješene ili otvorene priče bit će uvezene sa postojećim stanjima.",
  importStaleStories: "Uvezi zastarjele priče",
  importStaleStoriesDesc:
    "Priče koji nisu otvorene u više od 6 mjeseci smatraju se zastarjelim. Bit će uvezeni u arhivu i mogu se pretraživati i dearhivirati kasnije.",
  wedLikeToTake: "Želimo vam uzeti",
  thirtySeconds: "30 sekundi",
  toShowYouAround: "da vam pokažemo okolo",
  getStarted: "Počni",
  youCanAlways:
    "Uvijek možete ponovo posjetiti ovaj tutorial iz sekcije pomoći u sidebaru",
  youreGoodToGo: "Spremni ste za početak",
  quickStart: "Brzi start tutorial",
  getToKnow: "Upoznaj Superthread u 30 sekundi",
  desktopApp: "Desktop aplikacija",
  thisLinkWasOpenedInApp: "Ovaj link je otvoren u desktop aplikaciji",
  openHereInstead: "Otvori ovdje umjesto toga",
  browseAndManageSpaces: "Pregledaj i upravljaj svojim prostorima",
  manageSpaces: "Upravljaj prostorima",
  searchSpaces: "Pretraži prostore",
  createSpace: "Kreiraj prostor",
  addADescription: "Dodaj opis",
  showingNumberOfSpaces: "Prikazano je %{num} od ukupno %{totalNum} prostora",
  noResultsFoundFor: 'Nema rezultata koji odgovaraju "%{query}"',
  changeDescription: "Promijeni opis",
  contents: "Sadržaj",
  createSpaceSubtitle:
    "Prostor sadrži povezane ploče, zadatke i stranice. Možda ćete imati prostor po timu ili po poslovnom području.",
  spaceNameAndIcon: "Ime prostora i ikona",
  somethingShortAndClear: "Nešto kratko i jasno",
  youCanChangeThisLater: "Možete promijeniti ovo kasnije",
  descritionOptional: "Opis (opcionalno)",
  whatIsThisSpaceFor: "Za šta je ovaj prostor?",
  addPeopleToSpaceOptional: "Dodaj osobe u ovaj prostor (opcionalno)",
  addPeople: "Dodaj osobe",
  addPeopleSubtitle:
    "Ako dodate osobe koje nisu dio %{workspaceName} workspace-a, one će biti dodani.",
  openSpace: "Javni prostor",
  openSpaceSubtitle:
    "Svi članovi tvog workspace-a mogu pretraživati i pridružiti se prostorima",
  privateSpaceSubtitle:
    "Workspace članovi ne mogu se pridružiti privatnim prostorima osim ako nisu pozvani od strane člana",
  inviteNewPeople: "Pozovi nove osobe",
  inviteeEmailAddress: "Email adresa pozvanog",
  couldntCreateSpace: "Nije moguće kreirati prostor, pokušajte ponovo.",
  spaceCreated: "Prostor je kreiran",
  emailAlreadyAdded: "Email je već dodan",
  addingSomeMembersFailed: "Dodavanje nekih članova nije uspjelo",
  ["my-work"]: "Moj rad",
  newCard: "Nova kartica",
  ["myWork.assigned"]: "Dodijeljeno %{userName}",
  ["myWork.created"]: "Kreirano od %{userName}",
  upgradePlan: "Nadogradi plan",
  upgradePrivateSpaceTitle: "Nadogradi za korištenje privatnih space-ova",
  upgradePrivateSpaceDescription:
    "Možete kreirati privatne space-ove na plaćenom planu",
  upgradePlanBadgeTooltip:
    "Samo vlasnik space-a (%{spaceOwner}) i admini mogu mijenjati plan workspace-a",
  upgradeUserRolesTitle: "Nadogradi za postavljanje korisničkih uloga",
  upgradeUserRolesDescription: "Možete birati ne-admin role na plaćenom planu.",
  electronDownloadApp: "Preuzmi aplikaciju",
  electronDownloadAppDescription:
    "Trenutno samo podržavamo macOS. Obavijestite nas da li postoji potražnja i za Windowsom.",
  prStateOpen: "%{count} otvoreno",
  prStateClosed: "%{count} zatvoreno",
  prStateMerged: "%{count} spojeno",
  shortcutWarningText:
    "Shortcut priče koje nisu dodijeljene timu neće biti importovane.",
  language: "Jezik",
  statusType: "Tip statusa",
  resourceAndContentWillBeDeleted:
    '%{resourceType} "%{resourceTitle}" i njegov sadržaj će biti trajno izbrisan za sve. Ovo se ne može poništiti.',
  resourceWillBeDeleted:
    '%{resourceType} "%{resourceTitle}" će biti trajno izbrisan za sve. Ovo se ne može poništiti.',
  epicWillBeDeleted:
    '%{resourceType} "%{resourceTitle}" će biti trajno izbrisan. Ovo se ne može poništiti. Sve kartice koje su dodane projektu neće biti izbrisane.',
  listNameLabel: "Ime liste",
  deleteList: "Izbriši listu",
  itemName: "Ime stavke",
  inviteTeamMembersTo: "Pozovi članove time u workspace",
  loggingIn: "Prijavljujemo vas",
  defaultSpaceName: "Podrazumijevano ime prostora",
  onboardingSpaceName: "Dobrodošli 👋",
  loginCodeSendAgain: "Ponovo pošalji kod za prijavu",
  loginCodeResent: "Vaš kod za prijavu je ponovo poslan.",
  loginCodeError: "Neispravan verifikacijski kod za prijavu.",
  loginCodeErrorSending:
    "Došlo je do greške prilikom slanja verifikacijskog koda za prijavu.",
  loginCodeErrorExpired:
    "Vaš verifikacijski kod za prijavu je istekao, poslali smo vam novi.",
  loginCodeErrorRateLimited:
    "Imate previše pokušaja, pokušajte ponovo kasnije.",
  pickAWorkspaceName: "Odaberite ime",
  creatingWorkspace: "Kreiranje workspace-a",
  createaSpace: "Kreiraj prostor",
  subdomainExists:
    "Ovo ime radnog prostora je već zauzeto. Molimo pokušajte ponovo.",
  weSentALoginCode: "Poslali smo kod za prijavu na:",
  sixDigits: "6 cifara kod",
  confTo: "na",
  checkInbox: "Molimo provjerite Vaš inbox.",
  workspaceNameLabel: "Ime workspace-a",
  workspaceNamePlaceHolder: "npr. Acme industries",
  continueWithGoogle: "Nastavi sa Google-om",
  welcomeToSuperThread: "Dobrodošli u Superthread",
  aWorkspaceIs:
    "Workspace se obično imenuje prema vašoj organizaciji ili velikom samostalnom timu. Ovo ime kasnije ne možete promijeniti, ali možete imati više od jednog workspace-a.",
  youCanChangeThis:
    "Ovo možete kasnije promijeniti i napraviti prostora koliko želite.",
  LoginCode: "Kod za prijavu",
  enterLoginCode: "Unesite kod za prijavu",
  continueWithEmail: "Nastavi s email-om",
  registerGoogle: "Registruj se sa Google-om",
  onboardingEmailPlaceholder: "you@example.ba",

  cardsLayoutList: "Lista",
  cardsLayoutBoard: "Ploča",
  cardsLayoutTimeline: "Vremenska linija",
  cardsLayoutCalendar: "Kalendar (Beta)",

  ["slash.group.media"]: "Mediji",
  ["slash.group.basic"]: "Osnovni",
  ["slash.group.inline"]: "U redu",
  ["slash.group.embed"]: "Ugradi",

  ["slash.keyword.media"]: "priloži,slika,datoteka,učitaj,mediji,prilog",
  ["slash.display.attach"]: "Priloži",
  ["slash.search.attach"]: "priloži",
  "slash.display.image": "Slika",
  "slash.display.youtube": "Ugradi YouTube video",
  "slash.display.checklist": "Čeklista",
  "slash.display.table": "Tabela",
  "slash.display.h1": "H1",
  "slash.display.h2": "H2",
  "slash.display.h3": "H3",
  "slash.display.bulleted": "Lista s crticama",
  "slash.display.numbered": "Numerisana lista",
  "slash.display.blockquote": "Blok citacije",
  "slash.display.hr": "Horizontalna linija",
  "slash.display.card": "Kartica",
  "slash.display.mention": "Označi",
  "slash.display.codeBlock": "Blok koda",
  "slash.display.board": "Ploča",
  "slash.display.callout": "Poziv",

  ["slash.search.image"]: "slika",
  ["slash.search.youtube"]: "youtube video",
  ["slash.search.checklist"]: "čeklista",
  ["slash.search.table"]: "tabela",
  ["slash.search.h1"]: "h1",
  ["slash.search.h2"]: "h2",
  ["slash.search.h3"]: "h3",
  ["slash.search.bulleted"]: "lista s crticama",
  ["slash.search.numbered"]: "numerisana lista",
  ["slash.search.blockquote"]: "blok citacije",
  ["slash.search.hr"]: "horizontalna linija",
  ["slash.search.card"]: "kartica",
  ["slash.search.mention"]: "označi",
  ["slash.search.codeBlock"]: "blok koda",
  ["slash.search.embed"]: "ugrađena ploča",

  "menu.add-column-before": "Dodaj kolonu ispred",
  "menu.add-column-after": "Dodaj kolonu iza",
  "menu.add-row-before": "Dodaj red ispred",
  "menu.add-row-after": "Dodaj red iza",
  "menu.merge-cells": "Spoji/razdvoji ćelije",
  "menu.toggle-header-row": "Uključi/isključi zaglavlje reda",
  "menu.delete-column": "Briši kolonu",
  "menu.delete-row": "Briši red",
  "menu.delete-table": "Briši tabelu",
  "menu.toggle-expand-to-page-size": "Proširi na cijelu stranicu",
  "menu.add-comment": "Dodaj komentar",
  "menu.heading": "Naslov %{level}",
  "menu.bold": "Podebljano",
  "menu.italic": "Kurziv",
  "menu.strikethrough": "Precrtano",
  "menu.underline": "Podvučeno",
  "menu.check-list": "Čeklista",
  "menu.bullet-list": "Lista s crticama",
  "menu.ordered-list": "Numerisana lista",
  "menu.horizontal-rule": "Horizontalna linija",
  "menu.link": "Link",
  "menu.quick-card": "Brza kartica",
  "menu.blockquote": "Blok citacije",
  "menu.codeblock": "Blok koda",
  "menu.code": "Inline kod",
  "menu.undo": "Poništi",
  "menu.redo": "Ponovo",
  "menu.table-cell-color": "Boja ćelije",
  "menu.clear-table-cell-color": "Očisti boju ćelije",
  "menu.align-left": "Poravnaj lijevo",
  "menu.align-center": "Poravnaj po centru",
  "menu.align-right": "Poravnaj desno",
  "editor.clickToDownload": "Klikni da preuzmeš",
  "editor.loading": "Učitavanje",
  "editor.characterLimitReachedTryFile":
    "Dostignuto je ograničenje broja znakova. Za veći sadržaj, slobodno direktno naljepite datoteke.",
  "editor.uploading": "Učitavanje",
  "editor.genericFileError": "Vaša datoteka se nije mogla učitati.",

  // billing
  ["billing.unlimitedMembers"]: "Neograničen broj članova tima",
  ["billing.unlimitedSpaces"]: "Neograničen broj prostora",
  ["billing.unlimitedBoards"]: "Neograničen broj ploča",
  ["billing.unlimitedCardsAndPages"]: "Neograničen broj kartica i stranica",
  ["billing.unlimitedViews"]: "Neograničen broj pogleda",
  ["billing.category.workspaceMembers"]: "Članovi workspace-a",
  ["billing.category.spaces"]: "Prostori",
  ["billing.category.boards"]: "Ploče",
  ["billing.category.cardsAndPages"]: "Kartice i stranice",
  ["billing.category.views"]: "Pogledi",
  ["billing.category.fileSize"]: "Veličina datoteke",
  ["billing.category.privateSpaces"]: "Privatni prostori",
  ["billing.category.userPermissions"]: "Korisničke dozvole",
  ["billing.category.guestAccounts"]: "Gost računi",
  ["billing.noPrivateSpaces"]: "Nema privatnih prostora",
  ["billing.everyoneIsAdmin"]: "Svi su administratori",
  ["billing.noGuestAccounts"]: "Nema gostujućih računa",
  ["billing.5mbFileSizeLimit"]: "5MB je ograničenje veličine datoteke",
  ["billing.noFileSizeLimit"]: "Nema ograničenja veličine datoteke",
  ["billing.unlimitedPrivateSpaces"]: "Neograničen broj privatnih prostora",
  ["billing.2Spaces"]: "2 prostora",
  ["billing.adminRolesAndPermissions"]: "Administratorske uloge i dozvole",
  ["billing.unlimitedCards"]: "Neograničen broj kartica",
  ["billing.sharePagesOnTheWeb"]: "Dijelite stranice na webu",
  ["billing.50Pages"]: "50 stranica",
  ["billing.unlimitedPages"]: "Neograničen broj stranica",
  ["billing.indexPublishedPages"]:
    "Indeksiranje objavljenih stranica u pretraživačima",
  ["billing.privateSpaces"]: "Privatni prostori",
  ["billing.timelineListAndBoardView"]: "Vremenske linija, lista i ploča",
  ["billing.guestAccounts"]: "Gost računi",
  ["billing.monthly"]: "Mjesečno",
  ["billing.yearly"]: "Godišnje (-20%)",
  ["billing.currentPlan"]: "Trenutni plan",
  ["billing.yourChosenPaymentMethodIs"]:
    "Vaš odabrani način plaćanja je %{method}",
  ["billing.thisIsThePaymentMethod"]:
    "Ovo je način plaćanja koji ćemo koristiti za buduće uplate. Možete ga promijeniti u bilo kojem trenutku.",
  ["billing.billing"]: "Naplata",
  ["billing.planAndBilling"]: "Plan i naplata",
  ["billing.paymentMethod"]: "Način plaćanja",
  ["billing.cardEndingIn"]: "%{cardType} završava na %{last4}",
  ["billing.manageBillingDetails"]: "Upravljanje detaljima naplate",
  ["billing.viewBillingDetails"]: "Pogledaj detalje naplate",
  ["billing.updatePaymentDetails"]: "Ažuriranje detalja plaćanja",
  ["billing.sendNewInvoicesTo"]: "Pošalji nove fakture na",
  ["billing.previousInvoices"]: "Prethodne fakture",
  ["billing.plan"]: "Plan",
  ["billing.manageWhichPlan"]: "Upravljaj koji plan koristi prostor",
  ["billing.standard"]: "Standardni",
  ["billing.changePlan"]: "Promijenite plan",
  ["billing.free"]: "Besplatno",
  ["billing.upgrade"]: "Unaprijedi",
  ["billing.noPaymentMethod"]: "Nema načina plaćanja",
  ["billing.thereIsNoPaymentMethod"]:
    "S ovim radnim prostorom nije povezan nijedan način plaćanja. Način plaćanja će se pojaviti ovdje čim odaberete plaćeni plan.",
  ["billing.selectAPaidPlan"]: "Odaberite plaćeni plan",
  ["billing.upgradePlan"]: "Pređi na ovaj plan",
  ["billing.downgradePlan"]: "Spusti se na ovaj plan",
  ["billing.downgradeToFree"]: "Spusti se na besplatni plan",
  ["billing.viewYourPaymentMethodInStripe"]:
    "Pogledajte svoj način plaćanja u Stripe-u",
  ["billing.weBillTheWorkspacePayment"]:
    "Naplaćujemo način plaćanja workspace-a kada se prihvati poziv.",
  ["billing.checkThePlanPanel"]:
    "Provjerite panel plana za procjenu troškova po sjedištu.",
  ["billing.12"]: "$12",
  ["billing.10"]: "$10",
  ["billing.perUserPerMonth"]: "/ korisnik / mjesec",
  ["billing.billedYearly"]: "naplaćuje se godišnje",
  ["billing.planStatus"]: "Status plana",
  ["billing.yourCurrentPlanIsNotSetToRenew"]:
    "Vašem trenutnom planu nije postavljeno automatsko obnavljanje",
  ["billing.on"]: "Na",
  ["billing.dateYourWorkspaceWillDowngrade"]:
    "Vaš radni prostor će se vratiti na besplatni plan na %{date}. Do tada još možete pozvati ljude u ovaj workspace, ali nećete moći premašiti limit od",
  ["billing.workspaceMembers"]: "članova workspace-a",
  ["billing.turnRenewalBackOn"]: "Ponovno uključite automatsko obnavljanje",
  ["billing.youCanStillInvite"]:
    "I dalje možete pozvati ljude u ovaj workspace, ali ne možete premašiti limit od",
  ["billing.workspaceFullError"]:
    "Dostignut je limit članova workspace-a. Administrator workspace-a može ga povisiti.",
  ["billing.genericJoinError"]: "Nije bilo moguće pridružiti se workspace-u.",
  ["billing.startsOn"]: "Počinje na %{date}",
  ["billing.switchToYearly"]: "Prebaci se na godišnje (-20%)",
  ["billing.switchToMonthly"]: "Prebaci se na mjesečno",
  ["billing.metadata"]: "Sve u %{plan}, plus...",
  ["billing.talkToOurExperts"]: "Razgovarajte sa našim stručnjacima",
  ["billing.samlAndScim"]: "SAML & SCIM",
  ["billing.auditLogs"]: "Evidencije revizije",
  ["billing.customBilling"]: "Prilagođeno naplaćivanje",
  ["billing.prioritySupport"]: "Prioritetna podrška",
  ["billing.unlimitedChildCards"]: "Neograničen broj child kartica",
  ["billing.publishPagesToTheWeb"]: "Objavi stranice na webu",
  ["billing.calendarLayout"]: "Raspored kalendara",
  ["billing.advancedSearch"]: "Napredna pretraga",
  ["billing.views"]: "Pogledi",
  ["billing.timelineLayout"]: "Raspored vremenske linije",
  ["billing.liveChatSupport"]: "Podrška putem chata uživo",

  // global
  ["global.text.create"]: "Kreiraj",
  ["option.label.cards"]: "Kartice",
  ["option.label.pages"]: "Stranice",
  ["option.label.boards"]: "Ploče",
  ["option.label.epics"]: "Projekti",
  ["option.label.spaces"]: "Prostori",
  ["option.label.showArchived"]: "Prikaži arhivirano",
  ["search.message.noResults"]: "Ništa nije pronađeno",
  ["global.text.discardDraft"]: "Odbaci nacrt",

  // ---------------------------------------------------

  switchAccount: "Promijeni račun",
  all: "Sve",
  searchPlaceholder: "Pretraži ili postavi pitanje...",
  replyToComment: "Odgovori na komentar...",
  join: "Pridruži se",
  couldntJoinSpace:
    "Nije moguće pridružiti se prostoru, pokušajte ponovo kasnije.",
  cardArchivedByCard: "Kartica je arhivirana.",
  cardArchivedByList:
    "Kartica je dio arhivirane liste. Premjestite je u aktivnu listu za vraćanje.",
  cardArchivedByBoard:
    "Kartica je dio arhivirane ploče. Premjestite je u aktivnu ploče za vraćanje.",
  epicArchived: "Projekt je arhiviran.",
  epicArchivedByEpic: "Projekt je arhiviran.",
  epicArchivedByList:
    "Projekt je dio arhivirane liste. Premjestite ga na aktivnu listu da biste ga vratili.",
  isArchived: "je arhivirano",
  project: "prostor",
  teamId: "ID tima",
  archiveResource: "Arhiviraj %{type}",
  restoreResource: "Vrati %{type}",
  deleteResource: "Obriši %{type}",
  deleteSuccess: "%{name} %{type} je obrisan(a)",
  archiveSuccess: "%{name} %{type} je arhivirano(a)",
  restoreSuccess: "%{name} %{type} je vraćeno(a)",
  deleteError: "Nije moguće obrisati %{name} %{type}",
  archiveError: "Nije moguće arhivirati %{name} %{type}",
  restoreError: "Nije moguće vratiti %{name} %{type}",
  addLink: "Dodaj link",
  couldntDeleteComment: "Komentar se ne može obrisati, pokušajte ponovo!",
  couldntLoadComments: "Komentari se ne mogu učitati.",
  commentOnPage: "Komentiraj na stranici",
  emailPlaceholder: "npr. yourname@yourcompany.com",
  addProject: "Dodaj prostor",
  roboto: "Roboto",
  sansserif: "Sans Serif",
  serif: "Serif",
  mono: "Mono",
  monospace: "Monospace",
  upload: "Postavi",
  paste_image_link: "Zalijepi link slike",
  embed_image: "Ugradi sliku",
  drag_and_drop: "Povuci i pusti",
  supported_files: "Podržane datoteke",
  maximum_size: "Maksimalna veličina",
  newPage: "Nova stranica",
  addNewPage: "Dodaj novu stranicu",
  attachFrom: "Priloži iz...",
  searchUnsplash: "Pretraži Unsplash",
  fullWidth: "Puna širina",
  largeText: "Veliki tekst",
  space___: "Prostor...",
  cannotExcludeAll: "Ne možete isključiti sve",
  mustIncludeAtLeastOne: "Mora da uključuje barem jedan",
  type: "Tip",
  noResultsFound: "Nisu pronađeni rezultati",
  cardStatus: "Status kartice",
  thisSpaceIsPrivate: "Ovaj prostor je privatan",
  hiddenMember: "Skriveni član",
  hiddenMemberDesc: "Ova osoba sa vama ne dijeli nijedan prostor",
  enterResourceTitle: "Unesite naslov %{type}...",
  openCardInBoard: "Otvori karticu u ploči",
  cardsAdded: "Dodate kartice",
  cardsFinished: "Završene kartice",
  cardsAddedBetween: "Jedinstvene dodane kartice između",
  cardsAddedTo: "Jedinstvene dodane kartice na",
  moreCardsAddedThanFinished:
    "%{number} više kartica je dodano nego što je završeno",
  sameNumberOfCardsAddedAndFinished: "Dodan i završen je isti broj kartica",
  moreCardsFinishedThanAdded:
    "%{number} više kartica je završeno nego što je dodano",
  oneMoreCardAddedThanFinished: "Dodata je 1 kartica više nego što je završena",
  oneMoreCardFinishedThanAdded: "Završena je 1 kartica više nego što je dodano",
  couldntResendLink: "Nije moguće ponovo poslati link za poziv.",
  thereAreNoFreeSeatsForThisWorkspace:
    "Nema slobodnih mjesta za ovaj workspace",
  thisWorkspaceCantAcceptAnyMoreMembers:
    "Ovaj workspace ne može prihvatiti više članova. Administrator workspace-a može povisiti limit, ili postojeći član može napustiti workspace kako bi otvorio mjesto.",
  links: "Linkovi",
  createNewView: "Kreiraj novi pogled",
  newView: "Novi pogled",
  workspace: "Workspace",
  views: "Pogledi",
  roadmap: "Plan rada",
  private: "Privatno",
  lastUpdate: "Posljednja izmjena",
  viewType: "Tip prikaza",
  filters: "Filteri",
  filter___: "Filtriraj...",
  filters___: "Filteri...",
  filterBy: "Filtriraj po",
  filter: "Filter",
  content: "sadržaj",
  status: "Status",
  subscriber: "pretplatnik",
  creator: "kreator",
  tag: "Tag",
  subscribers: "pretplatnici",
  creators: "kreatori",
  shareWithWorkspace: "Dijeli sa radnim prostorom",
  discard: "Odbaci",
  notificationCreated: "%{name} kreirano",
  notificationAdded: "%{name} dodano",
  typeContent: "Upiši sadržaj",
  ["global.placeholder.focusedStatePlaceholder"]:
    "@ za označavanje bilo čega, / za komande...",
  ["global.placeholder.focusedStatePlaceholderMobile"]:
    "@ za označavanje, / za komande...",
  checkListItemPlaceholder: "@ za označavanje bilo čega...",
  assignees: "Dodijeljeni",
  no_assignee: "Nema dodijeljenog",
  inThisSpace: "U ovom prostoru",
  invitationsFailed: "Slanje poziva nije uspjelo!",
  boardMovedToSpace: "Ploča premještena u prostor",
  pageMovedToSpace: "Stranica premještena u prostor",
  boardNotMoved: "Pomicanje ploče otkazano.",
  pageNotMoved: "Pomicanje stranice otkazano.",
  newTag: "Nova oznaka",
  toggleSection: "Sakrij/prikaži sekciju",
  toggleContent: "Prazna sekcija. Klikni da napišeš ili kopiraš sadržaj ovdje.",
  duplicateBoard: "Kopiraj ploču",
  duplicateBoardDescription:
    "Nijedna kartica na ovoj ploči neće biti kopirana. Odaberite prostor i naziv za kopiranu tablu.",
  boardDuplicated: "Ploča kopirana",
  boardDuplicateFailed: "Kopiranje ploče nije uspjelo",
  changeCardParent: "Promijeni roditeljsku karticu",
  changeParent: "Promijeni roditelja",
  changeParentDescription:
    "Ova kartica ima “%{card_title}” kao roditelja. Želite li promijeniti roditelja na trenutnu karticu?",
  shareToWeb: "Dijeli na webu",
  embedVideo: "Ugradi Youtube video",
  removePullRequest: "Ukloni zahtjev za spajanje",
  viewOnGitHub: "Pogledaj na GitHub-u",
  setUpGHIntegration: "Postavi GitHub integraciju",
  integrateSuperthread: "Integriši Superthread u svoj omiljeni git klijent.",
  githubIntegradionDescripiton:
    "Poveži Superthread kartice sa GitHub pull request-ovima. Uključi Superthread ID kartice (npr. ST-123) u naziv svoje grane ili naziv PR-a kako bi se automatski prikazao status PR-a u kartici.",
  connectGithub: "Poveži GitHub",
  connectedAccounts: "Povezani računi",
  integrationConnectedToSuperthread:
    "%{integrationName} povezan sa Superthread",
  enabledBy: "Omogućeno od",
  select: "Odaberi",
  github_pull_request: "GitHub",
  importBoards: "Uvezi ploče",
  selectWhichBoards: "Odaberi iz kojih ploča",
  quickImport: "Brzi uvoz",
  importBoardIntoExsistingSpace: "Prilagođeni uvoz",
  map: "Mapa",
  importAs: "Uvezi kao...",
  person1Email: "person1@example.com",
  createdDate: "Datum kreiranja",
  updatedDate: "Datum ažuriranja",
  now: "Danas",
  nowActivity: "sada",
  ["now+2d"]: "Za 2 dana",
  ["now+3d"]: "Za 3 dana",
  ["now+1w"]: "Za 1 sedmicu",
  ["now+2w"]: "Za 2 sedmice",
  ["now+3w"]: "Za 3 sedmice",
  ["now+1M"]: "Za 1 mjesec",
  ["now+2M"]: "Za 2 mjeseca",
  ["now+3M"]: "Za 3 mjeseca",
  ["now+6M"]: "Za 6 mjeseci",
  ["now+1y"]: "Za 1 godinu",
  ["now-1d"]: "Prije 1 dan",
  ["now-1h"]: "Prije 1 sat",
  ["now-4h"]: "Prije 4 sata",
  ["now-2d"]: "Prije 2 dana",
  ["now-3d"]: "Prije 3 dana",
  ["now-1w"]: "Prije 1 sedmice",
  ["now-2w"]: "Prije 2 sedmice",
  ["now-3w"]: "Prije 3 sedmice",
  ["now-1M"]: "Prije 1 mjesec",
  ["now-2M"]: "Prije 2 mjeseca",
  ["now-3M"]: "Prije 3 mjeseca",
  ["now-6M"]: "Prije 6 mjeseci",
  ["now-1y"]: "Prije 1 godinu",
  goToParentCard: "Idi na roditeljsku karticu",
  discardAndClose: "Odbaci i zatvori",
  changeStatus: "Promijeni status",
  createCardsInSelectedBoard: "Uvijek kreiraj kartice na odabranoj ploči",
  createCardIn: "Kreiraj karticu u",
  noduedate: "Nema roka",
  inviteToWorkspace: "Pozovi ljude u workspace %{workspaceName}",
  addNewBoardOrPage: "Dodaj novu ploču ili stranicu",
  spaceSettings: "Postavke prostora",
  addToFavorites: "Dodaj u favorite",
  removeFromFavorites: "Ukloni iz favorita",
  viewmoreassignees: "Pogledaj više dodijeljenih",
  noassignee: "Nema dodijeljenog",
  currentuser: "Trenutni korisnik",
  aPrivateSpace: "privatni prostor",
  youAreTheOnlyPersonInThisPrivateSpace:
    "Vi ste jedina osoba u ovom privatnom prostoru, ako napustite prostor, niko mu neće moći pristupiti. Ako vaša organizacija još uvijek treba pristup, pozovite nekoga da se pridruži prije nego što odete.",
  whenYouLeaveAPrivateSpace:
    "Kada napustite privatni prostor, više nećete moći vidjeti njegove ploče ili stranice. Da biste se ponovo pridružili, morat ćete biti ponovo pozvani.",
  youCanRejoinThePublicSpace:
    "Možete se ponovo pridružiti prostoru sa odjeljka za pregledanje prostora.",
  deleteItem: "Obriši %{item}",
  ifYouWantToDeleteSpace:
    "Ako želite obrisati ovaj prostor, upišite njegovo ime ispod.",
  unsubscribedFromResourceUpdates: "Odjavljen od ažuriranja %{name}",
  subscribingToResourceUpdatesFailed:
    "Pretplata na ažuriranja %{name} nije uspjela",
  unsubscribingFromResourceUpdatesFailed:
    "Odjava od ažuriranja %{name} nije uspjela",
  editStatus: "Uredi status",
  editName: "Uredi ime",
  numberOfCards: "Broj kartica",
  viewSpace: "Pogledaj prostor",
  deleted: "%{name} obrisan",
  leaveNamedSpace: "Napusti prostor %{name}?",
  leaveNamedPrivateSpace: "Napusti privatni prostor %{name}?",
  deleteAndLeaveNamedPrivateSpace: "Obriši i napusti privatni prostor %{name}?",
  youLeftNamedSpace: "Napustili ste prostor %{name}.",
  youCannotLeaveTheSpace: "Ne možete napustiti ovaj prostor",
  enableScrollFocus: "Prikaži trenutni stavku u bočnoj traci",
  addNewFolder: "Kreiraj datoteku",
  deletedSuccesfully: "uklonjena iz favorita",
  addedSuccesfully: "dodana u favorite",
  changedParentCardFrom: "promijenjena roditeljska kartica sa",
  addChildPage: "Dodaj podstranicu",
  reaction: "Reakcija",
  unresolved: "Nerješeno",
  unresolve: "Poništi rješavanje",
  unresolvedOnly: "Samo neriješeno",
  resolved: "Riješeno",
  unresolveComment: "Poništi rješavanje komentara",
  resolveComment: "Riješi komentar",
  commentResolved: "Komentar riješen",
  commentUnresolved: "Komentar neriješen",
  resolvedOnly: "Samo riješeno",
  allComments: "Svi komentari",
  noUnresolvedComments: "Nema neriješenih komentara",
  noResolvedComments: "Nema riješenih komentara",
  noComments: "Nema komentara",
  about: "O nama",
  markAsRead: "Označi kao pročitano",
  markAsUnread: "Označi kao nepročitano",
  markAllAsResolved: "Označi sve kao riješeno",
  showUnresolved: "Prikaži neriješeno",
  showResolved: "Prikaži riješeno",
  noNotifications: "Nema obavijesti",
  noNewNotifications: "Nema novih obavijesti",
  noUnresolvedNotifications: "Nema neriješenih obavijesti",
  youCanShow: "Možete prikazati",
  notificationsInstead: "obavijesti umjesto toga",
  subscribeToGetNotifications:
    "Pretplatite se na nešto i dobit ćete obavijesti kada ima aktivnosti",
  selectANotificationToViewIt: "Odaberite obavijest da biste je pregledali",
  youCanMarkANotificationAs: "Možete označiti obavijest kao",
  unreadOr: "nepročitano ili",
  resolveIt: "riješi",
  inboxNotificationsAreUnresolved:
    "Obavijesti su „neriješene“ ako ih niste označili kao riješene",
  notificationsAreNew: "Obavijesti su „nove“ ako ih ranije niste vidjeli",
  wantNotificationsIn: "Želite obavijesti u",
  slaskQuestionMarkVisit: "Slack? Posjetite",
  noCardsMatchChosenFilter:
    "Trenutno nema kartica koje odgovaraju odabranim filterima",
  noCardsFound: "Nije pronađena nijedna kartica",
  boardMoved: "Ploča premještena",
  pageMoved: "Stranica premještena",
  openPage: "Otvori stranicu",
  hasBeenDeleted: "je obrisano",
  deletedResourcePlain: "Ovaj resurs je obrisan.",
  deletedResourceWithName: "Ovaj %{name} je obrisan.",
  this: "Ovo",
  andTheEntire: "i cijeli",
  youWereRemoved: "Uklonjeni ste",
  fromPrivateSpace: "iz privatnog prostora",
  privateSpaceDesc:
    "Ovaj prostor je privatni pa više ne možete vidjeti njegovo ime ili sadržaj",
  privateSpace: "Privatni prostor",
  everything: "Sve",
  moveCardIntoBoard: "Kartica premještena u ploču",
  inList: "u listi",
  searchForParentCard: "Pretraži roditeljsku karticu",
  custom: "Prilagođeno",
  moveToBoard: "Premjesti u ploču",
  previous: "Prethodno",
  manualOrder: "Ručni redoslijed",
  sortedBy: "Sortirano po",
  toCancelDrag: "za poništavanje povlačenja",
  groupBy: "Grupiraj po",
  subpageCreated: "Podstranica kreirana",
  tableOfContents: "Sadržaj",
  editWorkspaceTagsInSettings: "Uredi oznake workspace-a u postavkama",
  sideDocked: "Bočno priključeno",
  modalOverlay: "Modalni prekrivač",
  cardLayout: "Raspored kartica",
  switchLayout: "Promijeni raspored",
  showSidebar: "Prikaži bočnu traku",
  notags: "Nema oznaka",
  resetLayoutToBoardDefault: "Vrati raspored na zadani raspored ploče",
  alreadyOpen: "%{resource} je već otvoren",
  defaultBoardLayout: "Zadani raspored ploče",
  defaultBoardLayoutDescription:
    "Svi će vidjeti ovaj raspored po defaultu. Ova postavka se može kasnije promijeniti.",
  boardDescription: "Kartice su grupirane u kolone",
  listDescription: "Kartice su u vertikalnoj listi, podijeljene u grupe",
  timelineDescription:
    "Vremenska linija zasnovana na početnim i krajnjim datumima.",
  calendarDescription: "Kartice su postavljene na svoj zadani rok",
  boardName: "Naziv ploče",
  memberRemoved: "Član uklonjen",
  resetLayoutToViewDefault: "Vrati redoslijed na zadani",
  earliestDueDate: "Najraniji rok",
  highestPriority: "Najviši prioritet",
  largestEstimate: "Najveća procjena",
  STIsMostUseful: "Superthread je najkorisniji kada radite s drugima.",
  readOnly: "Samo čitanje",
  removeBoard: "Ukloni ploču",
  noSprints: "Ciklusi će biti navedeni ovdje od najnovijeg do najstarijeg",
  noNonSprintBoardsInThisSpace: "Nema ne-ciklus ploča u ovom prostoru",
  inviteToWorkspaceDescription:
    "Da biste dodali postojeće članove u workspace, idite na postavke workspace-a",
  alreadyMembersOfWorkspace:
    "Neki ljudi su već u workspace-u. Biće dodati u sve relevantne prostore odabrane ispod.",
  information: "Informacije",
  success: "Uspjeh",
  error: "Greška",
  warning: "Upozorenje",
  typeSomething: "Ukucajte nešto...",
  childCards: "Child kartice",
  preferences: "Postavke",
  lastCreated: "Zadnje kreirano",
  lastUpdated: "Zadnje ažurirano",
  searchMembers: "Pretraži članove",
  or: "Ili",
  add_collaborators: "Dodaj saradnike",
  selectWorkspace: "Odaberi workspace",
  selectWorkspaceIntegrations: "Odaberi workspace za integraciju",
  change: "Promijeni",
  createNewWorkspace: "Kreiraj novi workspace",
  notSeeingYourWorkspace:
    "Ne vidite svoj workspace? Pokušajte promijeniti svoju email adresu:",
  dismiss: "Odustani",
  load: "Učitaj",
  youAlreadyHave: "Već imate",
  openBoard: "Otvori ploču",
  cardCannotBeMovedDirectlyToSpace:
    "Kartica se ne može direktno premjestiti u prostor.",
  clickToRename: "Kliknite za preimenovanje",
  info: "Info",
  clearAllFilters: "Očisti sve filtere",
  is: "je",
  is_not: "nije",
  includes: "uključuje",
  excludes: "isključuje",
  print: "Štampaj",
  reactedWith: "reagovao sa",
  you: "vi",
  updateAppToEditPage: "Molimo ažurirajte aplikaciju za uređivanje stranice",
  updateAppToEditComment:
    "Molimo ažurirajte aplikaciju za uređivanje komentara",
  updateAppToEditCard: "Molimo ažurirajte aplikaciju za uređivanje kartice",
  jiraBoardMapingSubtitle: "Odaberite koje ploče iz Jire želite uvesti.",
  trelloBoardMapingSubtitle: "Odaberite koje ploče iz Trella želite uvesti.",
  shortcutBoardMapingSubtitle:
    "Odaberite timove i tokove rada iz kojih želite uvesti priče.",
  jiraQuickImportText:
    "Svi timovi će biti uvezeni u prostor nazvan 'jira-import', možete lako preimenovati i reorganizovati svoje ploče odatle.",
  trelloQuickImportText:
    "Svi timovi će biti uvezeni u prostor nazvan 'trello-import', možete lako preimenovati i reorganizovati svoje ploče odatle.",
  shortcutQuickImportText:
    "Svaka ploča 'team-workflow' će biti uvezena u prostor nazvan 'shortcut-import', možete lako preimenovati i reorganizovati svoje ploče odatle.",
  jiraCustomImportText:
    "Odaberite koje ploče želite uvesti i u koje prostore treba da budu uvezene.",
  trelloCustomImportText:
    "Odaberite koje ploče želite uvesti i u koje prostore treba da budu uvezene.",
  shortcutCustomImportText:
    "Odaberite 'team-workflow' ploče koje želite uvesti i u koje prostore treba da budu uvezene.",
  projectsCannotBeMovedToSpaces: "Projekti se ne mogu premjestiti u prostore",
  founder: "Osnivač",
  director: "Direktor",
  teamLead: "Vođa tima",
  individualContributor: "Individualni doprinosilac",
  softwareEngineering: "Softversko inženjerstvo",
  design: "Dizajn",
  productManagement: "Upravljanje proizvodima",
  marketing: "Marketing",
  finance: "Finansije",
  development: "Razvoj",
  marketer: "Marketar",
  sales: "Prodaja",
  clickToView: "Kliknite za pregled",
  clickToDownload: "Kliknite za preuzimanje",
  business: "Poslovanje",
  pickAllThatApply: "Odaberite sve što se odnosi",
  pickOne: "Odaberite jedan",
  customerSupport: "Korisnička podrška",
  humanResources: "Ljudski resursi",
  socialMedia: "Društveni mediji",
  wordOfMouth: "Preporuka",
  searchEngine: "Pretraživač",
  advertising: "Oglašavanje",
  searchForSpaceOrBoard: "Pretraži prostor ili ploču",
  starTypingToSearchFor: "Počnite kucati da biste pretražili",
  ["myWorkNoResults.created"]: "Nema kartica koje ste vi kreirali",
  ["myWorkNoResults.assigned"]: "Nema kartica dodijeljenih vama",
  ["memberNoResults.assigned"]: "Nema kartica dodijeljenih %{userName}",
  ["memberNoResults.created"]: "Nema kartica koje je kreirao %{userName}",
  addedCommentHiddenByFilter: "Dodani komentar je sakriven filterom",
  createdCardHiddenByFilter: "Kreirana kartica može biti sakrivena filterom",
  viewWork: "Pogledaj rad",
  removeFromSpace: "Ukloni iz prostora",
  assignedInThisBoard: "Dodijeljeno u ovoj ploči",
  layout: "Izgled",
  createdCardMovedSortOrder:
    "Kreirana kartica može biti premještena sortiranjem",
  createCardGroupBy: "Kartica dodana u %{list}.",
  canNotMoveCardInsameBoard: "Kartica se ne može premjestiti u istu ploču.",
  latestReply: "Najnoviji odgovor",
  replyLabel: "Odgovor",
  totalReplies: "ukupno odgovora",
  olderReplies: "stariji odgovori",
  leaveReply: "Napišite odgovor...",
  hideReplies: "Sakrij odgovore",
  showReplies: "Prikaži odgovore",
  oneReply: "odgovor",
  discardComment: "Odustani od komentara?",
  areYouSureYouWantToDiscard:
    "Jeste li sigurni da želite odustati od komentara?",
  skipToEnd: "Preskoči na kraj",
  priority: "Prioritet",
  noPriority: "Bez prioriteta",
  urgent: "Hitno",
  high: "Visok",
  medium: "Srednji",
  low: "Nizak",
  priorities: "Prioriteti",
  changedThePriorityFrom: "promijenio prioritet sa",
  changedTheEstimateFrom: "promijenio procjenu sa",
  setThePriorityTo: "postavio prioritet na",
  setTheEstimateTo: "postavio procjenu na",
  removedTheEstimate: "uklonio procjenu",
  thereAreNoPages:
    "Nema stranica u ovom prostoru. Kreirajte novu stranicu ili prevucite postojeću stranicu u ovaj prostor u bočnoj traci.",
  thereAreNoBoards:
    "Nema ploča u ovom prostoru. Kreirajte novu ploču ili prevucite postojeću ploču u ovaj prostor u bočnoj traci.",
  commentsOnly: "Samo komentari",
  activityOnly: "Samo aktivnost",
  seeCardsWithThisTag:
    "Pogledajte kartice s ovom oznakom (broj uključuje kartice koje se možda neće prikazati drugdje)",
  noResultsForThatName: "Nema rezultata za to ime",
  youCan: "Možete",
  createASpace: "kreiraj prostor",
  named: 'nazvan "%{query}"',
  estimate: "Procjena",
  onePoint: "1 bod",
  numberOfPoints: "%{num} bodova",
  extraSmall: "Ekstra mali",
  small: "Mali",
  mediumSize: "Srednji",
  large: "Veliki",
  extraLarge: "Ekstra veliki",
  noEstimate: "Bez procjene",
  settingsProjectsPreferencesSubtitle:
    "Ova podešavanja će uticati na sve članove prostora",
  howCardsAreEstimated: "Kako se procjenjuju kartice u ovom prostoru",
  disableCardEstimationForThisSpace: "Onemogući procjenu",
  fibonacciPoints: "Fibonacci tacke",
  exponentialPoints: "Eksponencijalne tacke",
  tshirtSizes: "Veličine majica",
  setEstimate: "Postavi procjenu",
  emailNotificationHelperText:
    "Email svakog radnog dana sa obavijestima koje niste vidjeli od posljednjeg emaila",
  estimated: "procijenjeno",
  cardSpaceEstimationTurnedOff:
    "Ova kartica pripada workspace-u s isključenom procjenom",
  totalEstimatePointsTooltipContent:
    "%{totalPoints} procijenjeno kroz %{numOfCards}",
  estimates: "procjene",
  assignItTo: "dodijeli",
  searchForACard: "Pretraži karticu",
  createACard: "Kreiraj karticu",
  archivedCardsAreHidden: "arhivirane kartice su sakrivene",
  enterANameAbove: "Unesite ime iznad",
  chooseFiltersYouWouldLike:
    "Zatim odaberite filtere koje želite u traci filtera",
  cannotCreateViewOnMobile: "Ne možete kreirati prikaz na mobilnom uređaju.",
  viewCardInBoard: "Pogledaj karticu na vlastitoj ploči",
  guestsMustBeAddedToOneSpace:
    "Gosti moraju biti dodani na barem jedan prostor",
  createCard: "Kreiraj karticu",
  suggestedBasedOnTitle: "Predloženo na osnovu naslova",
  acceptSuggestion: "Prihvati prijedlog",
  rejectSuggestion: "Odbij prijedlog",
  suggestionPlaceholderText: "Prijedlog...",
  changeEmail: "Promijeni email",
  logOutAndContinue: "Odjavi se i nastavi",
  confirmAccountOwnership: "Potvrdi vlasništvo računa",
  reauthenticateEmailDescription:
    "Da bismo zaštitili vaš račun, morate se ponovo prijaviti na aplikaciju. Nakon prijave, moći ćete odabrati novu email adresu i završiti proces.",
  enterANewEmail: "Unesite novu email adresu:",
  resendLoginCode: "Pošalji ponovo kod za prijavu",
  emailAddressTakenByAnotherUser: "Email adresa zauzeta od drugog korisnika",
  assistant: "Asistent",
  changeTone: "Promijeni ton",
  simplify: "Pojednostavi",
  summarize: "Sumiraj",
  translate: "Prevedi",
  generate: "Generiraj",
  replaceText: "Zamijeni tekst",
  insertBelow: "Umetni ispod",
  assistanceWith: "S čim vam treba pomoć?",
  copiedToClipboard: "Kopirano u međuspremnik",
  academic: "Akademski",
  casual: "Neformalno",
  confident: "Siguran",
  friendly: "Prijateljski",
  neutral: "Neutralno",
  professional: "Profesionalno",
  aiFeatures: "AI funkcije",
  emailDigestSentAt: "Email sažetak poslan u",
  inYourTimezone: "u vašoj vremenskoj zoni (%{timezone})",
  enableNotificationsFirst: "Prvo omogući %{type} obavijesti",
  turnOnAIAssitantInFormatingToolbar:
    "Uključi AI asistenta u alatnoj traci za formatiranje teksta",
  superthreadSendingDataTo:
    "Imajte na umu da omogućavanjem ovoga za svoj radni prostor pristajete da Superthread šalje podatke na",
  experimentalFeatureMayChangeFunctionality:
    "Ova eksperimentalna funkcija može biti podložna promjenama u funkcionalnosti i cijenama.",
  contactUsToEnable: "Kontaktirajte nas da biste omogućili ovu funkciju.",
  boardOpenedInTheBackground: "Ploča %{boardTitle} otvorena u pozadini",
  resetFilters: "Resetiraj filtere",
  ["create_space.title"]: "Kreiraj prostor",
  ["create_space.tooltip"]: "Kreiraj dom za rad svog tima",
  ["create_private_space.title"]: "Kreiraj privatni prostor",
  ["create_private_space.tooltip"]:
    "Samo ljudi koje pozovete mogu vidjeti privatni prostor",
  ["invite_user.title"]: "Pozovi nekoga drugog",
  ["invite_user.tooltip"]:
    "Pozovi svoje kolege u radni prostor kako bi mogli pratiti svoj rad",
  ["mention_anything.title"]: "Spomeni nešto",
  ["mention_anything.tooltip"]:
    "Koristite znak @ da spomenete nešto, bilo gdje gdje možete pisati",
  ["add_child_card.title"]: "Dodaj child karticu",
  ["add_child_card.tooltip"]:
    "Child kartice vam pomažu da podijelite posao na manje zadatke",
  ["visit_inbox.title"]: "Provjeri svoju pristiglu poštu",
  ["visit_inbox.tooltip"]:
    "Pratite sve na što ste pretplaćeni u pristigloj pošti",
  ["move_page.title"]: "Premjesti stranicu",
  ["move_page.tooltip"]:
    "Povucite stranicu na bočnoj traci da je premjestite gdje god želite",
  ["create_subpage.title"]: "Kreiraj podstranicu",
  ["create_subpage.tooltip"]:
    "Podstranice se nalaze unutar drugih stranica i pomažu vam da strukturirate svoje dokumente",
  ["add_page_icon.title"]: "Dodaj ikonu stranice",
  ["add_page_icon.tooltip"]:
    "Ikona stranice pomaže vam da pronađete stranicu ponovo u pretraživanju i bočnoj traci",
  ["add_page_cover.title"]: "Dodaj sliku naslovnice stranice",
  ["add_page_cover.tooltip"]: "Postavite ton za stranicu sa slikom naslovnice",
  ["quick_card_shortcut.title"]: "Prečica za brzu karticu (C)",
  ["quick_card_shortcut.tooltip"]:
    "Dodirnite tipku C bilo gdje da kreirate karticu",
  ["quick_page_shortcut.title"]: "Prečica za brzu stranicu (P)",
  ["quick_page_shortcut.tooltip"]:
    "Dodirnite tipku P bilo gdje da kreirate stranicu",
  ["create_card.title"]: "Kreiraj karticu",
  ["create_card.tooltip"]:
    "Kreirajte karticu za svaki zadatak koji želite pratiti",
  ["comment_on_card.title"]: "Komentiraj karticu",
  ["comment_on_card.tooltip"]:
    "Pišite ažuriranja ili zapišite svoje misli na karticu",
  ["search_shortcut.title"]: "Pronađi nešto sa ⌘+K",
  ["search_shortcut.tooltip"]:
    "Brzo otvorite univerzalno pretraživanje bilo gdje s ovom prečicom",
  ["create_board.title"]: "Kreiraj ploču",
  ["create_board.tooltip"]: "Pratite rad podtima ili projekta",
  ["upload_avatar.title"]: "Učitaj avatar",
  ["upload_avatar.tooltip"]: "Pomozite ljudima da vas prepoznaju u aplikaciji",
  ["create_page.title"]: "Kreiraj stranicu",
  ["create_page.tooltip"]: "Zabilježite znanje i misli sa stranicama",
  ["set_your_name.title"]: "Postavi svoje ime",
  ["set_your_name.tooltip"]: "Vaše ime će se koristiti u cijeloj aplikaciji",
  aCardMustHaveATitle: "Kartica mora imati naslov",
  showAll: "Prikaži sve",
  showLess: "Prikaži manje",
  hideEmptyGroups: "Sakrij prazne grupe",
  showAnotherAssignee: "Prikaži drugog zaduženog",
  showAnotherTags: "Prikaži druge oznake",
  spaceMembers: "Članovi prostora",
  addExistingMembers: "Dodaj postojeće članove",
  inviteNewMembers: "Pozovi nove članove",
  spaceDetails: "Detalji prostora",
  makeBoardFullWidth: "Postavi ploču na cijelu širinu",
  askAiAssistantSearch: "Pitajte AI na osnovu vaših kartica i stranica",
  backToSearchResults: "Nazad na rezultate pretrage",
  sources: "Izvori",
  askAiQuestionLong: "Pitanje treba imati najmanje 10 znakova.",
  spaceSprintsSettings: "Postavke ciklusa prostora %{space}",
  turnOnSprintsForThisSpace: "Uključi cikluse za ovaj prostor",
  turnOnSprintsDesc:
    'Odjeljak "Ciklusi" će biti dodan na bočnu traku za ovaj prostor. Ciklus je ploča sa početnim i završnim datumom. Kada se jedan ciklus završi, sljedeći će automatski početi.',
  ownersAdminsCanTurnOnSprints:
    "Samo vlasnici radnog prostora, administratori i kreator prostora mogu uključiti cikluse",
  sprintLength: "Dužina ciklusa",
  weeks: "sedmice",
  sprintStartOn: "Ciklusi počinju",
  coolDownPeriod: "Cooldown period između ciklusa",
  coolDownPeriodDesc:
    "Cooldown period će biti dodan između svakog ciklusa. Oni su korisni za npr. retrospektive i aktivnosti čišćenja.",
  coolDownPeriodLength: "Dužina cooldown perioda",
  sprintBoardStatuses: "Status ciklus ploče",
  sprintBoardStatusesDesc:
    'Svaka ciklus ploča u ovom prostoru koristi iste statuse. Morate imati barem jedan od svakog tipa statusa. Tip statusa "Backlog" nije dostupan.',
  addStatus: "Dodaj status",
  dueInDays: "Rok za %{days} dana",
  sprints: "Ciklusi",
  addSprint: "Dodaj ciklus",
  sprint: "Ciklus",
  openSprint: "Otvori ciklus",
  renameSprint: "Preimenuj ciklus",
  markAsComplete: "Označi kao završen",
  changeSprintDates: "Promijeni datume ciklusa",
  changeSprintDatesFor: "Promijeni datume za %{sprintName}",
  cancelSprint: "Otkaži ciklus",
  changeDates: "Promijeni datume",
  chooseNewStartAndEndDates:
    "Odaberite novi datum početka ili završetka za %{sprintName}",
  renameSprintDescription: "Unesite novo ime za ciklus.",
  startDateIsEarlierThanPreviousEndDate:
    "Datum početka se preklapa s datumom završetka prethodnog ciklusa",
  enterSprintName: "Unesite ime ciklusa",
  cancelSprintWarning:
    "Sve nezavršene kartice na ovoj ploči će biti premještene u status otkazan.",
  dontCancel: "Ne otkazuj",
  sprintSettings: "Postavke ciklusa",
  macArm64Label: "Apple Silicon",
  macx64Label: "Apple Intel",
  mailCopiedToClipboard: "Pošta kopirana u međuspremnik.",
  cardsWithNoSprint: "Kartice bez ciklusa",
  showCardsFrom: "Prikaži kartice od",
  yourColor: "Vaša boja",
  thisColorWillHelp:
    "Ova boja će pomoći drugima da vas identifikuju na nekim mjestima.",
  logo: "Logo",
  upgradePublicPageIndexingTitle: "Nadogradi za indeksiranje pretraživača",
  upgradePublicPageIndexingDescription:
    "Možete uključiti indeksiranje pretraživača na plaćenom planu.",
  coolDown: "Cooldown",
  noBoardsOrPages: "Nema ploča ili stranica",
  usersWork: "%{name}'s rad",
  renameAttachment: "Preimenuj prilog",
  timelineLayoutDescription:
    "Nadogradite svoj plan radnog prostora da biste koristili raspored vremenske linije.",
  upgradeViewsDescription:
    "Nadogradite svoj plan radnog prostora da biste sačuvali poglede.",
  createNewItem: "Kreiraj novi stavku",
  spaceLimitReached:
    "Dosegnut je limit prostora. Možete obrisati neke workspace-a da biste kreirali više.",
  freePlanUsageLimits: "Granice korištenja besplatnog plana",
  item: "Stavka",
  usage: "Korištenje",
  limitReachedLong:
    "Ako se dostigne limit, morat ćete ukloniti stavke ili nadograditi plan prije nego što možete kreirati nove stavke.",
  limitReached: "Limit dosegnut",
  uploadFailedClickToRetry:
    "Učitavanje nije uspjelo, kliknite za ponovni pokušaj",
  actionFailed: "Akcija nije uspjela",
  createAndManageSpaces: "Kreiraj i upravljaj prostorima",
  thereAreNoListInBoard: "Nema listi u ploči.",
  pageMovedToParent: "Stranica premještena na roditelja",
  subscribedToResourceUpdates: "Pretplaćen na ažuriranja %{name}",
  thisFilterDoesNotMatch: "Ovaj filter trenutno ne odgovara nijednoj kartici",
  inviteSectionSubtitle:
    "Oni će biti pozvani na cijeli prostor, a ne samo na ovaj workspace.",
  invitingPeopleToWorkspace:
    "Samo administratori mogu pozvati nove ljude u ovaj workspace",
  addView: "Kreiraj pogled",
  timeCreatedSort: "Vremenu kreiranja",
  timeUpdatedSort: "Vremenu ažuriranja",
  dueDateSort: "Najranijem roku",
  createdViaEmailFrom: "kreirano putem e-maila od",
  couldNotBeVerified: "Nije moguće provjeriti",
  createCardsViaEmailTitle: "Kreiraj kartice u ovoj ploči putem e-maila",
  createCardsViaEmailDescription:
    "Kreiraj karticu u ovoj ploči ako neko pošalje poruku na e-mail adresu.",
  onlyCurrentAddressWillWork: "Samo trenutna adresa će raditi.",
  regenerate: "Regeneriraj",
  emailCopiedToClipboard: "E-mail kopiran u međuspremnik",
  emailRegenerated: "E-mail uspješno regeneriran",
  slackChannelNotifications: "Slack obavijesti za kanal",
  slackChannelNotificationsTitle:
    "Šaljite obavijesti o karticama na ovoj tabli u Slack kanal",
  slackChannelNotificationsDescriptionDisabled:
    "Otvorit će se Slack prozor i zatražiti da odaberete kanal",
  slackChannelNotificationsDescriptionEnabled:
    "Obavijesti s ove table se šalju na %{channel} u Slacku.",
  slackIntegrationError:
    "Nije moguće omogućiti integraciju sa Slackom. Molimo pokušajte ponovo",
  boardDoesNotExists: "Ta tabla ne postoji",
  boardActivity: "Aktivnost table",
  sendTo: "Pošalji na",
  slackPrivateMessage: "privatna poruka",
  slackPrivateGroup: "privatni razgovor",
  slackPrivateChannel: "privatni kanal",
  webhookNotificationCardAddedBoard: "Kartica dodana/premještena na ploču",
  webhookNotificationCardAddedList: "Kartica dodana/premještena u status",
  webhookNotificationCardCommented:
    "Komentar ostavljen na kartici u ploči (bez odgovora)",
  webhookNotificationCardDueDate: "Datum dospijeća kartice je uskoro/prošao",
  folder: "Datoteka",
  yourSpaces: "Vaši prostori",
  quoteReply: "Citiraj i odgovori",
  itemHasBeenDeleted: "%{resourceType} je izbrisana",
  deletedNotification: "Izbrisana",
  try: "Probajte",
  ["add_workspace_logo.title"]: "Dodaj logo workspace-u",
  ["add_workspace_logo.tooltip"]: "Učitaj logo",
  ["customise_your_profile.title"]: "Prilagodi svoj profil",
  ["customise_your_profile.tooltip"]: "Dodaj profilnu sliku",
  ["import_tasks.title"]: "Uvezi zadatke",
  ["import_tasks.tooltip"]: "Trello, Jira ili Shortcut uvoz",
  ["view_keyboard_shortcuts.title"]: "Pogledaj prečice na tastaturi",
  ["view_keyboard_shortcuts.tooltip"]:
    "Otvorite pomoćnik za prečice na tastaturi",
  ["connect_slack.title"]: "Poveži Slack",
  ["connect_slack.tooltip"]: "Uključi Slack obavještenja",
  seeAllWorkspaces: "Pregledaj sve radne prostore",
  workspaceSettings: "Postavke radnog prostora",
  switchToRecentWorkspace: "Prebacite se na nedavni radni prostor",
  icon: "Ikona",
  addToSprint: "Dodaj u ciklus",
  addToProject: "Dodaj u projekt",
  goToProject: "Idi na projekt",
  addTags: "Dodaj oznake",
  cancelled: "Otkazano",
  sprintBoards: "Ciklus ploče",
  sprintSettingsBoardsDescription:
    "Postavke ovdje se primjenjuju na sve ciklus ploče u ovom prostoru",
  addedCard: "Dodana kartica",
  removedCard: "Uklonjena kartica",
  addNewCard: "Dodaj novu karticu",
  addExistingCard: "Dodaj postojeću karticu",
  changeEpicOrParent: "Promijeni projekt ili roditelja",
  cardAlreadyHasEpicOrParent:
    "Odabrana kartica već ima projekt ili roditeljsku karticu. Oni će biti promijenjeni ako je dodate ovom projektu.",
  changeEpic: "Promijeni projekt",
  childCardIsPartOfEpic: 'Dječija kartica je dio projekta "%{epicName}".',
  parentCardHasNoEpic: "Roditeljska kartica nema projekt.",
  parentCardIsPartOfEpic: 'Roditeljska kartica je dio projekta "%{epicName}".',
  childCardsEpicWillBeRemoved:
    "Projekt dječije kartice će biti uklonjen ako nastavite.",
  childCardsEpicWillChangeToParents:
    "Projekt dječije kartice će se promijeniti u projekt roditeljske kartice ako nastavite.",
  removeEpic: "Ukloni projekt",
  epicWillNoLongerBeAssociated:
    'Dječija kartica više neće biti povezana s projektom "%{epicName}" ako je uklonite iz roditeljske kartice.',
  childCardAlreadyHasParent:
    "Dječija kartica već ima roditelja. Roditelj će biti promijenjen u ovu karticu ako nastavite.",
  cardsDirectlyAddedToEpicCantHaveParent:
    "Kartice dodane direktno u projekte ne mogu imati roditeljske kartice",
  epicNoTagsFound:
    "Nema pronađenih oznaka. Projekti mogu koristiti samo oznake radnog prostora.",
  cannotChangeStatusForCardsInFinishedSprint:
    "Ne možete promijeniti status kartica u završenom ciklusu.",
  cannotChangeStatusForArchivedCards:
    "Ne možete promijeniti status arhiviranih kartica.",
  cantMoveArchivedCardToSprint:
    "Ne možete premjestiti arhiviranu karticu u ciklus.",
  relatedTo: "Povezano sa",
  changePriority: "Promijeni prioritet",
  changeEstimate: "Promijeni procjenu",
  changeTags: "Promijeni oznake",
  changeSprint: "Promijeni ciklus",
  goToSprint: "Idi na ciklus",
  pastSprints: "Prošli ciklusi",
  currentAndPlannedSprints: "Trenutni i planirani ciklusi",
  seeAllSprints: "Pogledaj sve cikluse",
  currentAndNextSprint: "Trenutni i sljedeći ciklus",
  branchSpecificAutomationAddFailed:
    "Nije uspjelo dodavanje nove automatske radnje specifične za granu.",
  branchSpecificAutomationUpdateFailed:
    "Nije uspjelo ažuriranje automatske radnje specifične za granu.",
  branchSpecificAutomationRemoveFailed:
    "Nije uspjelo uklanjanje automatske radnje specifične za granu.",
  thereAreNoCurrentOrPlannedSprints: "Nema trenutnih ili planiranih ciklusa",
  thereIsNoCurrentOrNextSprint: "Nema trenutnog ili sljedećeg ciklusa",
  movedCardFrom: "Premještena kartica iz",
  movedEpicFrom: "Premješten projekt iz",
  rolledCardFrom: "Prebačena kartica iz",
  sprintMarkedAsCompleted: "Ciklus označen kao završen",
  sprintMarkedAsCancelled: "Ciklus označen kao otkazan",
  cardIsParent: "Kartica je roditelj",
  cardIsChild: "Kartica je dijete",
  cardIsRelated: "Kartica je povezana",
  parentCard: "Roditeljska kartica",
  moveTo: "Pomjeri u...",
  pageMovedTo: "Stranica pomjerena u",
  thisSpaceIsEmpty: "Ovaj prostor je prazan",
  createSomethingToGetStarted: "Kreirajte nešto da biste počeli",
  visualiseYourWorkflow:
    "Vizualizirajte svoj radni proces, pratite rad i organizujte stvari",
  captureImportantInformation:
    "Zabilježite važne informacije, surađujte s drugima i podijelite na web",
  organiseWorkIntoSprints:
    "Organizujte rad u vremenske periode kako biste lakše planirali",
  filterYourWorkspaceToCreateViews:
    "Filtrirajte svoj workspace da biste kreirali poglede i podijelili ih s timom",
  turnOnSprints: "Uključi cikluse",
  cardViews: "Pogledi kartica",
  convert: "Pretvori",
  convertCardToEpic: "Pretvori karticu u projekt",
  couldNotConvertCardToEpic: "Nije moguće pretvoriti karticu u projekt",
  cardSuccessfullyConvertedToEpic: "Kartica uspješno pretvorena u projekt",
  convertedCardWillLose:
    "Ako pretvorite ovu karticu u projekt, izgubit će svoje %{arr, list}.",
  convertedThisCardToEpic: "pretvorio ovu karticu u projekt",
  spaceLevelTags: "oznake na nivou prostora",
  effortEstimate: "procjena napora",
  existingEpic: "postojeći projekt",
  roadmapMustHaveAtLeastOneStatus: "Plan rada mora imati barem jedan status",
  chosenPageIsAlreadySubpage:
    "Odabrana stranica je već podstranica trenutne stranice",
  searchForResults: "Pretražite za prikaz rezultata",
  parentCardIs: "Roditeljska kartica je...",
  projectIs: "Projekt je...",
  convertedTo: "pretvoreno u",
  moveToCompletedSprint: "Pomjeri u završeni ciklus?",
  onlyDoneCardsCanBeMovedToCompletedSprint:
    'Samo "Završene" kartice mogu se premjestiti u završeni ciklus. Ova kartica će biti promijenjena u "Završeno" i premještena.',
  removeCardFromProject: "Ukloni karticu iz projekta",
  roadmapOpenedInTheBackground: "Plan rada otvoren u pozadini",
  unfavouriteCurrentSprint: "Ukloni iz omiljenih trenutni ciklus",
  favouriteCurrentSprint: "Dodaj u omiljene trenutni ciklus",
  unfavouriteNextSprint: "Ukloni iz omiljenih sljedeći ciklus",
  favouriteNextSprint: "Dodaj u omiljene sljedeći ciklus",
  unfavouriteSprintName: "Ukloni iz omiljene %{sprintName}",
  favouriteSprintName: "Dodaj u omiljene %{sprintName}",
  currentSprint: "Trenutni ciklus",
  parentWillBeRemovedIfAddToProject:
    "Roditeljska kartica bit će uklonjena ako dodate ovu karticu projektu, jer kartice nasljeđuju projekte od roditeljskih kartica",
  cannotArchiveCardFromSprint: "Ne mogu arhivirati karticu iz ciklusa",
  sprintCompleted: "Završen ciklus",
  sprintCancelled: "Otkazan ciklus",
  sprintDatesChanged: "Datumi ciklusa promijenjeni",
  myWorkAndNotes: "Moj rad i bilješke",
  ["myWork.notes"]: "Bilješke",
  tidyUp: "Očisti",
  convertTo: "Pretvori u...",
  newNote: "Nova bilješka",
  searchNotes: "Pretraži bilješke...",
  favouriteNote: "Dodaj u omiljene bilješke",
  archiveNote: "Arhiviraj bilješku",
  deleteNote: "Obriši bilješku",
  original: "Original",
  tidied: "Očišćeno",
  untitledNote: "Bilješka bez naslova",
  enhanced: "Unaprijeđeno",
  minimize: "Minimiziraj",
  maximize: "Maksimiziraj",
  createNewNote: "Kreiraj novu bilješku",
  youDontHaveAnyNotes: "Nemate nijednu bilješku",
  transcript: "Transkripcija",
  assignedCards: "Dodijeljene kartice",
  createdCards: "Kreirane kartice",
  noTranscriptAvailable: "Transkripcija nije dostupna",
  enhanceNotesUsingMacApp:
    "Superthread može uraditi audio transkripciju vaših sastanaka kako bi generisao poboljšane bilješke. Transkripcija je dostupna samo u Superthread desktop aplikaciji za macOS.",
  downloadApp: "Preuzmi aplikaciju",
  enhance: "Unaprijedi",
  macIntel: "Mac Intel",
  appleSilicon: "Apple Silicon",
  enhanceNotesUsingAI: "Poboljšajte bilješke koristeći AI",
  showTranscript: "Prikaži transkripciju",
  epicCreated: "Projekt kreiran",
  analysingTranscript: "Analiziranje transkripcije",
  comparingYourNotes: "Poređenje vaših bilješki",
  readingYourNotes: "Čitanje vaših bilješki",
  enhancingYourNotes: "Unapređivanje vaših bilješki",
  finished: "Završeno",
  note: "Bilješka",
  epicMustHaveTitle: "Projekt mora imati naslov",
  seeAllNotes: "Pogledaj sve bilješke",
  autoSaved: "Automatski sačuvano",
  projectsAreTrackedOnRoadmap: "Projekti se prate na planu rada",
  addCardsToProject: "Dodajte kartice u projekt",
  projectEmptyStateDescription:
    "Projekat je veliki dio posla koji se sastoji od mnogih kartica iz cijelog radnog prostora. Kreirajte projekat u koloni ili uredite zadane statuse.",
  cardInProjectEmptyStateFooter: "Kartica može pripadati samo jednom projektu",
  addCardsThatContributeToProject:
    "Dodajte kartice koje doprinose ovom projektu. Možete",
  noProject: "Nema projekta",
  noteTemplates: "Predlošci bilješki",
  noteTemplatesSettingsSubtitle:
    "Brzo promijenite formatiranje bilježaka pomoću predložaka",
  noNoteTemplates: "Nema predložaka bilješki",
  createNoteTemplate: "Kreiraj predložak bilješke",
  sections: "Sekcije",
  sectionHeading: "Naslov sekcije",
  sectionDescriptionPlaceholder: "Ova sekcija treba da se fokusira na...",
  addSection: "Dodaj sekciju",
  superthread: "Superthread",
  deletedTemplate: "Obrisani predložak",
  autoEnhanced: "Automatski poboljšano",
  meetingContext: "Kontekst sastanka",
  meetingContextPlaceholder:
    "Navedite kratak pregled sastanka i šta želite postići...",
  meetingContextDescription:
    "Ovo pomaže Superthreadu da razumije na šta da se fokusira prilikom poboljšavanja vaših bilješki",
  duplicateTemplate: "Dupliciraj predložak",
  favouriteTemplates: "Omiljeni predlošci",
  introduction: "Uvod",
  sampleSectionDescription:
    "Zabilježite sve zanimljive teme razgovora iz neformalne diskusije na početku sastanka. Zanemarite rasprave o vremenu.",
  allowSuperthreadToTranscribe:
    "Dozvoli Superthread-u da transkribuje vaše sastanke",
  superthreadCanEnhance:
    "Superthread može unaprijediti vaše bilješke transkripcijom zvuka direktno s vašeg laptopa, bez potrebe za botovima za sastanke. Radi za sastanke uživo i virtualne sastanke, uz potpunu kontrolu nad time kada je aktivan. Vaš zvuk nikada se ne pohranjuje niti koristi u druge svrhe.",
  transcribeYourVoice: "Transkribujte svoj glas",
  transcribeOthersVoice: "Transkribujte glasove drugih",
  allowMicrophoneCapture: "Dozvoli pristup mikrofonu",
  allowSystemAudioCapture: "Dozvoli pristup sistemskom zvuku",
  microphoneAccessNotAllowedTitle: "Ručno dozvolite pristup mikrofonu",
  microphoneAccessNotAllowedDesc1:
    "Pristup mikrofonu prethodno nije bio dozvoljen. Morate ga ručno omogućiti.",
  microphoneAccessNotAllowedDesc2:
    "Na macOS-u, idite na Postavke sistema > Privatnost i sigurnost > Mikrofon i dozvolite aplikaciji „Superthread”.",
  microphoneAccessNotAllowedDesc3:
    "Nakon što to učinite, zatvorite i ponovo otvorite aplikaciju, a zatim se vratite ovdje.",
  systemAccessNotAllowedTitle: "Ručno dozvolite pristup sistemskom zvuku",
  systemAccessNotAllowedDesc1:
    "Pristup sistemskom zvuku prethodno nije bio dozvoljen. Morate ga ručno omogućiti.",
  systemAccessNotAllowedDesc2:
    "Na macOS-u, idite na Postavke sistema > Privatnost i sigurnost > Snimanje sistemskog zvuka i dozvolite aplikaciji „Superthread”.",
  systemAccessNotAllowedDesc3:
    "Nakon što to učinite, zatvorite i ponovo otvorite aplikaciju, a zatim se vratite ovdje.",
  editNoteTemplate: "Uredi predložak bilješke",
  viewNoteTemplate: "Pregledaj predložak bilješke",
  viewTranscript: "Pogledaj transkript",
  transcribeHereInstead: "Prepisujte ovdje umjesto toga?",
  currentlyTranscribingAnotherNote:
    "Bilješka “%{noteTitle}” se trenutno prepisuje. Želite li zaustaviti prepisivanje tamo i prepisivati ovdje umjesto toga?",
  transcribeHere: "Prepišite ovdje",
  resume: "Nastavi",
  pause: "Pauza",
  transcribe: "Prepiši",
  currentlyTranscribing: "Trenutno se prepisuje",
  transcribingOnlyAvailableOnMac:
    "Prepisivanje je dostupno samo u aplikaciji za macOS",
  startTranscription: "Započni prepisivanje",
  stopTranscription: "Zaustavi prepisivanje",
  openTranscribingNote: "Otvori bilješku za prepisivanje",
  selectANote: "Odaberite bilješku",
  noteDoesntExist: "Bilješka ne postoji",
  deleteSection: "Izbriši sekciju",
  untitledSection: "Neimenovana sekcija",
  messageAgentAssistant: "Pošalji poruku agent asistentu",
  initialAgentMessage:
    "Ovdje sam da vam pomognem napisati upute za vašeg agenta. Javite mi što želite da radi.",
  agentMessageError: "Došlo je do greške. Molimo pokušajte ponovo.",
  agentInstructions: "Upute za agenta",
  version: "Verzija",
  templateWithChildCardsNotAllowed:
    "Možete primijeniti predložak na karticu samo ako predložak nema svojih vlastitih child kartica",
};

export default bs;
