import { Translations } from "../types";

const bs: Translations = {
  search: "Pretraga...",
  close: "Zatvori",
  send: "Pošalji",
  resendInviteLink: "Pošalji link ponovo",
  addComment: "Dodaj komentar",
  comment: "komentariši",
  writeComment: "Napiši komentar...",
  comments: "KOMENTARI",
  createBoard: "Kreiraj kanban tablu",
  createPage: "Kreiraj stranicu",
  delete: "Izbriši",
  edit: "Uredi",
  remove: "Izbriši",
  done: "Gotovo",
  enterBoardTitle: "Unesite naziv boarda",
  create: "Kreiraj",
  untitled: "Nenaslovljeno",
  containsNoContent: "Bez sadržaja.",
  ama: "AMA",
  me: "Ja",
  assigned: "dodjeljeno",
  mentions: "pominjanja",
  visited: "posjećeno",
  saved: "sačuvano",
  notifications: "Obavijesti",
  selectWhereWwhenWillNotified: "Odaberite gdje i kada ćete biti obaviješteni",
  recivePersonalNotification: "Primajte lična obavještenja u Slacku",
  notifyMe: "Obavijesti me kada",
  save: "Sačuvaj",
  saveChanges: "Sačuvaj Izmjene",
  archived: "arhivirano",
  archive: "Arhiviraj",
  cardArchived: "Ova kartica je arhivirana.",
  cellMerge: "Spajanje ćelija",
  new: "NOVI",
  view: "Pogled",
  signOut: "Odjava",
  leave: "Napusti",
  browseAllSpaces: "Pretražuj sve prostore",
  preview: "Pregledaj",
  goToCard: "Idi do kartice",
  zoomIn: "Uvećaj",
  zoomOut: "Umanji",
  notFoundPageHeader: "Naišli smo na problem...",
  notFoundPageContent:
    "Nismo sigurni šta nije uredu. Možete se vratiti nazad na prethodnu stranicu ili kontaktirati službu za podršku.",
  addCard: "Dodaj karticu",
  next: "Slijedeći",
  addToCard: "Dodaj u karticu",
  checklist: "Čeklista",
  moveList: "Pomjeri listu",
  board: "Board",
  timeline: "Timeline",
  templates: "Predlošci",
  cardTemplates: "Predlošci kartica",
  pageTemplates: "Predlošci stranica",
  saveCardContentYouRepeatedlyUse:
    "Sačuvajte sadržaj koji često koristite i primijenite ga kada kreirate kartice",
  savePageContentYouRepeatedlyUse:
    "Sačuvajte sadržaj koji često koristite i primijenite ga kada kreirate stranice",
  createCardTemplate: "Kreirajte predložak kartice",
  editCardTemplate: "Uredite predložak kartice",
  searchTemplates: "Pretražite predloške",
  name: "Naziv",
  noCardTemplates: "Nema predložaka kartica",
  noPageTemplates: "Nema predložaka stranica",
  calendar: "Kalendar",
  showAllCards: "Prikaži sve kartice",
  hideAllCards: "Sakrij sve kartice",
  showWeekends: "Prikaži vikende",
  youCanCreateATemplateAbove: "Možete kreirati predložak iznad",
  youCanCreateABoardFrom: "Možete kreirati ploču sa sidebara aplikacije",
  createPageTemplate: "Kreirajte predložak stranice ",
  editPageTemplate: "Uredite predložak stranice",
  templateNameAndIcon: "Naziv predloška i ikona",
  thisIsHowPeopleFindTemplate: "Ovako će ljudi kasnije pronaći vaš predložak",
  shortAndDescriptive: "Kratko i opisno",
  templateNameCannotBeEmpty: "Naziv predloška ne može biti prazan",
  templateSpace: "Predložak prostora",
  whichSpacesWillThisTemplateBeAvailableIn:
    "U kojim će prostorima ovaj predložak biti dostupan?",
  templateSpaceShouldHaveAtLeastOneSpaceSelected:
    "Predložak prostora mora imati barem jedan odabrani prostor",
  noSpacesFound: "Nema pronađenih prostora.",
  allSpaces: "Svi prostori",
  peopleWillBeAbleToEditThisAfterTheyApplyTheTemplate:
    "Ljudi će moći uređivati ovo nakon što primijene predložak",
  theseWillBeAddedToTheCardYouApplyTheTemplateTo:
    "Ovo će biti dodano kartici na koju primijenite predložak",
  taskDescription: "Opis kartice",
  pageBody: "Tijelo stranice",
  saveTemplate: "Spremi predložak",
  templateNotFound: "Predložak nije pronađen",
  addAssignees: "Dodaj dodjeljivače",
  setTags: "Postavi oznake",
  selectAll: "Odaberi sve",
  createInThisBoard: "Kreiraj u ovoj ploči",
  setThisStatus: "Postavi ovaj status",
  chooseABoard: "Odaberite ploču",
  chooseABoardToUseThisField: "Odaberite ploču da biste koristili ovo polje",
  ifYouLeaveThisPageAnyChangesWillBeLost:
    "Ako napustite ovu stranicu, sve promjene koje ste napravili na ovom predlošku bit će izgubljene.",
  areYouSureYouWantToDeleteTheTemplate:
    "Da li ste sigurni da želite izbrisati %{templateName} predložak?",
  applyTemplate: "Primijeni predložak",
  noTemplates: "Nema predložaka.",
  manageTemplates: "Upravljajte predlošcima",
  uploadFilesForTemplatesIsDisabled:
    "Prijenos datoteka za predloške onemogućen",
  uploadFilesIsDisabled: "Prijenos datoteka onemogućen",
  noTagsFoundSelectBoardToSeeTags:
    "Nema pronađenih oznaka. Odaberite ploču da biste vidjeli dostupne oznake u tom prostoru ili",
  createNewWorkspaceTagInSettings:
    "kreirajte novu oznaku radnog prostora u postavkama.",
  noTitle: "Nema naslova",
  addChecklist: "Dodaj čeklistu",
  title: "Naslov",
  add: "Dodaj",
  addItem: "Dodaj novu stavku",
  archiveList: "Arhiviraj listu",
  actions: "Akcije",
  reply: "Odgovori",
  replies: "Odgovora",
  description: "Opis",
  cardDescriptionPlaceholder: "Napisite detaljni opis...",
  templateDescriptionPlaceholder: "Unesite opis...",
  card: "Kartica",
  space: "Prostor",
  spaces: "Prostori",
  page: "Stranica",
  workspaceLabel: "Unesite ime radnog prostora",
  workspacePlaceholder: "Ime radnog prostora",
  download: "Preuzmi",
  move: "Premjesti",
  background: "Pozadina",
  share: "Podijeli",
  createNewPage: "Kreiraj novu stranicu",
  createNewBoard: "Kreiraj novu ploču",
  newBoard: "Nova ploča",
  addNewBoard: "Dodaj novu ploču",
  oneColumn: "1 kolona",
  twoColumns: "2 kolone",
  previewStillUpdating: "Pregled se još uvijek ažurira...",
  emptyPage: "Prazna stranica",
  searchSuperthread: "Pretraži Superthread",
  cancel: "Otkaži",
  cancelAndDiscard: "Otkaži i odbaci",
  makeItPrivate: "Učini privatnim",
  privateSpaceDescription:
    "Kada je prostor postavljen kao privatni moguće mu se pridružiti samo putem poziva.",
  boards: "Ploče",
  linkTextLabel: "Naziv",
  linkUrlLabel: "Adresa",
  linkTextPlaceholder: "Dodaj naziv...",
  linkUrlPlaceholder: "Dodaj adresu...",
  editList: "Uredi listu",
  copyList: "Kopiraj listu",
  sortBy: "Poredaj po...",
  moveAllCards: "Pomjeri sve kartice",
  archiveAllCards: "Arhiviraj sve kartice",
  open: "Otvori",
  editTitle: "Izmijeni naziv",
  editTags: "Izmijeni oznake",
  editMembers: "Izmijeni članove",
  copy: "Kopiraj",
  attachment: "Privitak",
  startDate: "Datum početka",
  dueDate: "Rok završetka",
  cover: "Naslovna fotografija",
  tags: "Oznake",
  activity: "Aktivnost",
  created: "Kreirano",
  updated: "Ažurirano",
  timePeriod: "Vremenski period",
  netChange: "Neto promjena",
  last7Days: "Zadnjih 7 dana",
  last14Days: "Zadnjih 14 dana",
  last30Days: "Zadnjih 30 dana",
  between: "između",
  deletedCards: "Izbrisane kartice smanjuju broj",
  convertToCard: "Pretvori u karticu",
  searchForTag: "Traži oznaku",
  createTag: "Kreiraj oznaku",
  tagName: "Ime oznake",
  editTagName: "Uredi ime oznake",
  hideCheckedItems: "Sakrij završene stavke",
  showCheckedItems: "Prikaži završene stavke",
  deleteChecklist: "Izbriši čeklistu",
  attachments: "Privitci",
  versionHistory: "Historija",
  profile: "Profil",
  settings: "Postavke",
  email: "Email",
  firstNamePlaceholder: "Unesite ime",
  lastNamePlaceholder: "Unesite prezime",
  displayNamePlaceholder: "Unesite ime za prikaz",
  profileBasicInfoSubtitle: "Personalni i kontakt podaci",
  uploadProfileImageRule:
    "Slika treba da bude PNG, GIF ili JPG format maksimalne veličine od 3 MB. Prijenos slike će zamijeniti boju vašeg avatara u cijeloj aplikaciji.",
  workspaceLogo:
    "Odaberite logo za svoj workspace. Preporučena veličina je 256x256px",
  logoSaved: "Logo sačuvan",
  logoRemoved: "Logo uklonjen",
  removeCover: "Izbriši naslovnu fotografiju",
  uploadCoverImage: "Postavi novu fotografiju",
  list: "Lista",
  addChildCard: "Dodaj child karticu",
  newChildCard: "Kreirajte novu child karticu",
  searchForCard: "Potražite postojeću karticu",
  cancelSearch: "Otkaži pretragu",
  computer: "Kompjuter",
  setDueDate: "Postavi rok završetka",
  months:
    "Januar,Februar,Mart,April,Maj,Juni,Juli,August,Septembar,Oktobar,Novembar,Decembar",
  monthsAbbreviation: "Jan,Feb,Mar,Apr,Maj,Jun,Jul,Aug,Sep,Okt,Nov,Dec",
  daysAbbreviation: "PO,UT,SR,ČE,PE,SU,NE",
  daysAbbreviationLong: "Pon,Uto,Sri,Čet,Pet,Sub,Ned",
  weekDays: "Ponedjeljak,Utorak,Srijeda,Četvrtak,Petak,Subota,Nedjelja",
  time: "Vrijeme",
  dueDateReminder: "Podsjetnik na rok",
  weekBefore: "Sedmica prije",
  daysBefore: "Dana prije",
  dayBefore: "Dan prije",
  hoursBefore: "Sati prije",
  hourBefore: "Sat prije",
  onTime: "Na vrijeme",
  none: "Nijedan",
  due: "Rok",
  insertFile: "Umetni datoteku",
  addImage: "Dodaj sliku",
  edited: "uređeno",
  insert: "Umetni",
  deleteAttachment: "Ukloni privitak",
  overdue: "Isteklo",
  continue: "Nastavi",
  createdBy: "Kreirao",
  press: "Pritisni",
  toClose: "za izlaz",
  useArrowKeys: "Koristi tipke sa strelicama",
  toNavigate: "za navigaciju, odaberite sa",
  cards: "Kartice",
  on: "na",
  sending: "Slanje pozivnog linka..",
  inviteDoesntExist: "Pozivni link ne postoji.",
  newInviteLinkSent: "Poslali smo vam novi pozivni link, provjerite vaš email.",
  inviteLinkAccepted: "Pozivni link je već prihvaćen.",
  inviteNoLongerValid:
    "Pozivni link nije više validan - molimo vas zatražite novi.",
  inviteCodeIncorrect:
    "Kod za pozivni link nije ispravan. Kliknite ispod za novi link.",
  spaceAccess: "Pristup prostoru",
  changeToPrivateSpace:
    "Svi postojeći članovi ovog prostora će i dalje biti članovi nakon što postane privatni. Nijedan novi član se neće moći pridružiti osim ako nisu pozvani.",
  changeToOpenSpace:
    "Svi članovi workspace-a moći će pronaći i pridružiti se ovom prostoru, te vidjeti njegov sadržaj.",
  changeToPrivate: "Promijeni u privatni",
  changeToOpen: "Promijeni u javni",
  changeToPrivateSpaceTitle: "Promijeni u privatni prostor?",
  changeToOpenSpaceTitle: "Promijeni u javni prostor?",
  ownersAdminsCreatorOfSpace:
    "Samo vlasnici workspace-a, administratori i kreator prostora mogu promijeniti ovu postavku",
  onlyOwnerOfPrivateSpace:
    "Samo vlasnik privatnog prostora može promijeniti ovu postavku",
  onlySpaceOwnerCanModifyMembers:
    "Samo vlasnik prostora može mijenjati članove",
  pageTitlePlaceholder: "Dodaj ime ovom dokumentu",
  markAllAsRead: "Označi sve kao pročitano",
  addTo: "Dodao te na",
  removeFrom: "Izbrisao te na",
  movedTo: "%{name} pomjeren",
  commented: "Komentarisano",
  mentioned: "Spominjani ste",
  dropFilesLabel: "ispusti datoteke ovdje",
  back: "Nazad",
  hasDueDate: "Ima rok završetka",
  dueSoon: "Uskoro ističe rok",
  dueToday: "Rok završetka danas",
  epic: "prostor",
  epics: "prostori",
  searchForEpic: "Potraži prostor",
  changedEpicFrom: "promijenio prostor iz",
  addedToEpicCard: "dodao karticu u prostor",
  removedFromEpicCard: "uklonio karticu iz prostora",
  epicInherited: "naslijedio prostor",
  untitledView: "Pogled bez naslova",
  cannotSaveUntitledView: "Ne možete spasiti pogled bez naslova",
  viewSaved: "pogled je spašen",
  pagePlaceholder: "Počnite pisati nešto :)",
  newViewTitele: "Naslov novog pogleda",
  ["global.placeholder.pagePlaceholder"]: "Počnite pisati nešto :)",
  viewAll: "Prikaži sve",
  filterByUnread: "Prikaži nepročitane",
  pagePublished: "Stranica objavljena",
  restore: "Vrati",
  cardPathArchivedBoard: "Ova kartica je dio arhiviranog borda",
  boardArchived: "Ovaj bord je arhiviran.",
  pageArchived: "Ova stranica je arhivirana.",
  restoreMakeChange: "Klikni ovdje za vraćanje.",
  boardUpdated: "Board ažuriran",
  defaultBoardLayoutChangedTo:
    "Predefinisani izgled board-a je promijenjen na %{layoutStyle}",
  esc: "Esc",
  assignee: "Dodjeli",
  findMembers: "Pretraži članove...",
  inviteExternalPeople: "Pozovite spoljne ljude",
  notInThisSpace: "Nisu u ovom prostoru",
  notWorkspaceMember: "Izgleda da se tražena osoba ne nalazi u vašem timu",
  deleteView: "Izbriši pogled",
  anchorLinkErrorMessage: "Nemoguće pronaći link",
  childCard: "Child card",
  parentCards: "Roditeljske kartice",
  blocking: "Blokirajuće",
  blocked: "Blokirane",
  favourites: "Favoriti",
  dragOr: "Prevucite ili",
  somethingHere: "nešto ovdje",
  linkCopiedToClipboard: "Link je kopiran u međuspremnik.",
  tomorrow: "Sutra",
  invitationsSent: "Pozivnice poslane!",
  retry: "Pokušaj ponovo",
  undo: "Poništi",
  tagExists: "Oznaka već postoji",
  removeChildCardFail: "Neuspješno uklanjanje child kartice",
  moveChildCardFail: "Neuspješno pomjeranje child kartice",
  addChildCardFail: "Neuspješno dodavanje child kartice",
  cantRemoveMembers: "Ne možete ukloniti članove iz prvog prostora",
  cantRemoveMembersFromSpace: "Ne možete ukloniti članove space-a",
  cannotModifyMembers: "Ne možete mijenjati članove",
  inactiveMembersCannotBeAdded: "Neaktivni članovi ne mogu biti dodani",
  duplicate: "Dupliciraj",
  setParentCard: "Dodaj roditeljsku karticu",
  duplicateCard: "Dupliciraj karticu",
  duplicateTo: "Dupliciraj u",
  duplicateDefaultTitle: "Unesite naslov kartice (defaults u original)",
  duplicates: "Duplicira",
  duplicateOf: "Duplikat od",
  markAsBlockedBy: "Označi kao blokirano od strane",
  markAsBlocking: "Označi kao blokiranje",
  markAsRelatedTo: "Označi kao povezano sa",
  markAsDuplicateOf: "Označi kao duplikat",
  blocks: "Blokira",
  blockedBy: "Blokirano od",
  related: "Povezano",
  relatedCards: "Povezane kartice",
  markedCardAsBlocking: "je označio ovu karticu kao blokirajuću",
  markedCardAsBlockedBy: "je označio ovu karticu kao blokiranu od strane",
  markedCardAsRelated: "je označio ovu karticu kao povezanu sa",
  markedCardAsDuplicate: "je označio ovu karticu kao duplikat od",
  removedCardRelationship: "je uklonio vezu",
  noListsInBoard: "Nema listi u ploči",
  noBoardsInSpace: "Nema ploča u prostoru",
  noBoardsInThisSpace: "Nema ploča u ovom prostoru",
  emptyList: "Prazna lista",
  cardDuplicated: "Kartica duplicirana",
  viewDuplicated: "Pogled dupliciran",
  viewDeleted: "Pogled izbrisan",
  cardDuplicateFailed: "Dupliciranje kartice nije uspjelo",
  viewDuplicateFailed: "Dupliciranje pogleda nije uspjelo",
  cantUndoneAction: "Ova akcija ne može biti opozvana",
  deleteCommentPopupMessage: "Da li ste sigurni da želite izbrisati komentar?",
  deleteMessage: "Izbriši komentar",
  eachSpaceCanContain: "Svaki prostor može sadržavati kartica koliko želite",
  browseSpaces: "Pretražite prostore",
  popupSpaceDescription:
    "Vaš workspace je organizovan u prostore. Oni mogu biti nazvani kao tim, tema, ili mogu biti fokusirani na specifičan dio posla",
  eachSpaceCanContainMultiple: "Svaki prostor može sadržavati više ",
  pagesLowercase: "stranice",
  kanbanBoards: "kanban ploča",
  and: "i",
  removeFromParent: "Ukloni iz roditelja",
  removeChildCard: "Izbriši child karticu",
  editChildCardDetails: "Uredi detalje child kartice",
  copyLink: "Kopiraj link",
  childCardTitleNotUpdated: "Naziv child kartice nije promijenjen.",
  addNewChildCard: "Dodaj novu child karticu",
  enterCardTitleOrFind: "Unesite naziv kartice ili pronađite postojeću karticu",
  createNewCard: "Kreiraj novu karticu",
  unsplashImage: "Unsplash slika",
  publishesSubpagesButNoComments: "Objavljuje podstranice, ali ne i komentare.",
  pageIsSharedToWeb: "Stranica je javno podijeljena.",
  shared: "Podijeljeno",
  openSharedPage: "Otvori podijeljenu stranicu",
  pageIsSetToPrivate: "Stranica je privatna",
  profileSettings: "Postavke profila",
  switchWorkspace: "Promijenite workspace",
  archivedItems: "Arhivirano",
  logOut: "Odjavi se",
  helpFeedback: "Pomoć i Feedback",
  help: "Pomoć",
  joinSlack: "Pridruži se našoj Slack zajednici",
  askQuestions: "Postavite pitanja i pomozite drugima",
  contactUs: "Kontaktirajte nas",
  letUsKnow: "Dajte nam doznanja ako imate problem ili pitanje",
  assign: "Dodjeli",
  pageIsNoLongerShared: "Stranica više nije javno podijeljena",
  favourite: "Dodaj u omiljene",
  unfavourite: "Ukloni iz omiljenih",
  allowSearchEngines: "Dozvoli pretraživačima da indeksiraju stranicu",
  searchEngineIndexing: "Indeksiranje pretraživača",
  searchIndexingEnabled: "Indeksiranje pretraživača uključeno",
  searchIndexingDisabled: "Indeksiranje pretraživača isključeno",
  attachIconFrom: "Dodajte ikonu iz...",
  addIcon: "Dodajte ikonu",
  addCoverImage: "Dodajte pozadinsku sliku",
  pageDuplicated: "Stranica je duplicirana",
  pageDuplicateFailed: "Dupliciranje stranice nije uspjelo",
  copyOf: "Kopija od",
  displayNameDescription:
    "Ovo može biti vaše ime ili nadimak - kako god želite da vas ljudi pozivaju u Superthread-u",
  integrations: "Integracije",
  importer: "Importer",
  github: "GitHub",
  gitlab: "GitLab",
  jira: "Jira",
  trello: "Trello",
  importFrom: "Uvoz sa",
  usersToSuperthreadUsers: "korisnice u Superthread korisnike",
  issues: "probleme",
  teams: "timove",
  selectYour: "Odaberite svoje",
  setUpImport: "Podesi uvoz",
  importHistory: "Historija uvoza",
  runImport: "Pokrenite uvoz",
  start: "Počni",
  started: "Počelo",
  DontImport: "Ne uvozit",
  dontImportUsers: "Don't import users",
  ImportUsers: "Import users",
  selectUser: "Odaberi korisnika",
  inviteByEmail: "Pozovi sa email adresom",
  users: "korisnici",
  options: "Opcije",
  chooseAditionslOptions: "Odaberite dodatne opcije",
  importAttachments: "Uvezite priloge",
  includeCardCoverImages: "Uključite slike naslovnice kartice",
  importInProgress: "Uvoz u procesu",
  importError: "Uvoz završen sa greskom",
  importSuccess: "Uvoz završen",
  importUnstarted: "Uvoz nije počeo",
  timeStarted: "Vrijeme početka",
  completed: "Završeno",
  showCompleted: "Prikaži završeno",
  details: "Detalji",
  finish: "Završi",
  validEmail: "Molimo unesite ispravnu email adresu",
  emailAdresses: "E-mail adrese, odvojene zarezima",
  addToSpaces: "Dodaj u prostore",
  addSpaces: "Dodaj prostore",
  browseProjects: "Pretražuj sve prostore",
  createAndBrowseSpaces: "Kreirajte i pretražujte prostore",
  nameIsRequired: "Ime je potrebno",
  noProjectFound: "Nema više prostora za dodati!",
  memberExplanation:
    "Članovi mogu pretraživati i pridružiti se bilo kojem prostoru u workspace-u",
  adminExplanation: "Admini imaju povećani pristup postavkama workspace-a",
  guestExplanation:
    "Gosti imaju ograničen pristup u workspace-u i mogu vidjeti samo prostore u koje su dodani",
  connect: "Poveži se",
  selectBoardImport: "Odaberite ploče koje želite uvesti.",
  selectUsersImport: "Odaberite korisnike koje želite uvesti.",
  notImportArchivedIssues: "Nećemo uvoziti arhivirane probleme",
  importTasksIntoSuperthread: "Uvezite postojeće zadatke u Superthread.",
  connectAccount: "Povežite svoj račun",
  completedOn: "Završen",
  importedBy: "Uvezen od:",
  timeCreated: "Vrijeme kada je napravljeno:",
  numberOfImportedBoards: "Broj uvezenih ploča:",
  numberOfImportedUsers: "Broj uvezenih korisnika:",
  importingIsFinished: "Uvoz je završen",
  importing: "Uvoz",
  selectService:
    "Odaberite iz koje usluge trebamo uvesti probleme. Zatražit ćemo vaše detalje o autentifikaciji kako bismo mogli pristupiti njihovom API-ju. Nećemo uvoziti nikakve podatke dok ne potvrdite sve opcije u završnom koraku procesa.",
  account: "Račun",
  importers: "Uvozi",
  general: "General",
  manageWorkspaceSettings: "Upravljajte općim postavkama workspace-a",
  avatarAppearance: "Izgled avatara",
  uploadImage: "Učitaj sliku",
  successfullySaved: "Uspješno spremljeno",
  errorSave: "Vaše promjene nisu mogle biti sačuvane",
  copyURL: "Kopiraj URL",
  copyUrl: "Kopira URL u međuspremnik",
  copyCardUrl: "Kopiraj URL kartice u međuspremnik",
  copyPageUrl: "Kopiraj URL stranice u međuspremnik",
  copyBoardUrl: "Kopiraj URL ploče u međuspremnik",
  copySpaceUrl: "Kopiraj URL prostora u međuspremnik",
  copyGitBranchNameToClipboard: "Kopiraj ime git grane u međuspremnik",
  copyGitBranchName: "Kopiraj ime git grane",
  branchCopiedToClipboard: "Ime git grane kopirana u međuspremnik",
  subscribe: "Pretplati se",
  unsubscribe: "Ukloni pretplatu",
  pullRequestAutomation: "Pull request automatizacija",
  prAutomationDescription:
    "Sa našom GitHub integracijom, kada je kartica povezana sa pull requestom, možete automatski pomjeriti karticu u odgovarajuću listu ploče kada se promijeni pull request.",
  whenPRChangesTo: "Kada se PR promijeni u",
  moveCardToList: "Pomjeri karticu u listu",
  doNotMove: "Ne pomjeraj",
  draftPROpened: "Otvoren PR nacrt",
  pROpened: "PR otvoren",
  pRReviewRequest: "PR zahtjev za pregled",
  pRMerged: "PR spojen",
  pRClosed: "PR zatvoren",
  noListInBoard: "Nema listi u ovoj ploči",
  unassigned: "Nije dodijeljeno",
  viewParentCard: "Pogledaj roditeljsku karticu",
  changeParentCard: "Promjeni roditeljsku karticu",
  removeParentCard: "Ukloni roditeljsku karticu",
  maxFileSize: "(maksimalna veličina fajla: 5 MB)",
  addAttachment: "Dodaj datoteku",
  createChecklist: "Dodaj čeklistu",
  assignedToMe: "Dodijeljeno meni",
  movedTAaNewList: "Pomjereno na novu listu",
  moved: "Pomjereno",
  published: "Objavljeno",
  cardComments: "Komentari kartica",
  pageComments: "Komentari stranica (uključujući odgovore u nitima)",
  movedBetweenSpaces: "Premješteno između prostora",
  addedToASpace: "Dodan u prostor",
  anywhereYouAreMentioned:
    "Gdje god ste spomenuti (bez obzira na status pretplate itd.)",
  anyCommentsOnResources: "Svi komentari na resurse koje gledate.",
  ifYouAreMemberOfABoard: "Ako ste član ploče:",
  manageMembers: "Organizujte članove",
  manageWhoHasAccess: "Odredite ko ima pristup ovom workspace-u",
  active: "Aktivan",
  suspended: "Suspendiran",
  inviteMembers: "Pozovite članove",
  emailAddress: "Email adresa",
  inviteAs: "Pozovite kao",
  teamMembers: "Članovi tima",
  gitHubConnected: "Uspješno ste se povezali na GitHub",
  nothingToShow: "Nema ništa za prikazat",
  findTagsOrCreateNew: "Pronađi tagove ili kreiraj novi",
  deleteTag: "Izbriši oznaku",
  rename: "Preimenuj",
  changeIcon: "Promijeni ikonu",
  areYouSureYouWantToRemove:
    "Da li ste sigurni da ih želite ukloniti? Oni će izgubiti pristup workspace-u.",
  areYouSureYouWantToLeave:
    "Da li ste sigurni da želite napustiti ovaj workspace? Trebat ćete biti ponovo pozvani da biste dobili pristup.",
  areYouSureYouWantToRevoke:
    "Da li ste sigurni da želite otkazati njihov poziv u ovaj workspace?",
  areYouSureYouWantToTransferOwnership:
    "Jeste li sigurni da želite prenijeti vlasništvo ovog workspace-a? Samo novi vlasnik će to moći poništiti.",
  transferOwnership: "Prenesite vlasništvo",
  transferOwnershipConfirmed: "Vlasništvo je preneseno",
  transferSpaceOwnershipShort:
    "Prenesite vlasništvo ovog workspace-a na drugog člana",
  transferSpaceOwnershipDescription:
    "Prenesite vlasništvo ovog workspace-a na drugog člana. Samo novi vlasnik će to moći poništiti.",
  transferSpaceOwnershipBeforeLeaving:
    "Prenesite vlasništvo ovog workspace-a na drugog člana prije nego što napustite workspace.",
  confirm: "Potvrdi",
  revoke: "Otkaži",
  notFound: "Nije pronađeno",
  itemNotFound: "Stavka nije pronađena",
  urlDoesntLeadAnywhere: "Taj URL ne vodi nikuda",
  itemMightBeDeleted: "Stavka je možda izbrisana ili joj nemate pristup",
  deleteSpace: "Izbriši prostor",
  contentWillBeDeleted:
    "i njegov sadržaj će biti trajno izbrisan za sve. Ovo se ne može poništiti.",
  willBeDeleted: "će biti trajno izbrisan za sve. Ovo se ne može poništiti.",
  ifYouWantToDeleteResource:
    "Ako želite da izbrišete ovaj %{resourceType}, upišite njegovo ime ispod.",
  typeTheNameOfTheSpace: "Upišite ime prostora",
  removeMember: "Ukloni člana",
  leaveWorkspace: "Napusti workspace",
  revokeInvite: "Otkaži poziv",
  invited: "Pozvan",
  pending: "Na čekanju",
  admin: "Admin",
  owner: "Vlasnik",
  guest: "Gost",
  inviteSent: "Poziv je poslan",
  resendInvite: "Pošaljite ponovo poziv",
  whatsNew: "Šta je novo",
  viewUpdates: "Pogledajte update u našem sedmičnom changelog-u",
  fullscreen: "Cijeli zaslon",
  whenYouCreateTags:
    "Kada kreirate oznake direktno na kartici, one se spremaju kao prilagođene oznake samo za taj prostor. Možete ponovo koristiti uobičajene oznake (npr. bug) u svim svojim prostorima tako što ćete ih umjesto toga kreirati ovdje. Da bi stvari bile uredne, spojit ćemo oznake prostora s istim imenom u novi radni prostor.",
  merge: "Spojite",
  theSpace: "prostor",
  haveSameTags: "imaju oznake sa istim imenom.",
  doYouWantToMerge: "Da li želite spojiti ove oznake u novu workspace oznaku?",
  tagWithThisNameWorkspace: "Želite li ih spojiti u novu oznaku workspace-a?",
  tagWithThisNameSpace: "Oznaka s ovim imenom već postoji u prostoru",
  editTag: "Uredite oznaku",
  workspaceTags: "Workspace Oznake",
  manageTags: "Upravljajte oznakama koje se dijele u svim prostorima",
  youCantUndo: "Ne možete vratiti ovu radnju.",
  merge2spaceTags: "Spojite dvije prostor oznake u jednu workspace oznaku?",
  areYouSureYouWantToDelete: "Da li ste sigurni da zelite izbrisati.",
  uploaded: "Učitano",
  cardCreatedInResource: "Kartica kreirana u '%{resourceName}' %{resourceType}",
  ["global.label.createIn"]: "Kreiraj u",
  rememberBoard: "Postavi kao zadani bord",
  cardTitle: "Naziv kartice",
  pageTitle: "Naslov stranice",
  cardDescription: "Opis kartice...",
  editAsignees: "Uredite dodjeljivače",
  thisBoardIsEmpty: "Ovaj bord je prazan. Prvo kreirajte listu.",
  pageCreated: "Stranica je kreirana",
  ["quickPage.label.setAsDefaultSpace"]: "Postavi kao zadani prostor",
  changesAreSavedAuto: "Izmjene spremljene automatski",
  untitledCard: "Nenaslovljena kartica",
  editAssignees: "Uredi članove",
  showChildCards: "Prikaži podkartice",
  hideChildCards: "Sakrij podkartice",
  createNewList: "Napravi novu listu",
  enterListName: "Unesite ime liste",
  listStatus: "Status liste",
  couldntArchiveCard: "Kartica nije arhivirana.",
  cardRestored: "Kartica je vraćena",
  dueOn: "Završava se",
  today: "Danas",
  yesterday: "Jučer",
  cannotModidyListStatus:
    "Nije moguće mijenjati status liste ako su kartice dodane.",
  attached: "zakačio",
  removed: "uklonio",
  updatedTheStartDate: "ažurirao datum početka na",
  setTheStartDate: "postavio datum početka na",
  removedStartDate: "uklonio datum početka",
  updatedTheDueDate: "azurirao datum u",
  setTheDueDate: "postavio datum u",
  removedDueDate: "uklonio datum",
  changedStausFrom: "promijenio status iz",
  createdCard: "kreirao karticu",
  people: "osobe",
  assignedMember: "dodao",
  archivedTheCard: "arhivirao karticu",
  restoredTheCard: "vratio karticu",
  theCardDescription: "opis kartice",
  theCardTitle: "naslov kartice",
  ["quickPage.title.attachImageFrom"]: "Zakači sliku sa...",
  ["quickPage.title.attachCoverImageFrom"]: "Zakači naslovnu sliku sa...",
  chooseWorkspaceZapier: "Izaberite workspace za povezati za Zapier-om",
  connectSTZapeir: "Povežite Superthread sa Zapier-om",
  zapierIntegradionDescripiton:
    "Zapier vam omogućava da izgradite prilagođene radne tokove koji povezuju Superthread sa gotovo bilo kojom drugom aplikacijom. Povezive aplikacije uključuju: Typeform, Gmail, Intercom, Google Forms, Zendesk, Airtable, Front i mnoge druge.",
  connectToZapier: "Povežite Zapier sa Superthread-om",
  zapier: "Zapier",
  openZapier: "Otvori Zapier",
  allow: "Dopusti",
  zappierWillHave:
    "Zapier će imati pristup za čitanje i pisanje karticama, tablama i stranicama u vašem radnom prostoru.",
  youMayBeSharing:
    "Možda dijelite osjetljive informacije s ovom web lokacijom ili aplikacijom. Uvijek možete vidjeti ili ukloniti pristup u svojim",
  stSettings: "Superthread postavkama",
  seeZapiers: "Vidite Zapier-ov",
  privacyPolicy: "Politika privatnosti",
  termsOfService: "Uslovi korištenja",
  makeSureYouTrustZapier: "Uvjerite se da vjerujete Zapier-u",
  connectZapierToSuperthread: "Zapier povezan sa Superthread-om",
  zapierIsRequesting: "Zapier traži pristup",
  previewStInSlack: "Pregledajte Superthread veze u Slacku",
  lookingForSlackNotifications: "Tražite Slack notifikacije?",
  turnThemOnInYour: "Upalite ih u vašim",
  notificationsSettings: "Postavkama notifikacija",
  connectToSlack:
    "Povežite se na Slack da pregledate ključne informacije sa Superthread kartica i stranica kada timovi zalijepe veze na njih u Slack poruke.",
  orLc: "ili",
  useBoardsToVisualise:
    "Koristite ploče da vizualizujete svoj tok posla, pratite napredak svog tima i planirate šta dalje. Napravite više ploča kako biste stvari organizirali.",
  collaborativeDocuments:
    "Kolaborativni dokumenti s tekstom, slikama, smanjenjem vrijednosti i umetnutim komentarima. Vodite bilješke, pišite specifikacije, napravite wiki ili javno dijelite informacije.",
  filterAcrossTheEntire:
    "Filtrirajte po cijelom radnom prostoru kako biste stvorili prikaz svih kartica koje su vam „dodijeljene” ili možda kreirajte globalni zaostatak „bugova”. Pregledi mogu biti privatni ili podijeljeni s vašim timom.",
  getStartedBy: "Započnite kreiranjem nove ploče ili stranice",
  useFiltersToCreate:
    "Koristite filtere da napravite novi pogled samo sa karticama koje zelite vidjeti",
  kanbanBoardsUc: "Kanban ploče",
  youCanAlsoImport: "Također možete uvesti svoje postojeće probleme iz",
  importIssues: "Uvezite probleme",
  welcomeToThe: "Dobrodošli u",
  leaveSpace: "Napusti prostor",
  joinSpace: "Pridruži se prostoru",
  joinThisSpace: "Pridruži se ovom prostoru",
  hasUnsupportedFileType: "ima nepodržan tip datoteke",
  maxAllowedImageSize: "Maksimalna dozvoljena veličina slike je",
  maxAllowedImageResolution: "Maksimalna dozvoljena rezolucija slike je",
  movedFromSpace: "maknuo iz prostora",
  onlineAgain: "Ponovo ste na mreži",
  youAreOffline: "Nemate interneta",
  untitledPage: "Stranica bez naslova",
  hideChildPages: "Sakrij podstranice",
  showSubpages: "Prikaži podstranice",
  addedTo: "dodan u",
  addMembers: "Dodaj članove...",
  removedFrom: "uklonjen iz",
  viewMembers: "Pogledaj članove",
  copyLinkToHeading: "Kopiraj link naslova",
  joined: "Pridružen",
  addOwner: "Dodaj vlasnika",
  noOwner: "Nema vlasnika",
  setOwner: "Postavi vlasnika",
  font: "Font",
  clickToUpdate: "Klikni za ažuriranje",
  NewVersionAvailable: "Nova verzija aplikacije je dostupna",
  deactivated: "deaktiviran",
  addedChildCard: "dodao pod karticu",
  removedChildCard: "uklonio pod karticu",
  removedChecklist: "uklonio checklistu",
  addedChecklist: "dodao checklistu",
  addedChecklists: "dodao checkliste",
  markedAsIncomplete: "označio kao nezavršeno",
  completedChecklistItem: "završio",
  addedParentCard: "dodao roditelj karticu",
  removedParentCard: "uklonio roditelj karticu",
  deleteFolder: "Izbriš datoteku",
  renameFolder: "Preimenuj datoteku",
  myViews: "Moji pogledi",
  workspaceViews: "Workspace pogledi",
  lockSidebar: "Zaključaj sidebar",
  hideSidebar: "Sakrij sidebar",
  appearance: "Izgled",
  changeHowSuperthreadLooksAndFeels:
    "Promijeni kako Superthread izgleda i radi",
  matchSistemSettings: "Podudaranje sa sistemskim postavkama",
  darkMode: "Tamni mod",
  lightMode: "Svijetli mod",
  year: "Godina",
  quarter: "Kvartal",
  month: "Mjesec",
  addNewPageInside: "Dodaj novu pod stranicu",
  theme: "Tema",
  boardSettings: "Postavke ploče",
  inbox: "Inbox",
  resolve: "Riješi",
  reactionsToYourComments: "Reakcije na vaše komentare",
  taskIsOverdue: "Zadatak je zakašnjeo",
  endDateIsBeforeStartDate: "Krajnji datum je prije početnog datuma",
  icons: "Ikone",
  emojis: "Emodžiji",
  boardWillNotShowOnPublicPage: "Ploča se neće prikazati na javnoj stranici",
  notInASprint: "Nije u ciklusu",

  // Onboarding
  emailLabel: "Vaš email",
  passwordLabel: "Lozinka",
  checkEmail: "Provjeri email",
  haveSent: "Mi smo poslali ",
  sixDigit: "6 brojeva",
  teamName: "Ime vaše ekipe?",
  spaceNameLabel: "Ime prostora",
  spaceNamePlaceHolder: "npr. web-trgovina",
  min3Characters: "Mora biti minimum 3 karaktera.",
  invite: "Pozovi",
  latest: "Zadnje",
  cardChildrenTitle: "Child kartice",
  members: "Članovi",
  removeFromCard: "Ukloni iz kartice",
  displayName: "Korisničko ime",
  firstName: "Ime",
  lastName: "Prezime",
  update: "Spremi",
  openSuperthread: "Otvori Superthread",
  infoNotification: "Info",
  errorNotification: "Greška",
  alertNotification: "Upozorenje",
  successNotification: "Uspjeh",
  SignInIntoExistingWorkspace: "Prijavi se u postojeći workspace",
  pages: "Stranice",
  gridView: "Grid",
  listView: "Lista",
  member: "Član",
  notMember: "Nije član",
  watch: "Posmatraj",
  unwatch: "Ne posmatraj",
  commentsActivity: "Komentari i aktivnosti",
  show: "Prikaži",
  newestFirst: "Najnovije prvo",
  oldestFirst: "oldest first",
  exploring: "Istraživanje",
  saveAsNewView: "Spasi kao novi pogled",
  noResults: "Nema rezultata",
  rememberChoice: "Zapamti izbor",
  electronOpenInApp: "Otvori u aplikaciji",
  electronOpenInDesktopApp: "Otvori u desktop aplikaciji",
  electronOpenLinksInDesktopApp: "Otvori linkove u desktop aplikaciji",
  electronAutoOpenLinksInDesktopApp:
    "Automatski otvori Superthread linkove u desktop aplikaciji",
  electronCurrentLinkOpenedInApp:
    "Trenutni link je otvoren u desktop aplikaciji",
  electronAppIsInstalled: "Izgleda da imate instaliranu aplikaciju",
  electronUserMentioned: "vas je spomenuo/la",
  electronResourceMoved: "je pomjerio/la",
  electronMemberAdded: "vas je dodao/la u",
  electronMemberRemoved: "vas je uklonio/la iz",
  electronCommentAdded: "je dodao/la novi komentar",
  electronResourceArchived: "je arhivirao/la",
  electronUserReacted: "je reagirao/la:",
  results: "Rezultati",
  tasks: "Zadaci",
  electronRecentlyViewed: "Nedavno posjeceno",
  electronOpenDesktopApp: "Otvori desktop aplikaciju",
  electronRedirectingToApp: "Preusmjeravanje na desktop aplikaciju...",
  connectToImporter: "Poveži se sa %{importerName}",
  accessToken: "Pristupni token",
  installationCloudHostname: "instalacija / cloud ime hosta",
  findInYour: "Pronađi u",
  emailAddressYouUseFor:
    "Email adresu koju koristiš za svoj %{importerName} račun",
  selectWhich: "Odaberi koje",
  selectBoardsToImport: "Izaberi %{boardEq} iz kojih ćeš uvesti %{cardEq}",
  importYourExistingNameToST:
    "Uvezi postojeće %{importerName} %{boardEq} u Superthread",
  superthreadSpace: "Superthread prostor",
  mapImporterUsersToSTUSers:
    "Mapiraj %{importerName} korisnike u Superthread korisnike (ili pozovite one koji fale) da sačuvate korisnike, kreatore i aktivnosti.",
  startImport: "Pokreni uvoz",
  wellLetYouKnowWhenImportFinishes: "Obavijestit ćemo vas kada uvoz završi",
  feelFreeToContuinueUsingST: "Slobodno nastavite koristiti Superthread",
  dontImportThisUser: "Nemoj uvoziti ovog korisnika",
  matchToAnExistingSTUser: "Mapiraj na postojećeg Superthread korisnika",
  createANewUser: "Kreirajte novog korisnika (poziv e-poštom)",
  // importEpics: 'Uvezi epics',
  // importEpicsDesc: "Epics će biti uvezeni u zasebnu Superthread ploču nazvanu 'Epics'.",
  importOpenStories: "Uvezi otvorene priče",
  importOpenStoriesDesc:
    "Neriješene ili otvorene priče bit će uvezene sa postojećim stanjima.",
  importStaleStories: "Uvezi zastarjele priče",
  importStaleStoriesDesc:
    "Priče koji nisu otvorene u više od 6 mjeseci smatraju se zastarjelim. Bit će uvezeni u arhivu i mogu se pretraživati i dearhivirati kasnije.",
  wedLikeToTake: "Želimo vam uzeti",
  thirtySeconds: "30 sekundi",
  toShowYouAround: "da vam pokažemo okolo",
  getStarted: "Počni",
  youCanAlways:
    "Uvijek možete ponovo posjetiti ovaj tutorial iz sekcije pomoći u sidebaru",
  youreGoodToGo: "Spremni ste za početak",
  quickStart: "Brzi start tutorial",
  getToKnow: "Upoznaj Superthread u 30 sekundi",
  desktopApp: "Desktop aplikacija",
  thisLinkWasOpenedInApp: "Ovaj link je otvoren u desktop aplikaciji",
  openHereInstead: "Otvori ovdje umjesto toga",
  browseAndManageSpaces: "Pregledaj i upravljaj svojim prostorima",
  manageSpaces: "Upravljaj prostorima",
  searchSpaces: "Pretraži prostore",
  createSpace: "Kreiraj prostor",
  addADescription: "Dodaj opis",
  showingNumberOfSpaces: "Prikazano je %{num} od ukupno %{totalNum} prostora",
  noResultsFoundFor: 'Nema rezultata koji odgovaraju "%{query}"',
  changeDescription: "Promijeni opis",
  contents: "Sadržaj",
  createSpaceSubtitle:
    "Prostor sadrži povezane ploče, zadatke i stranice. Možda ćete imati prostor po timu ili po poslovnom području.",
  spaceNameAndIcon: "Ime prostora i ikona",
  somethingShortAndClear: "Nešto kratko i jasno",
  youCanChangeThisLater: "Možete promijeniti ovo kasnije",
  descritionOptional: "Opis (opcionalno)",
  whatIsThisSpaceFor: "Za šta je ovaj prostor?",
  addPeopleToSpaceOptional: "Dodaj osobe u ovaj prostor (opcionalno)",
  addPeople: "Dodaj osobe",
  addPeopleSubtitle:
    "Ako dodate osobe koje nisu dio %{workspaceName} workspace-a, one će biti dodani.",
  openSpace: "Javni prostor",
  openSpaceSubtitle:
    "Svi članovi tvog workspace-a mogu pretraživati i pridružiti se prostorima",
  privateSpaceSubtitle:
    "Workspace članovi ne mogu se pridružiti privatnim prostorima osim ako nisu pozvani od strane člana",
  inviteNewPeople: "Pozovi nove osobe",
  inviteeEmailAddress: "Email adresa pozvanog",
  couldntCreateSpace: "Nije moguće kreirati prostor, pokušajte ponovo.",
  spaceCreated: "Prostor je kreiran",
  emailAlreadyAdded: "Email je već dodan",
  addingSomeMembersFailed: "Dodavanje nekih članova nije uspjelo",
  ["my-work"]: "Moj rad",
  newCard: "Nova kartica",
  myWorkAssignedToMe: "Dodijeljeno %{userName}",
  myWorkCreatedByMe: "Kreirano od %{userName}",
  upgradePlan: "Nadogradi plan",
  upgradePrivateSpaceTitle: "Nadogradi za korištenje privatnih space-ova",
  upgradePrivateSpaceDescription:
    "Možete kreirati privatne space-ove na plaćenom planu",
  upgradePlanBadgeTooltip:
    "Samo vlasnik space-a (%{spaceOwner}) i admini mogu mijenjati plan workspace-a",
  upgradeUserRolesTitle: "Nadogradi za postavljanje korisničkih uloga",
  upgradeUserRolesDescription: "Možete birati ne-admin role na plaćenom planu.",
  electronDownloadApp: "Preuzmi aplikaciju",
  electronDownloadAppDescription:
    "Trenutno samo podržavamo macOS. Obavijestite nas da li postoji potražnja i za Windowsom.",
  prStateOpen: "%{count} otvoreno",
  prStateClosed: "%{count} zatvoreno",
  prStateMerged: "%{count} spojeno",
  shortcutWarningText:
    "Shortcut priče koje nisu dodijeljene timu neće biti importovane.",
  language: "Jezik",
  statusType: "Tip statusa",
  resourceAndContentWillBeDeleted:
    '%{resourceType} "%{resourceTitle}" i njegov sadržaj će biti trajno izbrisan za sve. Ovo se ne može poništiti.',
  resourceWillBeDeleted:
    '%{resourceType} "%{resourceTitle}" će biti trajno izbrisan za sve. Ovo se ne može poništiti.',
  listNameLabel: "Ime liste",
  deleteList: "Izbriši listu",
  itemName: "Ime stavke",
  inviteTeamMembersTo: "Pozovi članove time u workspace",
  loggingIn: "Prijavljujemo vas",
  defaultSpaceName: "Podrazumijevano ime prostora",
  onboardingSpaceName: "Dobrodošli 👋",
  loginCodeSendAgain: "Ponovo pošalji kod za prijavu",
  loginCodeResent: "Vaš kod za prijavu je ponovo poslan.",
  loginCodeError: "Neispravan verifikacijski kod za prijavu.",
  loginCodeErrorSending:
    "Došlo je do greške prilikom slanja verifikacijskog koda za prijavu.",
  loginCodeErrorExpired:
    "Vaš verifikacijski kod za prijavu je istekao, poslali smo vam novi.",
  loginCodeErrorRateLimited:
    "Imate previše pokušaja, pokušajte ponovo kasnije.",
  pickAWorkspaceName: "Odaberite ime",
  creatingWorkspace: "Kreiranje workspace-a",
  createaSpace: "Kreiraj prostor",
  subdomainExists:
    "Ovo ime radnog prostora je već zauzeto. Molimo pokušajte ponovo.",
  weSentALoginCode: "Poslali smo kod za prijavu na:",
  sixDigits: "6 cifara kod",
  confTo: "na",
  checkInbox: "Molimo provjerite Vaš inbox.",
  workspaceNameLabel: "Ime workspace-a",
  workspaceNamePlaceHolder: "npr. Acme industries",
  continueWithGoogle: "Nastavi sa Google-om",
  welcomeToSuperThread: "Dobrodošli u Superthread",
  aWorkspaceIs:
    "Workspace se obično imenuje prema vašoj organizaciji ili velikom samostalnom timu. Ovo ime kasnije ne možete promijeniti, ali možete imati više od jednog workspace-a.",
  youCanChangeThis:
    "Ovo možete kasnije promijeniti i napraviti prostora koliko želite.",
  LoginCode: "Kod za prijavu",
  enterLoginCode: "Unesite kod za prijavu",
  continueWithEmail: "Nastavi s email-om",
  registerGoogle: "Registruj se sa Google-om",
  onboardingEmailPlaceholder: "you@example.ba",

  cardsLayoutList: "Lista",
  cardsLayoutBoard: "Board",
  cardsLayoutTimeline: "Vremenska linija",
  cardsLayoutCalendar: "Kalendar (Beta)",

  ["slash.group.media"]: "Mediji",
  ["slash.group.basic"]: "Osnovni",
  ["slash.group.inline"]: "U redu",
  ["slash.group.embed"]: "Ugradi",

  ["slash.keyword.media"]: "priloži,slika,datoteka,učitaj,mediji,prilog",
  ["slash.display.attach"]: "Priloži",
  ["slash.search.attach"]: "priloži",
  "slash.display.image": "Slika",
  "slash.display.youtube": "Ugradi YouTube video",
  "slash.display.checklist": "Čeklista",
  "slash.display.table": "Tabela",
  "slash.display.h1": "H1",
  "slash.display.h2": "H2",
  "slash.display.h3": "H3",
  "slash.display.bulleted": "Lista s crticama",
  "slash.display.numbered": "Numerisana lista",
  "slash.display.blockquote": "Blok citacije",
  "slash.display.hr": "Horizontalna linija",
  "slash.display.card": "Kartica",
  "slash.display.mention": "Označi",
  "slash.display.codeBlock": "Blok koda",
  "slash.display.board": "Tabla",
  "slash.display.callout": "Poziv",

  ["slash.search.image"]: "slika",
  ["slash.search.youtube"]: "youtube video",
  ["slash.search.checklist"]: "čeklista",
  ["slash.search.table"]: "tabela",
  ["slash.search.h1"]: "h1",
  ["slash.search.h2"]: "h2",
  ["slash.search.h3"]: "h3",
  ["slash.search.bulleted"]: "lista s crticama",
  ["slash.search.numbered"]: "numerisana lista",
  ["slash.search.blockquote"]: "blok citacije",
  ["slash.search.hr"]: "horizontalna linija",
  ["slash.search.card"]: "kartica",
  ["slash.search.mention"]: "označi",
  ["slash.search.codeBlock"]: "blok koda",
  ["slash.search.embed"]: "ugrađena ploča",

  "menu.add-column-before": "Dodaj kolonu ispred",
  "menu.add-column-after": "Dodaj kolonu iza",
  "menu.add-row-before": "Dodaj red ispred",
  "menu.add-row-after": "Dodaj red iza",
  "menu.merge-cells": "Spoji/razdvoji ćelije",
  "menu.toggle-header-row": "Uključi/isključi zaglavlje reda",
  "menu.delete-column": "Briši kolonu",
  "menu.delete-row": "Briši red",
  "menu.delete-table": "Briši tabelu",
  "menu.toggle-expand-to-page-size": "Proširi na cijelu stranicu",
  "menu.add-comment": "Dodaj komentar",
  "menu.heading": "Naslov %{level}",
  "menu.bold": "Podebljano",
  "menu.italic": "Kurziv",
  "menu.strikethrough": "Precrtano",
  "menu.underline": "Podvučeno",
  "menu.check-list": "Čeklista",
  "menu.bullet-list": "Lista s crticama",
  "menu.ordered-list": "Numerisana lista",
  "menu.horizontal-rule": "Horizontalna linija",
  "menu.link": "Link",
  "menu.quick-card": "Brza kartica",
  "menu.blockquote": "Blok citacije",
  "menu.codeblock": "Blok koda",
  "menu.code": "Inline kod",
  "menu.undo": "Poništi",
  "menu.redo": "Ponovo",
  "menu.table-cell-color": "Boja ćelije",
  "menu.clear-table-cell-color": "Očisti boju ćelije",
  "menu.align-left": "Poravnaj lijevo",
  "menu.align-center": "Poravnaj po centru",
  "menu.align-right": "Poravnaj desno",
  "editor.clickToDownload": "Klikni da preuzmeš",
  "editor.loading": "Učitavanje",
  "editor.characterLimitReachedTryFile":
    "Dostignuto je ograničenje broja znakova. Za veći sadržaj, slobodno direktno naljepite datoteke.",
  "editor.uploading": "Učitavanje",
  "editor.genericFileError": "Vaša datoteka se nije mogla učitati.",

  // billing
  ["billing.unlimitedMembers"]: "Neograničen broj članova tima",
  ["billing.unlimitedSpaces"]: "Neograničen broj prostora",
  ["billing.unlimitedBoards"]: "Neograničen broj ploča",
  ["billing.unlimitedCardsAndPages"]: "Neograničen broj kartica i stranica",
  ["billing.unlimitedViews"]: "Neograničen broj pogleda",
  ["billing.category.workspaceMembers"]: "Članovi workspace-a",
  ["billing.category.spaces"]: "Prostori",
  ["billing.category.boards"]: "Ploče",
  ["billing.category.cardsAndPages"]: "Kartice i stranice",
  ["billing.category.views"]: "Pogledi",
  ["billing.category.fileSize"]: "Veličina datoteke",
  ["billing.category.privateSpaces"]: "Privatni prostori",
  ["billing.category.userPermissions"]: "Korisničke dozvole",
  ["billing.category.guestAccounts"]: "Gost računi",
  ["billing.noPrivateSpaces"]: "Nema privatnih prostora",
  ["billing.everyoneIsAdmin"]: "Svi su administratori",
  ["billing.noGuestAccounts"]: "Nema gostujućih računa",
  ["billing.5mbFileSizeLimit"]: "5MB je ograničenje veličine datoteke",
  ["billing.noFileSizeLimit"]: "Nema ograničenja veličine datoteke",
  ["billing.unlimitedPrivateSpaces"]: "Neograničen broj privatnih prostora",
  ["billing.2Spaces"]: "2 prostora",
  ["billing.adminRolesAndPermissions"]: "Administratorske uloge i dozvole",
  ["billing.unlimitedCards"]: "Neograničen broj kartica",
  ["billing.sharePagesOnTheWeb"]: "Dijelite stranice na webu",
  ["billing.50Pages"]: "50 stranica",
  ["billing.unlimitedPages"]: "Neograničen broj stranica",
  ["billing.indexPublishedPages"]:
    "Indeksiranje objavljenih stranica u pretraživačima",
  ["billing.privateSpaces"]: "Privatni prostori",
  ["billing.timelineListAndBoardView"]: "Vremenske linija, lista i tabela",
  ["billing.guestAccounts"]: "Gost računi",
  ["billing.monthly"]: "Mjesečno",
  ["billing.yearly"]: "Godišnje (-20%)",
  ["billing.currentPlan"]: "Trenutni plan",
  ["billing.yourChosenPaymentMethodIs"]:
    "Vaš odabrani način plaćanja je %{method}",
  ["billing.thisIsThePaymentMethod"]:
    "Ovo je način plaćanja koji ćemo koristiti za buduće uplate. Možete ga promijeniti u bilo kojem trenutku.",
  ["billing.billing"]: "Naplata",
  ["billing.planAndBilling"]: "Plan i naplata",
  ["billing.paymentMethod"]: "Način plaćanja",
  ["billing.cardEndingIn"]: "%{cardType} završava na %{last4}",
  ["billing.manageBillingDetails"]: "Upravljanje detaljima naplate",
  ["billing.updatePaymentDetails"]: "Ažuriranje detalja plaćanja",
  ["billing.sendNewInvoicesTo"]: "Pošalji nove fakture na",
  ["billing.previousInvoices"]: "Prethodne fakture",
  ["billing.plan"]: "Plan",
  ["billing.manageWhichPlan"]: "Upravljaj koji plan koristi prostor",
  ["billing.standard"]: "Standardni",
  ["billing.changePlan"]: "Promijenite plan",
  ["billing.free"]: "Besplatno",
  ["billing.upgrade"]: "Unaprijedi",
  ["billing.noPaymentMethod"]: "Nema načina plaćanja",
  ["billing.thereIsNoPaymentMethod"]:
    "S ovim radnim prostorom nije povezan nijedan način plaćanja. Način plaćanja će se pojaviti ovdje čim odaberete plaćeni plan.",
  ["billing.selectAPaidPlan"]: "Odaberite plaćeni plan",
  ["billing.upgradePlan"]: "Pređi na ovaj plan",
  ["billing.downgradePlan"]: "Spusti se na ovaj plan",
  ["billing.downgradeToFree"]: "Spusti se na besplatni plan",
  ["billing.viewYourPaymentMethodInStripe"]:
    "Pogledajte svoj način plaćanja u Stripe-u",
  ["billing.weBillTheWorkspacePayment"]:
    "Naplaćujemo način plaćanja workspace-a kada se prihvati poziv.",
  ["billing.checkThePlanPanel"]:
    "Provjerite panel plana za procjenu troškova po sjedištu.",
  ["billing.12"]: "$12",
  ["billing.10"]: "$10",
  ["billing.perUserPerMonth"]: "/ korisnik / mjesec",
  ["billing.billedYearly"]: "naplaćuje se godišnje",
  ["billing.planStatus"]: "Status plana",
  ["billing.yourCurrentPlanIsNotSetToRenew"]:
    "Vašem trenutnom planu nije postavljeno automatsko obnavljanje",
  ["billing.on"]: "Na",
  ["billing.dateYourWorkspaceWillDowngrade"]:
    "Vaš radni prostor će se vratiti na besplatni plan na %{date}. Do tada još možete pozvati ljude u ovaj workspace, ali nećete moći premašiti limit od",
  ["billing.workspaceMembers"]: "članova workspace-a",
  ["billing.turnRenewalBackOn"]: "Ponovno uključite automatsko obnavljanje",
  ["billing.youCanStillInvite"]:
    "I dalje možete pozvati ljude u ovaj workspace, ali ne možete premašiti limit od",
  ["billing.workspaceFullError"]:
    "Dostignut je limit članova workspace-a. Administrator workspace-a može ga povisiti.",
  ["billing.genericJoinError"]: "Nije bilo moguće pridružiti se workspace-u.",
  ["billing.startsOn"]: "Počinje na %{date}",
  ["billing.switchToYearly"]: "Prebaci se na godišnje (-20%)",
  ["billing.switchToMonthly"]: "Prebaci se na mjesečno",
  ["billing.metadata"]: "Sve u %{plan}, plus...",
  ["billing.talkToOurExperts"]: "Razgovarajte sa našim stručnjacima",
  ["billing.samlAndScim"]: "SAML & SCIM",
  ["billing.auditLogs"]: "Evidencije revizije",
  ["billing.customBilling"]: "Prilagođeno naplaćivanje",
  ["billing.prioritySupport"]: "Prioritetna podrška",
  ["billing.unlimitedChildCards"]: "Neograničen broj child kartica",
  ["billing.publishPagesToTheWeb"]: "Objavi stranice na webu",
  ["billing.calendarLayout"]: "Raspored kalendara",
  ["billing.advancedSearch"]: "Napredna pretraga",
  ["billing.views"]: "Pogledi",
  ["billing.timelineLayout"]: "Raspored vremenske linije",
  ["billing.liveChatSupport"]: "Podrška putem chata uživo",

  // global
  ["global.text.create"]: "Kreiraj",
  ["option.label.cards"]: "Kartice",
  ["option.label.pages"]: "Stranice",
  ["option.label.boards"]: "Ploče",
  ["option.label.epics"]: "Projekti",
  ["option.label.spaces"]: "Prostori",
  ["option.label.showArchived"]: "Prikaži arhivirano",
  ["search.message.noResults"]: "Ništa nije pronađeno",
  ["global.text.discardDraft"]: "Odbaci nacrt",

  // ---------------------------------------------------

  switchAccount: "Switch account",
  all: "All",
  searchPlaceholder: "Search or ask a question...",
  replyToComment: "Reply to comment...",
  join: "Join",
  couldntJoinSpace: "Could not join space, try again later.",
  cardArchivedByCard: "Card is archived.",
  cardArchivedByList:
    "Card is part of an archived list. Move to active list to restore.",
  cardArchivedByBoard:
    "Card is part of an archived board. Move to active board to restore.",
  isArchived: "is archived",
  project: "space",
  teamId: "team id",
  archiveResource: "Archive %{type}",
  restoreResource: "Restore %{type}",
  deleteResource: "Delete %{type}",
  deleteSuccess: "%{name} %{type} is deleted",
  archiveSuccess: "%{name} %{type} is archived",
  restoreSuccess: "%{name} %{type} is restored",
  deleteError: "Couldn't delete %{name} %{type}",
  archiveError: "Couldn't archive %{name} %{type}",
  restoreError: "Couldn't restore %{name} %{type}",
  addLink: "Add link",
  couldntDeleteComment: "Could not delete comment, please try again!",
  couldntLoadComments: "Could not load comments.",
  commentOnPage: "Comment on page",
  emailPlaceholder: "e. g. yourname@yourcompany.com",
  addProject: "Add project",
  roboto: "Roboto",
  sansserif: "Sans Serif",
  serif: "Serif",
  mono: "Mono",
  monospace: "Monospace",
  upload: "Upload",
  paste_image_link: "Paste image link",
  embed_image: "Embed image",
  drag_and_drop: "Drag and drop",
  supported_files: "Supported files",
  maximum_size: "Maximum size",
  newPage: "New page",
  addNewPage: "Add new page",
  attachFrom: "Attach from...",
  searchUnsplash: "Search Unsplash",
  fullWidth: "Full width",
  largeText: "Large text",
  space___: "Space...",
  cannotExcludeAll: "Cannot exclude all",
  mustIncludeAtLeastOne: "Must include at least one",
  type: "Type",
  noResultsFound: "No results found",
  cardStatus: "Card status",
  thisSpaceIsPrivate: "This space is private",
  hiddenMember: "Hidden member",
  hiddenMemberDesc: "This person does not share any spaces with you",
  enterResourceTitle: "Enter %{type} title...",
  openCardInBoard: "Open card in board",
  cardsAdded: "Cards added",
  cardsFinished: "Cards finished",
  cardsAddedBetween: "Unique cards added between",
  cardsAddedTo: "Unique cards added to",
  moreCardsAddedThanFinished: "%{number} more cards were added than finished",
  sameNumberOfCardsAddedAndFinished:
    "The same number of cards were added and finished",
  moreCardsFinishedThanAdded: "%{number} more cards were finished than added",
  oneMoreCardAddedThanFinished: "1 more card was added than finished",
  oneMoreCardFinishedThanAdded: "1 more card was finished than added",
  couldntResendLink: "Couldn't resend the invite link.",
  thereAreNoFreeSeatsForThisWorkspace:
    "There are no free seats for this workspace",
  thisWorkspaceCantAcceptAnyMoreMembers:
    "This workspace cannot accept any more members. A workspace admin can raise the limit, or an existing member can leave the workspace to open a seat.",
  links: "Links",
  createNewView: "Create new view",
  newView: "New view",
  workspace: "Workspace",
  views: "Views",
  roadmap: "Roadmap",
  private: "Private",
  lastUpdate: "Last update",
  viewType: "View type",
  filters: "Filters",
  filter___: "Filter...",
  filters___: "Filters...",
  filterBy: "Filter by",
  filter: "Filter",
  content: "content",
  status: "Status",
  subscriber: "subscriber",
  creator: "creator",
  tag: "Tag",
  subscribers: "subscribers",
  creators: "creators",
  shareWithWorkspace: "Share with workspace",
  discard: "Discard",
  notificationCreated: "%{name} created",
  notificationAdded: "%{name} added",
  typeContent: "Type a content",
  ["global.placeholder.focusedStatePlaceholder"]:
    "@ to mention anything, / for commands...",
  ["global.placeholder.focusedStatePlaceholderMobile"]:
    "@ to mention, / for commands...",
  checkListItemPlaceholder: "@ to mention anything...",
  assignees: "Assignees",
  no_assignee: "No assignee",
  inThisSpace: "In this space",
  invitationsFailed: "Invitations failed!",
  boardMovedToSpace: "Board moved to space",
  pageMovedToSpace: "Page moved to space",
  boardNotMoved: "Moving board cancelled.",
  pageNotMoved: "Moving page cancelled.",
  newTag: "New tag",
  toggleSection: "Toggle section",
  toggleContent: "Empty section. Click to write or copy content here.",
  duplicateBoard: "Duplicate board",
  duplicateBoardDescription:
    "Any cards in this board will not be duplicated. Choose a space and name for the duplicated board.",
  boardDuplicated: "Board duplicated",
  boardDuplicateFailed: "Failed to duplicate board",
  changeCardParent: "Change card parent",
  changeParent: "Change parent",
  changeParentDescription:
    "This card has “%{card_title}” as a parent. Do you want to change the parent to the current card?",
  shareToWeb: "Share to web",
  embedVideo: "Embed Youtube video",
  removePullRequest: "Remove pull request",
  viewOnGitHub: "View on GitHub",
  setUpGHIntegration: "Set up GitHub integration",
  integrateSuperthread: "Integrate Superthread into your favorite git client.",
  githubIntegradionDescripiton:
    "Link Superthread cards to GitHub pull requests. Include a Superthread Card-ID (e.g ST-123) in your branch name/s or pull request title/s to automatically show the statuses of the PRs in the Card.",
  connectGithub: "Connect GitHub",
  connectedAccounts: "Connected accounts",
  connectGhToSuperthread: "GitHub connected to Superthread",
  enabledBy: "Enabled by",
  select: "Select",
  github_pull_request: "GitHub",
  importBoards: "Import boards",
  selectWhichBoards: "Select which boards from",
  quickImport: "Quick import",
  importBoardIntoExsistingSpace: "Custom import",
  map: "Map",
  importAs: "Import as...",
  person1Email: "person1@example.com, person2@example.com…",
  createdDate: "Created date",
  updatedDate: "Updated date",
  goToParentCard: "Go to parent card",
  discardAndClose: "Discard and close",
  changeStatus: "Change status",
  createCardsInSelectedBoard: "Always create cards in the selected board",
  createCardIn: "Create card in",
  noduedate: "No due date",
  ["now+2d"]: "2 days from now",
  ["now+3d"]: "3 days from now",
  ["now+1w"]: "1 week from now",
  ["now+2w"]: "2 weeks from now",
  ["now+3w"]: "3 weeks from now",
  ["now+1M"]: "1 month from now",
  ["now+2M"]: "2 months from now",
  ["now+3M"]: "3 months from now",
  ["now+6M"]: "6 months from now",
  ["now+1y"]: "1 year from now",
  now: "Today",
  nowActivity: "now",
  ["now-1h"]: "1 hour ago",
  ["now-4h"]: "4 hours ago",
  ["now-1d"]: "Yesterday",
  ["now-2d"]: "2 days ago",
  ["now-3d"]: "3 days ago",
  ["now-1w"]: "1 week ago",
  ["now-2w"]: "2 weeks ago",
  ["now-3w"]: "3 weeks ago",
  ["now-1M"]: "1 month ago",
  ["now-2M"]: "2 months ago",
  ["now-3M"]: "3 months ago",
  ["now-6M"]: "6 months ago",
  ["now-1y"]: "1 year ago",
  inviteToWorkspace: "Invite people to the %{workspaceName} workspace",

  addNewBoardOrPage: "Add new Board or Page",
  spaceSettings: "Space settings",
  addToFavorites: "Add to favourites",
  removeFromFavorites: "Remove from favourites",
  viewmoreassignees: "View more assignees",
  noassignee: "No assignee",
  currentuser: "Current user",
  aPrivateSpace: "a private space",
  youAreTheOnlyPersonInThisPrivateSpace:
    "You are the only person in this private space, if you leave, no-one will be able to access it. If your organisation still needs access, invite someone to join before you leave.",
  whenYouLeaveAPrivateSpace: `When you leave a private space, you'll no longer be able to see any of its boards or pages. To rejoin, you'll need to be invited again.`,
  youCanRejoinThePublicSpace:
    "You can rejoin the space from the browse spaces screen.",

  deleteItem: "Delete %{item}",
  ifYouWantToDeleteSpace:
    "If you want to delete this space, type its name below.",
  unsubscribedFromResourceUpdates: "Unsubscribed from %{name} updates",
  subscribingToResourceUpdatesFailed: "Subscribing to %{name} updates failed",
  unsubscribingFromResourceUpdatesFailed:
    "Unsubscribing from %{name} updates failed",
  editStatus: "Edit status",
  editName: "Edit name",
  numberOfCards: "Number of cards",
  viewSpace: "View space",
  deleted: "%{name} deleted",
  leaveNamedSpace: "Leave %{name} space?",
  leaveNamedPrivateSpace: "Leave %{name} private space?",
  deleteAndLeaveNamedPrivateSpace: "Delete and leave %{name} private space?",
  youLeftNamedSpace: "You left the %{name} space.",
  youCannotLeaveTheSpace: "You cannot leave this space",
  enableScrollFocus: "Show current item in sidebar",
  addNewFolder: "Create folder",
  deletedSuccesfully: "removed from favourites",
  addedSuccesfully: "added in favourites",
  changedParentCardFrom: "changed parent card from",
  addChildPage: "Add subpage",
  reaction: "Reaction",
  unresolved: "Unresolved",
  unresolve: "Unresolve",
  unresolvedOnly: "Unresolved only",
  resolved: "Resolved",
  unresolveComment: "Unresolve comment",
  resolveComment: "Resolve comment",
  commentResolved: "Comment resolved",
  commentUnresolved: "Comment unresolved",
  resolvedOnly: "Resolved only",
  allComments: "All comments",
  noUnresolvedComments: "No unresolved comments",
  noResolvedComments: "No resolved comments",
  noComments: "No comments",
  about: "About",
  markAsRead: "Mark as read",
  markAsUnread: "Mark as unread",
  markAllAsResolved: "Mark all as resolved",
  showUnresolved: "Show unresolved",
  showResolved: "Show resolved",
  noNotifications: "No notifications",
  noNewNotifications: "No new notifications",
  noUnresolvedNotifications: "No unresolved notifications",
  youCanShow: "You can show",
  notificationsInstead: "notifications instead",
  subscribeToGetNotifications:
    "Subscribe to something and you'll get notifications when there's activity",
  selectANotificationToViewIt: "Select a notification to view it",
  youCanMarkANotificationAs: "You can mark a notification as",
  unreadOr: "unread or",
  resolveIt: "resolve it",
  inboxNotificationsAreUnresolved:
    "Notifications are “unresolved” if you haven't marked them as resolved",
  notificationsAreNew:
    "Notifications are “new” if you haven't seen them before",
  wantNotificationsIn: "Want notifications in",
  slaskQuestionMarkVisit: "Slack? Visit",
  noCardsMatchChosenFilter:
    "There are currently no cards that match the chosen filters",
  noCardsFound: "No cards found",
  boardMoved: "Board moved",
  pageMoved: "Page moved",
  openPage: "Open page",
  hasBeenDeleted: "has been deleted",
  deletedResourcePlain: "This resource has been deleted.",
  deletedResourceWithName: "This %{name} has been deleted.",
  this: "This",
  andTheEntire: "and the entire",
  youWereRemoved: "You were removed",
  fromPrivateSpace: "from a private space",
  privateSpaceDesc:
    "This space is private so you can no longer see its name or contents",
  privateSpace: "Private space",
  everything: "Everything",
  moveCardIntoBoard: "Card moved to board",
  inList: "in list",
  searchForParentCard: "Search for parent card",
  custom: "Custom",
  moveToBoard: "Move to board",
  previous: "Previous",
  manualOrder: "Manual order",
  sortedBy: "Sorted by",
  toCancelDrag: "to cancel drag",
  groupBy: "Group by",
  subpageCreated: "Subpage created",
  tableOfContents: "Table of contents",
  editWorkspaceTagsInSettings: "Edit workspace tags in Settings",
  sideDocked: "Side docked",
  modalOverlay: "Modal overlay",
  cardLayout: "Card layout",
  switchLayout: "Switch layout",
  showSidebar: "Show sidebar",
  notags: "No tags",
  resetLayoutToBoardDefault: "Reset layout to board default",
  alreadyOpen: "%{resource} already open",
  defaultBoardLayout: "Default board layout",
  defaultBoardLayoutDescription:
    "Everyone will see this layout by default. This setting can be changed later.",
  boardDescription: "Cards are grouped into columns",
  listDescription: "Cards are in a vertical list, split into groups",
  timelineDescription: "A timeline based on start and due dates",
  calendarDescription: "Cards are placed on their due date",
  boardName: "Board name",
  memberRemoved: "Member removed",
  resetLayoutToViewDefault: "Reset order to default",
  earliestDueDate: "Earliest due date",
  highestPriority: "Highest priority",
  largestEstimate: "Largest estimate",
  STIsMostUseful: "Superthread is most useful when you work with others.",
  readOnly: "Read only",
  removeBoard: "Remove board",
  noSprints: "Sprints will be listed here from latest to earliest",
  noNonSprintBoardsInThisSpace: "No non-sprint boards in this space",
  inviteToWorkspaceDescription:
    "To add existing members to a space, go to space settings",
  alreadyMembersOfWorkspace:
    "Some people are already in the workspace. They'll be added to any relevant spaces chosen below.",
  information: "Information",
  success: "Success",
  error: "Error",
  warning: "Warning",
  typeSomething: "Type something...",
  childCards: "Child cards",
  preferences: "Preferences",
  lastCreated: "Last created",
  lastUpdated: "Last updated",
  searchMembers: "Search members",
  or: "Or",
  add_collaborators: "Add Collaborators",
  selectWorkspace: "Select a workspace",
  selectWorkspaceIntegrations: "Select a workspace for integration",
  change: "Change",
  createNewWorkspace: "Create new workspace",
  notSeeingYourWorkspace: "Not seeing your workspace? Try changing your email:",
  dismiss: "Dismiss",
  load: "Load",
  youAlreadyHave: "You already have",
  openBoard: "Open board",
  cardCannotBeMovedDirectlyToSpace:
    "Card can not be moved directly into space.",
  clickToRename: "Click to rename",
  info: "Info",
  clearAllFilters: "Clear all filters",
  is_not: "is not",
  includes: "includes",
  excludes: "excludes",
  print: "Print",
  reactedWith: "reacted with",
  you: "you",
  updateAppToEditPage: "Please update app to edit page",
  updateAppToEditComment: "Please update app to edit comment",
  updateAppToEditCard: "Please update app to edit card",
  jiraBoardMapingSubtitle: "Select which boards from Jira you want to import.",
  trelloBoardMapingSubtitle:
    "Select which boards from Trello you want to import.",
  shortcutBoardMapingSubtitle:
    "Select the teams and workflows that you would like to import stories from.",
  jiraQuickImportText:
    "All teams will be imported into a space called 'jira-import', you can easily rename and reorganise your boards from there.",
  trelloQuickImportText:
    "All teams will be imported into a space called 'trello-import', you can easily rename and reorganise your boards from there.",
  shortcutQuickImportText:
    "Each 'team-workflow' board will be imported into a space called 'shortcut-import', you can easily rename and reorganise your boards from there.",
  jiraCustomImportText:
    "Choose which boards to import, and which spaces they should be imported to.",
  trelloCustomImportText:
    "Choose which boards to import, and which spaces they should be imported to.",
  shortcutCustomImportText:
    "Choose which 'team-workflow' boards to import, and which spaces they should be imported to.",
  projectsCannotBeMovedToSpaces: "Projects cannot be moved to spaces",
  founder: "Founder",
  director: "Director",
  teamLead: "Team lead",
  individualContributor: "Individual contributor",
  softwareEngineering: "Software engineering",
  design: "Design",
  productManagement: "Product management",
  marketing: "Marketing",
  finance: "Finance",
  development: "Development",
  marketer: "Marketer",
  sales: "Sales",
  clickToView: "Click to view",
  clickToDownload: "Click to download",
  business: "Business",
  pickAllThatApply: "Pick all that apply",
  pickOne: "Pick one",
  customerSupport: "Customer support",
  humanResources: "Human resources",
  socialMedia: "Social media",
  wordOfMouth: "Word of mouth",
  searchEngine: "Search engine",
  advertising: "Advertising",
  searchForSpaceOrBoard: "Search for space or board",
  starTypingToSearchFor: "Start typing to search for",
  myWorkNoResultsCreatedByMe: "There are no cards created by you",
  myWorkNoResultsAssignedToMe: "There are no cards assigned to you",
  memberNoResultsAssignedToMe: "There are no cards assigned to %{userName}",
  memberNoResultsCreatedByMe: "There are no cards created by %{userName}",
  addedCommentHiddenByFilter: "Added comment is hidden by filter",
  createdCardHiddenByFilter: "Created card may be hidden by filter",
  viewWork: "View work",
  removeFromSpace: "Remove from space",
  assignedInThisBoard: "Assigned in this board",
  layout: "Layout",
  createdCardMovedSortOrder: "Created card may be moved by sort order",
  createCardGroupBy: "Card added to %{list}.",
  canNotMoveCardInsameBoard: "Can not move card in same board.",
  latestReply: "Latest reply",
  replyLabel: "Reply",
  totalReplies: "total replies",
  olderReplies: "older replies",
  leaveReply: "Leave a reply...",
  hideReplies: "Hide replies",
  showReplies: "Show replies",
  oneReply: "reply",
  discardComment: "Discard comment?",
  areYouSureYouWantToDiscard: "Are you sure you want to discard your comment?",
  skipToEnd: "Skip to end",
  priority: "Priority",
  noPriority: "No priority",
  urgent: "Urgent",
  high: "High",
  medium: "Medium",
  low: "Low",
  priorities: "Priorities",
  changedThePriorityFrom: "changed the priority from",
  changedTheEstimateFrom: "changed the estimate from",
  setThePriorityTo: "set the priority to",
  setTheEstimateTo: "set the estimate to",
  removedTheEstimate: "removed the estimate",
  thereAreNoPages:
    "There are no pages in this space. Create a new page, or drag an existing page into this space in the sidebar.",
  thereAreNoBoards:
    "There are no boards in this space. Create a new board, or drag an existing board into this space in the sidebar.",
  commentsOnly: "Comments only",
  activityOnly: "Activity only",
  seeCardsWithThisTag:
    "See cards with this tag (count includes cards that might not show elsewhere)",
  noResultsForThatName: "No results for that name",
  youCan: "You can",
  createASpace: "create a space",
  named: 'named "%{query}"',
  estimate: "Estimate",
  onePoint: "1 point",
  numberOfPoints: "%{num} points",
  extraSmall: "Extra small",
  small: "Small",
  mediumSize: "Medium",
  large: "Large",
  extraLarge: "Extra large",
  noEstimate: "No estimate",
  settingsProjectsPreferencesSubtitle:
    "These settings will affect all members of the space",
  howCardsAreEstimated: "How cards are estimated in this space",
  disableCardEstimationForThisSpace: "Disable card estimation for this space",
  fibonacciPoints: "Fibbonaci points",
  exponentialPoints: "Exponential points",
  tshirtSizes: "T-shirt sizes",
  setEstimate: "Set estimate",
  emailNotificationHelperText:
    "An email every weekday with any notifications you haven't seen since the last email",
  estimated: "estimated",
  cardSpaceEstimationTurnedOff:
    "This card belongs to a space with estimation turned off",
  totalEstimatePointsTooltipContent:
    "%{totalPoints} estimated across %{numOfCards}",
  estimates: "estimates",
  assignItTo: "assign it to",
  searchForACard: "Search for a card",
  createACard: "Create a card",
  archivedCardsAreHidden: "archived cards are hidden",
  enterANameAbove: "Enter a name above",
  chooseFiltersYouWouldLike:
    "Then choose the filters you'd like in the filter bar",
  cannotCreateViewOnMobile: "You cannot create a view on mobile.",
  viewCardInBoard: "View card in its own board",
  guestsMustBeAddedToOneSpace: "Guests must be added to at least one space",
  createCard: "Create card",
  suggestedBasedOnTitle: "Suggested based on title",
  acceptSuggestion: "Accept suggestion",
  rejectSuggestion: "Reject suggestion",
  suggestionPlaceholderText: "Suggestion...",
  changeEmail: "Change email",
  logOutAndContinue: "Log out and continue",
  confirmAccountOwnership: "Confirm account ownership",
  reauthenticateEmailDescription:
    "To keep your account secure, we need you to log in to the app again. After logging in, you'll be able to choose a new email address and complete the process.",
  enterANewEmail: "Enter a new email address:",
  resendLoginCode: "Resend login code",
  emailAddressTakenByAnotherUser: "Email address taken by another user",
  assistant: "Assistant",
  changeTone: "Change tone",
  simplify: "Simplify",
  summarize: "Summarise",
  translate: "Translate",
  generate: "Generate",
  replaceText: "Replace text",
  insertBelow: "Insert below",
  assistanceWith: "What do you need assistance with?",
  copiedToClipboard: "Copied to clipboard",
  academic: "Academic",
  casual: "Casual",
  confident: "Confident",
  friendly: "Friendly",
  neutral: "Neutral",
  professional: "Professional",
  aiFeatures: "AI features",
  emailDigestSentAt: "Email digest at",
  inYourTimezone: "in your timezone (%{timezone})",
  enableNotificationsFirst: "Enable %{type} notifications first",
  turnOnAIAssitantInFormatingToolbar:
    "Turn on AI assistant in the text formatting toolbar",
  superthreadSendingDataTo:
    "Note that by enabling this for your workspace you consent to Superthread sending data to",
  experimentalFeatureMayChangeFunctionality:
    "This experimental feature may be subject to change in functionality and pricing.",
  contactUsToEnable: "Contact us to enable this feature.",
  boardOpenedInTheBackground: "%{boardTitle} board opened in the background",
  resetFilters: "Reset filters",
  ["create_space.title"]: "Create a space",
  ["create_space.tooltip"]: "Create a home for your team's work",
  ["create_private_space.title"]: "Create a private space",
  ["create_private_space.tooltip"]:
    "Only people you invite can see a private space",
  ["invite_user.title"]: "Invite someone else",
  ["invite_user.tooltip"]:
    "Invite your team-mates to the workspace so they can track their work",
  ["mention_anything.title"]: "Mention something",
  ["mention_anything.tooltip"]:
    "Use the @ key to mention something, anywhere you can write",
  ["add_child_card.title"]: "Add a child card",
  ["add_child_card.tooltip"]:
    "Child cards help you break work down into smaller tasks",
  ["visit_inbox.title"]: "Check your inbox",
  ["visit_inbox.tooltip"]:
    "Keep track of everything you're subscribed to in the inbox",
  ["move_page.title"]: "Move a page",
  ["move_page.tooltip"]:
    "Drag a page in the sidebar to move it wherever you want it",
  ["create_subpage.title"]: "Create a subpage",
  ["create_subpage.tooltip"]:
    "Subpages live inside other pages and help you structure your documents",
  ["add_page_icon.title"]: "Add a page icon",
  ["add_page_icon.tooltip"]:
    "A page icon helps you find the page again in search and the sidebar",
  ["add_page_cover.title"]: "Add a page cover image",
  ["add_page_cover.tooltip"]: "Set the tone for a page with a cover image",
  ["quick_card_shortcut.title"]: "Quick card shortcut (C)",
  ["quick_card_shortcut.tooltip"]: "Tap the C key anywhere to create a card",
  ["quick_page_shortcut.title"]: "Quick page shortcut (P)",
  ["quick_page_shortcut.tooltip"]: "Tap the P key anywhere to create a page",
  ["create_card.title"]: "Create a card",
  ["create_card.tooltip"]: "Create a card for each task you want to track",
  ["comment_on_card.title"]: "Comment on a card",
  ["comment_on_card.tooltip"]:
    "Write updates or note down your thoughts on a card",
  ["search_shortcut.title"]: "Find something with ⌘+K",
  ["search_shortcut.tooltip"]:
    "Quickly open universal search anywhere with this shortcut",
  ["create_board.title"]: "Create a board",
  ["create_board.tooltip"]: "Track the work of a sub-team or project",
  ["upload_avatar.title"]: "Upload avatar",
  ["upload_avatar.tooltip"]: "Help people recognise you around the app",
  ["create_page.title"]: "Create a page",
  ["create_page.tooltip"]: "Capture knowledge and thoughts with pages",
  ["set_your_name.title"]: "Set your name",
  ["set_your_name.tooltip"]: "Your name will be used throughout the app",
  aCardMustHaveATitle: "A card must have a title",
  showAll: "Show all",
  showLess: "Show less",
  hideEmptyGroups: "Hide empty groups",
  showAnotherAssignee: "Show another assignee",
  showAnotherTags: "Show another tags",
  spaceMembers: "Space members",
  addExistingMembers: "Add existing members",
  inviteNewMembers: "Invite new members",
  spaceDetails: "Space details",
  makeBoardFullWidth: "Make board full width",
  askAiAssistantSearch: "Ask AI based on your cards and pages",
  backToSearchResults: "Back to search results",
  sources: "Sources",
  askAiQuestionLong: "Question should have at least 10 chars long.",
  spaceSprintsSettings: "%{space} space sprints settings",
  turnOnSprints: "Turn on sprints for this space",
  turnOnSprintsDesc:
    "A “Sprints” section will be added to the sidebar for this space. A sprint is a board with a start and end date. When one sprint is completed, the next will start automatically.",
  ownersAdminsCanTurnOnSprints:
    "Only workspace owners, admins, and the creator of the space can turn on sprints",
  sprintLength: "Sprint length",
  weeks: "weeks",
  sprintStartOn: "Sprints start on",
  coolDownPeriod: "Cool-down period between sprints",
  coolDownPeriodDesc:
    "A cool-down period will be added between each sprint. These are useful for e.g. retrospectives and clean-up activities.",
  coolDownPeriodLength: "Cool-down period length",
  sprintBoardStatuses: "Sprint board statuses",
  sprintBoardStatusesDesc:
    "Every sprint board in this space uses the same statuses. You must have at least one of each type of status. The “Backlog” status type is not available.",
  addStatus: "Add status",
  dueInDays: "Due in %{days} days",
  sprints: "Sprints",
  addSprint: "Add sprint",
  sprint: "Sprint",
  openSprint: "Open sprint",
  renameSprint: "Rename sprint",
  markAsComplete: "Mark as complete",
  changeSprintDates: "Change sprint dates",
  cancelSprint: "Cancel sprint",
  changeDates: "Change dates",
  chooseNewStartAndEndDates: "Choose new start and end dates for the sprint.",
  renameSprintDescription: "Enter a new name for the sprint.",
  startDateIsEarlierThanPreviousEndDate:
    "Start date is earlier than previous end date.",
  enterSprintName: "Enter sprint name",
  cancelSprintWarning:
    "All unfinished cards in this board will be moved into the cancelled status.",
  dontCancel: "Don't cancel",
  sprintSettings: "Sprint settings",
  macArm64Label: "Apple Silicon",
  macx64Label: "Apple Intel",
  mailCopiedToClipboard: "Mail copied to clipboard.",
  cardsWithNoSprint: "Cards with no sprint",
  showCardsFrom: "Show cards from",
  yourColor: "Your color",
  thisColorWillHelp:
    "This colour will help others identify you in some places.",
  logo: "Logo",
  upgradePublicPageIndexingTitle: "Upgrade for search engine indexing",
  upgradePublicPageIndexingDescription:
    "You can turn on search engine indexing on a paid plan.",
  coolDown: "Cool-down",
  noBoardsOrPages: "No boards or pages",
  usersWork: "%{name}'s work",
  renameAttachment: "Rename attachment",
  timelineLayoutDescription:
    "Upgrade your workspace plan to use the timeline layout.",
  upgradeViewsDescription: "Upgrade your workspace plan to save views.",
  createNewItem: "Create new item",
  spaceLimitReached:
    "The space limit has been reached. You can delete some spaces to create more.",
  freePlanUsageLimits: "Free plan usage limits",
  item: "Item",
  usage: "Usage",
  limitReachedLong:
    "If a limit is reached, you will need to remove items or upgrade the plan before new items can be created.",
  limitReached: "Limit reached",
  uploadFailedClickToRetry: "Upload failed, click to retry",
  actionFailed: "Action failed",
  createAndManageSpaces: "Create and manage spaces",
  thereAreNoListInBoard: "There are no lists in board.",
  pageMovedToParent: "Page moved to parent",
  subscribedToResourceUpdates: "Subscribed to %{name} updates",
  thisFilterDoesNotMatch: "This filter does not currently match any cards",
  inviteSectionSubtitle:
    "They'll be invited to the whole workspace, not just this space.",
  invitingPeopleToWorkspace:
    "Only admins can invite new people to this workspace",
};

export default bs;
