import { Translations } from "../types";

const bs: Translations = {
  search: "Pretraga...",
  close: "Zatvori",
  send: "Pošalji",
  resendInviteLink: "Pošalji ponovo link",
  addComment: "Dodaj komentar",
  comment: "komentariši",
  writeComment: "Napiši comment...",
  comments: "KOMENTARI",
  createBoard: "Kreiraj Kanban Tablu",
  createPage: "Kreiraj Stranicu",
  delete: "Izbriši",
  edit: "Uredi",
  remove: "Izbriši",
  done: "Gotovo",
  enterBoardTitle: "Unesite naziv boarda",
  create: "Kreiraj",
  untitled: "Nenaslovljeno",
  containsNoContent: "Bez sadržaja.",
  ama: "AMA",
  me: "Ja",
  assigned: "dodjeljeno",
  mentions: "pominjanja",
  visited: "posjećeno",
  saved: "sačuvano",
  notifications: "Obavijesti",
  selectWhereWwhenWillNotified: "Odaberite gdje i kada ćete biti obaviješteni",
  recivePersonalNotification: "Primajte lična obavještenja u Slacku",
  notifyMe: "Obavijesti me kada",
  save: "Sačuvaj",
  saveChanges: "Sačuvaj Izmjene",
  archived: "arhivirano",
  archive: "Arhiviraj",
  cardArchived: "Ova kartica je arhivirana.",
  cellMerge: "Spajanje ćelija",
  new: "NOVI",
  view: "Pogled",
  signOut: "Odjava",
  leave: "Napusti",
  browseAllSpaces: "Pretražuj sve projekte",
  preview: "Pregledaj",
  goToCard: "Idi do kartice",
  zoomIn: "Uvećaj",
  zoomOut: "Umanji",
  notFoundPageHeader: "Naišli smo na problem...",
  notFoundPageContent:
    "Nismo sigurni šta nije uredu. Možete se vratiti nazad na prethodnu stranicu ili kontaktirati službu za podršku.",
  addCard: "Dodaj karticu",
  next: "Sledeci",
  addToCard: "Dodaj u karticu",
  checklist: "Čeklista",
  moveList: "Pomjeri listu",
  board: "Board",
  timeline: "Timeline",
  templates: "Predlošci",
  cardTemplates: "Predlošci kartica",
  pageTemplates: "Predlošci stranica",
  saveCardContentYouRepeatedlyUse:
    "Sačuvajte sadržaj koji često koristite i primijenite ga kada kreirate kartice",
  savePageContentYouRepeatedlyUse:
    "Sačuvajte sadržaj koji često koristite i primijenite ga kada kreirate stranice",
  createCardTemplate: "Kreirajte predložak kartice",
  editCardTemplate: "Uredite predložak kartice",
  searchTemplates: "Pretražite predloške",
  name: "Naziv",
  noCardTemplates: "Nema predložaka kartica",
  noPageTemplates: "Nema predložaka stranica",
  calendar: "Kalendar",
  showAllCards: "Prikaži sve kartice",
  hideAllCards: "Sakrij sve kartice",
  showWeekends: "Prikaži vikende",
  youCanCreateATemplateAbove: "Možete kreirati predložak iznad",
  youCanCreateABoardFrom: "Možete kreirati ploču sa sidebara aplikacije",
  createPageTemplate: "Kreirajte predložak stranice ",
  editPageTemplate: "Uredite predložak stranice",
  templateNameAndIcon: "Naziv predloška i ikona",
  thisIsHowPeopleFindTemplate: "Ovako će ljudi kasnije pronaći vaš predložak",
  shortAndDescriptive: "Kratko i opisno",
  templateNameCannotBeEmpty: "Naziv predloška ne može biti prazan",
  templateSpace: "Predložak prostora",
  whichSpacesWillThisTemplateBeAvailableIn:
    "U kojim će prostorima ovaj predložak biti dostupan?",
  templateSpaceShouldHaveAtLeastOneSpaceSelected:
    "Predložak prostora mora imati barem jedan odabrani prostor",
  noSpacesFound: "Nema pronađenih prostora.",
  allSpaces: "Svi prostori",
  peopleWillBeAbleToEditThisAfterTheyApplyTheTemplate:
    "Ljudi će moći uređivati ovo nakon što primijene predložak",
  theseWillBeAddedToTheCardYouApplyTheTemplateTo:
    "Ovo će biti dodano kartici na koju primijenite predložak",
  taskDescription: "Opis kartice",
  pageBody: "Tijelo stranice",
  saveTemplate: "Spremi predložak",
  templateNotFound: "Predložak nije pronađen",
  addAssignees: "Dodaj dodjeljivače",
  setTags: "Postavi oznake",
  selectAll: "Odaberi sve",
  createInThisBoard: "Kreiraj u ovoj ploči",
  setThisStatus: "Postavi ovaj status",
  chooseABoard: "Odaberite ploču",
  chooseABoardToUseThisField: "Odaberite ploču da biste koristili ovo polje",
  ifYouLeaveThisPageAnyChangesWillBeLost:
    "Ako napustite ovu stranicu, sve promjene koje ste napravili na ovom predlošku bit će izgubljene.",
  areYouSureYouWantToDeleteTheTemplate:
    "Da li ste sigurni da želite izbrisati %{templateName} predložak?",
  applyTemplate: "Primijeni predložak",
  noTemplates: "Nema predložaka.",
  manageTemplates: "Upravljajte predlošcima",
  uploadFilesForTemplatesIsDisabled:
    "Prijenos datoteka za predloške onemogućen",
  uploadFilesIsDisabled: "Prijenos datoteka onemogućen",
  noTagsFoundSelectBoardToSeeTags:
    "Nema pronađenih oznaka. Odaberite ploču da biste vidjeli dostupne oznake u tom prostoru ili",
  createNewWorkspaceTagInSettings:
    "kreirajte novu oznaku radnog prostora u postavkama.",
  noTitle: "Nema naslova",
  addChecklist: "Dodaj čeklistu",
  title: "Naslov",
  add: "Dodaj",
  addItem: "Dodaj novu stavku",
  archiveList: "Arhiviraj listu",
  actions: "Akcije",
  reply: "Odgovori",
  replies: "Odgovora",
  description: "Opis",
  cardDescriptionPlaceholder: "Napisite detaljni opis...",
  templateDescriptionPlaceholder: "Unesite opis...",
  card: "Kartica",
  space: "Prostor",
  spaces: "Prostori",
  page: "Stranica",
  workspaceLabel: "Unesite ime radnog prostora",
  workspacePlaceholder: "Ime radnog prostora",
  download: "Preuzmi",
  move: "Premjesti",
  background: "Pozadina",
  share: "Podijeli",
  createNewPage: "Kreiraj Novu Stranicu",
  createNewBoard: "Kreiraj Novu Ploču",
  newBoard: "Nova ploča",
  addNewBoard: "Dodaj novu ploču",
  oneColumn: "1 kolona",
  twoColumns: "2 kolone",
  previewStillUpdating: "Pregled se još uvijek ažurira...",
  emptyPage: "Prazna stranica",
  searchSuperthread: "Pretraži Superthread",
  cancel: "Otkaži",
  cancelAndDiscard: "Otkaži i odbaci",
  makeItPrivate: "Učini privatnim",
  privateSpaceDescription:
    "Kada je projekat postavljen kao privatni moguće mu se pridružiti samo putem poziva.",
  boards: "Ploče",
  linkTextLabel: "Naziv",
  linkUrlLabel: "Adresa",
  linkTextPlaceholder: "Dodaj naziv...",
  linkUrlPlaceholder: "Dodaj adresu...",
  editList: "Uredi Listu",
  copyList: "Kopiraj Listu",
  sortBy: "Poredaj po...",
  moveAllCards: "Pomjeri sve kartice",
  archiveAllCards: "Arhiviraj sve kartice",
  open: "Otvori",
  editTitle: "Izmjeni naziv",
  editTags: "Izmjeni oznake",
  editMembers: "Izmjeni članove",
  copy: "Kopiraj",
  attachment: "Privitak",
  startDate: "Datum početka",
  dueDate: "Rok završetka",
  cover: "Naslovna fotografija",
  tags: "Oznake",
  activity: "Aktivnost",
  created: "Kreirano",
  updated: "Ažurirano",
  timePeriod: "Vremenski period",
  netChange: "Neto promjena",
  last7Days: "Zadnjih 7 dana",
  last14Days: "Zadnjih 14 dana",
  last30Days: "Zadnjih 30 dana",
  between: "između",
  deletedCards: "Izbrisane kartice smanjuju broj",
  convertToCard: "Pretvori u karticu",
  searchForTag: "Traži oznaku",
  createTag: "Kreiraj oznaku",
  tagName: "Ime oznake",
  editTagName: "Uredi ime oznake",
  hideCheckedItems: "Sakrij završene stavke",
  showCheckedItems: "Prikaži završene stavke",
  deleteChecklist: "Izbriši čeklistu",
  attachments: "Privitci",
  versionHistory: "Historija",
  profile: "Profil",
  settings: "Postavke",
  email: "Email",
  firstNamePlaceholder: "Unesite ime",
  lastNamePlaceholder: "Unesite prezime",
  displayNamePlaceholder: "Unesite ime za prikaz",
  profileBasicInfoSubtitle: "Personalni i kontakt podaci",
  uploadProfileImageRule:
    "Slika treba da bude PNG, GIF ili JPG format maksimalne veličine od 3 MB. Prijenos slike će zamijeniti boju vašeg avatara u cijeloj aplikaciji.",
  workspaceLogo:
    "Odaberite logo za svoj workspace. Preporučena veličina je 256x256px",
  logoSaved: "Logo sačuvan",
  logoRemoved: "Logo uklonjen",
  removeCover: "Izbriši naslovnu fotografiju",
  uploadCoverImage: "Postavi novu fotografiju",
  list: "Lista",
  addChildCard: "Dodaj child karticu",
  newChildCard: "Kreirajte novu child karticu",
  searchForCard: "Potražite postojeću karticu",
  cancelSearch: "Otkaži pretragu",
  computer: "Kompjuter",
  setDueDate: "Postavi rok završetka",
  months:
    "Januar,Februar,Mart,April,Maj,Juni,Juli,August,Septembar,Oktobar,Novembar,Decembar",
  monthsAbbreviation: "Jan,Feb,Mar,Apr,Maj,Jun,Jul,Aug,Sep,Okt,Nov,Dec",
  daysAbbreviation: "PO,UT,SR,ČE,PE,SU,NE",
  daysAbbreviationLong: "Pon,Uto,Sri,Čet,Pet,Sub,Ned",
  weekDays: "Ponedjeljak,Utorak,Srijeda,Četvrtak,Petak,Subota,Nedjelja",
  time: "Vrijeme",
  dueDateReminder: "Podsjetnik na rok",
  weekBefore: "Sedmica prije",
  daysBefore: "Dana prije",
  dayBefore: "Dan prije",
  hoursBefore: "Sati prije",
  hourBefore: "Sat prije",
  onTime: "Na vrijeme",
  none: "Nijedan",
  due: "Rok",
  insertFile: "Umetni datoteku",
  addImage: "Dodaj sliku",
  edited: "uređeno",
  insert: "Umetni",
  deleteAttachment: "Uklini privitak",
  overdue: "Isteklo",
  continue: "Nastavi",
  createdBy: "Kreirao",
  press: "Pritisni",
  toClose: "za izlaz",
  useArrowKeys: "Koristi tipke sa strelicama",
  toNavigate: "za navigaciju, odaberite sa",
  cards: "Kartice",
  on: "na",
  sending: "Slanje pozivnog linka..",
  inviteDoesntExist: "Pozivni link ne postoji.",
  newInviteLinkSent: "Poslali smo vam novi pozivni link, provjerite vaš email.",
  inviteLinkAccepted: "Pozivni link je već prihvaćen.",
  inviteNoLongerValid:
    "Pozivni link nije više validan - molimo vas zatražite novi.",
  inviteCodeIncorrect:
    "Kod za pozivni link nije ispravan. Kliknite ispod za novi link.",
  spaceAccess: "Pristup projektu",
  changeToPrivateSpace:
    "Svi postojeći članovi ovog projekta će i dalje biti članovi nakon što postane privatni. Nijedan novi član se neće moći pridružiti osim ako nisu pozvani.",
  changeToOpenSpace:
    "Svi članovi workspace-a moći će pronaći i pridružiti se ovom projektu, te vidjeti njegov sadržaj.",
  changeToPrivate: "Promijeni u privatni",
  changeToOpen: "Promijeni u javni",
  changeToPrivateSpaceTitle: "Promijeni u privatni projekat?",
  changeToOpenSpaceTitle: "Promijeni u javni projekat?",
  ownersAdminsCreatorOfSpace:
    "Samo vlasnici workspace-a, administratori i kreator projekta mogu promijeniti ovu postavku",
  onlyOwnerOfPrivateSpace:
    "Samo vlasnik privatnog projekta može promijeniti ovu postavku",
  pageTitlePlaceholder: "Daodaj ime ovom dokumentu",
  markAllAsRead: "Označi sve kao pročitano",
  addTo: "Dodao te na",
  removeFrom: "Izbrisao te na",
  movedTo: "%{name} pomjeren",
  commented: "Komentarisano",
  mentioned: "Spominjani ste",
  dropFilesLabel: "ispusti datoteke ovdje",
  back: "Nazad",
  hasDueDate: "Ima rok završetka",
  dueSoon: "Uskoro ističe rok",
  dueToday: "Rok završetka danas",
  epic: "Projekt",
  epics: "Projekti",
  searchForEpic: "Potraži projekat",
  changedEpicFrom: "promijenio projekt iz",
  addedToEpicCard: "dodao karticu u projekt",
  removedFromEpicCard: "uklonio karticu iz projekta",
  epicInherited: "naslijedio projekt",
  untitledView: "Pogled bez naslov",
  cannotSaveUntitledView: "Ne mozeete spasiti pogled bez naslova",
  viewSaved: "pogled je spasen",
  pagePlaceholder: "Počnite pisati nešto :)",
  newViewTitele: "Naslov novog pogleda",
  ["global.placeholder.pagePlaceholder"]: "Počnite pisati nešto :)",
  viewAll: "Prikaži sve",
  filterByUnread: "Prikaži nepročitane",
  pagePublished: "Stranica objavljena",
  restore: "Vrati",
  cardPathArchivedBoard: "Ova kartica je dio arhiviranog borda",
  boardArchived: "Ovaj bord je arhiviran.",
  pageArchived: "Ova stranica je arhivirana.",
  restoreMakeChange: "Klikni ovdje za vraćanje.",
  boardUpdated: "Board ažuriran",
  defaultBoardLayoutChangedTo:
    "Predefinisani izgled board-a je promijenjen na %{layoutStyle}",
  esc: "Esc",
  assignee: "Dodjeli",
  findMembers: "Pretraži članove...",
  inviteExternalPeople: "Pozovite spoljne ljude",
  notInThisSpace: "Nisu u ovom projektu",
  notWorkspaceMember: "Izgleda da tražena osoba se ne nalazi u vašem timu",
  deleteView: "Izbriši pogled",
  anchorLinkErrorMessage: "Nemoguće pronaći link",
  childCard: "Child card",
  parentCards: "Roditeljske kartice",
  blocking: "Blokirajuće",
  blocked: "Blokirane",
  favourites: "Favoriti",
  dragOr: "Prevucite ili",
  somethingHere: "nešto ovdje",
  linkCopiedToClipboard: "Link je kopiran u međuspremnik.",
  tomorrow: "Sutra",
  invitationsSent: "Pozivnice poslane!",
  retry: "Retry",
  undo: "UNDO",
  tagExists: "Oznaka već postoji",
  removeChildCardFail: "Neuspješno uklanjanje child kartice",
  moveChildCardFail: "Neuspješno pomjeranje child kartice",
  addChildCardFail: "Neuspješno dodavanje child kartice",
  cantRemoveMembers: "Ne možete ukloniti članove iz prvog projekta",
  cantRemoveMembersFromSpace: "Ne možete ukloniti članove space-a",
  duplicate: "Dupliciraj",
  setParentCard: "Dodaj roditeljsku karticu",
  duplicateCard: "Dupliciraj karticu",
  duplicateTo: "Dupliciraj u",
  duplicateDefaultTitle: "Unesite naslov kartice (defaults u original)",
  duplicates: "Duplicira",
  duplicateOf: "Duplikat od",
  markAsBlockedBy: "Označi kao blokirano od strane",
  markAsBlocking: "Označi kao blokiranje",
  markAsRelatedTo: "Označi kao povezano sa",
  markAsDuplicateOf: "Označi kao duplikat",
  blocks: "Blokira",
  blockedBy: "Blokirano od",
  related: "Povezano",
  relatedCards: "Povezane kartice",
  markedCardAsBlocking: "je označio ovu karticu kao blokirajuću",
  markedCardAsBlockedBy: "je označio ovu karticu kao blokiranu od strane",
  markedCardAsRelated: "je označio ovu karticu kao povezanu sa",
  markedCardAsDuplicate: "je označio ovu karticu kao duplikat od",
  removedCardRelationship: "je uklonio vezu",
  noListsInBoard: "Nema listi u ploči",
  noBoardsInSpace: "Nema ploča u projektu",
  noBoardsInThisSpace: "Nema ploča u ovom projektu",
  emptyList: "Prazna lista",
  cardDuplicated: "Kartica duplicirana",
  viewDuplicated: "Pogled dupliciran",
  viewDeleted: "Pogled izbrisan",
  cardDuplicateFailed: "Dupliciranje kartice nije uspjelo",
  viewDuplicateFailed: "Dupliciranje pogleda nije uspjelo",
  cantUndoneAction: "Ova akcija ne može biti opozvana",
  deleteCommentPopupMessage: "Da li ste sigurni da želite izbrisati komentar?",
  deleteMessage: "Izbriši komentar",
  eachSpaceCanContain: "Svaki projekt može sadržavati koliko želite kartica",
  browseSpaces: "Pretražite projekte",
  popupSpaceDescription:
    "Vaš workspace je organizovan u prostore. Oni mogu biti nazvani kao tim, tema, ili biti fokusirani na specifičan dio posla",
  eachSpaceCanContainMultiple: "Svaki projekt može sadržavati više ",
  pagesLowercase: "stranice",
  kanbanBoards: "kanban ploča",
  and: "i",
  removeFromParent: "Ukloni iz roditelja",
  removeChildCard: "Izbriši child karticu",
  editChildCardDetails: "Uredi detalje child kartice",
  copyLink: "Kopiraj link",
  childCardTitleNotUpdated: "Naziv child kartice nije promijenjen.",
  addNewChildCard: "Dodaj novu child karticu",
  enterCardTitleOrFind: "Unesite naziv kartice ili pronađite postojeću karticu",
  createNewCard: "Kreiraj novu karticu",
  unsplashImage: "Unsplash image",
  publishesSubpagesButNoComments: "Objavljuje podstranice, ali ne i komentare.",
  pageIsSharedToWeb: "Stranica je javno podijeljena.",
  shared: "Podijeljeno",
  openSharedPage: "Otvori podijeljenu stranicu",
  pageIsSetToPrivate: "Stranica je privatna",
  profileSettings: "Postavke profila",
  switchWorkspace: "Promijenite workspace",
  archivedItems: "Arhivirano",
  logOut: "Odjavi se",
  helpFeedback: "Pomoć i Feedback",
  help: "Pomoć",
  joinSlack: "Pridruži se našoj Slack zajednici",
  askQuestions: "Postavite pitanja i pomozite drugima",
  contactUs: "Kontaktirajte nas",
  letUsKnow: "Dajte nam doznanja ako imate problem ili pitanje",
  assign: "Dodjeli",
  pageIsNoLongerShared: "Stranica više nije javno podijeljena",
  favourite: "Dodaj u omiljene",
  unfavourite: "Ukloni iz omiljenih",
  allowSearchEngines: "Dozvoli pretraživačima da indeksiraju stranicu",
  searchEngineIndexing: "Indeksiranje pretraživača",
  searchIndexingEnabled: "Indeksiranje pretraživača uključeno",
  searchIndexingDisabled: "Indeksiranje pretraživača isključeno",
  attachIconFrom: "Dodajte ikonu iz...",
  addIcon: "Dodajte ikonu",
  addCoverImage: "Dodajte pozadinsku sliku",
  pageDuplicated: "Stranica je duplicirana",
  pageDuplicateFailed: "Dupliciranje stranice nije uspjelo",
  copyOf: "Kopija od",
  displayNameDescription:
    "Ovo može biti vaše ime ili nadimak - kako god želite da vas ljudi pozivaju u Superthread-u",
  integrations: "Integracije",
  importer: "Importer",
  github: "GitHub",
  gitlab: "GitLab",
  jira: "Jira",
  trello: "Trello",
  importFrom: "Uvoz sa",
  usersToSuperthreadUsers: "korisnice u Superthread korisnike",
  issues: "probleme",
  teams: "timove",
  selectYour: "Odaberite svoje",
  setUpImport: "Podesi uvoz",
  importHistory: "Historija uvoza",
  runImport: "Pokrenite uvoz",
  start: "Počni",
  started: "Počelo",
  DontImport: "Ne uvozit",
  dontImportUsers: "Don’t import users",
  ImportUsers: "Import users",
  selectUser: "Odaberi korisnika",
  inviteByEmail: "Pozovi sa email adresom",
  users: "korisnici",
  options: "Opcije",
  chooseAditionslOptions: "Odaberite dodatne opcije",
  importAttachments: "Uvezite priloge",
  includeCardCoverImages: "Uključite slike naslovnice kartice",
  importInProgress: "Uvoz u procesu",
  importError: "Uvoz završen sa greskom",
  importSuccess: "Uvoz završen",
  importUnstarted: "Uvoz nije počeo",
  timeStarted: "Vrijeme početka",
  completed: "Završeno",
  showCompleted: "Prikaži završeno",
  details: "Detalji",
  finish: "Završi",
  validEmail: "Molimo unesite ispravnu email adresu",
  emailAdresses: "E-mail adrese, odvojene zarezima",
  addToSpaces: "Dodaj u projekte",
  addSpaces: "Dodaj projekte",
  browseProjects: "Pretražuj sve projekte",
  createAndBrowseSpaces: "Kreirajte i pretražujte projekte",
  nameIsRequired: "Ime je potrebno",
  noProjectFound: "Nema više projekata za dodati!",
  memberExplanation:
    "Članovi mogu pretraživati i pridružiti se bilo kojem projektu u workspace-u",
  adminExplanation: "Admini imaju povećani pristup postavkama workspace-a",
  guestExplanation:
    "Gosti imaju ograničen pristup u workspace-u i mogu vidjeti samo projekte u koje su dodani",
  connect: "Poveži se",
  selectBoardImport: "Odaberite ploče koje želite uvesti.",
  selectUsersImport: "Odaberite korisnike koje želite uvesti.",
  notImportArchivedIssues: "We will not import archived issues.",
  importTasksIntoSuperthread: "Import your existing tasks into Superthread.",
  connectAccount: "Povežite svoj račun",
  completedOn: "Completed on",
  importedBy: "Imported by:",
  timeCreated: "Time created:",
  numberOfImportedBoards: "Number of imported boards:",
  numberOfImportedUsers: "Number of imported users:",
  importingIsFinished: "Uvoz je završen",
  importing: "Importing",
  selectService:
    "Odaberite iz koje usluge trebamo uvesti probleme. Zatražit ćemo vaše detalje o autentifikaciji kako bismo mogli pristupiti njihovom API-ju. Nećemo uvoziti nikakve podatke dok ne potvrdite sve opcije u završnom koraku procesa.",
  account: "Račun",
  importers: "Uvozi",
  general: "General",
  manageWorkspaceSettings: "Upravljajte općim postavkama workspace-a",
  avatarAppearance: "Avatar appearance",
  uploadImage: "Učitaj sliku",
  successfullySaved: "Uspješno spremljeno",
  errorSave: "Your changes could not be saved",
  copyURL: "Kopiraj URL",
  copyUrl: "Kopira URL u međuspremnik",
  copyCardUrl: "Kopiraj URL kartice u međuspremnik",
  copyPageUrl: "Kopiraj URL stranice u međuspremnik",
  copyBoardUrl: "Kopiraj URL ploče u međuspremnik",
  copySpaceUrl: "Kopiraj URL projekta u međuspremnik",
  copyGitBranchNameToClipboard: "Kopiraj ime git grane u međuspremnik",
  copyGitBranchName: "Kopiraj ime git grane",
  branchCopiedToClipboard: "Ime git grane kopirana u međuspremnik",
  subscribe: "Pretplati se",
  unsubscribe: "Ukloni pretplatu",
  pullRequestAutomation: "Pull request automation",
  prAutomationDescription:
    "Sa našom GitHub integracijom, kada je kartica povezana sa pull requestom, možete automatski pomjeriti karticu u odgovarajuću listu ploče kada se promijeni pull request.",
  whenPRChangesTo: "When PR changes to",
  moveCardToList: "Pomjeri karticu u listu",
  doNotMove: "Do not move",
  draftPROpened: "Draft PR opened",
  pROpened: "PR opened",
  pRReviewRequest: "PR review request",
  pRMerged: "PR merged",
  pRClosed: "PR closed",
  noListInBoard: "Nema listi u ovoj ploči",
  unassigned: "Nije dodjeljeno",
  viewParentCard: "Pogledaj roditeljsku karticu",
  changeParentCard: "Promjeni roditeljsku karticu",
  removeParentCard: "Ukloni roditeljsku karticu",
  maxFileSize: "(maksimalna veličina fajla: 5 MB)",
  addAttachment: "Dodaj datoteku",
  createChecklist: "Dodaj spisak",
  assignedToMe: "Dodijeljeno meni",
  movedTAaNewList: "Pomjereno na novu listu",
  moved: "Pomjereno",
  published: "Objavljeno",
  cardComments: "Komentari kartica",
  pageComments: "Komentari stranica (uključujući odgovore u nitima)",
  movedBetweenSpaces: "Premješteno između prostora",
  addedToASpace: "Dodan u prostor",
  anywhereYouAreMentioned:
    "Gdje god ste spomenuti (bez obzira na status pretplate itd.)",
  anyCommentsOnResources: "Svi komentari na resurse koje gledate.",
  ifYouAreMemberOfABoard: "Ako ste član ploče:",
  manageMembers: "Organizujte članove",
  manageWhoHasAccess: "Odredite ko ima pristup ovom workspace-u",
  active: "Aktivan",
  suspended: "Suspendiran",
  inviteMembers: "Pozovite članove",
  emailAddress: "Email adresa",
  inviteAs: "Pozovite kao",
  teamMembers: "Članovi tima",
  gitHubConnected: "Uspješno ste se povezali na GitHub",
  nothingToShow: "Nema nista za prikazat",
  findTagsOrCreateNew: "Pronađi tagove ili kreiraj novi",
  deleteTag: "Izbriši oznaku",
  rename: "Preimenuj",
  changeIcon: "Promjeni ikonu",
  areYouSureYouWantToRemove:
    "Da li ste sigurni da ih želite ukloniti? Oni će izgubiti pristup workspace-u.",
  areYouSureYouWantToLeave:
    "Da li ste sigurni da želite napustiti ovaj workspace? Trebat ćete biti ponovo pozvani da biste dobili pristup.",
  areYouSureYouWantToRevoke:
    "Da li ste sigurni da želite otkazati njihov poziv u ovaj workspace?",
  areYouSureYouWantToTransferOwnership:
    "Jeste li sigurni da želite prenijeti vlasništvo ovog workspace-a? Samo novi vlasnik će to moći poništiti.",
  transferOwnership: "Prenesite vlasništvo",
  confirm: "Potvrdi",
  revoke: "Otkaži",
  notFound: "Nije pronađeno",
  itemNotFound: "Stavka nije pronađena",
  urlDoesntLeadAnywhere: "Taj URL ne vodi nikuda",
  itemMightBeDeleted: "Stavka je možda izbrisana ili joj nemate pristup",
  deleteSpace: "Izbriši projekat",
  contentWillBeDeleted:
    "i njegov sadržaj će biti trajno izbrisan za sve. Ovo se ne može poništiti.",
  willBeDeleted: "će biti trajno izbrisan za sve. Ovo se ne može poništiti.",
  ifYouWantToDeleteResource:
    "Ako želite da izbrišete ovaj %{resourceType}, upišite njegovo ime ispod.",
  typeTheNameOfTheSpace: "Upišite ime projekta",
  removeMember: "Ukloni člana",
  leaveWorkspace: "Napusti workspace",
  revokeInvite: "Otkaži poziv",
  invited: "Pozvan",
  pending: "Na čekanju",
  admin: "Admin",
  owner: "Vlasnik",
  guest: "Gost",
  inviteSent: "Poziv je poslan",
  resendInvite: "Pošaljite ponovo poziv",
  whatsNew: "Šta je novo",
  viewUpdates: "Pogledajte update u našem sedmičnom changelog-u",
  fullscreen: "Cijeli zaslon",
  whenYouCreateTags:
    "Kada kreirate oznake direktno na kartici, one se spremaju kao prilagođene oznake samo za taj projekat. Možete ponovo koristiti uobičajene oznake (npr. bug) u svim svojim projektima tako što ćete ih umjesto toga kreirati ovdje. Da bi stvari bile uredne, spojit ćemo oznake projekta s istim imenom u novi radni prostor.",
  merge: "Spojite",
  theSpace: "Projekt",
  haveSameTags: "imaju oznake sa istim imenom.",
  doYouWantToMerge: "Da li zelite spojiti ove oznake u novu workspace oznaku?",
  tagWithThisNameWorkspace: "Želite li ih spojiti u novu oznaku workspace-a?",
  tagWithThisNameSpace: "Oznaka s ovim imenom već postoji u projektu",
  editTag: "Uredite oznaku",
  workspaceTags: "Workspace Oznake",
  manageTags: "Upravljajte oznakama koje se dijele u svim projektima",
  youCantUndo: "Ne možete vratiti ovu radnju.",
  merge2spaceTags: "Spojite dvije projekt oznake u jednu workspace oznaku?",
  areYouSureYouWantToDelete: "Da li ste sigurni da zelite izbrisati.",
  uploaded: "Učitano",
  cardCreatedInResource: "Kartica kreirana u '%{resourceName}' %{resourceType}",
  ["global.label.createIn"]: "Kreiraj u",
  rememberBoard: "Postavi kao zadani bord",
  cardTitle: "Naziv kartice",
  pageTitle: "Naslov stranice",
  cardDescription: "Opis kartice...",
  editAsignees: "Uredite dodjeljivače",
  thisBoardIsEmpty: "Ovaj bord je prazan. Prvo kreirajte listu.",
  pageCreated: "Stranica je kreirana",
  ["quickPage.label.setAsDefaultSpace"]: "Postavi kao zadani projekt",
  changesAreSavedAuto: "Izmjene spremljene automatski",
  untitledCard: "Nenaslovljena kartica",
  editAssignees: "Uredi članove",
  showChildCards: "Prikaži podkartice",
  hideChildCards: "Sakrij podkartice",
  createNewList: "Napravi novu listu",
  enterListName: "Unesite ime liste",
  listStatus: "Status liste",
  couldntArchiveCard: "Kartica nije arhivirana.",
  cardRestored: "Kartica je vraćena",
  dueOn: "Završava se",
  today: "Danas",
  yesterday: "Jučer",
  cannotModidyListStatus:
    "Nije moguće mijenjati status liste ako su kartice dodane.",
  attached: "zakačio",
  removed: "uklonio",
  updatedTheStartDate: "ažurirao datum početka na",
  setTheStartDate: "postavio datum početka na",
  removedStartDate: "uklonio datum početka",
  updatedTheDueDate: "azurirao datum u",
  setTheDueDate: "postavio datum u",
  removedDueDate: "uklonio datum",
  changedStausFrom: "promijenio status iz",
  createdCard: "kreirao articu",
  people: "osobe",
  assignedMember: "dodao",
  archivedTheCard: "arhivirao karticu",
  restoredTheCard: "restorao karticu",
  theCardDescription: "opis kartice",
  theCardTitle: "naslov kartice",
  ["quickPage.title.attachImageFrom"]: "Zakači sliku sa...",
  ["quickPage.title.attachCoverImageFrom"]: "Zakači naslovnu sliku sa...",
  chooseWorkspaceZapier: "Izaberite workspace za povezati za Zapier-om",
  connectSTZapeir: "Povežite Superthread sa Zapier-om",
  zapierIntegradionDescripiton:
    "Zapier vam omogućava da izgradite prilagođene radne tokove koji povezuju Superthread sa gotovo bilo kojom drugom aplikacijom. Povezive aplikacije uključuju: Typeform, Gmail, Intercom, Google Forms, Zendesk, Airtable, Front i mnoge druge.",
  connectToZapier: "Povežite Zapier sa Superthread-om",
  zapier: "Zapier",
  openZapier: "Otvori Zapier",
  allow: "Dopusti",
  zappierWillHave:
    "Zapier će imati pristup za čitanje i pisanje karticama, tablama i stranicama u vašem radnom prostoru.",
  youMayBeSharing:
    "Možda dijelite osjetljive informacije s ovom web lokacijom ili aplikacijom. Uvijek možete vidjeti ili ukloniti pristup u svojim",
  stSettings: "Superthread postavkama",
  seeZapiers: "Vidite Zapier-ov",
  privacyPolicy: "Privacy Policy",
  termsOfService: "Terms of Service",
  makeSureYouTrustZapier: "Uvjerite se da vjerujete Zapier-u",
  connectZapierToSuperthread: "Zapier povezan sa Superthread-om",
  zapierIsRequesting: "Zapier traži pristup",
  previewStInSlack: "Pregledajte Superthread veze u Slacku",
  lookingForSlackNotifications: "Tražite Slack notifikacije?",
  turnThemOnInYour: "Upalite ih u vašim",
  notificationsSettings: "Postavkama notifikacija",
  connectToSlack:
    "Povežite se na Slack da pregledate ključne informacije sa Superthread kartica i stranica kada timovi zalijepe veze na njih u Slack poruke.",
  orLc: "ili",
  useBoardsToVisualise:
    "Koristite ploče da vizualizujete svoj tok posla, pratite napredak svog tima i planirate šta dalje. Napravite više ploča kako biste stvari organizirali.",
  collaborativeDocuments:
    "Kolaborativni dokumenti s tekstom, slikama, smanjenjem vrijednosti i umetnutim komentarima. Vodite bilješke, pišite specifikacije, napravite wiki ili javno dijelite informacije.",
  filterAcrossTheEntire:
    "Filtrirajte po cijelom radnom prostoru kako biste stvorili prikaz svih kartica koje su vam „dodijeljene” ili možda kreirajte globalni zaostatak „bugova”. Pregledi mogu biti privatni ili podijeljeni s vašim timom.",
  getStartedBy: "Započnite kreiranjem nove ploče ili stranice",
  useFiltersToCreate:
    "Koristite filtere da napravite novi pogled samo sa karticama koje zelite vidjeti",
  kanbanBoardsUc: "Kanban ploče",
  youCanAlsoImport: "Također možete uvesti svoje postojeće probleme iz",
  importIssues: "Uvezite probleme",
  welcomeToThe: "Dobrodošli u",
  leaveSpace: "Napusti prostor",
  joinSpace: "Pridruži se prostoru",
  joinThisSpace: "Pridruži se ovom prostoru",
  hasUnsupportedFileType: "ima nepodržan tip datoteke",
  maxAllowedImageSize: "Maksimalna dozvoljena veličina slike je",
  maxAllowedImageResolution: "Maksimalna dozvoljena rezolucija slike je",
  movedFromSpace: "maknuo iz prostora",
  onlineAgain: "Ponovo ste na mreži",
  youAreOffline: "Nemate interneta",
  untitledPage: "Stranica bez naslova",
  hideChildPages: "Sakrij podstranice",
  showSubpages: "Prikaži podstranice",
  addedTo: "dodan u",
  addMembers: "Dodaj članove...",
  removedFrom: "uklonjen iz",
  viewMembers: "Pogledaj članove",
  copyLinkToHeading: "Kopiraj link naslova",
  joined: "Pridružen",
  addOwner: "Dodaj vlasnika",
  noOwner: "Nema vlasnika",
  setOwner: "Postavi vlasnika",
  font: "Font",
  clickToUpdate: "Klikni za ažuriranje",
  NewVersionAvailable: "Nova verzija aplikacije je dostupna",
  deactivated: "deaktiviran",
  addedChildCard: "dodao pod karticu",
  removedChildCard: "uklonio pod karticu",
  removedChecklist: "uklonio checklistu",
  addedChecklist: "dodao checklistu",
  addedChecklists: "dodao checkliste",
  markedAsIncomplete: "označio kao nezavršeno",
  completedChecklistItem: "završio",
  addedParentCard: "dodao roditelj karticu",
  removedParentCard: "uklonio roditelj karticu",
  deleteFolder: "Izbriš datoteku",
  renameFolder: "Preimenuj datoteku",
  myViews: "Moji pogledi",
  workspaceViews: "Workspace pogledi",
  lockSidebar: "Zaključaj sidebar",
  hideSidebar: "Sakrij sidebar",
  appearance: "Izgled",
  changeHowSuperthreadLooksAndFeels:
    "Promijeni kako Superthread izgleda i radi",
  matchSistemSettings: "Podudaranje sa sistemskim postavkama",
  darkMode: "Tamni mod",
  lightMode: "Svijetli mod",
  year: "Godina",
  quarter: "Kvartal",
  month: "Mjesec",
  addNewPageInside: "Dodaj novu pod stranicu",
  theme: "Tema",
  boardSettings: "Postavke ploče",
  inbox: "Inbox",
  resolve: "Riješi",
  reactionsToYourComments: "Reakcije na vaše komentare",
  taskIsOverdue: "Zadatak je zakašnjeo",
  endDateIsBeforeStartDate: "Krajnji datum je prije početnog datuma",
  icons: "Ikone",
  emojis: "Emodžiji",
  boardWillNotShowOnPublicPage: "Ploča se neće prikazati na javnoj stranici",
  notInASprint: "Nije u ciklusu",

  // Onboarding
  emailLabel: "Vasa email",
  passwordLabel: "Lozinka",
  checkEmail: "Provjeri email",
  haveSent: "Mi smo poslali ",
  sixDigit: "6 brojeva",
  teamName: "Ime vase ekipe?",
  spaceNameLabel: "Ime projekta",
  spaceNamePlaceHolder: "npr. web-trgovina",
  min3Characters: "Mora biti minimum 3 karaktera.",
  invite: "Pozovi",
  latest: "Zadnje",
  cardChildrenTitle: "Child kartice",
  members: "Članovi",
  removeFromCard: "Ukloni iz kartice",
  displayName: "Korisničko ime",
  firstName: "Ime",
  lastName: "Prezime",
  update: "Spremi",
  openSuperthread: "Otvori Superthread",
  infoNotification: "Info",
  errorNotification: "Greška",
  alertNotification: "Upozorenje",
  successNotification: "Success notification",
  SignInIntoExistingWorkspace: "Prijavi se u postojeći workspace",
  pages: "Srtanice",
  gridView: "Grid",
  listView: "Lista",
  member: "Član",
  notMember: "Nije član",
  watch: "Posmatraj",
  unwatch: "Neposmatraj",
  commentsActivity: "Komentari i aktivnosti",
  show: "Prikazi",
  newestFirst: "Najnovije prvo",
  oldestFirst: "oldest first",
  exploring: "Istraživanje",
  saveAsNewView: "Spasi kao novi pogled",
  noResults: "No results",
  rememberChoice: "Zapamti izbor",
  electronOpenInApp: "Otvori u aplikaciji",
  electronOpenInDesktopApp: "Otvori u desktop aplikaciji",
  electronOpenLinksInDesktopApp: "Otvori linkove u desktop aplikaciji",
  electronAutoOpenLinksInDesktopApp:
    "Automatski otvori Superthread linkove u desktop aplikaciji",
  electronCurrentLinkOpenedInApp:
    "Trenutni link je otvoren u desktop aplikaciji",
  electronAppIsInstalled: "Izgleda da imate instaliranu aplikaciju",
  electronUserMentioned: "vas je spomenuo/la",
  electronResourceMoved: "je pomjerio/la",
  electronMemberAdded: "vas je dodao/la u",
  electronMemberRemoved: "vas je uklonio/la iz",
  electronCommentAdded: "je dodao/la novi komentar",
  electronResourceArchived: "je arhivirao/la",
  electronUserReacted: "je reagirao/la:",
  results: "Rezultati",
  tasks: "Zadaci",
  electronRecentlyViewed: "Nedavno posjeceno",
  electronOpenDesktopApp: "Otvori desktop aplikaciju",
  electronRedirectingToApp: "Preusmjeravanje na desktop aplikaciju...",
  connectToImporter: "Poveži se sa %{importerName}",
  accessToken: "access token",
  installationCloudHostname: "installation / cloud hostname",
  findInYour: "Pronađi u",
  emailAddressYouUseFor:
    "Email adresu koju koristiš za svoj %{importerName} račun",
  selectWhich: "Odaberi koje",
  selectBoardsToImport: "Izaberi %{boardEq} iz kojih ćeš uvesti %{cardEq}",
  importYourExistingNameToST:
    "Uvezi postojeće %{importerName} %{boardEq} u Superthread",
  superthreadSpace: "Superthread prostor",
  mapImporterUsersToSTUSers:
    "Mapiraj %{importerName} korisnike u Superthread korisnike (ili pozovite one koji fale) da sačuvate korisnike, kreatore i aktivnosti.",
  startImport: "Pokreni uvoz",
  wellLetYouKnowWhenImportFinishes: "Obavijestit ćemo vas kada uvoz završi",
  feelFreeToContuinueUsingST: "Slobodno nastavite koristiti Superthread",
  dontImportThisUser: "Nemoj uvoziti ovog korisnika",
  matchToAnExistingSTUser: "Mapiraj na postojećeg Superthread korisnika",
  createANewUser: "Kreirajte novog korisnika (poziv e-poštom)",
  // importEpics: 'Uvezi epics',
  // importEpicsDesc: "Epics će biti uvezeni u zasebanu Superthread ploču nazvanu 'Epics'.",
  importOpenStories: "Uvezi otvorene priče",
  importOpenStoriesDesc:
    "Neriješene ili otvorene priče bit će uvezene sa postojećim stanjima.",
  importStaleStories: "Uvezi zastarjele priče",
  importStaleStoriesDesc:
    "Priče koji nisu otvorene u više od 6 mjeseci smatraju se zastarjelim. Bit će uvezeni u arhivu i mogu se pretraživati i dearhivirati kasnije.",
  wedLikeToTake: "Želimo vam uzeti",
  thirtySeconds: "30 sekundi",
  toShowYouAround: "da vam pokažemo okolo",
  getStarted: "Počni",
  youCanAlways:
    "Uvijek možete ponovo posjetiti ovaj tutorial iz sekcije pomoći u sidebaru",
  youreGoodToGo: "Spremni ste za početak",
  quickStart: "Brzi start tutorial",
  getToKnow: "Upoznaj Superthread u 30 sekundi",
  desktopApp: "Desktop aplikacija",
  thisLinkWasOpenedInApp: "Ovaj link je otvoren u desktop aplikaciji",
  openHereInstead: "Otvori ovdje umjesto toga",
  browseAndManageSpaces: "Pregledaj i upravljaj svojim prostorima",
  manageSpaces: "Upravljaj prostorima",
  searchSpaces: "Pretraži prostore",
  createSpace: "Kreiraj prostor",
  addADescription: "Dodaj opis",
  showingNumberOfSpaces: "Prikazano je %{num} od ukupno %{totalNum} prostora",
  noResultsFoundFor: 'Nema rezultata koji odgovaraju "%{query}"',
  changeDescription: "Promijeni opis",
  contents: "Sadržaj",
  createSpaceSubtitle:
    "Prostor sadrži povezane ploče, zadatke i stranice. Možda ćete imati prostor po timu ili po poslovnom području.",
  spaceNameAndIcon: "Ime prostora i ikona",
  somethingShortAndClear: "Nešto kratko i jasno",
  youCanChangeThisLater: "Možete promijeniti ovo kasnije",
  descritionOptional: "Opis (opcionalno)",
  whatIsThisSpaceFor: "Za šta je ovaj prostor?",
  addPeopleToSpaceOptional: "Dodaj osobe u ovaj prostor (opcionalno)",
  addPeople: "Dodaj osobe",
  addPeopleSubtitle:
    "Ako dodate osobe koje nisu dio %{workspaceName} workspace-a, one će biti dodani.",
  openSpace: "Javni prostor",
  openSpaceSubtitle:
    "Svi članovi tvog workspace-a mogu pretraživati i pridružiti se prostorima",
  privateSpaceSubtitle:
    "Workspace članovi ne mogu se pridružiti privatnim prostorima osim ako nisu pozvani od strane člana",
  inviteNewPeople: "Pozovi nove osobe",
  inviteeEmailAddress: "Email adresa pozvanog",
  couldntCreateSpace: "Nije moguće kreirati prostor, pokušajte ponovo.",
  spaceCreated: "Prostor je kreiran",
  emailAlreadyAdded: "Email je već dodan",
  addingSomeMembersFailed: "Dodavanje nekih članova nije uspjelo",
  ["my-work"]: "Moj posao",
  newCard: "Nova kartica",
  myWorkAssignedToMe: "Dodijeljeno %{userName}",
  myWorkCreatedByMe: "Kreirano od %{userName}",
  upgradePlan: "Nadogradi plan",
  upgradePrivateSpaceTitle: "Nadogradi za korištenje privatnih space-ova",
  upgradePrivateSpaceDescription:
    "Možete kreirati privatne space-ove na plaćenom planu",
  upgradePlanBadgeTooltip:
    "Samo vlasnik space-a (%{spaceOwner}) i admini mogu mijenjati plan workspace-a",
  upgradeUserRolesTitle: "Nadogradi za postavljanje korisničkih uloga",
  upgradeUserRolesDescription: "Možete birati ne-admin role na plaćenom planu.",
  electronDownloadApp: "Preuzmi aplikaciju",
  electronDownloadAppDescription:
    "Trenutno samo podržavamo macOS. Obavijestite nas da li postoji potražnja i za Windowsom.",
  prStateOpen: "%{count} otvoreno",
  prStateClosed: "%{count} zatvoreno",
  prStateMerged: "%{count} spojeno",
  shortcutWarningText:
    "Shortcut priče koje nisu dodijeljene timu neće biti importovane.",
  language: "Jezik",
  statusType: "Tip statusa",
  resourceAndContentWillBeDeleted:
    '%{resourceType} "%{resourceTitle}" i njegov sadržaj će biti trajno izbrisan za sve. Ovo se ne može poništiti.',
  resourceWillBeDeleted:
    '%{resourceType} "%{resourceTitle}" će biti trajno izbrisan za sve. Ovo se ne može poništiti.',
  listNameLabel: "Ime liste",
  deleteList: "Izbriši listu",
  itemName: "Ime stavke",
};

export default bs;
