import { Translations } from "../types";

const zhHans: Translations = {
  // onboarding
  inviteTeamMembersTo: "邀请团队成员加入您的工作区",
  loggingIn: "正在登录",
  defaultSpaceName: "常规",
  onboardingSpaceName: "欢迎 👋",
  loginCodeSendAgain: "再次发送您的登录代码",
  loginCodeResent: "您的登录代码已再次发送。",
  loginCodeError: "登录验证码错误。",
  loginCodeErrorSending: "发送登录验证码时出现问题。",
  loginCodeErrorExpired: "您的登录验证已过期，我们已发送另一个。",
  loginCodeErrorRateLimited: "您尝试次数过多，请稍后再试。",
  pickAWorkspaceName: "选择一个工作区名称",
  creatingWorkspace: "正在创建工作区",
  createaSpace: "创建一个空间",
  subdomainExists: "此工作区名称已被占用。请尝试另一个。",
  emailLabel: "您的电子邮件地址",
  passwordLabel: "密码",
  checkEmail: "检查您的电子邮件",
  haveSent: "我们已发送一个",
  weSentALoginCode: "我们已发送登录代码至：",
  ifEmailIsValidWeSentYouACode:
    "如果此电子邮件有效且可以更改，已发送一次性密码。",
  genericEmailUpdateError: "更新您的电子邮件地址时出现问题。请重试。",
  sixDigit: "6位数登录代码",
  sixDigits: "6位数",
  confTo: "至",
  checkInbox: "请查看您的通知。",
  teamName: "您的团队名称是什么？",
  workspaceNameLabel: "工作区名称",
  workspaceNamePlaceHolder: "例如 Acme industries",
  spaceNameLabel: "空间名称",
  spaceNamePlaceHolder: "例如 web-shop",
  min3Characters: "至少3个字符。",
  continueWithProvider: "继续使用%{provider}",
  welcomeToSuperThread: "欢迎来到 Superthread",
  aWorkspaceIs: "工作区通常以您的组织或公司名称命名。您可以稍后更改此名称。",
  youCanChangeThis: "您可以稍后更改此项并创建任意数量的空间。",
  LoginCode: "登录代码",
  enterLoginCode: "输入登录代码",
  continueWithEmail: "继续使用电子邮件",
  registerProvider: "注册使用%{provider}",
  onboardingEmailPlaceholder: "你@example.com",
  // cards
  cardsLayoutList: "列表",
  cardsLayoutBoard: "看板",
  cardsLayoutTimeline: "时间线",
  cardsLayoutCalendar: "日历 (Beta)",
  // Group titles
  ["slash.group.media"]: "媒体",
  ["slash.group.basic"]: "基础",
  ["slash.group.inline"]: "内联",
  ["slash.group.embed"]: "嵌入",
  // Keywords
  ["slash.keyword.media"]: "附件,图片,文件,上传,媒体,附件",
  // Commands
  // slashCommands
  ["slash.display.attach"]: "附件",
  ["slash.search.attach"]: "附件",
  "slash.display.image": "图片",
  "slash.display.video": "视频",
  "slash.display.file": "文件",
  "slash.display.youtube": "嵌入YouTube视频",
  "slash.display.checklist": "清单",
  "slash.display.table": "表格",
  "slash.display.h1": "H1",
  "slash.display.h2": "H2",
  "slash.display.h3": "H3",
  "slash.display.bulleted": "项目符号列表",
  "slash.display.numbered": "编号列表",
  "slash.display.blockquote": "引用块",
  "slash.display.hr": "水平线",
  "slash.display.card": "卡片",
  "slash.display.mention": "提及",
  "slash.display.codeBlock": "代码块",
  "slash.display.board": "看板",
  "slash.display.callout": "标注",
  "slash.display.embedIframe": "嵌入 iframe",
  "slash.display.embedFigma": "嵌入 Figma",
  "slash.display.embedMiro": "嵌入 Miro 白板",
  "slash.display.embedLoom": "嵌入 Loom 视频",
  "slash.display.embedExcalidraw": "嵌入 Excalidraw",
  "slash.display.embedLucid": "嵌入 Lucid 图表",
  "slash.search.image": "图片",
  "slash.search.video": "视频",
  "slash.search.file": "文件",
  "slash.search.youtube": "youtube视频",
  "slash.search.checklist": "清单",
  "slash.search.table": "表格",
  "slash.search.h1": "h1",
  "slash.search.h2": "h2",
  "slash.search.h3": "h3",
  "slash.search.bulleted": "项目符号列表",
  "slash.search.numbered": "编号列表",
  "slash.search.blockquote": "引用块",
  "slash.search.hr": "水平线",
  "slash.search.card": "卡片",
  "slash.search.mention": "提及",
  "slash.search.codeBlock": "代码块",
  "slash.search.embed": "嵌入看板",
  "slash.search.embedIframe": "嵌入 iframe",
  "slash.search.embedFigma": "嵌入 figma iframe",
  "slash.search.embedMiro": "嵌入 miro iframe",
  "slash.search.embedLoom": "嵌入 loom iframe",
  "slash.search.embedExcalidraw": "嵌入 excalidraw iframe",
  "slash.search.embedLucid": "嵌入 lucid iframe",
  // menus
  "menu.add-column-before": "在前面添加列",
  "menu.add-column-after": "在后面添加列",
  "menu.add-row-before": "在前面添加行",
  "menu.add-row-after": "在后面添加行",
  "menu.merge-cells": "切换合并单元格",
  "menu.toggle-header-row": "切换标题行",
  "menu.delete-column": "删除列",
  "menu.delete-row": "删除行",
  "menu.delete-table": "删除表格",
  "menu.toggle-expand-to-page-size": "切换全宽",
  "menu.add-comment": "添加评论",
  "menu.heading": "标题%{level}",
  "menu.bold": "加粗",
  "menu.italic": "斜体",
  "menu.strikethrough": "删除线",
  "menu.underline": "下划线",
  "menu.check-list": "清单",
  "menu.bullet-list": "项目符号列表",
  "menu.ordered-list": "有序列表",
  "menu.horizontal-rule": "水平线",
  "menu.link": "链接",
  "menu.quick-card": "快速卡片",
  "menu.blockquote": "块引用",
  "menu.codeblock": "代码块",
  "menu.code": "内联代码",
  "menu.undo": "撤销",
  "menu.redo": "重做",
  "menu.table-cell-color": "单元格颜色",
  "menu.clear-table-cell-color": "清除单元格颜色",
  "menu.align-left": "左对齐",
  "menu.align-center": "居中对齐",
  "menu.align-right": "右对齐",
  "menu.align-justify": "两端对齐",
  "editor.clickToDownload": "点击下载",
  "editor.loading": "加载中",
  "editor.characterLimitReachedTryFile":
    "已达到字符限制。对于较大的内容，您可以附加文件。",
  "editor.uploading": "上传中",
  "editor.genericFileError": "您的文件无法上传。",
  // billing
  ["billing.unlimitedMembers"]: "无限制团队成员",
  ["billing.unlimitedSpaces"]: "无限制空间",
  ["billing.unlimitedBoards"]: "无限制看板",
  ["billing.unlimitedCardsAndPages"]: "无限制卡片和页面",
  ["billing.unlimitedViews"]: "无限数量的已保存筛选器",
  ["billing.category.workspaceMembers"]: "工作区成员",
  ["billing.category.spaces"]: "空间",
  ["billing.category.boards"]: "看板",
  ["billing.category.cardsAndPages"]: "卡片和页面",
  ["billing.category.views"]: "已保存的筛选器",
  ["billing.category.fileSize"]: "文件大小",
  ["billing.category.privateSpaces"]: "私人空间",
  ["billing.category.userPermissions"]: "用户权限",
  ["billing.category.guestAccounts"]: "访客账户",
  ["billing.noPrivateSpaces"]: "无私人空间",
  ["billing.everyoneIsAdmin"]: "所有人都是管理员",
  ["billing.noGuestAccounts"]: "无访客账户",
  ["billing.5mbFileSizeLimit"]: "5MB 文件大小限制",
  ["billing.noFileSizeLimit"]: "无文件大小限制",
  ["billing.unlimitedPrivateSpaces"]: "无限制私人空间",
  ["billing.2Spaces"]: "2 个空间",
  ["billing.adminRolesAndPermissions"]: "管理员角色和权限",
  ["billing.unlimitedCards"]: "无限制卡片",
  ["billing.sharePagesOnTheWeb"]: "在网上分享页面",
  ["billing.50Pages"]: "50 个页面",
  ["billing.unlimitedPages"]: "无限制页面",
  ["billing.indexSharedPages"]: "在搜索引擎中索引共享页面",
  ["billing.privateSpaces"]: "私人空间",
  ["billing.viewOnlySpaces"]: "仅查看空间",
  ["billing.timelineListAndBoardView"]: "时间线、列表和看板视图",
  ["billing.guestAccounts"]: "访客账户",
  ["billing.monthly"]: "每月",
  ["billing.yearly"]: "每年",
  ["billing.currentPlan"]: "当前计划",
  ["billing.yourChosenPaymentMethodIs"]: "您选择的付款方式是%{method}",
  ["billing.thisIsThePaymentMethod"]:
    "这是我们将用于未来付款的付款方式。您可以随时更改。",
  ["billing.billing"]: "账单",
  ["billing.planAndBilling"]: "计划和账单",
  ["billing.paymentMethod"]: "付款方式",
  ["billing.cardEndingIn"]: "%{cardType}，末尾数字为%{last4}",
  ["billing.manageBillingDetails"]: "管理账单详情",
  ["billing.viewBillingDetails"]: "查看账单详情",
  ["billing.updatePaymentDetails"]: "更新付款详情",
  ["billing.sendNewInvoicesTo"]: "发送新发票至",
  ["billing.previousInvoices"]: "以前的发票",
  ["billing.plan"]: "计划",
  ["billing.manageWhichPlan"]: "管理工作区使用的计划",
  ["billing.standard"]: "随心付费",
  ["billing.pro"]: "商业版",
  ["billing.standardSubtitle"]: "适合个人和小型团队",
  ["billing.proSubtitle"]: "适合发展中的公司",
  ["billing.enterprise"]: "企业版",
  ["billing.changePlan"]: "更改计划",
  ["billing.free"]: "免费",
  ["billing.upgrade"]: "升级",
  ["billing.noPaymentMethod"]: "无付款方式",
  ["billing.thereIsNoPaymentMethod"]:
    "此工作区没有关联的付款方式。选择付费计划后，付款方式将显示在此处。",
  ["billing.selectAPaidPlan"]: "选择付费计划",
  ["billing.upgradePlan"]: "付更多",
  ["billing.downgradePlan"]: "付更少",
  ["billing.downgradeToFree"]: "降级到免费",
  ["billing.viewYourPaymentMethodInStripe"]: "在Stripe中查看您的付款方式",
  ["billing.weBillTheWorkspacePayment"]:
    "当邀请被接受时，我们会向工作区的付款方式收费。",
  ["billing.checkThePlanPanel"]: "查看计划面板以获取每个席位的费用估算。",
  ["billing.12"]: "$12",
  ["billing.10"]: "$10",
  ["billing.dollarPrice"]: "$%{price}",
  ["billing.numberSpaces"]: "%{number}个空间",
  ["billing.numberBoards"]: "%{number}个看板",
  ["billing.fileSizeLimit"]: "%{size}MB文件大小限制",
  ["billing.sprints"]: "冲刺",
  ["billing.projectsAndRoadmap"]: "项目",
  ["billing.ssoAndSaml"]: "SSO和SAML",
  ["billing.unlimitedFileUploads"]: "无限文件上传",
  ["billing.cardAndPageTemplates"]: "卡片和页面模板",
  ["billing.guestUsers"]: "访客用户",
  ["billing.meetingTranscription"]: "会议转录",
  ["billing.aiNoteTemplates"]: "AI笔记模板",
  ["billing.askAiSearch"]: "询问AI搜索",
  ["billing.perUserPerMonth"]: "每用户每月",
  ["billing.perUserPerYear"]: "每用户每年",
  ["billing.inAppLiveChatSupport"]: "应用内实时聊天支持",
  ["billing.aiTrainingOptOut"]: "选择退出AI训练",
  ["billing.timelineListAndCalendar"]: "时间轴、列表和日历布局",
  ["billing.billedYearly"]: "按年计费",
  ["billing.planStatus"]: "计划状态",
  ["billing.yourCurrentPlanIsNotSetToRenew"]: "您的当前计划未设置为续订",
  ["billing.canceledDescription"]:
    "在 %{date} 您的工作区将降级为 $t(billing.free) 计划。在此之前，您仍然可以邀请人加入此工作区，但您将无法超过 %{memberCount} 个工作区成员",
  ["billing.turnRenewalBackOn"]: "重新开启续订",
  ["billing.youCanStillInvite"]: "您仍然可以邀请人加入此工作区，但您不能超过",
  ["billing.workspaceFullError"]:
    "已达到工作区成员限制。工作区管理员可以提高限制。",
  ["billing.genericJoinError"]: "无法加入工作区。",
  ["billing.startsOn"]: "开始于%{date}",
  ["billing.switchToYearly"]: "切换到年度 (-20%)",
  ["billing.switchToMonthly"]: "切换到每月",
  ["billing.metadata"]: "%{plan}中的所有内容，加上...",
  ["billing.dedicatedAnalyst"]: "专属战略分析师",
  ["billing.onsiteAdoption"]: "现场采用和推广",
  ["billing.customImplementation"]: "定制实施",
  ["billing.uptimeSLA"]: "%{percentage}% 正常运行时间SLA",
  ["billing.byoc"]: "自带云",
  ["billing.samlAndScim"]: "Single Sign-On (SSO) and SCIM provisioning",
  ["billing.auditLogs"]: "审计日志",
  ["billing.customBilling"]: "自定义账单",
  ["billing.prioritySupport"]: "优先支持和咨询",
  ["billing.unlimitedChildCards"]: "无限子卡片",
  ["billing.publishPagesToTheWeb"]: "将页面发布到网络",
  ["billing.calendarLayout"]: "日历布局",
  ["billing.customViews"]: "自定义已保存筛选器",
  ["billing.advancedSearch"]: "高级搜索",
  ["billing.views"]: "已保存的筛选器",
  ["billing.timelineLayout"]: "时间线布局",
  ["billing.guestsUsersAreFree"]: "在您当前的计划中，访客用户是免费的。",
  ["billing.newMembersAreBilledProRata"]:
    "新成员按比例计费，按年度计费周期的剩余时间计算。",
  ["billing.workspacePaymentMethodWillBeCharged"]:
    "工作区的付款方式将在他们加入的月份结束时扣费。",
  ["billing.learnModeAboutBilling"]: "了解更多关于计费的信息",
  ["billing.guestViewOnly"]: "访客 - 仅查看",
  ["billing.daysLeftOnTrial_one"]: "试用期剩余%{count}天",
  ["billing.daysLeftOnTrial_other"]: "试用期剩余%{count}天",
  ["billing.keepPlan"]: "保留计划",
  ["billing.yourTrialEndsSoon"]: "您的试用即将结束",
  ["billing.thereAreDaysLeftOnYourTrial_one"]:
    "您的%{planName}计划试用期还剩%{count}天。",
  ["billing.thereAreDaysLeftOnYourTrial_other"]:
    "您的%{planName}计划试用期还剩%{count}天。",
  ["billing.afterTrialLong"]:
    "试用期结束后，您将降级到%{planName}计划。您可以在计划页面查看您将失去的功能。",
  ["billing.afterTrialShort"]: "试用期结束后，您将降级到%{planName}计划。",
  ["billing.contactAdminOrOwner"]: "联系您的管理员或所有者",
  ["billing.seeAvailablePlans"]: "查看可用计划",
  ["billing.yourTrialHasExpired"]: "您的试用已过期",
  ["billing.youHaveBeenDowngradedLong"]:
    "您已降级到%{planName}计划。您可以在计划页面查看您失去的功能。",
  ["billing.youHaveBeenDowngradedShort"]: "您已降级到%{planName}计划。",
  ["billing.legacy"]: "旧版",
  ["billing.youAreOnLegacyPlan"]:
    "您正在使用旧版 %{planName} %{planPeriod} 计划",
  ["billing.legacyDescription"]:
    "此版本不再向新用户提供。您可以继续使用它，或%{contactUs}以探索我们当前计划的更新功能和定价。",

  // global
  ["global.text.create"]: "创建",
  ["option.label.cards"]: "卡片",
  ["option.label.pages"]: "页面",
  ["option.label.boards"]: "看板",
  ["option.label.epics"]: "项目",
  ["option.label.spaces"]: "空间",
  ["option.label.showArchived"]: "显示已归档",
  ["search.message.noResults"]: "未找到",
  ["global.text.discardDraft"]: "放弃草稿",
  switchAccount: "切换账户",
  all: "全部",
  search: "搜索",
  searchPlaceholder: "搜索或提问...",
  close: "关闭",
  send: "发送",
  resendInviteLink: "重新发送邀请链接",
  addComment: "添加评论",
  comment: "评论",
  replyToComment: "回复评论...",
  writeComment: "写评论...",
  draftComment: "草稿评论",
  finaliseCard: "完成卡片",
  comments: "评论",
  createBoard: "创建看板",
  createPage: "创建页面",
  delete: "删除",
  edit: "编辑",
  remove: "移除",
  done: "完成",
  cancel: "取消",
  cancelAndDiscard: "取消并放弃",
  enterBoardTitle: "看板标题",
  create: "创建",
  join: "加入",
  couldntJoinSpace: "无法加入空间，请稍后再试。",
  untitled: "无标题",
  containsNoContent: "无内容。",
  ama: "问我任何事",
  me: "我",
  assigned: "已分配",
  mentions: "提及",
  visited: "已访问",
  saved: "已保存",
  notifications: "通知",
  selectWhereWwhenWillNotified: "选择您希望如何接收通知",
  recivePersonalNotification: "在 Slack 中接收个人通知",
  notifyMe: "通知我当",
  save: "保存",
  saveChanges: "保存更改",
  archived: "已归档",
  archive: "归档",
  watch: "关注",
  unwatch: "取消关注",
  cardArchived: "卡片已归档。",
  cardArchivedByCard: "卡片已归档。",
  cardArchivedByList: "卡片属于已归档列表。移动到活动列表以恢复。",
  cardArchivedByBoard: "卡片是已归档看板的一部分。移动到活动看板以恢复。",
  epicArchived: "项目已归档。",
  epicArchivedByEpic: "项目已归档。",
  epicArchivedByList: "项目是已归档列表的一部分。移动到活动列表以恢复。",
  boardArchived: "看板已归档。",
  isArchived: "已归档",
  pageArchived: "页面已归档。",
  cellMerge: "单元格合并",
  new: "新建",
  view: "已保存的筛选器",
  project: "空间",
  spaces: "空间",
  teamId: "团队 ID",
  deleteCommentPopupMessage: "您确定要删除此评论吗？",
  deleteMessage: "删除评论",
  archiveResource: "归档%{type}",
  restoreResource: "恢复%{type}",
  deleteResource: "删除%{type}",
  deleteSuccess: "%{name} %{type} 已删除",
  archiveSuccess: "%{name} %{type} 已归档",
  restoreSuccess: "%{name} %{type} 已恢复",
  deleteError: "无法删除%{name} %{type}",
  archiveError: "无法归档%{name} %{type}",
  restoreError: "无法恢复%{name} %{type}",
  addLink: "添加链接",
  couldntDeleteComment: "无法删除评论，请重试",
  couldntLoadComments: "无法加载评论。",
  commentOnPage: "页面评论",
  commentOn: "评论",
  emailPlaceholder: "例如 you@example.com",
  signOut: "登出",
  leave: "离开",
  browseAllSpaces: "浏览所有空间",
  preview: "预览",
  goToCard: "前往卡片",
  zoomIn: "放大",
  zoomOut: "缩小",
  notFoundPageHeader: "出现了一些小故障...",
  notFoundPageContent:
    "我们不太确定出了什么问题。您可以返回，或者如果需要帮助，可以查看我们的帮助中心。",
  addCard: "添加卡片",
  addProject: "添加项目",
  next: "下一步",
  addToCard: "添加到卡片",
  checklist: "清单",
  moveList: "移动列表",
  board: "看板",
  timeline: "时间线",
  templates: "模板",
  cardTemplates: "卡片模板",
  pageTemplates: "页面模板",
  saveCardContentYouRepeatedlyUse: "保存您重复使用的内容，并在创建卡片时应用",
  savePageContentYouRepeatedlyUse: "保存您重复使用的内容，并在创建页面时应用",
  createCardTemplate: "创建卡片模板",
  editCardTemplate: "编辑卡片模板",
  searchTemplates: "搜索模板",
  name: "名称",
  noCardTemplates: "没有卡片模板",
  noPageTemplates: "没有页面模板",
  calendar: "日历",
  showAllCards: "显示所有卡片",
  hideAllCards: "隐藏所有卡片",
  showWeekends: "显示周末",
  youCanCreateATemplateAbove: "您可以在上方创建一个模板",
  youCanCreateABoardFrom: "您可以从应用侧边栏创建一个看板",
  createPageTemplate: "创建页面模板",
  editPageTemplate: "编辑页面模板",
  templateNameAndIcon: "模板名称和图标",
  thisIsHowPeopleFindTemplate: "这是人们以后找到您的模板的方式",
  shortAndDescriptive: "简短且具有描述性",
  templateNameCannotBeEmpty: "模板名称不能为空",
  templateSpace: "模板空间",
  whichSpacesWillThisTemplateBeAvailableIn: "此模板将在哪些空间中可用？",
  templateSpaceShouldHaveAtLeastOneSpaceSelected: "模板空间应至少选择一个空间",
  noSpacesFound: "未找到空间。",
  allSpaces: "所有空间",
  peopleWillBeAbleToEditThisAfterTheyApplyTheTemplate:
    "人们在应用模板后可以编辑此内容",
  theseWillBeAddedToTheCardYouApplyTheTemplateTo:
    "这些将被添加到您应用模板的卡片中",
  taskDescription: "卡片描述",
  pageBody: "页面正文",
  saveTemplate: "保存模板",
  templateNotFound: "未找到模板",
  addAssignees: "添加受让人",
  removeAssignees: "移除受让人",
  changeAssignees: "更改受让人",
  setTags: "设置标签",
  selectAll: "全选",
  createInThisBoard: "在此看板中创建",
  setThisStatus: "设置此状态",
  chooseABoard: "选择一个看板",
  chooseABoardToUseThisField: "选择一个看板以使用此字段",
  ifYouLeaveThisPageAnyChangesWillBeLost:
    "如果您离开此页面，您对该模板所做的任何更改都将丢失。",
  uploadFailedClickToRetry: "上传失败，点击重试",
  areYouSureYouWantToDeleteTheTemplate: "您确定要删除“%{templateName}”模板吗？",
  applyTemplate: "应用模板",
  noTemplates: "没有模板。",
  manageTemplates: "管理模板",
  uploadFilesForTemplatesIsDisabled: "模板中禁用文件上传",
  uploadFilesIsDisabled: "文件上传已禁用",
  noTagsFoundSelectBoardToSeeTags:
    "未找到标签。选择一个看板以查看该空间中可用的标签，或",
  createNewWorkspaceTagInSettings: "在设置中创建一个新的工作区标签。",
  noTitle: "无标题",
  addChecklist: "添加清单",
  title: "标题",
  add: "添加",
  addItem: "添加新项目",
  archiveList: "归档列表",
  actions: "操作",
  reply: "回复...",
  replies: "回复",
  description: "描述",
  cardDescriptionPlaceholder: "撰写描述...",
  templateDescriptionPlaceholder: "输入描述...",
  card: "卡片",
  space: "空间",
  page: "页面",
  workspaceLabel: "输入工作区名称",
  workspacePlaceholder: "工作区名称",
  roboto: "Roboto",
  sansserif: "无衬线",
  serif: "衬线",
  mono: "等宽",
  monospace: "等宽字体",
  download: "下载",
  move: "移动",
  background: "背景",
  share: "分享",
  upload: "上传",
  paste_image_link: "粘贴图片链接",
  embed_image: "嵌入图片",
  embedIframe: "嵌入 iframe",
  embedProductIframe: "嵌入 %{product}",
  drag_and_drop: "拖放",
  supported_files: "支持的文件",
  maximum_size: "最大尺寸",
  createNewPage: "创建新页面",
  createNewBoard: "创建新看板",
  newPage: "新页面",
  addNewPage: "添加新页面",
  newBoard: "新看板",
  addNewBoard: "添加新看板",
  oneColumn: "1 列",
  twoColumns: "2 列",
  previewStillUpdating: "预览仍在更新...",
  emptyPage: "空页面",
  searchSuperthread: "搜索 Superthread",
  attachFrom: "附加自...",
  searchUnsplash: "搜索 Unsplash",
  fullWidth: "全宽",
  largeText: "大文本",
  space___: "空间...",
  cannotExcludeAll: "不能全部排除",
  mustIncludeAtLeastOne: "必须至少包含一个",
  type: "类型",
  noResultsFound: "未找到结果",
  cardStatus: "卡片状态",
  makeItPrivate: "设为私密",
  thisSpaceIsPrivate: "此空间为私密",
  privateSpaceDescription: "当一个空间设置为私密时，只能通过邀请加入。",
  boards: "看板",
  boardsCount_one: "%{count} 个看板",
  boardsCount_other: "%{count} 个看板",
  cardsCount_one: "%{count} 张卡片",
  cardsCount_other: "%{count} 张卡片",
  from: "来自",
  hiddenMember: "隐藏成员",
  hiddenMemberDesc: "此人与您没有共享任何空间",
  linkTextLabel: "文本",
  linkUrlLabel: "链接",
  linkTextPlaceholder: "添加文本...",
  linkUrlPlaceholder: "添加链接...",
  linkOrEmbedCode: "添加链接或嵌入代码...",
  editList: "编辑列表",
  copyList: "复制列表",
  sortBy: "排序方式",
  moveAllCards: "移动所有卡片",
  archiveAllCards: "归档所有卡片",
  enterResourceTitle: "输入%{type}标题...",
  open: "打开",
  openCardInBoard: "在看板中打开卡片",
  editTitle: "编辑标题",
  editTags: "编辑标签",
  editMembers: "编辑成员",
  copy: "复制",
  attachment: "附件",
  startDate: "开始日期",
  dueDate: "截止日期",
  cover: "封面",
  tags: "标签",
  activity: "活动",
  created: "已创建",
  updated: "已更新",
  reload: "重新加载",
  timePeriod: "时间段",
  cardsAdded: "已添加卡片",
  cardsFinished: "已完成卡片",
  netChange: "净变化",
  last7Days: "过去7天",
  last14Days: "过去14天",
  last30Days: "过去30天",
  cardsAddedBetween: "在...之间添加的唯一卡片",
  cardsAddedTo: "添加到的唯一卡片",
  between: "之间",
  deletedCards: "删除的卡片减少计数",
  moreCardsAddedThanFinished: "比完成的多%{number}张卡片被添加",
  sameNumberOfCardsAddedAndFinished: "添加和完成的卡片数量相同",
  moreCardsFinishedThanAdded: "比添加的多%{number}张卡片被完成",
  oneMoreCardAddedThanFinished: "比完成的多1张卡片被添加",
  oneMoreCardFinishedThanAdded: "比添加的多1张卡片被完成",
  convertToCard: "转换为卡片",
  searchForTag: "搜索标签",
  createTag: "创建标签",
  tagName: "标签名称",
  editTagName: "编辑标签名称",
  hideCheckedItems: "隐藏已选项目",
  showCheckedItems: "显示已选项目",
  deleteChecklist: "删除清单",
  attachments: "附件",
  versionHistory: "版本历史",
  profile: "个人资料",
  settings: "设置",
  email: "电子邮件",
  firstNamePlaceholder: "输入名字",
  lastNamePlaceholder: "输入姓氏",
  displayNamePlaceholder: "输入显示名称",
  profileBasicInfoSubtitle: "个人和联系信息",
  uploadProfileImageRule:
    "图片应为PNG、GIF或JPG格式，且不大于3MB。这将作为您的头像在应用中显示。",
  workspaceLogo: "选择一个工作区标志。推荐尺寸为256x256px",
  logoSaved: "标志已保存",
  logoRemoved: "标志已移除",
  removeCover: "移除封面",
  uploadCoverImage: "上传封面图片",
  list: "列表",
  addChildCard: "添加子卡片",
  searchForCard: "搜索现有卡片",
  newChildCard: "创建新的子卡片",
  cancelSearch: "取消搜索",
  computer: "电脑",
  setDueDate: "设置截止日期",
  months: "一月,二月,三月,四月,五月,六月,七月,八月,九月,十月,十一月,十二月",
  monthsAbbreviation:
    "一月,二月,三月,四月,五月,六月,七月,八月,九月,十月,十一月,十二月",
  daysAbbreviation: "周一,周二,周三,周四,周五,周六,周日",
  daysAbbreviationLong: "周一,周二,周三,周四,周五,周六,周日",
  weekDays: "星期一,星期二,星期三,星期四,星期五,星期六,星期日",
  time: "时间",
  dueDateReminder: "截止日期提醒",
  weekBefore: "一周前",
  daysBefore: "几天前",
  dayBefore: "一天前",
  hoursBefore: "几小时前",
  hourBefore: "一小时前",
  onTime: "准时",
  none: "无",
  due: "到期",
  insertFile: "插入文件",
  addImage: "添加图片",
  edited: "已编辑",
  insert: "插入",
  overdue: "过期",
  continue: "继续",
  createdBy: "创建者",
  press: "按",
  toClose: "关闭",
  cards: "卡片",
  on: "在",
  useArrowKeys: "使用方向键",
  toNavigate: "导航，选择",
  sending: "发送邀请链接中..",
  inviteDoesntExist: "邀请链接不存在。",
  couldntResendLink: "无法重新发送邀请链接。",
  newInviteLinkSent: "我们已向您发送新的邀请链接，请检查您的电子邮件。",
  inviteLinkAccepted: "邀请链接已被接受。",
  inviteNoLongerValid: "邀请链接已失效。请请求新的邀请链接。",
  inviteCodeIncorrect: "邀请链接不正确。点击下面重新发送。",
  thereAreNoFreeSeatsForThisWorkspace: "此工作区没有空闲席位",
  thisWorkspaceCantAcceptAnyMoreMembers:
    "此工作区无法接受更多成员。工作区管理员可以提高限制，或者现有成员可以离开工作区以腾出席位。",
  spaceAccess: "空间访问",
  changeToPrivateSpace:
    "此空间的所有现有成员在变为私有后仍将是成员。除非被邀请，否则无法加入新成员。",
  changeToOpenSpace: "工作区的所有成员都可以找到并加入此空间，并查看其内容。",
  changeToPrivate: "更改为私有",
  changeToOpen: "更改为开放",
  changeToPrivateSpaceTitle: "更改为私有空间？",
  changeToOpenSpaceTitle: "更改为开放空间？",
  ownersAdminsCreatorOfSpace:
    "只有工作区所有者、管理员和空间创建者可以更改此设置",
  member: "成员",
  notMember: "不是成员",
  links: "链接",
  createNewView: "创建已保存的筛选器",
  newView: "新的已保存筛选器",
  workspace: "工作区",
  views: "已保存的筛选器",
  roadmap: "项目",
  myViews: "我的已保存筛选器",
  workspaceViews: "工作区的已保存筛选器",
  private: "私有",
  lastUpdate: "最后更新",
  viewType: "已保存筛选器类型",
  filters: "筛选器",
  filter___: "筛选...",
  filters___: "筛选器...",
  filterBy: "筛选依据",
  filter: "筛选",
  content: "内容",
  status: "状态",
  subscriber: "订阅者",
  creator: "创建者",
  tag: "标签",
  subscribers: "订阅者",
  creators: "创建者",
  shareWithWorkspace: "与工作区共享",
  discard: "丢弃",
  pageTitlePlaceholder: "无标题页面",
  markAllAsRead: "标记全部为已读",
  addTo: "已添加到",
  removeFrom: "已从中移除",
  movedTo: "%{name} 已移动",
  notificationCreated: "%{name} 已创建",
  notificationAdded: "%{name} 已添加",
  commented: "已评论",
  mentioned: "已提及",
  dropFilesLabel: "拖放文件到此处",
  back: "返回",
  typeContent: "输入内容",
  hasDueDate: "有截止日期",
  dueSoon: "即将到期",
  dueToday: "今天到期",
  epic: "项目",
  epics: "项目",
  searchForEpic: "搜索项目",
  changedEpicFrom: "项目已从更改",
  addedToEpicCard: "已将此卡片添加到项目",
  removedFromEpicCard: "已将此卡片从项目中移除",
  epicInherited: "项目继承自父卡片",
  untitledView: "未命名的筛选器",
  cannotSaveUntitledView: "无法保存未命名的筛选器。",
  viewSaved: "筛选器已保存",
  pagePlaceholder: "写点什么...",
  newViewTitele: "新的筛选器标题",
  ["global.placeholder.pagePlaceholder"]: "写点什么...",
  ["global.placeholder.focusedStatePlaceholder"]:
    "@ 提及任何内容，/ 输入命令...",
  ["global.placeholder.focusedStatePlaceholderMobile"]: "@ 提及，/ 输入命令...",
  checkListItemPlaceholder: "@ 提及任何内容...",
  viewAll: "查看全部",
  filterByUnread: "按未读筛选",
  pagePublished: "页面已发布",
  restore: "恢复",
  cardPathArchivedBoard: "此卡片在已归档的看板中",
  restoreMakeChange: "点击此处恢复",
  boardUpdated: "看板已更新",
  defaultBoardLayoutChangedTo: "默认布局已更改为 %{layoutStyle}",
  esc: "逃",
  assignee: "负责人",
  assignees: "负责人",
  no_assignee: "无负责人",
  findMembers: "查找成员...",
  inviteExternalPeople: "邀请外部人员",
  notInThisSpace: "不在此空间中",
  inThisSpace: "在此空间中",
  notWorkspaceMember: "那个人还不是此工作区的成员",
  anchorLinkErrorMessage: "找不到该链接",
  childCard: "子卡片",
  parentCards: "父卡片",
  blocking: "阻塞中",
  blocked: "已阻塞",
  favourites: "收藏夹",
  dragOr: "拖动或",
  somethingHere: "某物到这里",
  linkCopiedToClipboard: "链接已复制到剪贴板。",
  tomorrow: "明天",
  invitationsSent: "邀请已发送。",
  invitationsFailed: "邀请失败。",
  retry: "重试",
  undo: "撤销",
  boardMovedToSpace: "看板已移动到空间",
  pageMovedToSpace: "页面已移动到空间",
  boardNotMoved: "看板移动已取消。",
  pageNotMoved: "页面移动已取消。",
  newTag: "新标签",
  tagExists: "标签已存在",
  toggleSection: "切换部分",
  toggleContent: "空部分。点击以在此处编写或复制内容。",
  removeChildCardFail: "删除子卡片失败",
  moveChildCardFail: "移动子卡片失败",
  addChildCardFail: "添加子卡片失败",
  cantRemoveMembers: "您不能从默认空间中移除成员",
  cantRemoveMembersFromSpace: "您不能从此空间中移除成员",
  cannotModifyMembers: "您没有权限更改成员",
  inactiveMembersCannotBeAdded: "无法将非活跃成员添加到空间",
  duplicate: "重复",
  setParentCard: "设置父卡片",
  duplicateCard: "复制卡片",
  duplicateBoard: "复制看板",
  duplicateBoardDescription:
    "此看板中的任何卡片都不会被复制。为复制的看板选择一个空间和名称。",
  duplicateTo: "复制到",
  duplicateDefaultTitle: "输入新标题（默认为原始标题）",
  duplicates: "重复项",
  duplicateOf: "的重复项",
  markAsBlockedBy: "标记为被阻塞",
  markAsBlocking: "标记为阻塞",
  markAsRelatedTo: "标记为相关",
  markAsDuplicateOf: "标记为的重复项",
  blocks: "阻塞",
  blockedBy: "被阻塞",
  related: "相关",
  relatedEpics: "相关项目",
  markedEpicAsBlocking: "将此项目标记为阻塞",
  markedEpicAsBlockedBy: "将此项目标记为被阻塞",
  markedEpicAsRelated: "将此项目标记为相关",
  markedEpicAsDuplicate: "将此项目标记为重复",
  relatedCards: "相关卡片",
  markedCardAsBlocking: "将此卡片标记为阻塞",
  markedCardAsBlockedBy: "将此卡片标记为被阻塞",
  markedCardAsRelated: "将此卡片标记为相关",
  markedCardAsDuplicate: "将此卡片标记为重复",
  removedCardRelationship: "移除关系",
  noListsInBoard: "看板中没有列表",
  noBoardsInSpace: "空间中没有看板",
  noBoardsInThisSpace: "此空间中没有看板",
  emptyList: "空列表",
  cardDuplicated: "卡片已复制",
  boardDuplicated: "看板已复制",
  viewDuplicated: "已保存的筛选器已复制",
  viewDeleted: "已保存的筛选器已删除",
  cardDuplicateFailed: "复制卡片失败",
  boardDuplicateFailed: "复制看板失败",
  viewDuplicateFailed: "无法复制已保存的筛选器",
  cantUndoneAction: "此操作无法撤销。",
  eachSpaceCanContain: "每个空间可以包含任意数量的看板",
  browseSpaces: "浏览空间",
  popupSpaceDescription:
    "在空间中组织工作。它们通常以团队、项目或高层目标命名。",
  eachSpaceCanContainMultiple: "每个空间可以包含多个",
  pagesLowercase: "页面",
  kanbanBoards: "看板",
  and: "和",
  removeFromParent: "从父级移除",
  removeChildCard: "移除子卡片",
  changeCardParent: "更改卡片父级",
  changeParent: "更改父级",
  changeParentDescription:
    "此卡片的父级为“%{card_title}”。您想将父级更改为当前卡片吗？",
  editChildCardDetails: "编辑子卡片详情",
  copyLink: "复制链接",
  childCardTitleNotUpdated: "子卡片标题未更新。",
  addNewChildCard: "添加新子卡片",
  enterCardTitleOrFind: "输入卡片标题或查找现有卡片",
  createNewCard: "创建新卡片",
  unsplashImage: "Unsplash 图片",
  shareToWeb: "分享至网络",
  publishesSubpagesButNoComments: "发布子页面，但不包括评论",
  pageIsSharedToWeb: "页面已分享至网络",
  shared: "已分享",
  openSharedPage: "打开共享页面",
  pageIsSetToPrivate: "页面设置为私密",
  profileSettings: "个人资料设置",
  switchWorkspace: "切换工作区",
  archivedItems: "已归档项目",
  logOut: "登出",
  helpFeedback: "帮助与反馈",
  help: "帮助",
  joinSlack: "加入我们的Slack社区",
  askQuestions: "提问并帮助他人",
  contactUs: "联系我们",
  letUsKnow: "如果有问题或疑问，请告诉我们",
  assign: "分配",
  unassign: "取消分配",
  pageIsNoLongerShared: "页面不再共享到网络",
  favourite: "收藏",
  unfavourite: "取消收藏",
  allowSearchEngines: "允许搜索引擎索引此页面",
  searchEngineIndexing: "搜索引擎索引",
  searchIndexingEnabled: "搜索索引已启用",
  searchIndexingDisabled: "搜索索引已禁用",
  attachIconFrom: "从...附加图标",
  addIcon: "添加图标",
  addCoverImage: "添加封面图片",
  pageDuplicated: "页面已复制",
  pageDuplicateFailed: "复制页面失败",
  copyOf: "的副本",
  displayNameDescription: "这可以是您的名字或昵称。它将在应用程序中显示。",
  embedVideo: "嵌入Youtube视频",
  removePullRequest: "移除拉取请求",
  viewOnGitHub: "在GitHub上查看",
  setUpGHIntegration: "设置GitHub集成",
  integrateSuperthread: "将Superthread集成到您喜欢的git客户端中。",
  githubIntegradionDescripiton:
    "将Superthread卡片链接到GitHub拉取请求。在您的分支名称或拉取请求标题中包含一个Superthread卡片ID（例如C-123），以便在卡片中自动显示PR状态。",
  connectGithub: "连接GitHub",
  connectedAccounts: "已连接账户",
  integrationConnectedToSuperthread: "%{integrationName}已连接到Superthread",
  enabledBy: "启用者",
  select: "选择",
  integrations: "集成",
  importer: "导入器",
  github: "GitHub",
  github_pull_request: "GitHub",
  gitlab: "GitLab",
  jira: "Jira",
  trello: "Trello",
  importFrom: "导入自",
  selectYour: "选择您的",
  usersToSuperthreadUsers: "用户到Superthread用户",
  issues: "问题",
  teams: "团队",
  setUpImport: "设置导入",
  importHistory: "导入历史",
  importBoards: "导入看板",
  selectWhichBoards: "选择哪些看板",
  runImport: "运行导入",
  quickImport: "快速导入",
  importBoardIntoExsistingSpace: "自定义导入",
  start: "开始",
  started: "已开始",
  DontImport: "不导入",
  map: "映射",
  dontImportUsers: "不导入用户",
  ImportUsers: "导入用户",
  importAs: "导入为...",
  selectUser: "选择用户",
  inviteByEmail: "通过电子邮件邀请",
  users: "用户",
  options: "选项",
  chooseAditionslOptions: "选择其他选项",
  importAttachments: "导入附件",
  includeCardCoverImages: "包括卡片封面图片",
  importInProgress: "导入进行中",
  importError: "导入完成但有错误",
  importSuccess: "导入完成",
  importUnstarted: "导入未开始",
  timeStarted: "开始时间",
  completed: "已完成",
  showCompleted: "显示已完成",
  details: "详情",
  finish: "完成",
  validEmail: "请输入有效的电子邮件地址。",
  emailAdresses: "电子邮件地址，用逗号分隔",
  person1Email: "person1@example.com, person2@example.com…",
  addToSpaces: "添加到空间",
  addSpaces: "添加空间",
  browseProjects: "浏览所有空间",
  createAndBrowseSpaces: "浏览和创建空间",
  nameIsRequired: "需要一个名称",
  noProjectFound: "没有更多空间可添加",
  memberExplanation: "成员可以浏览和加入工作区中的任何空间",
  adminExplanation: "管理员对工作区设置有更多访问权限",
  guestExplanation: "访客对工作区的访问权限有限，只能看到他们被添加到的空间",
  connect: "连接",
  selectBoardImport: "选择要导入的看板",
  selectUsersImport: "选择要导入的用户",
  notImportArchivedIssues: "我们不会导入已归档的问题。",
  importTasksIntoSuperthread: "将现有任务导入到Superthread中。",
  connectAccount: "连接您的账户",
  completedOn: "完成于",
  importedBy: "导入者：",
  timeCreated: "创建时间：",
  createdDate: "创建日期",
  updatedDate: "更新日期",
  numberOfImportedBoards: "导入板的数量:",
  numberOfImportedUsers: "导入用户数量:",
  importingIsFinished: "导入完成",
  importing: "您的导入已完成",
  selectService:
    "选择我们应该从哪里导入问题。我们将要求您的身份验证详细信息，以便我们可以访问他们的API。在您在最后一步确认选择之前，我们不会导入任何数据。",
  account: "账户",
  importers: "进口商",
  general: "一般",
  manageWorkspaceSettings: "管理常规工作区设置",
  dangerZone: "危险区域",
  notOwnerOrAdmin: "您不是此工作区的所有者或管理员",
  archiveWorkspace: "存档工作区",
  archiveWorkspaceDescription:
    "如果工作区被存档，所有成员将失去访问权限。任何公开共享的内容仍将可用。",
  archiveWorkspaceDescriptionDetail:
    "所有成员将失去对此工作区的访问权限。如果您想撤销此操作，请发送电子邮件至contact@superthread.com。",
  deleteWorkspace: "删除工作区",
  deleteWorkspaceDescription:
    "如果一个工作区及其数据被删除，所有成员将失去访问权限。这无法撤销。",
  deleteWorkspaceDescriptionDetail:
    "所有成员将失去对此工作区及其数据的访问权限。这无法撤销。",
  avatarAppearance: "头像外观",
  uploadImage: "上传图片",
  successfullySaved: "成功保存",
  errorSave: "无法保存您的更改",
  copyURL: "复制URL",
  copyUrl: "将URL复制到剪贴板",
  copyCardUrl: "将卡片URL复制到剪贴板",
  copyPageUrl: "将页面URL复制到剪贴板",
  copyBoardUrl: "将板 URL 复制到剪贴板",
  copySpaceUrl: "将网址复制到剪贴板",
  copyGitBranchNameToClipboard: "将 git 分支名称复制到剪贴板",
  copyGitBranchName: "复制 git 分支名称",
  branchCopiedToClipboard: "Git 分支名称已复制到剪贴板",
  subscribe: "订阅",
  unsubscribe: "退订",
  pullRequestAutomation: "拉取请求自动化",
  prAutomationDescription: "在GitHub中更新拉取请求时移动Superthread中的卡片。",
  whenACardIsLinkedToPR: "当卡片链接到拉取请求时",
  whenPRTargetsTheBranch: "当拉取请求目标分支",
  addBranchSpecificAutomation: "添加分支特定的自动化",
  automationMustHaveBranchName: "自动化必须有一个分支名称。这些规则将被忽略。",
  addBranchSpecificAutomationErrorAlreadyExists:
    "该分支名称已经有自动化。这些规则将被忽略。",
  invalidGitBranchName: "这不是一个有效的分支名称。这些规则将被忽略。",
  branchSpecificAutomationAdded: "分支特定的自动化已添加。",
  branchSpecificAutomationUpdated: "分支特定的自动化已更新。",
  branchSpecificAutomationRemoved: "分支特定的自动化已移除。",
  deleteAutomation: "删除自动化",
  deleteThisAutomation: "删除此自动化",
  deleteAutomationConfirmation: "这组规则将被删除且无法恢复。",
  whenPRChangesTo: "当 PR 更改为",
  moveCardToList: "将卡片移动到列表",
  doNotMove: "不要移动",
  draftPROpened: "草稿PR已打开",
  pROpened: "PR已开启",
  pRReviewRequest: "PR审查请求",
  pRMerged: "PR合并",
  pRClosed: "PR已关闭",
  noListInBoard: "此板块中没有列表",
  unassigned: "未分配",
  viewParentCard: "查看父卡",
  changeParentCard: "更改父卡",
  removeParentCard: "移除父卡",
  goToParentCard: "转到父卡",
  discardAndClose: "丢弃并关闭",
  changeStatus: "更改状态",
  createCardsInSelectedBoard: "始终在所选板中创建卡片",
  createCardIn: "在中创建卡片",
  maxFileSize: "最大文件大小：5MB",
  addAttachment: "添加附件",
  createChecklist: "创建清单",
  assignedToMe: "分配给我",
  movedTAaNewList: "移动到新列表",
  moved: "移动",
  published: "已发布",
  cardComments: "卡片评论",
  pageComments: "页面评论（包括线程中的回复）",
  movedBetweenSpaces: "移动到不同的空间",
  addedToASpace: "已将您添加到一个空间",
  noduedate: "没有截止日期",
  ["now+2d"]: "2天后",
  ["now+3d"]: "3天后",
  ["now+1w"]: "1周后",
  ["now+2w"]: "2周后",
  ["now+3w"]: "3周后",
  ["now+1M"]: "1个月后",
  ["now+2M"]: "2个月后",
  ["now+3M"]: "3个月后",
  ["now+6M"]: "6个月后",
  ["now+1y"]: "1年后",
  now: "今天",
  nowActivity: "现在",
  ["now-1h"]: "1小时前",
  ["now-4h"]: "4小时前",
  ["now-1d"]: "昨天",
  ["now-2d"]: "2天前",
  ["now-3d"]: "3天前",
  ["now-1w"]: "1周前",
  ["now-2w"]: "2周前",
  ["now-3w"]: "3周前",
  ["now-1M"]: "1个月前",
  ["now-2M"]: "2个月前",
  ["now-3M"]: "3个月前",
  ["now-6M"]: "6个月前",
  ["now-1y"]: "1年前",
  anywhereYouAreMentioned: "无论您在哪里被提及（无论是否订阅状态等）",
  anyCommentsOnResources: "您订阅的资源上的任何评论。",
  ifYouAreMemberOfABoard: "如果您是看板的成员：",
  manageMembers: "管理成员",
  manageWhoHasAccess: "管理谁可以访问此工作区",
  active: "活跃",
  suspended: "已暂停",
  inviteMembers: "邀请成员",
  inviteToWorkspace: "邀请人加入%{workspaceName}工作区",
  emailAddress: "电子邮件地址",
  inviteAs: "邀请为",
  teamMembers: "团队成员",
  gitHubConnected: "GitHub连接成功",
  nothingToShow: "这里没有内容显示",
  findTagsOrCreateNew: "查找标签或创建新标签",
  deleteTag: "删除标签",
  addNewBoardOrPage: "添加新看板或页面",
  spaceSettings: "空间设置",
  rename: "重命名",
  changeIcon: "更改图标",
  addToFavorites: "添加到收藏夹",
  removeFromFavorites: "从收藏夹中移除",
  viewmoreassignees: "查看更多受托人",
  noassignee: "无受托人",
  currentuser: "当前用户",
  aPrivateSpace: "一个私人空间",
  areYouSureYouWantToRemove:
    "您确定要移除他们吗？他们将失去对此工作区的访问权限。",
  areYouSureYouWantToLeave:
    "您确定要离开此工作区吗？您需要邀请才能重新获得访问权限。",
  youAreTheOnlyPersonInThisPrivateSpace:
    "您是此私人空间中唯一的人。如果您离开，将没有人能够访问它。如果您的组织仍然需要访问，请在您离开之前邀请其他人。",
  whenYouLeaveAPrivateSpace:
    "当您离开私人空间时，您将无法再看到其任何看板或页面。要重新加入，您需要再次被邀请。",
  youCanRejoinThePublicSpace: "您可以从空间屏幕重新加入该空间。",
  areYouSureYouWantToRevoke: "您确定要撤销他们对此工作区的邀请吗？",
  areYouSureYouWantToTransferOwnership:
    "您确定要转移此工作区的所有权吗？只有新所有者才能撤销此操作。",
  transferOwnership: "转移所有权",
  transferSpaceOwnershipConfirmed: "空间所有权已转移",
  transferSpaceOwnershipShort: "您必须在离开之前转移所有权",
  transferSpaceOwnershipDescription:
    "如果您将%{name}设为此空间的所有者，您将不再是所有者，并将更改为成员。",
  transferSpaceOwnershipBeforeLeaving:
    "您必须在离开此空间之前将其他人设为所有者。请转到空间设置以将其他人设为所有者。",
  confirm: "确认",
  revoke: "撤销",
  notFound: "未找到",
  itemNotFound: "未找到项目",
  urlDoesntLeadAnywhere: "该URL未指向任何地方",
  itemMightBeDeleted: "该项目可能已被删除，或者您可能无权访问",
  deleteItem: "删除%{item}",
  deleteSpace: "删除空间",
  ifYouWantToDeleteSpace: "如果您想删除此空间，请在下方输入其名称。",
  ifYouWantToDeleteResource:
    "如果您想删除此%{resourceType}，请在下方输入其名称。",
  ifYouWantToArchiveResource:
    "如果您想存档此%{resourceType}，请在下方输入其名称。",
  typeTheNameOfTheSpace: "输入空间名称",
  removeMember: "移除成员",
  leaveWorkspace: "离开工作区",
  revokeInvite: "撤销邀请",
  invited: "已邀请",
  pending: "待处理",
  admin: "管理员",
  owner: "所有者",
  guest: "访客",
  inviteSent: "邀请已发送",
  resendInvite: "重新发送邀请",
  whatsNew: "新功能",
  viewUpdates: "查看我们每周更新日志中的更新",
  whenYouCreateTags:
    "当您从卡片创建标签时，它们仅保存为该空间的标签。在此处创建通用标签（例如 bug），以便在所有空间中可用。如果存在同名的空间级标签，我们将其合并到工作区标签中。",
  merge: "合并",
  theSpace: "该空间",
  haveSameTags: "有同名标签。",
  doYouWantToMerge: "您想将这些合并到新的工作区标签中吗？",
  tagWithThisNameWorkspace: "具有此名称的工作区标签已存在",
  tagWithThisNameSpace: "空间中已存在具有此名称的标签",
  editTag: "编辑标签",
  workspaceTags: "工作区标签",
  manageTags: "管理跨所有空间共享的标签",
  youCantUndo: "您无法撤销此操作。",
  merge2spaceTags: "同名标签合并到工作区标签中？",
  areYouSureYouWantToDelete:
    "您确定要删除“%{resourceTitle}” %{resourceType}吗？",
  uploaded: "已上传",
  cardCreatedInResource: "在 ’%{resourceName}’ %{resourceType} 中创建的卡片",
  ["global.label.createIn"]: "创建于",
  rememberBoard: "记住看板",
  cardTitle: "卡片标题",
  pageTitle: "页面标题",
  cardDescription: "卡片描述...",
  editAsignees: "编辑分配者",
  actionFailed: "操作失败",
  thisBoardIsEmpty: "此看板为空。请先创建一个列表。",
  changesAreSavedAuto: "更改已自动保存",
  untitledCard: "无标题卡片",
  editAssignees: "编辑分配者",
  showChildCards: "显示子卡片",
  hideChildCards: "隐藏子卡片",
  createAndManageSpaces: "创建和管理空间",
  thereAreNoListInBoard: "看板中没有列表。",
  pageMovedToParent: "页面已移动到父级",
  subscribedToResourceUpdates: "已订阅 %{name} 更新",
  unsubscribedFromResourceUpdates: "已取消订阅 %{name} 更新",
  subscribingToResourceUpdatesFailed: "订阅 %{name} 更新失败",
  unsubscribingFromResourceUpdatesFailed: "取消订阅 %{name} 更新失败",
  couldntArchiveCard: "无法归档卡片。",
  cardRestored: "卡片已恢复",
  dueOn: "到期日",
  today: "今天",
  yesterday: "昨天",
  attached: "已附加",
  removed: "已移除",
  updatedTheStartDate: "将开始日期更新为",
  setTheStartDate: "将开始日期设置为",
  removedStartDate: "已移除开始日期",
  updatedTheDueDate: "将到期日期更新为",
  setTheDueDate: "将到期日期设置为",
  removedDueDate: "已移除到期日期",
  changedStausFrom: "将状态从",
  editStatus: "编辑状态",
  editName: "编辑名称",
  numberOfCards: "卡片数量",
  createdCard: "创建了卡片",
  createdEpic: "创建了项目",
  people: "人员",
  assignedMember: "已分配",
  archivedTheCard: "已归档卡片",
  restoredTheCard: "已恢复卡片",
  archivedTheEpic: "已归档项目",
  restoredTheEpic: "已恢复项目",
  theCardDescription: "卡片描述",
  theCardTitle: "卡片标题",
  theEpicDescription: "项目描述",
  theEpicTitle: "项目标题",
  ["quickPage.title.attachImageFrom"]: "从...附加图片",
  ["quickPage.title.attachCoverImageFrom"]: "从...附加封面图片",
  chooseWorkspaceToConnectIntegration:
    "选择一个工作区以连接 %{integrationName}",
  connectSuperthreadWith: "将 Superthread 连接到 %{integrationName}",
  zapierIntegradionDescripiton:
    "Zapier 允许您构建自定义工作流，将 Superthread 与几乎任何其他应用程序连接：Typeform、Gmail、Intercom、Google Forms、Zendesk、Airtable、Front 等。",
  connectToZapier: "将 Zapier 连接到 Superthread",
  zapier: "Zapier",
  openZapier: "打开 Zapier",
  allow: "允许",
  integrationWillHave:
    "%{integrationName} 将拥有读取和写入您工作区中卡片、看板和页面的权限。",
  youMayBeSharing: "您可能会与此网站或应用程序共享敏感信息。您始终可以在您的",
  stSettings: "Superthread 设置中查看或移除访问权限",
  seeIntegration: "查看 %{integrationName} 的",
  privacyPolicy: "隐私政策",
  termsOfService: "服务条款",
  makeSureYouTrust: "确保您信任 %{integrationName}",
  integrationIsRequesting: "%{integrationName} 正在请求访问",
  previewStInSlack: "在 Slack 中预览 Superthread 链接",
  lookingForSlackNotifications: "寻找 Slack 通知？",
  turnThemOnInYour: "在您的",
  notificationsSettings: "通知设置中打开它们",
  connectToSlack:
    "连接到 Slack 以在 Slack 消息中包含链接时查看来自 Superthread 卡片和页面的关键信息。",
  orLc: "或",
  useBoardsToVisualise:
    "使用看板来可视化您的工作流程，跟踪团队的进展，并计划接下来的工作。创建多个看板以保持井井有条。",
  collaborativeDocuments:
    "协作文档支持文本、图片、markdown和内联评论。记笔记、写规格、建立维基或公开分享信息。",
  filterAcrossTheEntire:
    "在整个工作区中进行筛选，以创建包含所有分配给您的卡片的已保存筛选器，或例如一个全局缺陷待办。已保存的筛选器可以是私密的，也可以与团队共享。",
  useFiltersToCreate: "使用筛选器创建只包含你想查看卡片的自定义已保存筛选器",
  kanbanBoardsUc: "看板",
  importYourExistingTasksFrom: "从中导入您现有的任务",
  importTasks: "导入任务",
  leaveSpace: "离开空间",
  viewSpace: "查看空间",
  deleted: "%{name} 已删除",
  leaveNamedSpace: "离开 %{name} 空间？",
  leaveNamedPrivateSpace: "离开 %{name} 私有空间？",
  deleteAndLeaveNamedPrivateSpace: "删除并离开 %{name} 私有空间？",
  youLeftNamedSpace: "您已离开 %{name} 空间。",
  youCannotLeaveTheSpace: "您无法离开此空间",
  joinSpace: "加入空间",
  joinThisSpace: "加入此空间",
  hasUnsupportedFileType: "不支持的文件类型",
  maxAllowedImageSize: "允许的最大图像大小为",
  maxAllowedImageResolution: "允许的最大图像分辨率为",
  movedFromSpace: "从空间移出",
  untitledPage: "无标题页面",
  hideChildPages: "隐藏子页面",
  showSubpages: "显示子页面",
  addedTo: "已添加到",
  addMembers: "添加成员...",
  removedFrom: "已从中移除",
  viewMembers: "查看成员",
  enableScrollFocus: "在侧边栏中显示当前项目",
  copyLinkToHeading: "复制链接到标题",
  joined: "已加入",
  addOwner: "添加所有者",
  noOwner: "无所有者",
  setOwner: "设置所有者",
  font: "字体",
  addNewFolder: "创建文件夹",
  deletedSuccesfully: "已从收藏中移除",
  addedSuccesfully: "已添加到收藏",
  clickToUpdate: "点击更新",
  NewVersionAvailable: "有新版本的应用可用",
  addedChildCard: "已添加子卡片",
  removedChildCard: "已移除子卡片",
  removedChecklist: "已移除检查清单",
  addedChecklist: "已创建检查清单",
  addedChecklists: "已创建检查清单",
  markedAsIncomplete: "标记为未完成",
  completedChecklistItem: "已完成",
  addedParentCard: "已添加父卡片",
  removedParentCard: "已移除父卡片",
  changedParentCardFrom: "已更改父卡片从",
  deleteFolder: "删除文件夹",
  renameFolder: "重命名文件夹",
  lockSidebar: "保持侧边栏打开",
  hideSidebar: "隐藏侧边栏",
  appearance: "外观",
  changeHowSuperthreadLooksAndFeels: "更改Superthread的外观和感觉",
  matchSistemSettings: "匹配系统设置",
  darkMode: "深色模式",
  lightMode: "浅色模式",
  darkGreyMode: "深灰色模式",
  darkBlueMode: "深蓝色模式",
  lightBlueMode: "浅蓝色模式",
  year: "年",
  quarter: "季度",
  month: "月",
  addNewPageInside: "添加子页面",
  addChildPage: "添加子页面",
  theme: "主题",
  boardSettings: "看板设置",
  reaction: "反应",
  inbox: "通知",
  resolve: "解决",
  unresolved: "未解决",
  unresolve: "取消解决",
  unresolvedOnly: "仅未解决",
  resolved: "已解决",
  unresolveComment: "取消解决评论",
  resolveComment: "解决评论",
  commentResolved: "评论已解决",
  commentUnresolved: "评论未解决",
  resolvedOnly: "仅已解决",
  allComments: "所有评论",
  noUnresolvedComments: "没有未解决的评论",
  noResolvedComments: "没有已解决的评论",
  noComments: "没有评论",
  about: "关于",
  markAsRead: "标记为已读",
  markAsUnread: "标记为未读",
  markAllAsResolved: "全部标记为已解决",
  showUnresolved: "显示未解决",
  showResolved: "显示已解决",
  noNotifications: "没有通知",
  noNewNotifications: "没有新通知",
  noUnresolvedNotifications: "没有未解决的通知",
  youCanShow: "您可以显示",
  notificationsInstead: "通知代替",
  subscribeToGetNotifications: "订阅某些内容，您将收到活动通知",
  selectANotificationToViewIt: "选择一个通知以查看",
  youCanMarkANotificationAs: "您可以将通知标记为",
  unreadOr: "未读或",
  resolveIt: "解决它",
  inboxNotificationsAreUnresolved: "通知将保持未解决状态，直到您解决它们",
  notificationsAreNew: "如果您之前没有看到通知，它们就是新的",
  wantNotificationsIn: "想要通知在",
  slaskQuestionMarkVisit: "Slack？访问",
  noCardsMatchChosenFilter: "没有符合所选筛选条件的卡片",
  noCardsFound: "未找到卡片",
  boardMoved: "看板已移动",
  pageMoved: "页面已移动",
  openPage: "打开页面",
  hasBeenDeleted: "已被删除",
  deletedResourcePlain: "此资源已被删除。",
  deletedResourceWithName: "此%{name}已被删除。",
  this: "这个",
  andTheEntire: "和整个",
  reactionsToYourComments: "对您的评论的反应",
  youWereRemoved: "您已被移除",
  fromPrivateSpace: "从一个私人空间",
  privateSpaceDesc: "此空间是私密的，因此您无法查看其名称或内容",
  privateSpace: "私人空间",
  everything: "所有内容",
  taskIsOverdue: "任务已过期",
  endDateIsBeforeStartDate: "结束日期早于开始日期",
  moveCardIntoBoard: "卡片已移动到看板",
  inList: "在列表中",
  searchForParentCard: "搜索父卡片",
  icons: "图标",
  emojis: "表情符号",
  custom: "自定义",
  moveToBoard: "移动到看板",
  previous: "上一个",
  manualOrder: "手动排序",
  sortedBy: "排序依据",
  toCancelDrag: "取消拖动",
  groupBy: "分组依据",
  subpageCreated: "子页面已创建",
  tableOfContents: "目录",
  editWorkspaceTagsInSettings: "在设置中编辑工作区标签",
  sideDocked: "侧边停靠",
  modalOverlay: "模态覆盖",
  cardLayout: "卡片布局",
  switchLayout: "切换布局",
  showSidebar: "显示侧边栏",
  notags: "无标签",
  resetLayoutToBoardDefault: "重置布局为看板默认",
  alreadyOpen: "%{resource}已打开",
  defaultBoardLayout: "默认看板布局",
  defaultBoardLayoutDescription: "每个人默认会看到此布局。此设置可以稍后更改。",
  boardDescription: "卡片被分组到列中",
  listDescription: "卡片在垂直列表中，分成组",
  timelineDescription: "基于开始和截止日期的时间线",
  calendarDescription: "卡片被放置在其截止日期",
  boardName: "看板名称",
  memberRemoved: "成员已移除",
  resetLayoutToViewDefault: "重置顺序为默认",
  earliestDueDate: "最早截止日期",
  highestPriority: "最高优先级",
  largestEstimate: "最大估算",
  STIsMostUseful: "Superthread 在与他人合作时最有用。",
  readOnly: "只读",
  boardWillNotShowOnPublicPage: "此看板不会显示在公共页面上",
  removeBoard: "移除看板",
  noSprints: "冲刺将从最新到最早列出在此",
  noNonSprintBoardsInThisSpace: "此空间中没有非冲刺看板",
  inviteToWorkspaceDescription: "要将现有成员添加到空间，请转到空间设置",
  alreadyMembersOfWorkspace:
    "有些人已经在工作区中。他们将被添加到下面选择的任何相关空间。",
  information: "信息",
  success: "成功",
  error: "错误",
  warning: "警告",
  typeSomething: "输入一些内容...",
  invite: "邀请",
  latest: "最新",
  cardChildrenTitle: "子卡片",
  childCards: "子卡片",
  members: "成员",
  removeFromCard: "从卡片中移除",
  displayName: "显示名称",
  firstName: "名字",
  lastName: "姓氏",
  update: "更新",
  openSuperthread: "打开 Superthread",
  infoNotification: "信息通知",
  errorNotification: "错误通知",
  alertNotification: "警报通知",
  successNotification: "成功通知",
  SignInIntoExistingWorkspace: "登录到现有工作区",
  preferences: "偏好设置",
  pages: "页面",
  gridView: "网格视图",
  listView: "列表视图",
  lastCreated: "最后创建",
  lastUpdated: "最后更新",
  searchMembers: "搜索成员",
  or: "或者",
  add_collaborators: "添加协作者",
  selectWorkspace: "选择一个工作区",
  selectWorkspaceIntegrations: "为集成选择一个工作区",
  change: "更改",
  createNewWorkspace: "创建新工作区",
  notSeeingYourWorkspace: "看不到您的工作区？尝试使用其他电子邮件：",
  dismiss: "忽略",
  load: "加载",
  youAlreadyHave: "您已经有",
  openBoard: "打开看板",
  cardCannotBeMovedDirectlyToSpace: "卡片无法直接移动到空间中。",
  clickToRename: "点击重命名",
  info: "信息",
  clearAllFilters: "清除所有筛选器",
  is: "是",
  is_not: "不是",
  includes: "包括",
  excludes: "排除",
  fullscreen: "全屏",
  commentsActivity: "评论和活动",
  show: "显示",
  newestFirst: "最新优先",
  oldestFirst: "最旧优先",
  pageCreated: "页面已创建",
  ["quickPage.label.setAsDefaultSpace"]: "设为默认空间",
  createNewList: "创建新列表",
  enterListName: "输入列表名称",
  listStatus: "列表状态",
  print: "打印",
  reactedWith: "做出反应",
  you: "您",
  cannotModidyListStatus: "添加%{resourceType}后无法修改列表状态",
  onlineAgain: "您已重新联网",
  youAreOffline: "您已离线",
  exploring: "探索",
  deactivated: "已停用",
  deleteView: "删除已保存的筛选器",
  saveAsNewView: "另存为新的已保存筛选器",
  noResults: "无结果",
  thisFilterDoesNotMatch: "此筛选器不匹配任何卡片",
  rememberChoice: "记住选择",
  electronOpenInApp: "在应用中打开",
  electronOpenInDesktopApp: "在桌面应用中打开",
  electronOpenLinksInDesktopApp: "在桌面应用中打开链接",
  electronAutoOpenLinksInDesktopApp: "自动在桌面应用中打开Superthread链接",
  electronCurrentLinkOpenedInApp: "当前链接已在桌面应用中打开",
  electronAppIsInstalled: "看起来您已安装该应用",
  electronUserMentioned: "提到了您",
  electronResourceMoved: "移动了一个",
  electronMemberAdded: "将您添加到一个",
  electronMemberRemoved: "将您从一个中移除",
  electronCommentAdded: "添加了一条新评论",
  electronResourceArchived: "归档了一个",
  electronUserReacted: "做出反应：",
  results: "结果",
  tasks: "任务",
  updateAppToEditPage: "请更新应用以编辑此页面",
  electronRecentlyViewed: "最近查看",
  electronOpenDesktopApp: "打开桌面应用",
  electronRedirectingToApp: "正在重定向到桌面应用...",
  updateAppToEditComment: "请更新应用以编辑此评论",
  updateAppToEditCard: "请更新应用以编辑此卡片",
  connectToImporter: "连接到%{importerName}",
  accessToken: "访问令牌",
  installationCloudHostname: "安装/云主机名",
  findInYour: "在你的",
  emailAddressYouUseFor: "用于%{importerName}账户的电子邮件地址",
  selectWhich: "选择哪个",
  selectBoardsToImport: "选择要从中导入%{cardEq}的%{boardEq}",
  importYourExistingNameToST:
    "将您现有的%{importerName} %{boardEq}导入到Superthread",
  jiraBoardMapingSubtitle: "选择要从Jira导入的看板。",
  trelloBoardMapingSubtitle: "选择要从Trello导入的看板。",
  shortcutBoardMapingSubtitle: "选择要从中导入故事的团队和工作流程。",
  jiraQuickImportText:
    "所有团队将被导入到名为“jira-import”的空间。您可以轻松重命名和重新组织您的看板。",
  trelloQuickImportText:
    "所有团队将被导入到名为“trello-import”的空间。您可以轻松重命名和重新组织您的看板。",
  shortcutQuickImportText:
    "每个“团队-工作流程”看板将被导入到名为“shortcut-import”的空间。您可以轻松重命名和重新组织您的看板。",
  jiraCustomImportText: "选择要导入的看板，以及它们应导入到的空间。",
  trelloCustomImportText: "选择要导入的看板，以及它们应导入到的空间。",
  shortcutCustomImportText:
    "选择要导入的“团队-工作流程”看板，以及它们应导入到的空间。",
  superthreadSpace: "Superthread空间",
  mapImporterUsersToSTUSers:
    "将%{importerName}用户映射到Superthread用户（或邀请缺失的用户）以保留卡片成员、创建者和活动。",
  startImport: "开始导入",
  wellLetYouKnowWhenImportFinishes: "导入完成时我们会通知您",
  feelFreeToContuinueUsingST: "请继续使用Superthread",
  dontImportThisUser: "不要导入此用户",
  matchToAnExistingSTUser: "匹配到现有的Superthread用户",
  createANewUser: "创建新用户（电子邮件邀请）",
  projectsCannotBeMovedToSpaces: "项目无法移动到空间",
  importOpenStories: "导入未完成的故事",
  importOpenStoriesDesc: "未解决或未完成的故事将以其现有状态导入。",
  importStaleStories: "导入过期的故事",
  importStaleStoriesDesc:
    "超过6个月未打开的故事被视为过期。它们将被导入到存档中，可以稍后取消存档。",
  wedLikeToTake: "我们想花",
  thirtySeconds: "30秒",
  toShowYouAround: "向您展示一下",
  getStarted: "开始",
  youCanAlways: "您可以随时从侧边栏的帮助部分重新访问本教程",
  youreGoodToGo: "您可以开始了。",
  quickStart: "快速入门教程",
  getToKnow: "在30秒内了解Superthread",
  desktopApp: "桌面应用",
  thisLinkWasOpenedInApp: "此链接已在桌面应用中打开",
  openHereInstead: "改为在此处打开",
  browseAndManageSpaces: "浏览和管理空间",
  manageSpaces: "管理空间",
  searchSpaces: "搜索空间",
  createSpace: "创建空间",
  addADescription: "添加描述",
  showingNumberOfSpaces: "显示 %{totalNum} 个空间中的 %{num} 个结果",
  noResultsFoundFor: "未找到与“%{query}”相关的结果",
  changeDescription: "更改描述",
  contents: "内容",
  createSpaceSubtitle:
    "空间包含相关的看板、任务和页面。您可能会为每个团队或业务领域创建一个空间。",
  spaceNameAndIcon: "空间名称和图标",
  somethingShortAndClear: "简短而清晰",
  youCanChangeThisLater: "您可以稍后更改",
  descritionOptional: "描述（可选）",
  whatIsThisSpaceFor: "这个空间是用来做什么的？",
  addPeopleToSpaceOptional: "添加人员到此空间（可选）",
  addPeople: "添加人员",
  addPeopleSubtitle:
    "如果您邀请不属于 %{workspaceName} 工作区的人，他们将被添加到该工作区。",
  openSpace: "打开空间",
  openSpaceSubtitle: "工作区的所有成员都可以浏览和加入开放空间",
  privateSpaceSubtitle:
    "工作区成员无法查看或加入私人空间，除非他们被现有成员邀请",
  inviteNewPeople: "邀请新成员",
  inviteeEmailAddress: "被邀请者的电子邮件地址",
  inviteSectionSubtitle: "他们将被邀请加入整个工作区，而不仅仅是这个空间。",
  couldntCreateSpace: "无法创建空间，请重试。",
  spaceCreated: "空间已创建。",
  emailAlreadyAdded: "电子邮件已添加",
  addingSomeMembersFailed: "添加某些成员失败",
  founder: "创始人",
  director: "总监",
  teamLead: "团队负责人",
  individualContributor: "个人贡献者",
  softwareEngineering: "软件工程",
  design: "设计",
  productManagement: "产品管理",
  marketing: "市场营销",
  finance: "财务",
  development: "开发",
  marketer: "市场专员",
  sales: "销售",
  clickToView: "点击查看",
  clickToDownload: "点击下载",
  business: "商业",
  pickAllThatApply: "选择所有适用项",
  pickOne: "选择一个",
  customerSupport: "客户支持",
  humanResources: "人力资源",
  socialMedia: "社交媒体",
  wordOfMouth: "口碑",
  searchEngine: "搜索引擎",
  advertising: "广告",
  searchForSpaceOrBoard: "搜索空间或看板",
  starTypingToSearchFor: "开始输入以搜索",
  ["my-work"]: "我的卡片",
  ["myWork.assigned"]: "分配给%{userName}",
  ["myWork.created"]: "由%{userName}创建",
  ["myWork.notes"]: "备注",
  ["myWorkNoResults.created"]: "没有您创建的卡片",
  ["myWorkNoResults.assigned"]: "没有分配给您的卡片",
  ["memberNoResults.assigned"]: "没有分配给%{userName}的卡片",
  ["memberNoResults.created"]: "没有由%{userName}创建的卡片",
  newCard: "新卡片",
  addedCommentHiddenByFilter: "添加的评论被过滤器隐藏",
  createdCardHiddenByFilter: "创建的卡片可能被过滤器隐藏",
  viewMyWork: "查看我的卡片",
  viewWork: "查看 %{displayName} 的卡片",
  removeFromSpace: "从空间中移除",
  assignedInThisBoard: "在此看板中分配",
  layout: "布局",
  createdCardMovedSortOrder: "创建的卡片可能被排序顺序移动",
  createCardGroupBy: "卡片已添加到%{list}。",
  canNotMoveCardInsameBoard: "无法在同一看板中移动卡片。",
  latestReply: "最新回复",
  replyLabel: "回复",
  totalReplies: "总回复数",
  olderReplies: "较早回复",
  leaveReply: "留下回复...",
  hideReplies: "隐藏回复",
  showReplies: "显示回复",
  oneReply: "回复",
  discardComment: "放弃评论？",
  areYouSureYouWantToDiscard: "您确定要放弃您的评论吗？",
  skipToEnd: "跳到结尾",
  priority: "优先级",
  noPriority: "无优先级",
  urgent: "紧急",
  high: "高",
  medium: "中",
  low: "低",
  priorities: "优先级",
  changedThePriorityFrom: "将优先级从更改为",
  changedTheEstimateFrom: "将估算从更改为",
  setThePriorityTo: "将优先级设置为",
  setTheEstimateTo: "将估算设置为",
  removedTheEstimate: "移除估算",
  thereAreNoPages: "此空间中没有页面。",
  createNewPageOrDrag: "创建新页面，或将现有页面拖到侧边栏中的此空间。",
  thereAreNoBoards: "此空间中没有看板。",
  createNewBoardOrDrag: "创建新看板，或将现有看板拖到侧边栏中的此空间。",
  commentsOnly: "仅评论",
  activityOnly: "仅活动",
  seeCardsWithThisTag:
    "查看带有此标签的卡片（计数包括可能不会在其他地方显示的卡片）",
  noResultsForThatName: "没有该名称的结果",
  youCan: "你可以",
  createASpace: "创建一个空间",
  named: "命名为“%{query}”",
  estimate: "估算",
  onePoint: "1 点",
  numberOfPoints: "%{num} 点",
  extraSmall: "特小",
  small: "小",
  mediumSize: "中",
  large: "大",
  extraLarge: "特大",
  noEstimate: "无估算",
  settingsProjectsPreferencesSubtitle: "这些设置将影响空间的所有成员",
  howCardsAreEstimated: "此空间中卡片的估算方式",
  disableCardEstimationForThisSpace: "禁用此空间的卡片估算",
  fibonacciPoints: "斐波那契点",
  exponentialPoints: "指数点",
  tshirtSizes: "T恤尺寸",
  setEstimate: "设置估算",
  emailNotificationHelperText:
    "每个工作日发送一封电子邮件，包含自上次电子邮件以来您未查看的通知",
  estimated: "已估算",
  cardSpaceEstimationTurnedOff: "此卡片属于已关闭估算的空间",
  totalEstimatePointsTooltipContent:
    "在%{numOfCards}张卡片中估算了%{totalPoints}点",
  estimates: "估算",
  assignItTo: "分配给",
  searchForACard: "搜索卡片",
  createACard: "创建卡片",
  archivedCardsAreHidden: "已归档的卡片被隐藏",
  enterANameAbove: "在上方输入名称",
  chooseFiltersYouWouldLike: "然后在过滤栏中选择您想要的过滤器",
  cannotCreateViewOnMobile: "无法在移动设备上创建已保存的筛选器。",
  viewCardInBoard: "在其所属的看板中查看卡片",
  guestsMustBeAddedToOneSpace: "访客必须至少被添加到一个空间",
  createCard: "创建卡片",
  suggestedBasedOnTitle: "根据标题建议",
  acceptSuggestion: "接受建议",
  rejectSuggestion: "拒绝建议",
  suggestionPlaceholderText: "建议...",
  changeEmail: "更改电子邮件",
  logOutAndContinue: "注销并继续",
  confirmAccountOwnership: "确认账户所有权",
  reauthenticateEmailDescription:
    "为了确保您的账户安全，我们需要您重新登录。然后您将能够选择一个新的电子邮件地址并完成该过程。",
  enterANewEmail: "输入新的电子邮件地址：",
  resendLoginCode: "重新发送登录代码",
  emailAddressTakenByAnotherUser: "电子邮件地址已被其他用户使用",
  assistant: "助手",
  changeTone: "更改语气",
  simplify: "简化",
  summarize: "总结",
  translate: "翻译",
  generate: "生成",
  replaceText: "替换文本",
  insertBelow: "插入下面",
  assistanceWith: "您需要什么帮助？",
  copiedToClipboard: "已复制到剪贴板",
  academic: "学术",
  casual: "随意",
  confident: "自信",
  friendly: "友好",
  neutral: "中性",
  professional: "专业",
  aiFeatures: "AI 功能",
  emailDigestSentAt: "电子邮件摘要时间",
  inYourTimezone: "在您的时区 (%{timezone})",
  timezone: "时区",
  setAutomatically: "自动设置",
  searchTimezone: "搜索时区",
  changeYourTimezoneInProfile: "在个人资料中更改您的时区。",
  enableNotificationsFirst: "首先启用 %{type} 通知",
  turnOnAIAssitantInFormatingToolbar: "在文本格式工具栏中开启 AI 助手",
  superthreadSendingDataTo:
    "请注意，如果您为您的工作区启用此功能，您同意 Superthread 向外发送数据",
  experimentalFeatureMayChangeFunctionality:
    "此实验性功能可能会在功能和定价上有所变化。",
  contactUsToEnable: "联系我们以启用此功能。",
  boardOpenedInTheBackground: "%{boardTitle} 看板已在后台打开",
  resetFilters: "重置筛选器",
  ["create_space.title"]: "创建空间",
  ["create_space.tooltip"]: "为您的团队工作创建一个家",
  ["create_private_space.title"]: "创建私人空间",
  ["create_private_space.tooltip"]: "只有您邀请的人才能看到私人空间",
  ["invite_user.title"]: "邀请其他人",
  ["invite_user.tooltip"]:
    "邀请您的团队成员加入工作区，以便他们可以跟踪他们的工作",
  ["mention_anything.title"]: "提及某事",
  ["mention_anything.tooltip"]: "使用 @ 键在任何可以写的地方提及某事",
  ["mention_something.title"]: "提及某事",
  ["mention_something.tooltip"]: "使用 @ 键在任何可以写的地方提及某事",
  ["add_child_card.title"]: "添加子卡片",
  ["add_child_card.tooltip"]: "子卡片帮助您将工作分解为更小的任务",
  ["visit_inbox.title"]: "查看通知",
  ["visit_inbox.tooltip"]: "通过通知跟进你订阅的所有内容",
  ["move_page.title"]: "移动页面",
  ["move_page.tooltip"]: "在侧边栏中拖动页面以将其移动到您想要的位置",
  ["create_subpage.title"]: "创建子页面",
  ["create_subpage.tooltip"]: "子页面位于其他页面内，帮助您构建文档结构",
  ["add_page_icon.title"]: "添加页面图标",
  ["add_page_icon.tooltip"]: "页面图标帮助您在搜索和侧边栏中再次找到该页面",
  ["add_page_cover.title"]: "添加页面封面图片",
  ["add_page_cover.tooltip"]: "用封面图片为页面定下基调",
  ["quick_card_shortcut.title"]: "快速卡片快捷键 (C)",
  ["quick_card_shortcut.tooltip"]: "在任何地方按 C 键创建卡片",
  ["quick_page_shortcut.title"]: "快速页面快捷键 (P)",
  ["quick_page_shortcut.tooltip"]: "在任何地方按 P 键创建页面",
  ["create_card.title"]: "创建卡片",
  ["create_card.tooltip"]: "为每个您想跟踪的任务创建一个卡片",
  ["comment_on_card.title"]: "在卡片上评论",
  ["comment_on_card.tooltip"]: "在卡片上写更新或记录您的想法",
  ["search_shortcut.title"]: "使用⌘+K查找内容",
  ["search_shortcut.tooltip"]: "使用此快捷键快速在任何地方打开全局搜索",
  ["create_board.title"]: "创建一个看板",
  ["create_board.tooltip"]: "跟踪子团队或项目的工作",
  ["upload_avatar.title"]: "上传头像",
  ["upload_avatar.tooltip"]: "帮助人们在应用中识别您",
  ["create_page.title"]: "创建一个页面",
  ["create_page.tooltip"]: "使用页面捕捉知识和想法",
  ["set_your_name.title"]: "设置您的姓名",
  ["set_your_name.tooltip"]: "您的姓名将在整个应用中使用",
  ["create_quick_card.title"]: "快速卡片快捷键 (C)",
  ["create_quick_card.tooltip"]: "在任何地方按下 C 键即可创建卡片",
  ["create_quick_page.title"]: "快速页面快捷键 (P)",
  ["create_quick_page.tooltip"]: "在任何地方按下 P 键即可创建页面",
  ["open_search_modal.title"]: "使用⌘+K查找内容",
  ["open_search_modal.tooltip"]: "随时快速打开搜索以查找您的资源",
  ["check_your_notifications.title"]: "查看你的通知",
  ["check_your_notifications.tooltip"]: "通过通知跟进你订阅的所有内容",
  ["change_board_layout.title"]: "尝试不同的看板布局",
  ["change_board_layout.tooltip"]: "了解不同布局如何帮助您管理工作",
  ["try_slash_command.title"]: "尝试一个斜杠命令",
  ["try_slash_command.tooltip"]: "输入 / 查看可用命令列表",
  ["move_card.title"]: "移动卡片",
  ["move_card.tooltip"]: "将卡片移动到不同的看板或状态",
  ["add_card_cover_image.title"]: "添加卡片封面图片",
  ["add_card_cover_image.tooltip"]: "为卡片添加封面图片以获得更好的视觉效果",
  aCardMustHaveATitle: "卡片必须有一个标题",
  showAll: "显示全部",
  showLess: "显示较少",
  hideEmptyGroups: "隐藏空组",
  showAnotherAssignee: "显示另一个负责人",
  showAnotherTags: "显示其他标签",
  spaceMembers: "空间成员",
  addExistingMembers: "添加现有成员",
  inviteNewMembers: "邀请新成员",
  spaceDetails: "空间详情",
  makeBoardFullWidth: "使看板全宽",
  askAiAssistantSearch: "根据您的卡片、页面和笔记询问AI",
  backToSearchResults: "返回搜索结果",
  sources: "来源",
  askAiQuestionLong: "问题应至少包含10个字符。",
  spaceSprintsSettings: "%{space}空间冲刺设置",
  turnOnSprintsForThisSpace: "为此空间开启冲刺",
  turnOnSprintsDesc:
    "将为此空间的侧边栏添加一个“冲刺”部分。冲刺是一个具有开始和结束日期的看板。当一个冲刺完成后，下一个将自动开始。",
  ownersAdminsCanTurnOnSprints:
    "只有工作区所有者、管理员和空间创建者可以更改此设置",
  onlyOwnerOfPrivateSpace: "只有私人空间的所有者可以更改此设置",
  onlySpaceOwnerCanModifyMembers: "只有所有者可以更改空间成员",
  cannotModifySpaceOwner: "您无法更改空间所有者",
  sprintLength: "冲刺长度",
  weeks: "周",
  sprintStartOn: "冲刺开始于",
  coolDownPeriod: "冲刺之间的冷却期",
  coolDownPeriodDesc:
    "每个冲刺之间将添加一个冷却期。这对于例如回顾和清理活动很有用。",
  coolDownPeriodLength: "冷却期长度",
  sprintBoardStatuses: "冲刺看板状态",
  sprintBoardStatusesDesc:
    "此空间中的每个冲刺使用相同的状态。您必须至少有每种状态类型的一个。“待办事项”状态类型不可用。",
  addStatus: "添加状态",
  dueInDays: "在%{days}天后到期",
  sprints: "冲刺",
  addSprint: "添加冲刺",
  sprint: "冲刺",
  openSprint: "打开冲刺",
  renameSprint: "重命名冲刺",
  markAsComplete: "标记为完成",
  changeSprintDates: "更改冲刺日期",
  changeSprintDatesFor: "更改%{sprintName}的日期",
  cancelSprint: "取消冲刺",
  changeDates: "更改日期",
  chooseNewStartAndEndDates: "为%{sprintName}选择新的开始或结束日期",
  renameSprintDescription: "输入冲刺的新名称。",
  startDateIsEarlierThanPreviousEndDate: "开始日期与上一个冲刺的结束日期重叠",
  enterSprintName: "输入冲刺名称",
  cancelSprintWarning: "此看板中所有未完成的卡片将被移至取消状态。",
  dontCancel: "不要取消",
  upgradePlan: "升级计划",
  choosePlan: "选择计划",
  upgradePrivateSpaceTitle: "为私人空间升级",
  upgradePrivateSpaceDescription: "您可以在付费计划中创建私人空间。",
  upgradePlanBadgeTooltip:
    "只有所有者（%{spaceOwner}）和管理员可以更改工作区计划",
  upgradeUserRolesTitle: "为用户角色升级",
  upgradeUserRolesDescription: "您可以在付费计划中选择非管理员用户角色。",
  upgradedWorkspace: "您的工作区已升级！",
  workspaceSubscriptionChanged: "您的工作区订阅已更改",
  sprintSettings: "冲刺设置",
  electronDownloadApp: "下载应用程序",
  electronDownloadAppDescription:
    "我们仅支持macOS。如果有Windows应用程序的需求，请告知我们。",
  macArm64Label: "苹果芯片",
  macx64Label: "苹果 英特尔",
  windowsx64Label: "Windows",
  mailCopiedToClipboard: "电子邮件已复制到剪贴板",
  cardsWithNoSprint: "没有冲刺的卡片",
  showCardsFrom: "显示卡片来自",
  yourColor: "您的颜色",
  thisColorWillHelp: "此颜色将帮助其他人在某些地方识别您。",
  logo: "标志",
  prStateOpen: "%{count}个打开",
  prStateClosed: "%{count}个关闭",
  prStateMerged: "%{count}个合并",
  invitingPeopleToWorkspace: "只有管理员可以邀请新成员加入此工作区",
  upgradePublicPageIndexingTitle: "为搜索引擎索引升级",
  upgradePublicPageIndexingDescription: "您可以在付费计划中开启搜索引擎索引。",
  shortcutWarningText: "未分配给团队的任何Shortcut故事将不会被导入。",
  coolDown: "冷却期",
  noBoardsOrPages: "没有看板或页面",
  language: "语言",
  usersWork: "%{name}的工作",
  renameAttachment: "重命名附件",
  deleteAttachment: "删除附件",
  timelineLayoutDescription: "升级您的工作区计划以使用时间线布局。",
  calendarLayoutDescription: "升级您的工作区计划以使用日历布局。",
  upgradeTemplatesDescription: "升级您的工作区计划以使用模板。",
  upgradeRoadmapAndProjectsDescription: "升级您的工作区计划以使用项目。",
  upgradeViewsDescription: "升级工作区计划以保存已保存的筛选器。",
  createNewItem: "创建新项目",
  statusType: "状态类型",
  spaceLimitReached: "已达到空间限制。您可以删除一些空间以创建更多。",
  freePlanUsageLimits: "免费计划使用限制",
  item: "项目",
  usage: "使用情况",
  limitReachedLong: "如果达到限制，您需要删除项目或升级计划才能创建新项目。",
  limitReached: "已达到限制",
  resourceAndContentWillBeDeleted:
    "%{resourceType} ”%{resourceTitle}”及其内容将被永久删除，无法撤销。",
  resourceWillBeDeleted:
    "%{resourceType} ”%{resourceTitle}”将被永久删除，无法撤销。",
  epicWillBeDeleted:
    "%{resourceType} ”%{resourceTitle}”将被永久删除，无法撤销。已添加到项目的任何卡片将不会被删除。",
  listNameLabel: "列表名称",
  deleteList: "删除列表",
  hideColumn: "Hide column",
  selectAllInColumn: "Select all in column",
  selectAllInBoard: "Select all in board",
  showColumn: "Show",
  hiddenColumns: "Hidden lists",
  hiddenByLayoutToggle: "This list is hidden by the layout toggle",
  itemName: "项目名称",
  moveCardIntoSprint: "卡片已移动到冲刺 %{sprintName}",
  addView: "添加已保存的筛选器",
  timeCreatedSort: "创建时间",
  timeUpdatedSort: "更新时间",
  dueDateSort: "截止日期",
  noSprintsLabel: "无冲刺",
  createdViaEmailFrom: "通过电子邮件创建",
  couldNotBeVerified: "无法验证",
  createCardsViaEmailTitle: "通过电子邮件在此看板中创建卡片",
  createCardsViaEmailDescription:
    "如果有人发送消息到一个电子邮件地址，则在此看板中创建一个卡片。",
  onlyCurrentAddressWillWork: "只有当前显示的地址有效。",
  regenerate: "重新生成",
  emailCopiedToClipboard: "电子邮件已复制到剪贴板",
  emailRegenerated: "电子邮件已重新生成",
  slackChannelNotifications: "Slack频道通知",
  slackChannelNotificationsTitle: "将此看板中的卡片通知发送到Slack频道",
  slackChannelNotificationsDescriptionDisabled:
    "将打开一个Slack窗口并要求您选择一个频道",
  slackChannelNotificationsDescriptionEnabled:
    "此看板的通知已发送到Slack中的%{channel}。",
  slackIntegrationError: "无法启用Slack集成。请重试",
  boardDoesNotExists: "该看板不存在",
  boardActivity: "看板活动",
  sendTo: "发送到",
  slackPrivateMessage: "私人消息",
  slackPrivateGroup: "私人对话",
  slackPrivateChannel: "私人频道",
  webhookNotificationCardCreatedOnBoard: "在此看板上创建的卡片",
  webhookNotificationCardMovedToBoard: "卡片已移动到此看板",
  webhookNotificationCardAddedBoard: "卡片已添加/移动到看板",
  webhookNotificationCardAddedList: "卡片已添加/移动到状态",
  webhookNotificationCardCommented: "在看板上的卡片上留下的评论（不包括回复）",
  webhookNotificationCardDueDate: "卡片截止日期临近/逾期",
  folder: "文件夹",
  yourSpaces: "您的空间",
  quoteReply: "引用并回复",
  itemHasBeenDeleted: "%{resourceType}已被删除",
  deletedNotification: "已删除",
  searchForBoard: "搜索看板",
  activeSprintText: "当前",
  loadMoreSprints: "加载更多冲刺",
  try: "尝试",
  ["add_workspace_logo.title"]: "添加工作区标志",
  ["add_workspace_logo.tooltip"]: "上传标志",
  ["customise_your_profile.title"]: "自定义您的个人资料",
  ["customise_your_profile.tooltip"]: "添加个人资料照片",
  ["import_tasks.title"]: "导入任务",
  ["import_tasks.tooltip"]: "从Trello、Jira或Shortcut导入",
  ["view_keyboard_shortcuts.title"]: "查看键盘快捷键",
  ["view_keyboard_shortcuts.tooltip"]: "打开键盘快捷键表",
  ["connect_slack.title"]: "连接Slack",
  ["connect_slack.tooltip"]: "打开Slack通知",
  seeAllWorkspaces: "查看所有工作区",
  workspaceSettings: "设置和偏好",
  switchToRecentWorkspace: "切换到最近的工作区",
  icon: "图标",
  addToSprint: "添加到冲刺",
  addToProject: "添加到项目",
  goToProject: "转到项目",
  addTags: "添加标签",
  cancelled: "已取消",
  sprintBoards: "冲刺板",
  sprintSettingsBoardsDescription: "这些设置适用于此空间中的所有冲刺",
  addedCard: "已添加卡片",
  removedCard: "已移除卡片",
  addNewCard: "添加新卡片",
  addExistingCard: "添加现有卡片",
  changeEpicOrParent: "更改项目或父级",
  cardAlreadyHasEpicOrParent:
    "所选卡片已经有项目或父卡。如果您将其添加到此项目中，它们将被更改。",
  changeEpic: "更改项目",
  childCardIsPartOfEpic: "子卡片是项目“%{epicName}”的一部分。",
  parentCardHasNoEpic: "父卡片没有项目。",
  parentCardIsPartOfEpic: "父卡片是项目“%{epicName}”的一部分。",
  childCardsEpicWillBeRemoved: "如果继续，子卡片的项目将被移除。",
  childCardsEpicWillChangeToParents:
    "如果继续，子卡片的项目将更改为父卡片的项目。",
  removeEpic: "移除项目",
  epicWillNoLongerBeAssociated:
    "如果从父卡片中移除，子卡片将不再与项目“%{epicName}”关联。",
  childCardAlreadyHasParent: "子卡片已经有父级。如果继续，父级将更改为此卡片。",
  cardsDirectlyAddedToEpicCantHaveParent: "直接添加到项目的卡片不能有父卡片",
  epicNoTagsFound: "未找到标签。项目只能使用工作区标签",
  cannotChangeStatusForCardsInFinishedSprint: "无法更改已完成冲刺中卡片的状态",
  cannotChangeStatusForArchivedCards: "无法更改已归档卡片的状态",
  cantMoveArchivedCardToSprint: "无法将已归档卡片移动到冲刺",
  relatedTo: "相关于",
  changePriority: "更改优先级",
  changeEstimate: "更改估算",
  changeTags: "更改标签",
  changeSprint: "更改冲刺",
  goToSprint: "转到冲刺",
  pastSprints: "过去的冲刺",
  currentAndPlannedSprints: "当前和计划中的冲刺",
  seeAllSprints: "查看所有冲刺",
  currentAndNextSprint: "当前和下一个冲刺",
  branchSpecificAutomationAddFailed: "添加新的分支特定自动化失败。",
  branchSpecificAutomationUpdateFailed: "更新分支特定自动化失败。",
  branchSpecificAutomationRemoveFailed: "移除分支特定自动化失败。",
  thereAreNoCurrentOrPlannedSprints: "没有当前或计划中的冲刺",
  thereIsNoCurrentOrNextSprint: "没有当前或下一个冲刺",
  movedCardFrom: "已将卡片从",
  movedEpicFrom: "已将项目从",
  rolledCardFrom: "已将卡片滚动从",
  sprintMarkedAsCompleted: "冲刺标记为已完成",
  sprintMarkedAsCancelled: "冲刺标记为已取消",
  cardIsParent: "卡片是父项",
  cardIsChild: "卡片是子项",
  cardIsRelated: "卡片是相关项",
  parentCard: "父卡片",
  moveTo: "移动到...",
  pageMovedTo: "页面已移动到",
  thisSpaceIsEmpty: "此空间为空",
  createSomethingToGetStarted: "创建一些内容以开始",
  visualiseYourWorkflow: "可视化您的工作流程，跟踪工作，并保持井井有条",
  captureImportantInformation: "捕捉重要信息，与他人协作，并分享至网络",
  organiseWorkIntoSprints: "将工作组织成一段时间，以便更轻松地计划",
  filterYourWorkspaceToCreateViews:
    "筛选你的工作区以创建已保存的筛选器，并与团队共享。",
  turnOnSprints: "开启冲刺",
  cardViews: "卡片视图",
  convert: "转换",
  convertCardToEpic: "将卡片转换为项目",
  couldNotConvertCardToEpic: "无法将卡片转换为项目",
  cardSuccessfullyConvertedToEpic: "卡片成功转换为项目",
  convertedCardWillLose: "如果将此卡片转换为项目，它将失去其%{arr, list}。",
  convertedThisCardToEpic: "将此卡片转换为项目",
  spaceLevelTags: "空间级标签",
  effortEstimate: "工作量估计",
  existingEpic: "现有项目",
  roadmapMustHaveAtLeastOneStatus: "项目看板必须至少有一个状态",
  chosenPageIsAlreadySubpage: "所选页面已是当前页面的子页面",
  searchForResults: "搜索以显示结果",
  parentCardIs: "父卡片是...",
  projectIs: "项目是...",
  convertedTo: "转换为",
  moveToCompletedSprint: "移动到已完成的冲刺？",
  onlyDoneCardsCanBeMovedToCompletedSprint:
    "只有“完成”的卡片才能移动到已完成的冲刺。此卡片将更改为“完成”并移动。",
  removeCardFromProject: "从项目中移除卡片",
  roadmapOpenedInTheBackground: "项目在后台打开",
  unfavouriteCurrentSprint: "取消收藏当前冲刺",
  favouriteCurrentSprint: "收藏当前冲刺",
  unfavouriteNextSprint: "取消收藏下一个冲刺",
  favouriteNextSprint: "收藏下一个冲刺",
  unfavouriteSprintName: "取消收藏%{sprintName}",
  favouriteSprintName: "收藏%{sprintName}",
  currentSprint: "当前冲刺",
  parentWillBeRemovedIfAddToProject:
    "如果您将此卡片添加到项目中，父卡片将被移除，因为卡片从父卡片继承项目",
  cannotArchiveCardFromSprint: "无法从冲刺中归档卡片",
  sprintCompleted: "冲刺已完成",
  sprintCancelled: "冲刺已取消",
  sprintDatesChanged: "冲刺日期已更改",
  myWorkAndNotes: "我的卡片和笔记",
  notes: "我的笔记",
  suggestedActions: "建议的操作",
  noSuggestedActions: "无建议的操作",
  noChanges: "无更改",
  changes: "更改",
  cardUpdatedSuccessfully: "卡片更新成功",
  commentAddedSuccessfully: "评论添加成功",
  updateCard: "更新卡片",
  moveCard: "移动卡片",
  assignMembers: "分配成员",
  removeMembers: "移除成员",
  generatingSuggestedActions: "生成建议的操作",
  replaceContent: "替换内容",
  appendContent: "追加内容",
  addDescription: "添加描述",
  addDueDate: "添加截止日期",
  setTitle: "设置标题",
  reject: "拒绝",
  accept: "接受",
  finaliseDetails: "完成细节",
  tidyUp: "整理",
  convertTo: "转换为...",
  newNote: "新笔记",
  searchNotes: "搜索笔记...",
  favouriteNote: "收藏笔记",
  archiveNote: "归档笔记",
  deleteNote: "删除笔记",
  original: "原始",
  tidied: "已整理",
  untitledNote: "无标题笔记",
  enhanced: "增强",
  minimize: "最小化",
  maximize: "最大化",
  createNewNote: "创建新笔记",
  youDontHaveAnyNotes: "您还没有任何笔记",
  transcript: "记录",
  assignedCards: "已分配的卡片",
  createdCards: "已创建的卡片",
  noTranscriptAvailable: "无可用记录",
  enhanceNotesUsingMacApp:
    "Superthread可以将会议中的音频转录为增强笔记。转录仅在macOS的Superthread桌面应用中可用。",
  downloadApp: "下载应用程序",
  enhance: "增强",
  macIntel: "Mac Intel",
  appleSilicon: "苹果芯片",
  enhanceNotesUsingAI: "使用AI增强您的笔记",
  showTranscript: "显示文字记录",
  epicCreated: "项目已创建",
  analysingTranscript: "分析文字记录",
  comparingYourNotes: "比较您的笔记",
  readingYourNotes: "阅读您的笔记",
  enhancingYourNotes: "增强您的笔记",
  finished: "完成",
  note: "笔记",
  epicMustHaveTitle: "项目必须有一个标题",
  seeAllNotes: "查看所有笔记",
  autoSaved: "自动保存",
  projectsAreTrackedOnRoadmap: "项目会在项目看板上跟踪",
  addCardsToProject: "向此项目添加卡片",
  projectEmptyStateDescription:
    "一个项目是由工作区中多个卡片组成的大型工作。可以在列中创建项目，或编辑默认状态。",
  cardInProjectEmptyStateFooter: "一个卡片只能属于一个项目",
  addCardsThatContributeToProject: "添加有助于此项目的卡片。您可以",
  noProject: "无项目",
  noteTemplates: "笔记模板",
  noteTemplatesSettingsSubtitle: "使用模板快速更改笔记格式",
  noNoteTemplates: "无笔记模板",
  createNoteTemplate: "创建笔记模板",
  sections: "部分",
  sectionHeading: "部分标题",
  sectionDescriptionPlaceholder: "此部分应重点关注...",
  addSection: "添加部分",
  superthread: "Superthread",
  deletedTemplate: "模板已删除",
  autoEnhanced: "自动增强",
  meetingContext: "会议背景",
  meetingContextPlaceholder: "提供会议概述以及您希望从中获得的内容...",
  meetingContextDescription: "这有助于Superthread在增强您的笔记时了解重点",
  duplicateTemplate: "复制模板",
  favouriteTemplates: "收藏模板",
  introduction: "介绍",
  sampleSectionDescription:
    "记录会议开始时的小谈话中的任何有趣话题。忽略关于天气的讨论。",
  allowSuperthreadToTranscribe: "允许Superthread转录您的会议",
  superthreadCanEnhance:
    "Superthread可以通过直接从您的笔记本电脑转录音频来增强您的笔记，无需会议机器人。适用于面对面和虚拟会议，您可以完全控制何时开启。您的音频绝不会被存储或用于其他用途。",
  transcribeYourVoice: "转录您的声音",
  transcribeOthersVoice: "转录他人的声音",
  allowMicrophoneCapture: "允许麦克风捕获",
  allowSystemAudioCapture: "允许系统音频捕获",
  microphoneAccessNotAllowedTitle: "手动允许麦克风访问",
  microphoneAccessNotAllowedDesc1: "之前未允许麦克风访问，因此您需要手动允许。",
  microphoneAccessNotAllowedDesc2:
    "在macOS中，前往系统设置 > 隐私与安全 > 麦克风，并允许“Superthread”应用程序。",
  microphoneAccessNotAllowedDesc3:
    "完成后，请退出并重新打开此应用程序，然后返回此处。",
  systemAccessNotAllowedTitle: "手动允许系统音频访问",
  systemAccessNotAllowedDesc1: "系统音频访问之前未被允许，因此您需要手动允许。",
  systemAccessNotAllowedDesc2:
    "在macOS中，前往系统设置 > 隐私与安全 > 屏幕与系统音频录制 > 仅系统音频录制，并允许“Superthread”应用。",
  systemAccessNotAllowedDesc3: "完成后，请退出并重新打开此应用，然后返回此处。",
  editNoteTemplate: "编辑笔记模板",
  viewNoteTemplate: "查看笔记模板",
  viewTranscript: "查看转录",
  transcribeHereInstead: "改在这里转录？",
  currentlyTranscribingAnotherNote:
    "笔记“%{noteTitle}”当前正在转录。您想停止那里的转录并改在这里转录吗？",
  transcribeHere: "在这里转录",
  resume: "继续",
  pause: "暂停",
  transcribe: "转录",
  currentlyTranscribing: "当前正在转录",
  transcribingOnlyAvailableOnMac: "转录仅在macOS应用中可用",
  transcribingOnlyAvailableOnDesktop: "转录仅在桌面应用中可用",
  transcribingOnlyAvailableOnNewerMacVersions:
    "转录仅在macOS 14.2及更新版本中可用",
  startTranscription: "开始转录",
  stopTranscription: "停止转录",
  openTranscribingNote: "打开转录笔记",
  notesSettings: "笔记设置",
  theseSettingsArePersonalToYou: "这些设置是您个人的",
  transcriptionJargonTitle: "术语",
  transcriptionJargonPlaceholder: "技术术语、不常见的名称、项目名称等。",
  transcriptionJargonDescription:
    "添加您认为音频转录可能有问题的任何单词。用逗号分隔单词。",
  selectANote: "选择一个笔记",
  noteDoesntExist: "笔记不存在",
  deleteSection: "删除部分",
  untitledSection: "无标题部分",
  messageAgentAssistant: "消息代理助手",
  initialAgentMessage:
    "我在这里帮助您为您的代理编写指令。让我知道您希望它做什么。",
  agentMessageError: "发生错误。请再试一次。",
  agentInstructions: "代理指令",
  agentIcon: "代理图标",
  agentName: "代理名称",
  agentNamePlaceholder: "代理名称",
  agentInvalidNameError: "请输入有效的名称。",
  agentSkill: "技能",
  agentRepository: "仓库",
  agentRepositoryPlaceholder: "https://github.com/org/repo",
  agentInvalidRepositoryError: "请输入有效的仓库URL。",
  agentRefOptional: "引用（可选）",
  agentTarget: "目标",
  agentAutoCreatePr: "自动创建PR",
  agentOpenAsCursorGithubApp: "以Cursor GitHub应用打开",
  agentSkipReviewerRequest: "跳过审阅者请求",
  agentBranchNameOptional: "分支名称（可选）",
  agentApiKey: "API密钥",
  agentApiKeyPlaceholder: "Cursor API密钥",
  agentApiKeyHelpText: "在后端加密存储。更新时留空以保留现有密钥。",
  agentCustomInstructionsOptional: "自定义指令（可选）",
  agentCustomInstructionsPlaceholder:
    "描述此代理应如何行为。这些指令会添加到每个提示的前面。",
  agentRuns: "代理运行",
  agentRunsColumnId: "ID",
  agentRunsColumnCreated: "创建时间",
  agentRunsColumnStatus: "状态",
  agentRunsColumnInputTokens: "输入令牌",
  agentRunsColumnOutputTokens: "输出令牌",
  agentRunsColumnIterations: "迭代",
  agentAttachedResources: "已附加资源",
  agentAttachmentResource: "资源",
  agentAttachmentTimeAttached: "附加时间",
  agentAttachmentAttachedBy: "附加者",
  agentDetach: "分离",
  agentAddAgent: "添加代理",
  agentAddAgentDescription: "创建新的Cursor Cloud代理模板。",
  agents: "代理",
  agentNewAgent: "新建代理",
  agentUpdateAgent: "更新代理",
  agentDeleteAgent: "删除代理",
  agentDeleteConfirmation: "您确定要删除此代理吗？此操作无法撤销。",
  agentCreatedSuccessfully: "代理创建成功。",
  agentUpdatedSuccessfully: "代理更新成功。",
  agentDeletedSuccessfully: "代理删除成功。",
  agentLaunchedSuccessfully: "代理启动成功。",
  agentLaunchFailed: "代理启动失败。",
  agentPromptSetSuccessfully: "代理提示设置成功。",
  agentPromptSetFailed: "代理提示设置失败。",
  agentResetConversationHistory: "重置对话历史",
  agentSelectThisInstruction: "选择此指令",
  agentDebug: "[DEBUG]",
  agentIterationId: "迭代ID：",
  agentStatus: "状态：",
  agentReasoning: "推理：",
  agentFunctions: "函数：",
  agentTriggers: "触发器：",
  agentFallbackName: "代理",
  agentWorkOnThisCard: "处理此卡片",
  agentActive: "代理已激活",
  agentSkillCursor: "Cursor",
  agentSkillSuperthread: "Superthread",
  version: "版本",
  templateWithChildCardsNotAllowed:
    "只有当模板没有自己的子项时，您才能将模板应用于子卡",
  copyNoteToClipboard: "复制笔记到剪贴板",
  noteCopiedToClipboard: "笔记已复制到剪贴板",
  copyTranscriptToClipboard: "复制转录到剪贴板",
  transcriptCopiedToClipboard: "转录已复制到剪贴板",
  anyoneWithThisLinkCanViewNote: "任何拥有此链接的人都可以查看笔记",
  notesEnhancedBySuperthread: "由Superthread增强的笔记",
  connectGoogleCalendar: "连接Google日历",
  googleCalendarIntegration: "Google日历集成",
  googleCalendarIntegrationSubtitle:
    "连接到您的Google日历，以便轻松为即将举行的会议创建笔记",
  calendarAccountConnected: "日历账户已连接",
  disconnect: "断开连接",
  showCalendarMeetingsUpTo: "在笔记列表中显示最多",
  dayAheadInNotesList: "提前一天的日历会议",
  daysAheadInNotesList: "提前几天的日历会议",
  eventTypesToIncludeInNotesList: "要在笔记列表中包含的事件类型",
  ["calendar.all_day"]: "全天事件，包括多天事件",
  ["calendar.event_link"]: "没有会议链接的事件",
  ["calendar.participants"]: "只有一个参与者的事件",
  createNoteFromUpcomingMeeting: "从即将举行的会议创建笔记",
  noUpcomingMeetings: "没有即将举行的会议。您可以更改时间范围",
  seeUpcomingMeetings: "在此查看即将举行的会议",
  searchForAnApp: "搜索应用程序...",
  meetingAppsWatched: "%{num} 个会议应用程序已被监控",
  automaticMeetingDetectionTitle: "自动会议检测",
  automaticMeetingDetectionDescription:
    "Superthread 检测到会议应用正在使用麦克风，并通知您创建笔记",
  joinMeetingFromNote: "加入 %{provider} 会议 (%{time})",
  searchPlaceholderAskAiNotes: "询问关于您的笔记的问题...",
  askAi: "询问 AI",
  transcribeHereInsteadPositive: "在此转录",
  notesAreBetterWithOurApp: "使用我们的应用程序，笔记更好",
  downloadTheMacOSApp: "下载 macOS 应用程序",
  toTranscribeMeetings: "以转录会议",
  notifyUpcomingMeetingsTitle: "通知我即将举行的日历会议",
  notifyUpcomingMeetingsDescription:
    "如果会议即将开始，Superthread 会通知您并提供创建新笔记的选项。",
  macOSApp: "macOS 应用程序",
  requiresMacosAppOne: "需要",
  requiresMacosAppTwo: "macOS 应用程序。",
  meetingsMenuBarTitle: "在菜单栏应用程序旁显示即将举行的日历会议",
  meetingsMenuBarDescription:
    "当天的下一个会议将在菜单栏的 Superthread 图标旁显示。",
  meetingName: "会议名称",
  meetingTime: "会议时间",
  searchLanguage: "搜索语言",
  ["get_started_notes.title"]: "开始使用笔记",
  ["get_started_notes.tooltip"]: "会议转录和 AI 增强的笔记记录",
  transcriptionNotAvailableOnPlan: "此计划不提供转录功能。点击查看可用计划",
  openLinksInDesktopAppTitle: "登录时打开桌面应用程序",
  openLinksInDesktopAppDescription: "登录时自动打开 Superthread 桌面应用程序",
  automaticallyStartTranscription: "自动开始转录",
  wheneverICreateANote: "每当我创建笔记时",
  onlyWhenITakeNotesForMeeting: "仅当我为会议做笔记时",
  learnMore: "了解更多",
  withAnInteractiveVideoTutorial: "通过互动视频教程",
  newToNotes: "新手笔记？",
  onlyWhenITakeNotesForMeetingSubtitle:
    "如果您在开始时间前最多 5 分钟从日历事件创建笔记，或从笔记加入视频通话",
  instantEmail: "即时邮件",
  emailDigest: "邮件摘要",
  instantEmailNotifications: "即时邮件通知",
  goToLatest: "转到最新",
  meetingAndTranscriptionSettings: "会议和转录设置",
  meetingAndTranscriptionSettingsSubtitle: "这些设置只能在",
  customiseNotesSettingsOne: "或者自定义您的",
  customiseNotesSettingsTwo: "笔记设置",
  enableSubGroupBy: "子分组依据",
  boardLimitReached: "已达到看板限制。您可以删除一些看板以创建更多。",
  alphabetical: "按字母顺序",
  chronological: "按时间顺序",
  numeric: "数字",
  role: "角色",
  invitesPending: "邀请待处理",
  standardMembers: "标准成员",
  guests: "访客",
  selected: "已选择",
  bulkActions: "批量操作",
  parentCardWasRemoved: "父卡片已被移除。",
  cardRemovedFromProject: "卡片已从项目中移除。",
  inactiveMembers: "非活跃成员",
  viewOnlyGuests: "仅查看访客",
  memberType: "成员类型",
  noGroup: "无分组",
  showEmptyGroups: "显示空组",
  notJoined: "未加入",
  inactive: "非活跃",
  imported: "已导入",
  addToSpace: "添加到空间",
  memberAddedToSpace: "已将1名成员添加到%{space}空间",
  membersAddedToSpace: "已将%{count}名成员添加到%{space}空间",
  cannotRemoveSpaceOwner: "无法移除空间所有者",
  pageUsageDescription:
    "使用量是内容和历史编辑的组合，可能会随着时间的推移继续增长",
  pageUsage: "页面使用情况",
  pageUsageWarning:
    "警告：如果使用量达到100%，您的更改可能不会被保存。考虑创建子页面或移动到新页面",
  jobDescription: "职位描述",
  jobDescriptionPlaceholder: "输入职位描述",
  letPeopleKnowWhatYouDo:
    "让人们知道你在做什么。这也有助于Superthread创建更相关的增强笔记。",
  workspaceDescriptionLabel: "工作区描述",
  workspaceDescriptionPlaceholder: "输入工作区描述",
  notesTutorial: "笔记教程",
  learnHowToUseSuperthreadNotes: "学习如何使用Superthread笔记",
  myTemplates: "我的模板",
  otherTemplates: "其他模板",
  meetingDate: "会议日期",
  attendees: "与会者",
  withMeeting: "有会议",
  withoutMeeting: "无会议",
  futureMeetings: "未来会议",
  noMeetingDate: "无会议日期",
  noAttendees: "无与会者",
  metadata: "元数据",
  date: "日期",
  cardDueSoon: "卡片即将到期",
  cardOverdue: "卡片已过期",
  cardAddedToBoardList: "卡片已添加到看板或列表",
  pageCommentStatusUpdate: "页面评论标记为已解决/未解决",
  meetingNotes: "会议笔记",
  regularNotes: "常规笔记",
  editAttendees: "编辑与会者",
  editMeetingDate: "编辑会议日期",
  editMeetingTime: "编辑会议时间",
  meetingDetails: "会议详情",
  addMeetingDetails: "添加会议详情",
  copyEmail: "复制电子邮件",
  removeAttendee: "移除与会者",
  hours: "小时",
  minutes: "分钟",
  removeFromWorkspace: "从工作区移除",
  removeMembersDescription:
    "您确定要从工作区移除%{count}位成员吗？此操作将立即撤销他们的访问权限",
  cantIncludeYourselfInBulkRemoval: "您不能在批量移除成员时包括自己",
  changeRole: "更改角色",
  ownerRolesCannotBeModifiedBulkActions: "无法通过批量操作修改所有者角色",
  roleChangesOnlyForActiveMembers: "角色更改仅适用于活跃成员",
  allSelectedMembersHaveSelectedRole: "所有选定成员已经拥有选定的角色",
  successfullyChangedRoleForMember: "成功为%{count}位成员更改角色",
  successfullyChangedRolesForMembers: "成功为%{count}位成员更改角色",
  includedPeople: "包含人员",
  includedPeopleSubtitle: "最多选择%{numberOfPeople}人",
  selectMembers: "选择成员",
  noMemberSelected: "未选择成员",
  schedule: "日程安排",
  startToGenerateReportOne: "开始生成议程",
  startToGenerateReportTwo: "提问后分钟数",
  timeNextRun: "下次运行时间",
  timeNextReport: "下次报告时间",
  timeLastRun: "上次运行时间",
  timeLastReport: "上次报告时间",
  scheduleSubtitle: "在运行开始和议程生成之间，您将无法更改日程",
  startAskingQuestionsAt: "开始提问时间",
  days: "天",
  agendaDelay: "团队签到议程延迟",
  upgradePlanToUseRoadmapAndProjectsTitle: "升级您的计划以使用项目",
  upgradePlanToUseRoadmapAndProjectsDescription:
    "项目位于项目看板上。它们可以帮助你把与项目相关的所有卡片集中在一个地方，并让所有人保持同步。",
  weekdays: "工作日",
  weekends: "周末",
  question: "问题",
  submit: "提交",
  previouslyAnswered: "之前回答：",
  allQuestionsAnswered: "所有问题都已回答。",
  noReportTitle: "没有可用的建议报告",
  noReportDescription:
    "您的团队签到的建议报告尚未准备好。一旦准备好供您输入，我们会通知您。",
  whatChanged: "有什么变化？",
  clarificationQuestionReject: "不，我没有要添加的内容",
  reportFromPastTitle: "这是过去用户报告的通知",
  reportFromPastDescription: "查看通知以查找是否有新的报告通知",
  userSuggestedReportNotificationSidebar: "请回答这些签到问题",
  userFinalReportNotificationSidebar: "您的最终签到报告已准备好",
  getStartedWithSuperthread: "开始使用Superthread",
  whatDoYouIntendToUseSuperthreadFor: "您打算将Superthread用于什么？",
  thisWillHelpUsTailorYourExperience: "这将帮助我们根据您的需求定制您的体验。",
  chooseAUseCase: "选择一个用例",
  whereDidYouHearAboutSuperthread: "您是从哪里听说Superthread的？",
  yourFeedbackHelpsUsImproveHowWeReach:
    "您的反馈有助于我们改进如何接触像您这样的人。",
  twitter: "X（Twitter）",
  reddit: "Reddit",
  linkedin: "领英",
  substack: "Substack",
  ads: "广告",
  other: "其他",
  ["onboarding.software_development"]: "软件开发",
  ["onboarding.recruitment"]: "招聘",
  ["onboarding.marketing"]: "市场营销",
  ["onboarding.customer_support"]: "客户支持",
  ["onboarding.other"]: "其他",
  ["onboardingListTasks.committed.heading"]: '你的“"待办"”列表上有什么任务？',
  ["onboardingListTasks.started.heading"]: '你现在正在“"进行中"”哪些任务？',
  ["onboardingListTasks.completed.heading"]: '哪些任务已经“"已完成"”？',
  ["onboardingListTasks.committed.0"]: "为我的团队评估 Superthread 🧐",
  ["onboardingListTasks.committed.1"]: "取消我的 Trello 订阅 🙈",
  ["onboardingListTasks.committed.2"]: "给团队买甜甜圈 🍩",
  ["onboardingListTasks.started.0"]: "我那堆积如山的开销 🤑",
  ["onboardingListTasks.started.1"]: "规划我的下一次旅行 🏝️️",
  ["onboardingListTasks.started.2"]: "登上 K2 峰 🏔️",
  ["onboardingListTasks.completed.0"]: "已续订 ChatGPT ✨",
  ["onboardingListTasks.completed.1"]: "发布了100%真实（非AI）的领英帖子",
  ["onboardingListTasks.completed.2"]: "雇一位真正的社交媒体经理 😅",
  ["onboarding.quote.0"]: "计划本身毫无价值，但计划过程却至关重要。",
  ["onboarding.quote.author.0"]: "德怀特·D·艾森豪威尔",
  ["onboarding.quote.1"]: "不计划的人，就是在计划失败。",
  ["onboarding.quote.author.1"]: "温斯顿·丘吉尔",
  ["onboarding.quote.2"]: "最困难的事情是做出行动的决定，其余的只是坚持而已。",
  ["onboarding.quote.author.2"]: "阿梅莉亚·埃尔哈特",
  ["onboarding.quote.3"]: "每花一分钟整理，就能多赚取一小时。",
  ["onboarding.quote.author.3"]: "本杰明·富兰克林",
  ["onboarding.quote.4"]: "天赋能赢得比赛，但团队合作才能赢得冠军。",
  ["onboarding.quote.author.4"]: "迈克尔·乔丹",
  ["onboarding.quote.5"]: "当你把生活整理好，人生才真正开始。",
  ["onboarding.quote.author.5"]: "近藤麻理惠",
  ["onboarding.trustedBy.description"]:
    "加入 10,000+ 家借助 Superthread 完成更多工作的公司",
  ["onboarding.video.text1"]: "恭喜 🎉",
  ["onboarding.video.text2"]: "你刚刚只用",
  ["onboarding.video.text3"]: "先缓一缓，喘口气……",
  forExample: "例如",
  createYourProfile: "创建你的个人资料",
  createYourProfileDescription: "这将是你在 Superthread 中的展示方式",
  createYourProfileInputDesc: "你可以稍后更改",
  someonesWorkspace: "%{userName}的工作区",
  someonesPrivateSpace: "%{userName}的私人空间",
  someonesBoard: "%{userName}的看板",
  chooseYourVibe: "选择你的氛围",
  chooseYourVibeDescription: "至少选择 2 个，这只是为了好玩",
  exampleCardTitle: '👋 把我拖动到 "The essentials" 看板里，看看里面有什么',
  exampleListTitle: "👀 看这里",
  browseArchivedCards: "浏览已归档的卡片",
  cardIsArchived: "卡片已归档",
  yourSessionHasTimedOut: "您的会话已超时。",
  reloadPage: "重新加载页面",
  moreActions: "更多操作",
  copyTitles: "复制标题",
  copyTitlesAsLinks: "将标题复制为链接",
  changingTags: "更改标签",
  subscribingToResourceUpdates: "订阅资源更新",
  unsubscribingFromResourceUpdates: "取消订阅资源更新",
  removingFromFavourites: "从收藏中移除",
  addingToFavourites: "添加到收藏",
  changingAssignees: "更改负责人",
  changingDates: "更改日期",
  changingStatus: "更改状态",
  processed: "已处理",
  clearSelection: "清除选择",
  createPAT: "创建令牌",
  createPATLong: "创建个人访问令牌",
  patName: "令牌名称",
  patNamePlaceholder: "一个简短的描述性名称...",
  expiration: "过期",
  patExpirationTimeSubtitle: "令牌将在所选天数后自动过期，并且不能再使用。",
  expirationTimeSelect: "此令牌将在以下时间过期：",
  selectExpirationTime: "选择过期时间",
  patNoExpirationWarningTitle: "此令牌永不过期？",
  patNoExpirationWarningDescription:
    "选择无过期可能会使您的令牌在被泄露时无限期地处于危险中。过期令牌有助于降低长期安全风险。",
  day: "天",
  patDropdownOptionOne: "7天",
  patDropdownOptionTwo: "30天",
  patDropdownOptionThree: "60天",
  patDropdownOptionFour: "90天",
  noExpiration: "无过期",
  invalidPATExpirationDate: "过期日期需要在未来",
  personalAccessTokens: "个人访问令牌",
  personalAccessTokensSubtitle: "生成个人访问令牌以与Superthread API交互",
  searchPATs: "搜索令牌",
  noPATs: "没有个人访问令牌",
  noPATsSubtitle: "您可以在上方创建个人访问令牌",
  noPATsSubtitleAdmin: "您可以在“API访问”屏幕中创建个人访问令牌",
  revokePatConfirmation: "您确定要撤销“%{patName}”令牌吗？",
  lastUsed: "上次使用",
  revokePatDescription:
    "使用此令牌的任何应用程序或脚本将无法再访问Superthread API。此操作无法撤销。",
  never: "从未",
  patLimitReachedTooltip: "达到%{limit}个PAT的限制",
  newPatCreated: "复制您的个人访问令牌",
  newPatCreatedDescriptionOne: "请务必立即复制您的令牌。",
  newPatCreatedDescriptionTwo: "您将无法再次看到它！",
  tokenCopiedToClipboard: "令牌已复制到剪贴板",
  proceed: "继续",
  copyToken: "复制令牌",
  timeExpires: "时间到期",
  patRevokedSuccessfully: "PAT成功撤销",
  failedToRevokePat: "撤销PAT失败",
  stop: "停止",
  online: "在线",
  disconnected: "已断开连接",
  apiAccess: "API访问",
  apiAccessSubtitle:
    "Superthread 的 API 让你构建自定义集成。你需要以下信息来发起请求",
  workspaceIdDescription: '在 API 中称为 "team_id"',
  userIdDescription: '在 API 中称为 "user_id"',
  viewDocs: "查看 API 文档",
  user: "用户",
  createPatSubtitle: "使用个人访问令牌访问API时，所有操作都归因于您个人",
  expirationReminderText: "我们将在您的令牌过期前一天向您发送提醒邮件。",
  securityAndAccess: "安全与访问",
  securityAndAccessSubtitle:
    "工作区成员可以创建个人访问令牌以与Superthread API交互。管理员可以在此处查看和撤销它们。",
  youOnlyHavePermissionToViewContent: "您只有权限查看内容",
  namedSpace: "%{space}空间",
  contactEmailToRequestEditAccess: "联系%{email}以请求编辑权限。",
  viewOnly: "仅查看",
  viewOnlySubtitle: "不是空间成员的人和没有编辑权限的成员只能查看",
  canEdit: "可以编辑",
  canView: "可以查看",
  thisSpaceIsViewOnly: "此空间为仅查看",
  upgradeViewOnlySpacesDescription: "您可以在付费计划中创建仅查看空间。",
  changeToViewOnlySpaceTitle: "更改为仅查看空间？",
  changeToViewOnlySpace:
    "此空间的所有现有成员在更改为仅查看后仍将是成员。除非被邀请，否则无法加入新成员。",
  changeToViewOnly: "更改为仅查看",
  completeSprint: "完成冲刺",
  completeSprintWarning:
    "所有未完成的卡片将被转移到下一个冲刺中。如果没有即将到来的冲刺，将自动创建一个。",
  hideEmptyColumns: "隐藏空列",
  hideEmptyRows: "隐藏空行",
  rememberAssignees: "记住受让人",
  rememberAssigneesTooltip: "创建卡片时始终使用这些受让人",
  recentlyUsedBoards: "最近使用的看板",
  recent: "最近",
  copyAsMarkdown: "将内容复制为Markdown",
  copiedAsMarkdown: "已复制为Markdown",
  checklists: "清单",
  duplicateCards: "复制卡片",
  blockedByCards: "被卡片阻塞",
  blockingCards: "阻塞卡片",
  allChangesSavedToSuperthread: "所有更改已保存到Superthread",
  synced: "已同步",
  syncing: "正在同步",
  aFewSecondsAgo: "几秒钟前",
  lastSynced: "上次同步",
  transcriptionIndicatorTitle: "显示实时会议指示器",
  transcriptionIndicatorDescription:
    "会议指示器浮动在屏幕顶部，并显示转录何时处于活动状态",
  seeDetailedFeaturesComparison: "查看详细功能比较",
  parentPage: "父页面",
  subPages: "子页面",
  chatWithHuman: "与真人聊天",
  chatWithHumanDescription: "与Superthread团队实时聊天",
  helpCentre: "帮助中心",
  helpAndAiSupport: "帮助文章和AI支持",
  upgradeGoSquaredDescription: "升级您的计划以获得应用内聊天支持",
  searchActions: "搜索操作",
  teamSpaces: "团队空间",
  highToLow: "从高到低",
  lowToHigh: "从低到高",
  largestFirst: "最大优先",
  smallestFirst: "最小优先",
  descending: "降序",
  ascending: "升序",
  orderBy: "排序方式",
  workspaceURL: "工作区 URL",
  newWorkspaceURL: "新的工作区 URL",
  changeWorkspaceURL: "更改工作区 URL",
  changeWorkspaceURLWarning:
    "更改工作区 URL 将会导致在 Superthread 外部（例如邮件、Slack 或外部网站）共享的卡片、页面和看板的链接失效。",
  enterWorkspaceURL: "输入工作区 URL",
  workspaceNameDescription:
    "此内容显示在侧边栏顶部、菜单和电子邮件中。大多数人会将其设置为公司或组织的名称。",
  workspaceURLDescription:
    "工作区 URL 只能包含小写字母、数字和连字符。更改它会导致您在 Superthread 外部共享的所有现有链接失效，因此最好不要经常更改。",
  workspaceDescriptionDescription:
    "对您的公司/组织所做工作的简单说明。这有助于在使用 Superthread AI 功能（例如会议记录摘要）时提供上下文。",
  teamReports: "团队报告",
  teamReportsSubtitle: "Superthread 可以基于您团队的工作生成自定义报告",
  searchReports: " 搜索报告",
  createReport: "创建报告",
  editReport: "编辑报告",
  deleteReport: "删除报告",
  deleteReportDescription: "报告 “%{reportName}” 将被删除",
  noReports: "没有报告",
  noReportsSubtitle: "您可以在上方创建报告",
  reportName: "报告名称",
  reportNamePlaceholder: "例如：“工程站会”",
  enabled: "已启用",
  includedMembers: "包含成员",
  customInstructions: "自定义指令",
  customInstructionsSubtitle: "这些指令帮助我们生成您的最终报告",
  generateReport: "生成报告",
  generateReportAt: "生成报告在",
  teamReport: "团队报告",
  customAiGeneratedReports: "自定义 AI 生成的报告",
  recentInstructions: "最近指令",
  instructionsForAi: "指令用于 AI",
  accountRole: "账户角色",
  doNotGroup: "不分组",
  membersRemoved: "已移除 %{count} 个成员",
  youAreAboutToAddMemberToPrivateSpace:
    '您即将向私人空间添加成员。他们将能够查看该空间内的所有内容。如果您点击 "确认"，该成员将被添加到该空间，并会向空间所有者发送电子邮件。',
  addMemberToPrivateSpace: "添加成员到私人空间？",
  versions: "版本",
  restoreThisVersionConfirmTitle: "恢复此版本？",
  restoreThisVersionConfirmDescription:
    "您当前的页面将被来自 %{date} 的此版本替换。",
  versionSuccessfullyRestored: "版本恢复成功",
  versionRestoredBy: "版本由 %{userName} 恢复",
  contentReplacedBy: "内容由 %{userName} 替换",
  failedToRestoreVersion: "恢复版本失败",
  currentVersion: "当前版本",
  versionLockedDescription: "请升级您的计划以查看超过 %{days} 天的版本",
  cardCoverImageSettingsTitle: "卡片背景图片",
  cardCoverToggleTitle: "在卡片上显示背景图片",
  cardCoverToggleDescription:
    "这将为您提供在卡片上显示背景图片的选项。启用此功能后，默认情况下，附件中的第一张图片将自动设置为卡片的背景图片。",
  removeCoverImage: "移除背景图片",
  setAsCoverImage: "设为背景图片",
  meetingStart: "会议开始",
  meetingEnd: "会议结束",
  meetingLinks: "会议链接",
  meetingOrganiser: "会议组织者",
  coverImageRemoved: "背景图片已移除",
  coverImageSet: "背景图片已设置",
  coverImageSetFailed: "设置背景图片失败",
  anyoneWithThisLinkCanViewBoard: "任何拥有此链接的人都可以查看看板",
  createAViewOnlyVersionOfBoard: "在可分享的链接上创建看板的仅查看版本",
  boardIsSharedPublicly: "此看板已在网络上公开分享。",
  learnMoreAboutPublicBoards: "了解更多关于 Superthread 公开看板的信息",
  trySuperthread: "试用 Superthread",
  showBoardInfo: "显示看板信息",
  weCouldntFindThatBoard: "我们找不到那个看板",
  itMayHaveBeenUnpublished: "它可能已被取消发布，或者 URL 错误。",
  allInOneProjectManagement: "一体化项目管理。",
  tryItNow: "立即试用",
  thisPublicBoardIsViewOnly: "此公共板仅供查看。",
  customiseSidebar: "自定义侧边栏",
  customiseSidebarFavouritesDescriptionOne: "您标记的卡片、页面、看板或视图",
  customiseSidebarFavouritesDescriptionTwo: "将显示在此处。",
  customiseSidebarYourSpacesDescription:
    "您所属的空间将显示在此处。加入或离开空间以编辑此部分。",
  sidebarUpdated: "侧边栏已更新",
  myProfile: "我的个人资料",
  sectionHiddenFromSidebar: "从侧边栏隐藏的部分",
  pin: "固定",
  sectionPinnedToSidebar: "固定到侧边栏的部分",
  worksapceSettings: "工作区设置",
  hideFromSidebar: "从侧边栏隐藏",
  createACopyOfThisBoard: "创建此看板的副本。活动和评论将不会被复制。",
  chooseWhereToDuplicateBoard: "选择复制看板的位置",
  copyAllCardsIntoNewBoard: "将所有卡片复制到新看板",
  editCover: "编辑封面图片",
  toggleCoverImageFit: "更改缩放",
  imFeelingLucky: "手气不错",
  viewWord: "视图",
  saveAsTemplate: "另存为模板",
  // Keyboard shortcuts cheatsheet
  ["keyboardShortcuts.title"]: "键盘快捷键",
  ["keyboardShortcuts.description"]: "使用快速按键组合更快地工作",
  ["keyboardShortcuts.or"]: "或",
  ["keyboardShortcuts.then"]: "然后",
  ["keyboardShortcuts.proTip"]: "小贴士：",
  ["keyboardShortcuts.searchPlaceholder"]: "搜索快捷键...",
  ["keyboardShortcuts.noResults"]: "没有找到快捷键",
  // Sections
  ["keyboardShortcuts.sectionGeneral"]: "通用",
  ["keyboardShortcuts.sectionBoardsLists"]: "看板 / 列表",
  ["keyboardShortcuts.sectionCards"]: "卡片",
  ["keyboardShortcuts.sectionDropdownsMenus"]: "下拉菜单",
  ["keyboardShortcuts.sectionNotificationsInbox"]: "通知收件箱",
  ["keyboardShortcuts.sectionTextEditor"]: "文本编辑器",
  ["keyboardShortcuts.sectionMarkdownFormatting"]: "Markdown 格式",
  // General
  ["keyboardShortcuts.searchForAnything"]: "搜索任何内容",
  ["keyboardShortcuts.saveOrSubmit"]: "保存或提交",
  ["keyboardShortcuts.closeOrGoBack"]: "关闭或返回",
  ["keyboardShortcuts.createNewCard"]: "创建新卡片",
  ["keyboardShortcuts.createNewPage"]: "创建新页面",
  ["keyboardShortcuts.createNewNote"]: "创建新笔记",
  ["keyboardShortcuts.showHideSidebar"]: "显示/隐藏侧边栏",
  ["keyboardShortcuts.viewAllKeyboardShortcuts"]: "查看所有键盘快捷键",
  // Boards / lists
  ["keyboardShortcuts.selectCardAbove"]: "选择上方卡片",
  ["keyboardShortcuts.selectCardBelow"]: "选择下方卡片",
  ["keyboardShortcuts.selectLeftCard"]: "选择左侧卡片",
  ["keyboardShortcuts.selectRightCard"]: "选择右侧卡片",
  ["keyboardShortcuts.openSelectedCard"]: "打开所选卡片",
  ["keyboardShortcuts.closeTheCard"]: "关闭卡片",
  ["keyboardShortcuts.moveCardUp"]: "上移卡片",
  ["keyboardShortcuts.moveCardDown"]: "下移卡片",
  ["keyboardShortcuts.moveCardLeft"]: "左移卡片",
  ["keyboardShortcuts.moveCardRight"]: "右移卡片",
  ["keyboardShortcuts.addCardToMultiSelect"]: "添加卡片到多选",
  ["keyboardShortcuts.selectRangeOfCards"]: "选择卡片范围",
  ["keyboardShortcuts.selectAllCards"]: "选择所有卡片",
  ["keyboardShortcuts.clearMultiSelect"]: "清除多选",
  ["keyboardShortcuts.addCardInlineAndOpen"]: "内联添加卡片并打开",
  ["keyboardShortcuts.addBoardFilter"]: "添加看板筛选器",
  // Cards
  ["keyboardShortcuts.renameTitle"]: "重命名标题",
  ["keyboardShortcuts.assignUnassignYourself"]: "分配/取消分配自己",
  ["keyboardShortcuts.statusList"]: "状态/列表",
  ["keyboardShortcuts.assignees"]: "负责人",
  ["keyboardShortcuts.tags"]: "标签",
  ["keyboardShortcuts.setDueDate"]: "设置截止日期",
  ["keyboardShortcuts.submitComment"]: "提交评论",
  ["keyboardShortcuts.copyGitBranchName"]: "复制所选卡片的 git 分支名",
  ["keyboardShortcuts.copyCardAsMarkdown"]: "将卡片内容复制为 Markdown",
  // Dropdowns and menus
  ["keyboardShortcuts.moveFocusDown"]: "焦点下移",
  ["keyboardShortcuts.moveFocusUp"]: "焦点上移",
  ["keyboardShortcuts.selectAndClose"]: "选择并关闭",
  ["keyboardShortcuts.addFocusedItemToSelection"]: "将选中项添加到选择区",
  ["keyboardShortcuts.closeTheMenu"]: "关闭菜单",
  // Notifications inbox
  ["keyboardShortcuts.selectNextNotification"]: "选择下一条通知",
  ["keyboardShortcuts.selectPreviousNotification"]: "选择上一条通知",
  ["keyboardShortcuts.resolveNotification"]: "标记通知为已处理",
  // Text editor
  ["keyboardShortcuts.textEditorNote"]: "在卡片描述、评论或页面中，您可以：",
  ["keyboardShortcuts.mentionAnybodyOrAnything"]: "提及任何人或任何内容",
  ["keyboardShortcuts.openSlashMenu"]: "打开斜杠菜单以获取格式选项",
  ["keyboardShortcuts.addEmoji"]: "添加表情符号（短代码）",
  ["keyboardShortcuts.boldSelectedText"]: "加粗选中文本",
  ["keyboardShortcuts.italiciseSelectedText"]: "斜体选中文本",
  ["keyboardShortcuts.strikethroughSelectedText"]: "给选中文本添加删除线",
  ["keyboardShortcuts.proTipUrlPaste"]:
    "如果您的剪贴板上有 URL，可以将其粘贴到高亮文本上，将该文本转换为链接。",
  // Markdown formatting
  ["keyboardShortcuts.markdownItalic"]: "斜体",
  ["keyboardShortcuts.markdownBold"]: "加粗",
  ["keyboardShortcuts.markdownHeading1"]: "标题 1",
  ["keyboardShortcuts.markdownHeading2"]: "标题 2",
  ["keyboardShortcuts.markdownHeading3"]: "标题 3",
  ["keyboardShortcuts.markdownBulletList"]: "无序列表",
  ["keyboardShortcuts.markdownNumberedList"]: "有序列表",
  ["keyboardShortcuts.markdownChecklist"]: "任务清单",
  ["keyboardShortcuts.markdownStrikethrough"]: "删除线",
  ["keyboardShortcuts.markdownHorizontalDivider"]: "分隔线",
  ["keyboardShortcuts.markdownInlineCode"]: "行内代码",
  ["keyboardShortcuts.markdownCodeBlock"]: "代码块",
  publicBoardIsViewOnly: "此公共看板仅供查看。",
  duplicateToMyWorkspace: "复制到我的工作区",
  levelUp: "升级",
  core_knowledge: "核心知识",
  organise_work: "组织工作",
  shape_your_workspace: "塑造你的工作区",
  capture_knowledge: "获取知识",
  advanced_features: "高级功能",
  helper: "助手",
  organiser: "组织者",
  shaper: "塑造者",
  master: "大师",
  youHaveUnlocked: "你已解锁",
  rank: "等级",
  trelloDescription:
    "登录您的 Trello 账户以选择要导入的看板。Superthread 只会导入您选择的看板中的数据。",
  importQueued: "导入已排队",
  viewLink: "查看链接",
  removeLink: "删除链接",
  linkAdded: "链接已添加",
  errorAddingLink: "添加链接时出错",
  // PWYW Psychological Messages
  ["billing.pwyw.losingMoney"]: "感谢咖啡",
  ["billing.pwyw.barelyCovering"]: "感谢啤酒",
  ["billing.pwyw.breakeven"]: "收支平衡 — 不赚不赔",
  ["billing.pwyw.belowFair"]: "略低于公平价格",
  ["billing.pwyw.fairPrice"]: "公平价格,谢谢!",
  ["billing.pwyw.awesome"]: "您真棒!",
  ["billing.pwyw.bestHuman"]: "您简直是最棒的人!",
  ["billing.pwyw.topTier"]: "这到底是什么意思?",
  // PWYW UI Labels
  ["billing.pwyw.title"]: "随心支付",
  // Enterprise Tier Updates
  ["billing.enterpriseSubtitle"]: "适用于有严格要求的企业",
  ["billing.seatCount"]: "%{count} 个席位",
  ["billing.annualBilling"]: "年度计费",
  ["billing.versionHistory"]: "%{count} 天版本历史",
  ["billing.expertOnboarding"]: "专家入门指导",
  ["billing.nextPaymentOn"]: "下次付款日期：{date}",
  ["billing.paymentsWillStopOn"]: "付款将于 %{date} 停止",
  ["billing.youAreOnPlan"]: "您正在使用「%{planName}」计划",
  ["billing.cancelPlan"]: "Cancel subscription",
  ["billing.confirmPriceChangeTitle"]: "Confirm price change",
  ["billing.confirmPriceChangeDescription"]:
    "Your subscription will be changed to %{price} on your next invoice.",
  ["billing.priceChangeSuccess"]: "价格更改成功！",
  ["billing.priceChangeFail"]:
    "价格更改失败。如果问题仍然存在，请联系支持团队。",
  ["billing.choosePlanSectionTitle"]: "Choose a plan",
  ["billing.choosePlanSectionDescription"]:
    "Upgrading your plan removes your workspace limits",
  ["billing.youSetThePrice"]: "You set the price",
  ["billing.upgradeToRemoveUsageLimits"]: "Upgrade to remove usage limits",
  ["billing.fairPrice"]: "Fair %{period} pricing",
  ["billing.startsAt"]: "Starts at",
  ["billing.perYear"]: "/ year",
  ["billing.perMonth"]: "/ month",
  createMissingTags: "创建缺失的标签",
  createMissingTagsDescription: "在 %{space} 空间中创建不存在的标签",
  createACopyOfThisCard: "创建此卡片的副本。活动和评论不会被复制。",
  chooseWhereToDuplicateCard: "选择要复制卡片的位置",
  cardWillBeAddedToBottomOfList: "卡片将被添加到列表底部",
  learnFavourites: "学习收藏夹",
  learnFavouritesDescription: "构建您的个人基地",
  learnFavouritesMission: "通过将最重要的工作固定到侧边栏，让它成为您自己的。",
  commandMastery: "命令精通",
  commandMasteryDescription: "您隐藏的工具箱",
  commandMasteryMission: "我们的动态系统灵活，可帮助您扩展。",
  notesCourse: "AI 会议、转录和笔记模板",
  notesCourseDescription: "您的智能会议助手",
  notesCourseMission:
    "AI 转录为您的团队提供清晰度 - 捕获所说的一切，组织见解，并神奇地将讨论转化为行动 ✨",
  cardMastery: "卡片精通",
  cardMasteryDescription: "您可以感受到的速度",
  cardMasteryMission:
    "Superthread 专为速度而打造。一旦您熟悉了，您将飞快地完成工作。",
  learnSidedockView: "学习侧停靠视图",
  learnSidedockViewDescription: "您的深度专注伙伴",
  learnSidedockViewMission:
    "Superthread 中的所有内容都是为简单性和灵活性而设计的，包括视图。",
  spacesMastery: "空间精通 - 平静的指挥中心",
  spacesMasteryDescription: "以您的方式创建组织的空间",
  spacesMasteryMission:
    "空间适应您的工作流程 - 按部门、客户、项目。像您想要的那样灵活工作。",
  curator: "策展人",
  artisan: "工匠",
  scribe: "抄写员",
  speedster: "速度达人",
  navigator: "导航员",
  architect: "建筑师",
  favourite_board: "收藏看板",
  favourite_card: "收藏卡片",
  favourite_page: "收藏页面",
  reorder_favourites: "重新排序收藏",
  add_table_to_card: "/Table 在卡片描述中",
  add_callout_to_card: "/Callout 在卡片描述中",
  embed_youtube_to_page: "/YouTube 在页面中",
  embed_board_to_page: "/Board 在页面中嵌入看板",
  transcribe_meeting: "转录会议",
  view_transcript_action: "查看转录",
  pause_meeting_for_summary: "暂停结束并获取自动摘要",
  change_notes_template: "更改笔记模板（投资者会面、头脑风暴、1对1 等）",
  convert_notes_to_cards: "将笔记转换为卡片",
  use_arrow_keys_action: "使用箭头键",
  use_option_arrows: "使用 Option + 箭头",
  use_bulk_actions: "使用批量操作",
  use_magic_cover_image: "使用魔术封面图片",
  set_parent_card_action: "设置父卡片",
  open_side_dock_view_action: "打开侧停靠视图",
  view_card_in_sidebar: "在侧边栏中查看其他卡片",
  view_page_in_sidebar: "在侧边栏中查看其他页面",
  create_client_space: '创建一个名为"新客户"的空间',
  create_department_space: '创建一个名为"新部门"的空间',
  create_board_in_client_space:
    '在您的新客户空间内创建一个名为"新客户看板"的看板',
  create_board_in_department_space:
    '在您的新部门空间内创建一个名为"新部门看板"的看板',
  create_card_in_board: '在您的新客户看板内创建一张名为"新卡片"的卡片',
  move_card_between_spaces: "将您的新卡片从新客户拖到新部门",
  onboardingNewClientSpace: "新客户",
  onboardingNewDepartmentSpace: "新部门",
  onboardingNewClientBoard: "新客户看板",
  onboardingNewDepartmentBoard: "新部门看板",
  onboardingNewCard: "新卡片",
  moveBoard: "移动看板",
  moveBoardDescription:
    "此看板中使用的某些标签在 %{space} 空间中不存在，将从卡片中删除。",
  missingTags: "缺失的标签",
  createMissingTagsInSpaceDescription:
    "如果 %{space} 空间中不存在标签，则创建标签",
  cardLimitReached: "已达到卡片限制",
  cardLimitReachedDescription:
    "您的工作区使用的是免费计划。删除一些旧卡片或升级以移除限制。",
  forms: "表单",
  createForm: "创建表单",
  editForm: "编辑表单",
  saveForm: "保存表单",
  formCreated: "表单已创建",
  formUpdated: "表单已更新",
  formSubmitted: "表单已提交",
  failedToSubmitForm: "提交表单失败",
  submitForm: "提交表单",
  noFormsForThisBoard: "此看板没有表单",
  formsSettingsDescription: "为此看板创建和管理表单",
  formNameAndIcon: "表单名称和图标",
  formNameCannotBeEmpty: "表单名称不能为空",
  thisIsHowPeopleWillSeeForm: "这是人们看到您表单的方式",
  formDescription: "表单描述",
  descriptionWillBeShownOnPublicForm: "描述将显示在公开表单上",
  enterFormDescription: "输入表单描述",
  formFields: "表单字段",
  addFieldsForUsersToFillOut: "添加供用户填写的字段",
  fieldType: "字段类型",
  selectTypeOfField: "选择字段类型",
  fieldLabel: "字段标签",
  fieldLabelCannotBeEmpty: "字段标签不能为空",
  enterFieldLabel: "输入字段标签",
  addField: "添加字段",
  editField: "编辑字段",
  placeholder: "占位符",
  optionalPlaceholderText: "可选占位符文本",
  enterPlaceholder: "输入占位符",
  required: "必填",
  makeThisFieldRequired: "将此字段设为必填",
  option: "选项",
  addOption: "添加选项",
  addOptionsForThisField: "为此字段添加选项",
  atLeastTwoOptionsRequired: "至少需要两个选项",
  enterText: "输入文本",
  enterNumber: "输入数字",
  enterEmail: "输入邮箱",
  enterPhoneNumber: "输入电话号码",
  enterUrl: "输入网址",
  selectDate: "选择日期",
  selectOption: "选择选项",
  dragAndDropOrClick: "拖放或点击上传",
  yes: "是",
  no: "否",
  titleAZ: "标题 A-Z",
  titleZA: "标题 Z-A",
  shortText: "短文本",
  longText: "长文本",
  number: "数字",
  dropdown: "下拉菜单",
  checkbox: "复选框",
  phone: "电话",
  link: "链接",
  maximumCharactersAllowed: "最大允许字符数",
  pleaseEnterValidNumber: "请输入有效数字",
  pleaseSelectDate: "请选择日期",
  pleaseSelectOption: "请选择选项",
  pleaseUploadFile: "请上传文件",
  pleaseSelectAtLeastOneOption: "请至少选择一个选项",
  pleaseProvideValidEmail: "请提供有效的电子邮件",
  pleaseEnterValidPhoneNumber: "请输入有效的电话号码",
  pleaseEnterValidUrl: "请输入有效的网址",
  thisFieldIsRequired: "此字段为必填项",
  congratulations: "恭喜",
  nextLevel: "下一关",
  fieldDescription: "字段描述",
  enterFieldDescription: "输入字段描述",
  selectCardProperty: "选择卡片属性",
  chooseWhichPropertyToMapTo: "选择要映射的属性",
  pleaseSelectACardProperty: "请选择一个卡片属性",
  cardProperty: "卡片属性",
  selectPriority: "选择优先级",
  selectAssignees: "选择负责人",
  selectDueDate: "选择截止日期",
  noTagsAvailable: "没有可用的标签",
  allowMultipleSelections: "允许多选",
  allowUsersToSelectMultipleOptions: "允许用户选择多个选项",
  selectOptions: "选择选项",
  itemsSelected: "已选择 %{count} 项",
  cardPropertyAlreadyAddedToForm: "该卡片属性已添加到表单中",
  formNotFound: "未找到表单",
  formNotFoundDescription: "此表单可能已被删除或不再可用。",
  thankYou: "谢谢！",
  responseSubmitted: "您的回复已提交。",
  submitAnother: "提交另一个",
  submitting: "正在提交",
  publicFormSubmission: "公开表单提交",
  projectHealth: "项目健康状况",
  projectHealthUpdates: "项目健康状况更新",
  allUpdates: "所有更新",
  onTrack: "进展顺利",
  atRisk: "存在风险",
  offTrack: "进度落后",
  notExpected: "无需更新",
  stale: "过期",
  healthStatusNeedsUpdating: "需要更新",
  markedProjectAsStaleDueToLackOfUpdate:
    "因未按时提供健康状况更新而将项目标记为过期",
  downgradedHealthStatusAutomaticallyFrom: "自动降级健康状况从",
  revertedHealthStatusFrom: "恢复健康状况从",
  healthStatusMarkedStaleAutomaticallyPleaseUpdate:
    "健康状况已自动标记为过期，请发布更新！",
  healthStatusDowngradedAutomaticallyDueToInactivity: "健康状况已自动降级为",
  healthUpdateOnly: "仅健康状况更新",
  keepYourTeamInformed: "让团队随时了解情况",
  shareProjectHealthUpdatesWithYourTeam: "与团队分享项目健康状况更新",
  newProjectUpdate: "新项目更新",
  projectHealthUpdate: "项目健康状况更新",
  latestUpdate: "最新更新",
  viewOlderUpdates: "查看旧更新",
  hideOlderUpdates: "隐藏旧更新",
  previousUpdates: "以前的更新",
  writeYourUpdate: "撰写简短更新以告知大家此项目的状态...",
  postUpdate: "发布更新",
  healthPeriodConfiguration: "更新频率",
  healthPeriodDescription:
    "设置此项目应多久更新一次。错过更新将把健康状况标记为过期。设置为 0 以禁用。",
  noHealthUpdates: "无健康状况更新",
  noHealthUpdatesDescription:
    "没有要显示的更新。活跃项目的最新健康状况更新将显示在此处。尝试调整筛选器以查看更多内容。",
  healthPeriodUpdatedSuccessfully: "过期期限已成功更新",
  healthPeriodUpdateFailed: "更新过期期限失败",
  deleteLatestHealthUpdateWarning:
    "您即将删除此项目的最新健康状况更新。如果继续，健康状况将恢复到之前的更新。",
  healthStatusWasChangedTo: "项目的健康状况已更改为",
  healthStatusRemainedAt: "项目的健康状况保持在",
  healthStatusWasRevertedTo: "项目的健康状况已恢复到",
  regenerateUrlForForm: "重新生成 %{formName} 的公开链接",
  regenerateUrlForFormDescription:
    "这将使当前的公开链接失效。使用现有链接的任何人将无法再访问此表单。",
  formUrlRegenerated: "表单链接已重新生成",
  claimLastRank: "Claim last rank",
};

export default zhHans as Translations;
