name: release

on:
  workflow_dispatch:
  release:
    types: [released]

# enforce single job concurrency since we need to push commits
concurrency:
  group: localization-release
  cancel-in-progress: false

env:
  GIT_AUTHOR_NAME: github-actions[bot]
  GIT_COMMITTER_NAME: github-actions[bot]
  GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
  GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com

jobs:
  ts:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write

    if: contains(github.ref, 'tags')

    steps:
      - uses: actions/checkout@v4
      - id: parse-tag
        run: |
          echo "VERSION=$(echo ${{ github.ref }} | cut -d '/' -f 3)" >> $GITHUB_ENV
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@superthread-com'

      - name: Bump version
        run: npm version ${steps.parse-tag.outputs.VERSION} --no-git-tag-version

      - name: Check for modified files
        id: git-check
        run: echo "MODIFIED=$(if [ -n '$(git status --porcelain)' ]; then echo 'true'; else echo 'false'; fi)" >> $GITHUB_OUTPUT

      - name: Publish new version
        if: steps.git-check.outputs.MODIFIED == 'true'
        working-directory: ./
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm publish

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "[bot] Bump version to ${VERSION/v/}"
          branch: "release-${{ github.sha }}"
          title: "[bot] Bump version to ${VERSION/v/}"
          body: "This PR bumps the version to ${VERSION/v/}"
          base: main

      # separate approval step ensures that CI checks will pass before merge
      - name: approve pr
        if: steps.git-check.outputs.modified == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr review --approve ${{ steps.cpr.outputs.pull-request-url }}
